#!/usr/bin/python
#

# Copyright (C) 2008 Dejan Muhamedagic <dmuhamedagic@suse.de>
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# 
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

minimum_version = '2.4'
import sys

from distutils import version
v_min = version.StrictVersion(minimum_version)
v_this = version.StrictVersion(sys.version[:3])
if v_min > v_this:
    sys.stderr.write("abort: minimum python version support is %s\n", \
        minimum_version)
    sys.exit(-1)

try:
    import crm.main
except ImportError:
    sys.stderr.write("abort: couldn't find crm libraries in [%s]\n" %
                     ' '.join(sys.path))
    sys.stderr.write("(check your install and PYTHONPATH)\n")
    sys.exit(-1)

try:
    crm.main.run()
except KeyboardInterrupt:
    print "Ctrl-C, leaving"
    sys.exit(1)
# vim:ts=4:sw=4:et:
