<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="81" operation="monitor" operation_key="base:0_monitor_16000" on_node="base-bundle-0" on_node_uuid="base-bundle-0" router_node="node2">
        <primitive id="base" long-id="base:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_container_attribute_target="host" CRM_meta_globally_unique="false" CRM_meta_interval="16000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_on_node="base-bundle-0" CRM_meta_on_node_uuid="base-bundle-0" CRM_meta_physical_host="node2" CRM_meta_promoted_max="1" CRM_meta_promoted_node_max="1" CRM_meta_role="Unpromoted" CRM_meta_timeout="16000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="66" operation="start" operation_key="base-bundle-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="80" operation="start" operation_key="base:0_start_0" on_node="base-bundle-0" on_node_uuid="base-bundle-0" router_node="node2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="80" operation="start" operation_key="base:0_start_0" on_node="base-bundle-0" on_node_uuid="base-bundle-0" router_node="node2">
        <primitive id="base" long-id="base:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_container_attribute_target="host" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_on_node="base-bundle-0" CRM_meta_on_node_uuid="base-bundle-0" CRM_meta_physical_host="node2" CRM_meta_promoted_max="1" CRM_meta_promoted_node_max="1" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="64" operation="start" operation_key="base-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="66" operation="start" operation_key="base-bundle-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <pseudo_event id="86" operation="start" operation_key="base-bundle-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="83" operation="monitor" operation_key="base:1_monitor_16000" on_node="base-bundle-1" on_node_uuid="base-bundle-1" router_node="node3">
        <primitive id="base" long-id="base:1" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_container_attribute_target="host" CRM_meta_globally_unique="false" CRM_meta_interval="16000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_on_node="base-bundle-1" CRM_meta_on_node_uuid="base-bundle-1" CRM_meta_physical_host="node3" CRM_meta_promoted_max="1" CRM_meta_promoted_node_max="1" CRM_meta_role="Unpromoted" CRM_meta_timeout="16000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="70" operation="start" operation_key="base-bundle-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="82" operation="start" operation_key="base:1_start_0" on_node="base-bundle-1" on_node_uuid="base-bundle-1" router_node="node3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <rsc_op id="82" operation="start" operation_key="base:1_start_0" on_node="base-bundle-1" on_node_uuid="base-bundle-1" router_node="node3">
        <primitive id="base" long-id="base:1" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_container_attribute_target="host" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_on_node="base-bundle-1" CRM_meta_on_node_uuid="base-bundle-1" CRM_meta_physical_host="node3" CRM_meta_promoted_max="1" CRM_meta_promoted_node_max="1" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="68" operation="start" operation_key="base-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="70" operation="start" operation_key="base-bundle-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="80" operation="start" operation_key="base:0_start_0" on_node="base-bundle-0" on_node_uuid="base-bundle-0" router_node="node2"/>
      </trigger>
      <trigger>
        <pseudo_event id="86" operation="start" operation_key="base-bundle-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <rsc_op id="85" operation="monitor" operation_key="base:2_monitor_16000" on_node="base-bundle-2" on_node_uuid="base-bundle-2" router_node="node4">
        <primitive id="base" long-id="base:2" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_container_attribute_target="host" CRM_meta_globally_unique="false" CRM_meta_interval="16000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_on_node="base-bundle-2" CRM_meta_on_node_uuid="base-bundle-2" CRM_meta_physical_host="node4" CRM_meta_promoted_max="1" CRM_meta_promoted_node_max="1" CRM_meta_role="Unpromoted" CRM_meta_timeout="16000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="74" operation="start" operation_key="base-bundle-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="84" operation="start" operation_key="base:2_start_0" on_node="base-bundle-2" on_node_uuid="base-bundle-2" router_node="node4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <rsc_op id="84" operation="start" operation_key="base:2_start_0" on_node="base-bundle-2" on_node_uuid="base-bundle-2" router_node="node4">
        <primitive id="base" long-id="base:2" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_container_attribute_target="host" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_on_node="base-bundle-2" CRM_meta_on_node_uuid="base-bundle-2" CRM_meta_physical_host="node4" CRM_meta_promoted_max="1" CRM_meta_promoted_node_max="1" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="72" operation="start" operation_key="base-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="74" operation="start" operation_key="base-bundle-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="82" operation="start" operation_key="base:1_start_0" on_node="base-bundle-1" on_node_uuid="base-bundle-1" router_node="node3"/>
      </trigger>
      <trigger>
        <pseudo_event id="86" operation="start" operation_key="base-bundle-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6" priority="1000000">
    <action_set>
      <pseudo_event id="87" operation="running" operation_key="base-bundle-clone_running_0">
        <attributes CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_promoted_max="1" CRM_meta_promoted_node_max="1" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="80" operation="start" operation_key="base:0_start_0" on_node="base-bundle-0" on_node_uuid="base-bundle-0" router_node="node2"/>
      </trigger>
      <trigger>
        <rsc_op id="82" operation="start" operation_key="base:1_start_0" on_node="base-bundle-1" on_node_uuid="base-bundle-1" router_node="node3"/>
      </trigger>
      <trigger>
        <rsc_op id="84" operation="start" operation_key="base:2_start_0" on_node="base-bundle-2" on_node_uuid="base-bundle-2" router_node="node4"/>
      </trigger>
      <trigger>
        <pseudo_event id="86" operation="start" operation_key="base-bundle-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <pseudo_event id="86" operation="start" operation_key="base-bundle-clone_start_0">
        <attributes CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_promoted_max="1" CRM_meta_promoted_node_max="1" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="2" operation="monitor" operation_key="base-bundle-podman-0_monitor_0" on_node="node1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="4" operation="monitor" operation_key="base-bundle-podman-1_monitor_0" on_node="node1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="6" operation="monitor" operation_key="base-bundle-podman-2_monitor_0" on_node="node1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="14" operation="monitor" operation_key="base-bundle-podman-0_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="16" operation="monitor" operation_key="base-bundle-podman-1_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="18" operation="monitor" operation_key="base-bundle-podman-2_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="26" operation="monitor" operation_key="base-bundle-podman-0_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="28" operation="monitor" operation_key="base-bundle-podman-1_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="30" operation="monitor" operation_key="base-bundle-podman-2_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="38" operation="monitor" operation_key="base-bundle-podman-0_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="40" operation="monitor" operation_key="base-bundle-podman-1_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="42" operation="monitor" operation_key="base-bundle-podman-2_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="50" operation="monitor" operation_key="base-bundle-podman-0_monitor_0" on_node="node5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <rsc_op id="52" operation="monitor" operation_key="base-bundle-podman-1_monitor_0" on_node="node5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <rsc_op id="54" operation="monitor" operation_key="base-bundle-podman-2_monitor_0" on_node="node5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <pseudo_event id="76" operation="start" operation_key="base-bundle_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <rsc_op id="65" operation="monitor" operation_key="base-bundle-podman-0_monitor_60000" on_node="node2" on_node_uuid="2">
        <primitive id="base-bundle-podman-0" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_interval="60000" CRM_meta_name="monitor" CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-0" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-0:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="64" operation="start" operation_key="base-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9">
    <action_set>
      <rsc_op id="64" operation="start" operation_key="base-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2">
        <primitive id="base-bundle-podman-0" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-0" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-0:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="2" operation="monitor" operation_key="base-bundle-podman-0_monitor_0" on_node="node1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="14" operation="monitor" operation_key="base-bundle-podman-0_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="16" operation="monitor" operation_key="base-bundle-podman-1_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="18" operation="monitor" operation_key="base-bundle-podman-2_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="26" operation="monitor" operation_key="base-bundle-podman-0_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="38" operation="monitor" operation_key="base-bundle-podman-0_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="50" operation="monitor" operation_key="base-bundle-podman-0_monitor_0" on_node="node5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <pseudo_event id="76" operation="start" operation_key="base-bundle_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="10">
    <action_set>
      <rsc_op id="50" operation="monitor" operation_key="base-bundle-podman-0_monitor_0" on_node="node5" on_node_uuid="5">
        <primitive id="base-bundle-podman-0" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-0" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-0:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="11">
    <action_set>
      <rsc_op id="38" operation="monitor" operation_key="base-bundle-podman-0_monitor_0" on_node="node4" on_node_uuid="4">
        <primitive id="base-bundle-podman-0" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-0" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-0:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="12">
    <action_set>
      <rsc_op id="26" operation="monitor" operation_key="base-bundle-podman-0_monitor_0" on_node="node3" on_node_uuid="3">
        <primitive id="base-bundle-podman-0" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-0" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-0:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="13">
    <action_set>
      <rsc_op id="14" operation="monitor" operation_key="base-bundle-podman-0_monitor_0" on_node="node2" on_node_uuid="2">
        <primitive id="base-bundle-podman-0" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-0" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-0:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="14">
    <action_set>
      <rsc_op id="2" operation="monitor" operation_key="base-bundle-podman-0_monitor_0" on_node="node1" on_node_uuid="1">
        <primitive id="base-bundle-podman-0" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-0" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-0:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="15">
    <action_set>
      <rsc_op id="67" operation="monitor" operation_key="base-bundle-0_monitor_30000" on_node="node2" on_node_uuid="2">
        <primitive id="base-bundle-0" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-0" CRM_meta_interval="30000" CRM_meta_name="monitor" CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_timeout="30000" addr="node2"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="66" operation="start" operation_key="base-bundle-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="16">
    <action_set>
      <rsc_op id="66" operation="start" operation_key="base-bundle-0_start_0" on_node="node2" on_node_uuid="2">
        <primitive id="base-bundle-0" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-0" CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_timeout="20000" addr="node2"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="3" operation="monitor" operation_key="base-bundle-0_monitor_0" on_node="node1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="15" operation="monitor" operation_key="base-bundle-0_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="27" operation="monitor" operation_key="base-bundle-0_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="39" operation="monitor" operation_key="base-bundle-0_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="51" operation="monitor" operation_key="base-bundle-0_monitor_0" on_node="node5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <rsc_op id="64" operation="start" operation_key="base-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="17">
    <action_set>
      <rsc_op id="51" operation="monitor" operation_key="base-bundle-0_monitor_0" on_node="node5" on_node_uuid="5">
        <primitive id="base-bundle-0" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-0" CRM_meta_on_node="node5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node2"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="64" operation="start" operation_key="base-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="18">
    <action_set>
      <rsc_op id="39" operation="monitor" operation_key="base-bundle-0_monitor_0" on_node="node4" on_node_uuid="4">
        <primitive id="base-bundle-0" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-0" CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node2"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="64" operation="start" operation_key="base-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="19">
    <action_set>
      <rsc_op id="27" operation="monitor" operation_key="base-bundle-0_monitor_0" on_node="node3" on_node_uuid="3">
        <primitive id="base-bundle-0" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-0" CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node2"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="64" operation="start" operation_key="base-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="20">
    <action_set>
      <rsc_op id="15" operation="monitor" operation_key="base-bundle-0_monitor_0" on_node="node2" on_node_uuid="2">
        <primitive id="base-bundle-0" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-0" CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node2"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="64" operation="start" operation_key="base-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="21">
    <action_set>
      <rsc_op id="3" operation="monitor" operation_key="base-bundle-0_monitor_0" on_node="node1" on_node_uuid="1">
        <primitive id="base-bundle-0" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-0" CRM_meta_on_node="node1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node2"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="64" operation="start" operation_key="base-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="22">
    <action_set>
      <rsc_op id="69" operation="monitor" operation_key="base-bundle-podman-1_monitor_60000" on_node="node3" on_node_uuid="3">
        <primitive id="base-bundle-podman-1" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_interval="60000" CRM_meta_name="monitor" CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-1" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-1:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="68" operation="start" operation_key="base-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="23">
    <action_set>
      <rsc_op id="68" operation="start" operation_key="base-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3">
        <primitive id="base-bundle-podman-1" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-1" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-1:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="4" operation="monitor" operation_key="base-bundle-podman-1_monitor_0" on_node="node1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="16" operation="monitor" operation_key="base-bundle-podman-1_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="26" operation="monitor" operation_key="base-bundle-podman-0_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="28" operation="monitor" operation_key="base-bundle-podman-1_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="30" operation="monitor" operation_key="base-bundle-podman-2_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="40" operation="monitor" operation_key="base-bundle-podman-1_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="52" operation="monitor" operation_key="base-bundle-podman-1_monitor_0" on_node="node5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <pseudo_event id="76" operation="start" operation_key="base-bundle_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="24">
    <action_set>
      <rsc_op id="52" operation="monitor" operation_key="base-bundle-podman-1_monitor_0" on_node="node5" on_node_uuid="5">
        <primitive id="base-bundle-podman-1" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-1" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-1:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="25">
    <action_set>
      <rsc_op id="40" operation="monitor" operation_key="base-bundle-podman-1_monitor_0" on_node="node4" on_node_uuid="4">
        <primitive id="base-bundle-podman-1" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-1" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-1:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="26">
    <action_set>
      <rsc_op id="28" operation="monitor" operation_key="base-bundle-podman-1_monitor_0" on_node="node3" on_node_uuid="3">
        <primitive id="base-bundle-podman-1" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-1" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-1:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="27">
    <action_set>
      <rsc_op id="16" operation="monitor" operation_key="base-bundle-podman-1_monitor_0" on_node="node2" on_node_uuid="2">
        <primitive id="base-bundle-podman-1" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-1" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-1:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="28">
    <action_set>
      <rsc_op id="4" operation="monitor" operation_key="base-bundle-podman-1_monitor_0" on_node="node1" on_node_uuid="1">
        <primitive id="base-bundle-podman-1" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-1" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-1:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="29">
    <action_set>
      <rsc_op id="71" operation="monitor" operation_key="base-bundle-1_monitor_30000" on_node="node3" on_node_uuid="3">
        <primitive id="base-bundle-1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-1" CRM_meta_interval="30000" CRM_meta_name="monitor" CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="30000" addr="node3"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="70" operation="start" operation_key="base-bundle-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="30">
    <action_set>
      <rsc_op id="70" operation="start" operation_key="base-bundle-1_start_0" on_node="node3" on_node_uuid="3">
        <primitive id="base-bundle-1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-1" CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="20000" addr="node3"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="monitor" operation_key="base-bundle-1_monitor_0" on_node="node1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="17" operation="monitor" operation_key="base-bundle-1_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="29" operation="monitor" operation_key="base-bundle-1_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="41" operation="monitor" operation_key="base-bundle-1_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="53" operation="monitor" operation_key="base-bundle-1_monitor_0" on_node="node5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <rsc_op id="68" operation="start" operation_key="base-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="31">
    <action_set>
      <rsc_op id="53" operation="monitor" operation_key="base-bundle-1_monitor_0" on_node="node5" on_node_uuid="5">
        <primitive id="base-bundle-1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-1" CRM_meta_on_node="node5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node3"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="68" operation="start" operation_key="base-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="32">
    <action_set>
      <rsc_op id="41" operation="monitor" operation_key="base-bundle-1_monitor_0" on_node="node4" on_node_uuid="4">
        <primitive id="base-bundle-1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-1" CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node3"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="68" operation="start" operation_key="base-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="33">
    <action_set>
      <rsc_op id="29" operation="monitor" operation_key="base-bundle-1_monitor_0" on_node="node3" on_node_uuid="3">
        <primitive id="base-bundle-1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-1" CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node3"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="68" operation="start" operation_key="base-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="34">
    <action_set>
      <rsc_op id="17" operation="monitor" operation_key="base-bundle-1_monitor_0" on_node="node2" on_node_uuid="2">
        <primitive id="base-bundle-1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-1" CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node3"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="68" operation="start" operation_key="base-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="35">
    <action_set>
      <rsc_op id="5" operation="monitor" operation_key="base-bundle-1_monitor_0" on_node="node1" on_node_uuid="1">
        <primitive id="base-bundle-1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-1" CRM_meta_on_node="node1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node3"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="68" operation="start" operation_key="base-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="36">
    <action_set>
      <rsc_op id="73" operation="monitor" operation_key="base-bundle-podman-2_monitor_60000" on_node="node4" on_node_uuid="4">
        <primitive id="base-bundle-podman-2" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_interval="60000" CRM_meta_name="monitor" CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-2" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-2:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="72" operation="start" operation_key="base-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="37">
    <action_set>
      <rsc_op id="72" operation="start" operation_key="base-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4">
        <primitive id="base-bundle-podman-2" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-2" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-2:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="6" operation="monitor" operation_key="base-bundle-podman-2_monitor_0" on_node="node1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="18" operation="monitor" operation_key="base-bundle-podman-2_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="30" operation="monitor" operation_key="base-bundle-podman-2_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="38" operation="monitor" operation_key="base-bundle-podman-0_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="40" operation="monitor" operation_key="base-bundle-podman-1_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="42" operation="monitor" operation_key="base-bundle-podman-2_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="54" operation="monitor" operation_key="base-bundle-podman-2_monitor_0" on_node="node5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <pseudo_event id="76" operation="start" operation_key="base-bundle_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="38">
    <action_set>
      <rsc_op id="54" operation="monitor" operation_key="base-bundle-podman-2_monitor_0" on_node="node5" on_node_uuid="5">
        <primitive id="base-bundle-podman-2" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-2" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-2:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="39">
    <action_set>
      <rsc_op id="42" operation="monitor" operation_key="base-bundle-podman-2_monitor_0" on_node="node4" on_node_uuid="4">
        <primitive id="base-bundle-podman-2" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-2" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-2:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="40">
    <action_set>
      <rsc_op id="30" operation="monitor" operation_key="base-bundle-podman-2_monitor_0" on_node="node3" on_node_uuid="3">
        <primitive id="base-bundle-podman-2" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-2" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-2:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="41">
    <action_set>
      <rsc_op id="18" operation="monitor" operation_key="base-bundle-podman-2_monitor_0" on_node="node2" on_node_uuid="2">
        <primitive id="base-bundle-podman-2" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-2" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-2:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="42">
    <action_set>
      <rsc_op id="6" operation="monitor" operation_key="base-bundle-podman-2_monitor_0" on_node="node1" on_node_uuid="1">
        <primitive id="base-bundle-podman-2" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:base" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/base-bundle-2" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/base-bundle-2:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="43">
    <action_set>
      <rsc_op id="75" operation="monitor" operation_key="base-bundle-2_monitor_30000" on_node="node4" on_node_uuid="4">
        <primitive id="base-bundle-2" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-2" CRM_meta_interval="30000" CRM_meta_name="monitor" CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="30000" addr="node4"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="74" operation="start" operation_key="base-bundle-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="44">
    <action_set>
      <rsc_op id="74" operation="start" operation_key="base-bundle-2_start_0" on_node="node4" on_node_uuid="4">
        <primitive id="base-bundle-2" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-2" CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="20000" addr="node4"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="7" operation="monitor" operation_key="base-bundle-2_monitor_0" on_node="node1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="19" operation="monitor" operation_key="base-bundle-2_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="31" operation="monitor" operation_key="base-bundle-2_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="43" operation="monitor" operation_key="base-bundle-2_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="55" operation="monitor" operation_key="base-bundle-2_monitor_0" on_node="node5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <rsc_op id="72" operation="start" operation_key="base-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="45">
    <action_set>
      <rsc_op id="55" operation="monitor" operation_key="base-bundle-2_monitor_0" on_node="node5" on_node_uuid="5">
        <primitive id="base-bundle-2" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-2" CRM_meta_on_node="node5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node4"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="72" operation="start" operation_key="base-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="46">
    <action_set>
      <rsc_op id="43" operation="monitor" operation_key="base-bundle-2_monitor_0" on_node="node4" on_node_uuid="4">
        <primitive id="base-bundle-2" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-2" CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node4"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="72" operation="start" operation_key="base-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="47">
    <action_set>
      <rsc_op id="31" operation="monitor" operation_key="base-bundle-2_monitor_0" on_node="node3" on_node_uuid="3">
        <primitive id="base-bundle-2" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-2" CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node4"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="72" operation="start" operation_key="base-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="48">
    <action_set>
      <rsc_op id="19" operation="monitor" operation_key="base-bundle-2_monitor_0" on_node="node2" on_node_uuid="2">
        <primitive id="base-bundle-2" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-2" CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node4"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="72" operation="start" operation_key="base-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="49">
    <action_set>
      <rsc_op id="7" operation="monitor" operation_key="base-bundle-2_monitor_0" on_node="node1" on_node_uuid="1">
        <primitive id="base-bundle-2" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="base-bundle-podman-2" CRM_meta_on_node="node1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node4"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="72" operation="start" operation_key="base-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="50">
    <action_set>
      <rsc_op id="115" operation="monitor" operation_key="app:0_monitor_16000" on_node="app-bundle-0" on_node_uuid="app-bundle-0" router_node="node2">
        <primitive id="app" long-id="app:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_container_attribute_target="host" CRM_meta_globally_unique="false" CRM_meta_interval="16000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_on_node="app-bundle-0" CRM_meta_on_node_uuid="app-bundle-0" CRM_meta_physical_host="node2" CRM_meta_promoted_max="1" CRM_meta_promoted_node_max="1" CRM_meta_role="Unpromoted" CRM_meta_timeout="16000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="100" operation="start" operation_key="app-bundle-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="114" operation="start" operation_key="app:0_start_0" on_node="app-bundle-0" on_node_uuid="app-bundle-0" router_node="node2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="51">
    <action_set>
      <rsc_op id="114" operation="start" operation_key="app:0_start_0" on_node="app-bundle-0" on_node_uuid="app-bundle-0" router_node="node2">
        <primitive id="app" long-id="app:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_container_attribute_target="host" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_on_node="app-bundle-0" CRM_meta_on_node_uuid="app-bundle-0" CRM_meta_physical_host="node2" CRM_meta_promoted_max="1" CRM_meta_promoted_node_max="1" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="98" operation="start" operation_key="app-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="100" operation="start" operation_key="app-bundle-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <pseudo_event id="120" operation="start" operation_key="app-bundle-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="52">
    <action_set>
      <rsc_op id="117" operation="monitor" operation_key="app:1_monitor_16000" on_node="app-bundle-1" on_node_uuid="app-bundle-1" router_node="node3">
        <primitive id="app" long-id="app:1" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_container_attribute_target="host" CRM_meta_globally_unique="false" CRM_meta_interval="16000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_on_node="app-bundle-1" CRM_meta_on_node_uuid="app-bundle-1" CRM_meta_physical_host="node3" CRM_meta_promoted_max="1" CRM_meta_promoted_node_max="1" CRM_meta_role="Unpromoted" CRM_meta_timeout="16000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="104" operation="start" operation_key="app-bundle-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="116" operation="start" operation_key="app:1_start_0" on_node="app-bundle-1" on_node_uuid="app-bundle-1" router_node="node3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="53">
    <action_set>
      <rsc_op id="116" operation="start" operation_key="app:1_start_0" on_node="app-bundle-1" on_node_uuid="app-bundle-1" router_node="node3">
        <primitive id="app" long-id="app:1" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_container_attribute_target="host" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_on_node="app-bundle-1" CRM_meta_on_node_uuid="app-bundle-1" CRM_meta_physical_host="node3" CRM_meta_promoted_max="1" CRM_meta_promoted_node_max="1" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="102" operation="start" operation_key="app-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="104" operation="start" operation_key="app-bundle-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="114" operation="start" operation_key="app:0_start_0" on_node="app-bundle-0" on_node_uuid="app-bundle-0" router_node="node2"/>
      </trigger>
      <trigger>
        <pseudo_event id="120" operation="start" operation_key="app-bundle-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="54">
    <action_set>
      <rsc_op id="119" operation="monitor" operation_key="app:2_monitor_16000" on_node="app-bundle-2" on_node_uuid="app-bundle-2" router_node="node4">
        <primitive id="app" long-id="app:2" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_container_attribute_target="host" CRM_meta_globally_unique="false" CRM_meta_interval="16000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_on_node="app-bundle-2" CRM_meta_on_node_uuid="app-bundle-2" CRM_meta_physical_host="node4" CRM_meta_promoted_max="1" CRM_meta_promoted_node_max="1" CRM_meta_role="Unpromoted" CRM_meta_timeout="16000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="108" operation="start" operation_key="app-bundle-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="118" operation="start" operation_key="app:2_start_0" on_node="app-bundle-2" on_node_uuid="app-bundle-2" router_node="node4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="55">
    <action_set>
      <rsc_op id="118" operation="start" operation_key="app:2_start_0" on_node="app-bundle-2" on_node_uuid="app-bundle-2" router_node="node4">
        <primitive id="app" long-id="app:2" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_container_attribute_target="host" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_on_node="app-bundle-2" CRM_meta_on_node_uuid="app-bundle-2" CRM_meta_physical_host="node4" CRM_meta_promoted_max="1" CRM_meta_promoted_node_max="1" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="106" operation="start" operation_key="app-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="108" operation="start" operation_key="app-bundle-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="116" operation="start" operation_key="app:1_start_0" on_node="app-bundle-1" on_node_uuid="app-bundle-1" router_node="node3"/>
      </trigger>
      <trigger>
        <pseudo_event id="120" operation="start" operation_key="app-bundle-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="56" priority="1000000">
    <action_set>
      <pseudo_event id="121" operation="running" operation_key="app-bundle-clone_running_0">
        <attributes CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_promoted_max="1" CRM_meta_promoted_node_max="1" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="114" operation="start" operation_key="app:0_start_0" on_node="app-bundle-0" on_node_uuid="app-bundle-0" router_node="node2"/>
      </trigger>
      <trigger>
        <rsc_op id="116" operation="start" operation_key="app:1_start_0" on_node="app-bundle-1" on_node_uuid="app-bundle-1" router_node="node3"/>
      </trigger>
      <trigger>
        <rsc_op id="118" operation="start" operation_key="app:2_start_0" on_node="app-bundle-2" on_node_uuid="app-bundle-2" router_node="node4"/>
      </trigger>
      <trigger>
        <pseudo_event id="120" operation="start" operation_key="app-bundle-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="57">
    <action_set>
      <pseudo_event id="120" operation="start" operation_key="app-bundle-clone_start_0">
        <attributes CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_promoted_max="1" CRM_meta_promoted_node_max="1" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="8" operation="monitor" operation_key="app-bundle-podman-0_monitor_0" on_node="node1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="10" operation="monitor" operation_key="app-bundle-podman-1_monitor_0" on_node="node1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="12" operation="monitor" operation_key="app-bundle-podman-2_monitor_0" on_node="node1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="20" operation="monitor" operation_key="app-bundle-podman-0_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="22" operation="monitor" operation_key="app-bundle-podman-1_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="24" operation="monitor" operation_key="app-bundle-podman-2_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="32" operation="monitor" operation_key="app-bundle-podman-0_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="34" operation="monitor" operation_key="app-bundle-podman-1_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="36" operation="monitor" operation_key="app-bundle-podman-2_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="44" operation="monitor" operation_key="app-bundle-podman-0_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="46" operation="monitor" operation_key="app-bundle-podman-1_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="48" operation="monitor" operation_key="app-bundle-podman-2_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="56" operation="monitor" operation_key="app-bundle-podman-0_monitor_0" on_node="node5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <rsc_op id="58" operation="monitor" operation_key="app-bundle-podman-1_monitor_0" on_node="node5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <rsc_op id="60" operation="monitor" operation_key="app-bundle-podman-2_monitor_0" on_node="node5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <pseudo_event id="110" operation="start" operation_key="app-bundle_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="58">
    <action_set>
      <rsc_op id="99" operation="monitor" operation_key="app-bundle-podman-0_monitor_60000" on_node="node2" on_node_uuid="2">
        <primitive id="app-bundle-podman-0" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_interval="60000" CRM_meta_name="monitor" CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-0" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-0:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="98" operation="start" operation_key="app-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="59">
    <action_set>
      <rsc_op id="98" operation="start" operation_key="app-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2">
        <primitive id="app-bundle-podman-0" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-0" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-0:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="8" operation="monitor" operation_key="app-bundle-podman-0_monitor_0" on_node="node1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="20" operation="monitor" operation_key="app-bundle-podman-0_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="22" operation="monitor" operation_key="app-bundle-podman-1_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="24" operation="monitor" operation_key="app-bundle-podman-2_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="32" operation="monitor" operation_key="app-bundle-podman-0_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="44" operation="monitor" operation_key="app-bundle-podman-0_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="56" operation="monitor" operation_key="app-bundle-podman-0_monitor_0" on_node="node5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <rsc_op id="80" operation="start" operation_key="base:0_start_0" on_node="base-bundle-0" on_node_uuid="base-bundle-0" router_node="node2"/>
      </trigger>
      <trigger>
        <pseudo_event id="110" operation="start" operation_key="app-bundle_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="60">
    <action_set>
      <rsc_op id="56" operation="monitor" operation_key="app-bundle-podman-0_monitor_0" on_node="node5" on_node_uuid="5">
        <primitive id="app-bundle-podman-0" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-0" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-0:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="61">
    <action_set>
      <rsc_op id="44" operation="monitor" operation_key="app-bundle-podman-0_monitor_0" on_node="node4" on_node_uuid="4">
        <primitive id="app-bundle-podman-0" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-0" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-0:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="62">
    <action_set>
      <rsc_op id="32" operation="monitor" operation_key="app-bundle-podman-0_monitor_0" on_node="node3" on_node_uuid="3">
        <primitive id="app-bundle-podman-0" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-0" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-0:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="63">
    <action_set>
      <rsc_op id="20" operation="monitor" operation_key="app-bundle-podman-0_monitor_0" on_node="node2" on_node_uuid="2">
        <primitive id="app-bundle-podman-0" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-0" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-0:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="64">
    <action_set>
      <rsc_op id="8" operation="monitor" operation_key="app-bundle-podman-0_monitor_0" on_node="node1" on_node_uuid="1">
        <primitive id="app-bundle-podman-0" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-0" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-0:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="65">
    <action_set>
      <rsc_op id="101" operation="monitor" operation_key="app-bundle-0_monitor_30000" on_node="node2" on_node_uuid="2">
        <primitive id="app-bundle-0" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-0" CRM_meta_interval="30000" CRM_meta_name="monitor" CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_timeout="30000" addr="node2"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="100" operation="start" operation_key="app-bundle-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="66">
    <action_set>
      <rsc_op id="100" operation="start" operation_key="app-bundle-0_start_0" on_node="node2" on_node_uuid="2">
        <primitive id="app-bundle-0" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-0" CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_timeout="20000" addr="node2"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="9" operation="monitor" operation_key="app-bundle-0_monitor_0" on_node="node1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="21" operation="monitor" operation_key="app-bundle-0_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="33" operation="monitor" operation_key="app-bundle-0_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="45" operation="monitor" operation_key="app-bundle-0_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="57" operation="monitor" operation_key="app-bundle-0_monitor_0" on_node="node5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <rsc_op id="98" operation="start" operation_key="app-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="67">
    <action_set>
      <rsc_op id="57" operation="monitor" operation_key="app-bundle-0_monitor_0" on_node="node5" on_node_uuid="5">
        <primitive id="app-bundle-0" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-0" CRM_meta_on_node="node5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node2"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="98" operation="start" operation_key="app-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="68">
    <action_set>
      <rsc_op id="45" operation="monitor" operation_key="app-bundle-0_monitor_0" on_node="node4" on_node_uuid="4">
        <primitive id="app-bundle-0" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-0" CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node2"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="98" operation="start" operation_key="app-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="69">
    <action_set>
      <rsc_op id="33" operation="monitor" operation_key="app-bundle-0_monitor_0" on_node="node3" on_node_uuid="3">
        <primitive id="app-bundle-0" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-0" CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node2"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="98" operation="start" operation_key="app-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="70">
    <action_set>
      <rsc_op id="21" operation="monitor" operation_key="app-bundle-0_monitor_0" on_node="node2" on_node_uuid="2">
        <primitive id="app-bundle-0" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-0" CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node2"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="98" operation="start" operation_key="app-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="71">
    <action_set>
      <rsc_op id="9" operation="monitor" operation_key="app-bundle-0_monitor_0" on_node="node1" on_node_uuid="1">
        <primitive id="app-bundle-0" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-0" CRM_meta_on_node="node1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node2"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="98" operation="start" operation_key="app-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="72">
    <action_set>
      <rsc_op id="103" operation="monitor" operation_key="app-bundle-podman-1_monitor_60000" on_node="node3" on_node_uuid="3">
        <primitive id="app-bundle-podman-1" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_interval="60000" CRM_meta_name="monitor" CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-1" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-1:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="102" operation="start" operation_key="app-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="73">
    <action_set>
      <rsc_op id="102" operation="start" operation_key="app-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3">
        <primitive id="app-bundle-podman-1" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-1" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-1:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="10" operation="monitor" operation_key="app-bundle-podman-1_monitor_0" on_node="node1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="22" operation="monitor" operation_key="app-bundle-podman-1_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="32" operation="monitor" operation_key="app-bundle-podman-0_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="34" operation="monitor" operation_key="app-bundle-podman-1_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="36" operation="monitor" operation_key="app-bundle-podman-2_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="46" operation="monitor" operation_key="app-bundle-podman-1_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="58" operation="monitor" operation_key="app-bundle-podman-1_monitor_0" on_node="node5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <rsc_op id="82" operation="start" operation_key="base:1_start_0" on_node="base-bundle-1" on_node_uuid="base-bundle-1" router_node="node3"/>
      </trigger>
      <trigger>
        <pseudo_event id="110" operation="start" operation_key="app-bundle_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="74">
    <action_set>
      <rsc_op id="58" operation="monitor" operation_key="app-bundle-podman-1_monitor_0" on_node="node5" on_node_uuid="5">
        <primitive id="app-bundle-podman-1" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-1" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-1:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="75">
    <action_set>
      <rsc_op id="46" operation="monitor" operation_key="app-bundle-podman-1_monitor_0" on_node="node4" on_node_uuid="4">
        <primitive id="app-bundle-podman-1" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-1" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-1:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="76">
    <action_set>
      <rsc_op id="34" operation="monitor" operation_key="app-bundle-podman-1_monitor_0" on_node="node3" on_node_uuid="3">
        <primitive id="app-bundle-podman-1" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-1" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-1:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="77">
    <action_set>
      <rsc_op id="22" operation="monitor" operation_key="app-bundle-podman-1_monitor_0" on_node="node2" on_node_uuid="2">
        <primitive id="app-bundle-podman-1" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-1" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-1:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="78">
    <action_set>
      <rsc_op id="10" operation="monitor" operation_key="app-bundle-podman-1_monitor_0" on_node="node1" on_node_uuid="1">
        <primitive id="app-bundle-podman-1" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-1" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-1:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="79">
    <action_set>
      <rsc_op id="105" operation="monitor" operation_key="app-bundle-1_monitor_30000" on_node="node3" on_node_uuid="3">
        <primitive id="app-bundle-1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-1" CRM_meta_interval="30000" CRM_meta_name="monitor" CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="30000" addr="node3"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="104" operation="start" operation_key="app-bundle-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="80">
    <action_set>
      <rsc_op id="104" operation="start" operation_key="app-bundle-1_start_0" on_node="node3" on_node_uuid="3">
        <primitive id="app-bundle-1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-1" CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="20000" addr="node3"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="11" operation="monitor" operation_key="app-bundle-1_monitor_0" on_node="node1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="23" operation="monitor" operation_key="app-bundle-1_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="35" operation="monitor" operation_key="app-bundle-1_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="47" operation="monitor" operation_key="app-bundle-1_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="59" operation="monitor" operation_key="app-bundle-1_monitor_0" on_node="node5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <rsc_op id="102" operation="start" operation_key="app-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="81">
    <action_set>
      <rsc_op id="59" operation="monitor" operation_key="app-bundle-1_monitor_0" on_node="node5" on_node_uuid="5">
        <primitive id="app-bundle-1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-1" CRM_meta_on_node="node5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node3"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="102" operation="start" operation_key="app-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="82">
    <action_set>
      <rsc_op id="47" operation="monitor" operation_key="app-bundle-1_monitor_0" on_node="node4" on_node_uuid="4">
        <primitive id="app-bundle-1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-1" CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node3"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="102" operation="start" operation_key="app-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="83">
    <action_set>
      <rsc_op id="35" operation="monitor" operation_key="app-bundle-1_monitor_0" on_node="node3" on_node_uuid="3">
        <primitive id="app-bundle-1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-1" CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node3"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="102" operation="start" operation_key="app-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="84">
    <action_set>
      <rsc_op id="23" operation="monitor" operation_key="app-bundle-1_monitor_0" on_node="node2" on_node_uuid="2">
        <primitive id="app-bundle-1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-1" CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node3"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="102" operation="start" operation_key="app-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="85">
    <action_set>
      <rsc_op id="11" operation="monitor" operation_key="app-bundle-1_monitor_0" on_node="node1" on_node_uuid="1">
        <primitive id="app-bundle-1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-1" CRM_meta_on_node="node1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node3"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="102" operation="start" operation_key="app-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="86">
    <action_set>
      <rsc_op id="107" operation="monitor" operation_key="app-bundle-podman-2_monitor_60000" on_node="node4" on_node_uuid="4">
        <primitive id="app-bundle-podman-2" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_interval="60000" CRM_meta_name="monitor" CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-2" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-2:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="106" operation="start" operation_key="app-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="87">
    <action_set>
      <rsc_op id="106" operation="start" operation_key="app-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4">
        <primitive id="app-bundle-podman-2" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-2" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-2:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="12" operation="monitor" operation_key="app-bundle-podman-2_monitor_0" on_node="node1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="24" operation="monitor" operation_key="app-bundle-podman-2_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="36" operation="monitor" operation_key="app-bundle-podman-2_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="44" operation="monitor" operation_key="app-bundle-podman-0_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="46" operation="monitor" operation_key="app-bundle-podman-1_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="48" operation="monitor" operation_key="app-bundle-podman-2_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="60" operation="monitor" operation_key="app-bundle-podman-2_monitor_0" on_node="node5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <rsc_op id="84" operation="start" operation_key="base:2_start_0" on_node="base-bundle-2" on_node_uuid="base-bundle-2" router_node="node4"/>
      </trigger>
      <trigger>
        <pseudo_event id="110" operation="start" operation_key="app-bundle_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="88">
    <action_set>
      <rsc_op id="60" operation="monitor" operation_key="app-bundle-podman-2_monitor_0" on_node="node5" on_node_uuid="5">
        <primitive id="app-bundle-podman-2" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-2" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-2:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="89">
    <action_set>
      <rsc_op id="48" operation="monitor" operation_key="app-bundle-podman-2_monitor_0" on_node="node4" on_node_uuid="4">
        <primitive id="app-bundle-podman-2" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-2" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-2:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="90">
    <action_set>
      <rsc_op id="36" operation="monitor" operation_key="app-bundle-podman-2_monitor_0" on_node="node3" on_node_uuid="3">
        <primitive id="app-bundle-podman-2" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-2" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-2:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="91">
    <action_set>
      <rsc_op id="24" operation="monitor" operation_key="app-bundle-podman-2_monitor_0" on_node="node2" on_node_uuid="2">
        <primitive id="app-bundle-podman-2" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-2" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-2:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="92">
    <action_set>
      <rsc_op id="12" operation="monitor" operation_key="app-bundle-podman-2_monitor_0" on_node="node1" on_node_uuid="1">
        <primitive id="app-bundle-podman-2" class="ocf" provider="heartbeat" type="podman"/>
        <attributes CRM_meta_on_node="node1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" allow_pull="true"  force_kill="false" image="localhost/pcmktest:app" monitor_cmd="/bin/true" mount_points="/var/log/pacemaker/bundles/app-bundle-2" reuse="false" run_cmd="/usr/sbin/pacemaker-remoted" run_opts=" -e PCMK_stderr=1 -e PCMK_remote_port=3121 -v /etc/pacemaker/authkey:/etc/pacemaker/authkey -v /var/log/pacemaker/bundles/app-bundle-2:/var/log -p 3121:3121 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="93">
    <action_set>
      <rsc_op id="109" operation="monitor" operation_key="app-bundle-2_monitor_30000" on_node="node4" on_node_uuid="4">
        <primitive id="app-bundle-2" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-2" CRM_meta_interval="30000" CRM_meta_name="monitor" CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="30000" addr="node4"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="108" operation="start" operation_key="app-bundle-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="94">
    <action_set>
      <rsc_op id="108" operation="start" operation_key="app-bundle-2_start_0" on_node="node4" on_node_uuid="4">
        <primitive id="app-bundle-2" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-2" CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="20000" addr="node4"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="13" operation="monitor" operation_key="app-bundle-2_monitor_0" on_node="node1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="25" operation="monitor" operation_key="app-bundle-2_monitor_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="37" operation="monitor" operation_key="app-bundle-2_monitor_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="49" operation="monitor" operation_key="app-bundle-2_monitor_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="61" operation="monitor" operation_key="app-bundle-2_monitor_0" on_node="node5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <rsc_op id="106" operation="start" operation_key="app-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="95">
    <action_set>
      <rsc_op id="61" operation="monitor" operation_key="app-bundle-2_monitor_0" on_node="node5" on_node_uuid="5">
        <primitive id="app-bundle-2" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-2" CRM_meta_on_node="node5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node4"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="106" operation="start" operation_key="app-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="96">
    <action_set>
      <rsc_op id="49" operation="monitor" operation_key="app-bundle-2_monitor_0" on_node="node4" on_node_uuid="4">
        <primitive id="app-bundle-2" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-2" CRM_meta_on_node="node4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node4"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="106" operation="start" operation_key="app-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="97">
    <action_set>
      <rsc_op id="37" operation="monitor" operation_key="app-bundle-2_monitor_0" on_node="node3" on_node_uuid="3">
        <primitive id="app-bundle-2" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-2" CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node4"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="106" operation="start" operation_key="app-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="98">
    <action_set>
      <rsc_op id="25" operation="monitor" operation_key="app-bundle-2_monitor_0" on_node="node2" on_node_uuid="2">
        <primitive id="app-bundle-2" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-2" CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node4"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="106" operation="start" operation_key="app-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="99">
    <action_set>
      <rsc_op id="13" operation="monitor" operation_key="app-bundle-2_monitor_0" on_node="node1" on_node_uuid="1">
        <primitive id="app-bundle-2" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="app-bundle-podman-2" CRM_meta_on_node="node1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="30000" addr="node4"  port="3121"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="106" operation="start" operation_key="app-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="100" priority="1000000">
    <action_set>
      <pseudo_event id="111" operation="running" operation_key="app-bundle_running_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="98" operation="start" operation_key="app-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="102" operation="start" operation_key="app-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="106" operation="start" operation_key="app-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <pseudo_event id="121" operation="running" operation_key="app-bundle-clone_running_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="101">
    <action_set>
      <pseudo_event id="110" operation="start" operation_key="app-bundle_start_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="77" operation="running" operation_key="base-bundle_running_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="102" priority="1000000">
    <action_set>
      <pseudo_event id="77" operation="running" operation_key="base-bundle_running_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="64" operation="start" operation_key="base-bundle-podman-0_start_0" on_node="node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="68" operation="start" operation_key="base-bundle-podman-1_start_0" on_node="node3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="72" operation="start" operation_key="base-bundle-podman-2_start_0" on_node="node4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <pseudo_event id="87" operation="running" operation_key="base-bundle-clone_running_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="103">
    <action_set>
      <pseudo_event id="76" operation="start" operation_key="base-bundle_start_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
</transition_graph>
