<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="1"  transition_id="0">
  <synapse id="0">
    <action_set>
      <pseudo_event id="42" operation="stopped" operation_key="dummy2_stopped_0">
        <attributes CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="27" operation="stop" operation_key="dummy2a_stop_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="30" operation="stop" operation_key="dummy2b_stop_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="33" operation="stop" operation_key="dummy2c_stop_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="36" operation="stop" operation_key="dummy2d_stop_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="stop" operation_key="dummy2_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <pseudo_event id="41" operation="stop" operation_key="dummy2_stop_0">
        <attributes CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="2">
    <action_set>
      <pseudo_event id="40" operation="running" operation_key="dummy2_running_0">
        <attributes CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="28" operation="start" operation_key="dummy2a_start_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="31" operation="start" operation_key="dummy2b_start_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="34" operation="start" operation_key="dummy2c_start_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="37" operation="start" operation_key="dummy2d_start_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <pseudo_event id="39" operation="start" operation_key="dummy2_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <pseudo_event id="39" operation="start" operation_key="dummy2_start_0">
        <attributes CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="42" operation="stopped" operation_key="dummy2_stopped_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <rsc_op id="29" operation="monitor" operation_key="dummy2a_monitor_10000" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="dummy2a" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="28" operation="start" operation_key="dummy2a_start_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <rsc_op id="28" operation="start" operation_key="dummy2a_start_0" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="dummy2a" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_name="start" CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="27" operation="stop" operation_key="dummy2a_stop_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <pseudo_event id="39" operation="start" operation_key="dummy2_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <rsc_op id="27" operation="stop" operation_key="dummy2a_stop_0" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="dummy2a" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_name="stop" CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="30" operation="stop" operation_key="dummy2b_stop_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="stop" operation_key="dummy2_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <rsc_op id="32" operation="monitor" operation_key="dummy2b_monitor_10000" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="dummy2b" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="31" operation="start" operation_key="dummy2b_start_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <rsc_op id="31" operation="start" operation_key="dummy2b_start_0" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="dummy2b" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_name="start" CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="28" operation="start" operation_key="dummy2a_start_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="30" operation="stop" operation_key="dummy2b_stop_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <pseudo_event id="39" operation="start" operation_key="dummy2_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9">
    <action_set>
      <rsc_op id="30" operation="stop" operation_key="dummy2b_stop_0" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="dummy2b" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_name="stop" CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="33" operation="stop" operation_key="dummy2c_stop_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="stop" operation_key="dummy2_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="10">
    <action_set>
      <rsc_op id="35" operation="monitor" operation_key="dummy2c_monitor_10000" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="dummy2c" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="34" operation="start" operation_key="dummy2c_start_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="11">
    <action_set>
      <rsc_op id="34" operation="start" operation_key="dummy2c_start_0" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="dummy2c" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_name="start" CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="31" operation="start" operation_key="dummy2b_start_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="33" operation="stop" operation_key="dummy2c_stop_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <pseudo_event id="39" operation="start" operation_key="dummy2_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="12">
    <action_set>
      <rsc_op id="33" operation="stop" operation_key="dummy2c_stop_0" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="dummy2c" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_name="stop" CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="36" operation="stop" operation_key="dummy2d_stop_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="stop" operation_key="dummy2_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="13">
    <action_set>
      <rsc_op id="38" operation="monitor" operation_key="dummy2d_monitor_10000" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="dummy2d" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="37" operation="start" operation_key="dummy2d_start_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="14">
    <action_set>
      <rsc_op id="37" operation="start" operation_key="dummy2d_start_0" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="dummy2d" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_name="start" CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="34" operation="start" operation_key="dummy2c_start_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="36" operation="stop" operation_key="dummy2d_stop_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <pseudo_event id="39" operation="start" operation_key="dummy2_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="15">
    <action_set>
      <rsc_op id="36" operation="stop" operation_key="dummy2d_stop_0" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="dummy2d" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_name="stop" CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="41" operation="stop" operation_key="dummy2_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>
