<?xml version="1.0"?>
<!DOCTYPE transition_graph SYSTEM "crm-1.0.dtd">
<?xml version="1.0"?>
<transition_graph>
  <synapse>
    <action_set>
      <rsc_op id="2" rsc_id="rsc1" on_node="node1" on_node_uuid="node1" operation="start" allow_fail="false" optional="false" runnable="true" discard="false">
        <resource id="rsc1" type="apache" priority="1.0"/>
        <args/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
</transition_graph>
