 <transition_graph global_timeout="60s" transition_id="0">
   <synapse id="0">
     <action_set>
       <rsc_op id="1" rsc_id="rsc1" operation="start" operation_key="rsc1_start_0" on_node="node2" on_node_uuid="uuid2" allow_fail="false">
         <primitive id="rsc1" class="heartbeat" type="apache"/>
         <attributes>
           <nvpair name="interface" value="eth2"/>
         </attributes>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
 </transition_graph>

