<transition_graph global_timeout="60000">
  <synapse id="0">
    <action_set>
      <rsc_op id="1" rsc_id="rsc2" operation="start" on_node="node1" on_node_uuid="node1" allow_fail="false">
         <resource id="rsc2" class="heartbeat" type="apache"/>
         <attributes>
           <nvpair name="priority" value="2.0"/>
         </attributes>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
</transition_graph>

