#!/bin/sh

done=0
options=""
target=`uname -n`
lifetime=0
do_get=1
op='g'

while test "$done" = "0"; do
    case "$1" in
	-N|--node) target="$2"; shift; shift;;
	-v|--attr-value) options="$options $1 $2"; op=u; shift; shift;;
	-D|--delete-attr) options="$options $1"; op=d; shift;;
	-G|--get-value) options="$options $1"; op=g; shift;;
	-i|--attr-id) options="$options $1 $2"; shift; shift;;
	-l|--lifetime) options="$options $1 $2"; lifetime=1; shift; shift;;
	-Q|--quiet|-V|-VV|-VVV) options="$options $1"; shift;;
	"") done=1;;
	*) echo "crm_standby - A convenience wrapper for crm_attribute"; echo ""; crm_attribute -?; exit 1;;
    esac
done

case $op in
    g)
	crm_attribute -N $target -n standby $cmd $options -l forever 2>&1 > /dev/null
	if [ $? = 0 ]; then
	    crm_attribute -N $target -n standby $options -l forever
	    exit 0
	fi

	crm_attribute -N $target -n standby $cmd $options -l reboot -d off
	;;
    u) 
	if [ $lifetime = 0 ]; then
	    options="$options -l forever"
	fi
	crm_attribute -N $target -n standby $options 
	;;
    d) 
	if [ $lifetime = 0 ]; then
	    crm_attribute -N $target -n standby $options -l forever
	    crm_attribute -N $target -n standby $options -l reboot 

	else
	    crm_attribute -N $target -n standby $options 
	fi
	;;
esac
