 <transition_graph cluster-delay="120s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
   <synapse id="0">
     <action_set>
      <rsc_op id="26" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="c001n04" on_node_uuid="c2896699-96b8-4dbc-a94e-6c3b9252b559">
        <primitive id="DcIPaddr" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.10"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="1">
     <action_set>
      <rsc_op id="19" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193">
        <primitive id="DcIPaddr" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.10"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="2">
     <action_set>
      <rsc_op id="13" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f">
        <primitive id="DcIPaddr" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.10"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="3">
     <action_set>
      <rsc_op id="27" operation="monitor" operation_key="rsc_c001n09_monitor_0" on_node="c001n04" on_node_uuid="c2896699-96b8-4dbc-a94e-6c3b9252b559">
        <primitive id="rsc_c001n09" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.11"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="4">
     <action_set>
      <rsc_op id="20" operation="monitor" operation_key="rsc_c001n09_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193">
        <primitive id="rsc_c001n09" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.11"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="5">
     <action_set>
      <rsc_op id="14" operation="monitor" operation_key="rsc_c001n09_monitor_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f">
        <primitive id="rsc_c001n09" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.11"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="6">
     <action_set>
      <rsc_op id="45" operation="monitor" operation_key="rsc_c001n02_monitor_5000" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193">
        <primitive id="rsc_c001n02" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.12"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <rsc_op id="44" operation="start" operation_key="rsc_c001n02_start_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="7">
     <action_set>
      <rsc_op id="44" operation="start" operation_key="rsc_c001n02_start_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193">
        <primitive id="rsc_c001n02" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.12"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="11" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <rsc_op id="43" operation="stop" operation_key="rsc_c001n02_stop_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="8">
     <action_set>
      <rsc_op id="43" operation="stop" operation_key="rsc_c001n02_stop_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f">
        <primitive id="rsc_c001n02" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.12"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="11" operation="probe_complete" operation_key="probe_complete"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="9">
    <action_set>
      <rsc_op id="34" operation="monitor" operation_key="rsc_c001n02_monitor_0" on_node="c001n09" on_node_uuid="f67904e0-4dfc-4db1-83a2-e930fc1d20f4">
        <primitive id="rsc_c001n02" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.12"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
   <synapse id="10">
     <action_set>
      <rsc_op id="28" operation="monitor" operation_key="rsc_c001n02_monitor_0" on_node="c001n04" on_node_uuid="c2896699-96b8-4dbc-a94e-6c3b9252b559">
        <primitive id="rsc_c001n02" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.12"/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="11">
     <action_set>
      <rsc_op id="21" operation="monitor" operation_key="rsc_c001n02_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193">
        <primitive id="rsc_c001n02" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.12"/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="12">
     <action_set>
      <rsc_op id="35" operation="monitor" operation_key="rsc_c001n03_monitor_0" on_node="c001n09" on_node_uuid="f67904e0-4dfc-4db1-83a2-e930fc1d20f4">
        <primitive id="rsc_c001n03" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.13"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="13">
     <action_set>
      <rsc_op id="29" operation="monitor" operation_key="rsc_c001n03_monitor_0" on_node="c001n04" on_node_uuid="c2896699-96b8-4dbc-a94e-6c3b9252b559">
        <primitive id="rsc_c001n03" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.13"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="14">
     <action_set>
      <rsc_op id="15" operation="monitor" operation_key="rsc_c001n03_monitor_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f">
        <primitive id="rsc_c001n03" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.13"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="15">
     <action_set>
      <rsc_op id="36" operation="monitor" operation_key="rsc_c001n04_monitor_0" on_node="c001n09" on_node_uuid="f67904e0-4dfc-4db1-83a2-e930fc1d20f4">
        <primitive id="rsc_c001n04" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.14"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="16">
     <action_set>
      <rsc_op id="22" operation="monitor" operation_key="rsc_c001n04_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193">
        <primitive id="rsc_c001n04" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.14"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="17">
     <action_set>
      <rsc_op id="50" operation="stop" operation_key="child_DoFencing:0_stop_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f">
        <primitive id="child_DoFencing:0" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostlist="c001n09 c001n02 c001n03 c001n04 "/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="10" operation="all_stopped" operation_key="all_stopped"/>
      </trigger>
      <trigger>
        <pseudo_event id="11" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="59" operation="stop" operation_key="DoFencing_stop_0"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="18">
     <action_set>
      <rsc_op id="37" operation="monitor" operation_key="child_DoFencing:0_monitor_0" on_node="c001n09" on_node_uuid="f67904e0-4dfc-4db1-83a2-e930fc1d20f4">
        <primitive id="child_DoFencing:0" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostlist="c001n09 c001n02 c001n03 c001n04 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="19">
     <action_set>
      <rsc_op id="30" operation="monitor" operation_key="child_DoFencing:0_monitor_0" on_node="c001n04" on_node_uuid="c2896699-96b8-4dbc-a94e-6c3b9252b559">
        <primitive id="child_DoFencing:0" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostlist="c001n09 c001n02 c001n03 c001n04 "/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="20">
     <action_set>
      <rsc_op id="31" operation="monitor" operation_key="child_DoFencing:1_monitor_0" on_node="c001n04" on_node_uuid="c2896699-96b8-4dbc-a94e-6c3b9252b559">
        <primitive id="child_DoFencing:1" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostlist="c001n09 c001n02 c001n03 c001n04 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="21">
     <action_set>
      <rsc_op id="16" operation="monitor" operation_key="child_DoFencing:1_monitor_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f">
        <primitive id="child_DoFencing:1" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostlist="c001n09 c001n02 c001n03 c001n04 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="22">
     <action_set>
      <rsc_op id="38" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="c001n09" on_node_uuid="f67904e0-4dfc-4db1-83a2-e930fc1d20f4">
        <primitive id="child_DoFencing:2" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostlist="c001n09 c001n02 c001n03 c001n04 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="23">
     <action_set>
      <rsc_op id="23" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193">
        <primitive id="child_DoFencing:2" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostlist="c001n09 c001n02 c001n03 c001n04 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="24">
     <action_set>
      <rsc_op id="32" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="c001n04" on_node_uuid="c2896699-96b8-4dbc-a94e-6c3b9252b559">
        <primitive id="child_DoFencing:3" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostlist="c001n09 c001n02 c001n03 c001n04 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="25">
     <action_set>
      <rsc_op id="24" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193">
        <primitive id="child_DoFencing:3" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostlist="c001n09 c001n02 c001n03 c001n04 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="26">
     <action_set>
      <rsc_op id="17" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f">
        <primitive id="child_DoFencing:3" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostlist="c001n09 c001n02 c001n03 c001n04 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="27" priority="1000000">
     <action_set>
       <pseudo_event id="60" operation="stopped" operation_key="DoFencing_stopped_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <rsc_op id="50" operation="stop" operation_key="child_DoFencing:0_stop_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f"/>
       </trigger>
       <trigger>
         <pseudo_event id="59" operation="stop" operation_key="DoFencing_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="28">
     <action_set>
      <pseudo_event id="59" operation="stop" operation_key="DoFencing_stop_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
    <inputs/>
  </synapse>
  <synapse id="29">
    <action_set>
      <crm_event id="63" operation="do_shutdown" operation_key="do_shutdown" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.6"/>
      </crm_event>
    </action_set>
     <inputs>
       <trigger>
        <rsc_op id="43" operation="stop" operation_key="rsc_c001n02_stop_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f"/>
       </trigger>
      <trigger>
        <rsc_op id="50" operation="stop" operation_key="child_DoFencing:0_stop_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f"/>
      </trigger>
     </inputs>
   </synapse>
  <synapse id="30" priority="1000000">
     <action_set>
      <rsc_op id="33" operation="probe_complete" operation_key="probe_complete" on_node="c001n09" on_node_uuid="f67904e0-4dfc-4db1-83a2-e930fc1d20f4">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.6"/>
      </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="34" operation="monitor" operation_key="rsc_c001n02_monitor_0" on_node="c001n09" on_node_uuid="f67904e0-4dfc-4db1-83a2-e930fc1d20f4"/>
       </trigger>
       <trigger>
        <rsc_op id="35" operation="monitor" operation_key="rsc_c001n03_monitor_0" on_node="c001n09" on_node_uuid="f67904e0-4dfc-4db1-83a2-e930fc1d20f4"/>
       </trigger>
       <trigger>
        <rsc_op id="36" operation="monitor" operation_key="rsc_c001n04_monitor_0" on_node="c001n09" on_node_uuid="f67904e0-4dfc-4db1-83a2-e930fc1d20f4"/>
       </trigger>
       <trigger>
        <rsc_op id="37" operation="monitor" operation_key="child_DoFencing:0_monitor_0" on_node="c001n09" on_node_uuid="f67904e0-4dfc-4db1-83a2-e930fc1d20f4"/>
      </trigger>
      <trigger>
        <rsc_op id="38" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="c001n09" on_node_uuid="f67904e0-4dfc-4db1-83a2-e930fc1d20f4"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="31" priority="1000000">
     <action_set>
      <rsc_op id="25" operation="probe_complete" operation_key="probe_complete" on_node="c001n04" on_node_uuid="c2896699-96b8-4dbc-a94e-6c3b9252b559">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.6"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="26" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="c001n04" on_node_uuid="c2896699-96b8-4dbc-a94e-6c3b9252b559"/>
       </trigger>
       <trigger>
        <rsc_op id="27" operation="monitor" operation_key="rsc_c001n09_monitor_0" on_node="c001n04" on_node_uuid="c2896699-96b8-4dbc-a94e-6c3b9252b559"/>
       </trigger>
       <trigger>
        <rsc_op id="28" operation="monitor" operation_key="rsc_c001n02_monitor_0" on_node="c001n04" on_node_uuid="c2896699-96b8-4dbc-a94e-6c3b9252b559"/>
       </trigger>
       <trigger>
        <rsc_op id="29" operation="monitor" operation_key="rsc_c001n03_monitor_0" on_node="c001n04" on_node_uuid="c2896699-96b8-4dbc-a94e-6c3b9252b559"/>
       </trigger>
       <trigger>
        <rsc_op id="30" operation="monitor" operation_key="child_DoFencing:0_monitor_0" on_node="c001n04" on_node_uuid="c2896699-96b8-4dbc-a94e-6c3b9252b559"/>
      </trigger>
      <trigger>
        <rsc_op id="31" operation="monitor" operation_key="child_DoFencing:1_monitor_0" on_node="c001n04" on_node_uuid="c2896699-96b8-4dbc-a94e-6c3b9252b559"/>
      </trigger>
      <trigger>
        <rsc_op id="32" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="c001n04" on_node_uuid="c2896699-96b8-4dbc-a94e-6c3b9252b559"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="32" priority="1000000">
     <action_set>
      <rsc_op id="18" operation="probe_complete" operation_key="probe_complete" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.6"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="19" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193"/>
      </trigger>
      <trigger>
        <rsc_op id="20" operation="monitor" operation_key="rsc_c001n09_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193"/>
       </trigger>
       <trigger>
        <rsc_op id="21" operation="monitor" operation_key="rsc_c001n02_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193"/>
       </trigger>
       <trigger>
        <rsc_op id="22" operation="monitor" operation_key="rsc_c001n04_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193"/>
       </trigger>
       <trigger>
        <rsc_op id="23" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193"/>
       </trigger>
       <trigger>
        <rsc_op id="24" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="33" priority="1000000">
     <action_set>
      <rsc_op id="12" operation="probe_complete" operation_key="probe_complete" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.6"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="13" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f"/>
       </trigger>
       <trigger>
        <rsc_op id="14" operation="monitor" operation_key="rsc_c001n09_monitor_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f"/>
       </trigger>
       <trigger>
        <rsc_op id="15" operation="monitor" operation_key="rsc_c001n03_monitor_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f"/>
       </trigger>
       <trigger>
        <rsc_op id="16" operation="monitor" operation_key="child_DoFencing:1_monitor_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f"/>
       </trigger>
       <trigger>
        <rsc_op id="17" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="34">
     <action_set>
      <pseudo_event id="11" operation="probe_complete" operation_key="probe_complete">
        <attributes crm_feature_set="3.0.6"/>
      </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="12" operation="probe_complete" operation_key="probe_complete" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f"/>
       </trigger>
       <trigger>
        <rsc_op id="18" operation="probe_complete" operation_key="probe_complete" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193"/>
       </trigger>
       <trigger>
        <rsc_op id="25" operation="probe_complete" operation_key="probe_complete" on_node="c001n04" on_node_uuid="c2896699-96b8-4dbc-a94e-6c3b9252b559"/>
       </trigger>
       <trigger>
        <rsc_op id="33" operation="probe_complete" operation_key="probe_complete" on_node="c001n09" on_node_uuid="f67904e0-4dfc-4db1-83a2-e930fc1d20f4"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="35">
     <action_set>
      <pseudo_event id="10" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.6"/>
      </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="43" operation="stop" operation_key="rsc_c001n02_stop_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f"/>
       </trigger>
     </inputs>
   </synapse>
 </transition_graph>

