 <transition_graph cluster-delay="120s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
   <synapse id="0">
     <action_set>
      <rsc_op id="39" operation="monitor" operation_key="DcIPaddr_monitor_5000" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a">
        <primitive id="DcIPaddr" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_timeout="20000"  ip="127.0.0.10"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="1">
     <action_set>
      <rsc_op id="24" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947">
        <primitive id="DcIPaddr" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  ip="127.0.0.10"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="2">
     <action_set>
      <rsc_op id="14" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8">
        <primitive id="DcIPaddr" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  ip="127.0.0.10"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="3">
     <action_set>
      <rsc_op id="4" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="DcIPaddr" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  ip="127.0.0.10"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="4">
     <action_set>
      <rsc_op id="41" operation="monitor" operation_key="rsc_sgi2_monitor_5000" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8">
        <primitive id="rsc_sgi2" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_timeout="20000"  ip="127.0.0.11"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <rsc_op id="40" operation="start" operation_key="rsc_sgi2_start_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="5">
     <action_set>
      <rsc_op id="40" operation="start" operation_key="rsc_sgi2_start_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8">
        <primitive id="rsc_sgi2" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="20000"  ip="127.0.0.11"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="6">
     <action_set>
      <rsc_op id="33" operation="monitor" operation_key="rsc_sgi2_monitor_0" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a">
        <primitive id="rsc_sgi2" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  ip="127.0.0.11"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="7">
     <action_set>
      <rsc_op id="25" operation="monitor" operation_key="rsc_sgi2_monitor_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947">
        <primitive id="rsc_sgi2" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  ip="127.0.0.11"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="8">
     <action_set>
      <rsc_op id="15" operation="monitor" operation_key="rsc_sgi2_monitor_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8">
        <primitive id="rsc_sgi2" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  ip="127.0.0.11"/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="9">
     <action_set>
      <rsc_op id="5" operation="monitor" operation_key="rsc_sgi2_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="rsc_sgi2" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  ip="127.0.0.11"/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="10">
     <action_set>
      <rsc_op id="44" operation="monitor" operation_key="rsc_ibm1_monitor_5000" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="rsc_ibm1" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_timeout="20000"  ip="127.0.0.12"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <rsc_op id="43" operation="start" operation_key="rsc_ibm1_start_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="11">
     <action_set>
      <rsc_op id="43" operation="start" operation_key="rsc_ibm1_start_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="rsc_ibm1" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="20000"  ip="127.0.0.12"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <rsc_op id="42" operation="stop" operation_key="rsc_ibm1_stop_0" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="12">
     <action_set>
      <rsc_op id="42" operation="stop" operation_key="rsc_ibm1_stop_0" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a">
        <primitive id="rsc_ibm1" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="20000"  ip="127.0.0.12"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="13">
    <action_set>
      <rsc_op id="26" operation="monitor" operation_key="rsc_ibm1_monitor_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947">
        <primitive id="rsc_ibm1" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  ip="127.0.0.12"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
   <synapse id="14">
     <action_set>
      <rsc_op id="16" operation="monitor" operation_key="rsc_ibm1_monitor_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8">
        <primitive id="rsc_ibm1" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  ip="127.0.0.12"/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="15">
     <action_set>
      <rsc_op id="6" operation="monitor" operation_key="rsc_ibm1_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="rsc_ibm1" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  ip="127.0.0.12"/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="16">
     <action_set>
      <rsc_op id="46" operation="monitor" operation_key="rsc_test02_monitor_5000" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947">
        <primitive id="rsc_test02" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_timeout="20000"  ip="127.0.0.13"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <rsc_op id="45" operation="start" operation_key="rsc_test02_start_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="17">
     <action_set>
      <rsc_op id="45" operation="start" operation_key="rsc_test02_start_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947">
        <primitive id="rsc_test02" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="20000"  ip="127.0.0.13"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="18">
     <action_set>
      <rsc_op id="34" operation="monitor" operation_key="rsc_test02_monitor_0" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a">
        <primitive id="rsc_test02" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  ip="127.0.0.13"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="19">
     <action_set>
      <rsc_op id="27" operation="monitor" operation_key="rsc_test02_monitor_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947">
        <primitive id="rsc_test02" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  ip="127.0.0.13"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="20">
     <action_set>
      <rsc_op id="17" operation="monitor" operation_key="rsc_test02_monitor_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8">
        <primitive id="rsc_test02" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  ip="127.0.0.13"/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="21">
     <action_set>
      <rsc_op id="7" operation="monitor" operation_key="rsc_test02_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="rsc_test02" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  ip="127.0.0.13"/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="22">
     <action_set>
      <rsc_op id="49" operation="monitor" operation_key="rsc_test03_monitor_5000" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a">
        <primitive id="rsc_test03" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_timeout="20000"  ip="127.0.0.14"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="23">
     <action_set>
      <rsc_op id="28" operation="monitor" operation_key="rsc_test03_monitor_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947">
        <primitive id="rsc_test03" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  ip="127.0.0.14"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="24">
     <action_set>
      <rsc_op id="18" operation="monitor" operation_key="rsc_test03_monitor_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8">
        <primitive id="rsc_test03" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  ip="127.0.0.14"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="25">
     <action_set>
      <rsc_op id="8" operation="monitor" operation_key="rsc_test03_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="rsc_test03" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  ip="127.0.0.14"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="26">
     <action_set>
      <rsc_op id="52" operation="monitor" operation_key="child_DoFencing:0_monitor_5000" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947">
        <primitive id="child_DoFencing:0" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_requires="nothing" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <rsc_op id="50" operation="start" operation_key="child_DoFencing:0_start_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="27">
     <action_set>
      <rsc_op id="50" operation="start" operation_key="child_DoFencing:0_start_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947">
        <primitive id="child_DoFencing:0" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_requires="nothing" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
       </trigger>
       <trigger>
        <pseudo_event id="60" operation="start" operation_key="DoFencing_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="28">
    <action_set>
      <rsc_op id="19" operation="monitor" operation_key="child_DoFencing:0_monitor_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8">
        <primitive id="child_DoFencing:0" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
   <synapse id="29">
     <action_set>
      <rsc_op id="9" operation="monitor" operation_key="child_DoFencing:0_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="child_DoFencing:0" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="30">
    <action_set>
      <rsc_op id="55" operation="monitor" operation_key="child_DoFencing:1_monitor_5000" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a">
        <primitive id="child_DoFencing:1" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_requires="nothing" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="53" operation="start" operation_key="child_DoFencing:1_start_0" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="31">
     <action_set>
      <rsc_op id="53" operation="start" operation_key="child_DoFencing:1_start_0" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a">
        <primitive id="child_DoFencing:1" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_requires="nothing" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="60" operation="start" operation_key="DoFencing_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="32">
    <action_set>
      <rsc_op id="29" operation="monitor" operation_key="child_DoFencing:1_monitor_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947">
        <primitive id="child_DoFencing:1" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="33">
     <action_set>
      <rsc_op id="20" operation="monitor" operation_key="child_DoFencing:1_monitor_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8">
        <primitive id="child_DoFencing:1" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="34">
     <action_set>
      <rsc_op id="10" operation="monitor" operation_key="child_DoFencing:1_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="child_DoFencing:1" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="35">
     <action_set>
      <rsc_op id="57" operation="monitor" operation_key="child_DoFencing:2_monitor_5000" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="child_DoFencing:2" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_requires="nothing" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="56" operation="start" operation_key="child_DoFencing:2_start_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="36">
     <action_set>
      <rsc_op id="56" operation="start" operation_key="child_DoFencing:2_start_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="child_DoFencing:2" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_requires="nothing" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="60" operation="start" operation_key="DoFencing_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="37">
     <action_set>
      <rsc_op id="35" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a">
        <primitive id="child_DoFencing:2" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="38">
     <action_set>
      <rsc_op id="30" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947">
        <primitive id="child_DoFencing:2" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="39">
     <action_set>
      <rsc_op id="21" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8">
        <primitive id="child_DoFencing:2" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="40">
     <action_set>
      <rsc_op id="11" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="child_DoFencing:2" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="41">
     <action_set>
      <rsc_op id="59" operation="monitor" operation_key="child_DoFencing:3_monitor_5000" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8">
        <primitive id="child_DoFencing:3" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_requires="nothing" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="58" operation="start" operation_key="child_DoFencing:3_start_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="42">
     <action_set>
      <rsc_op id="58" operation="start" operation_key="child_DoFencing:3_start_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8">
        <primitive id="child_DoFencing:3" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_requires="nothing" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="60" operation="start" operation_key="DoFencing_start_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="43">
     <action_set>
      <rsc_op id="36" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a">
        <primitive id="child_DoFencing:3" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="44">
     <action_set>
      <rsc_op id="31" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947">
        <primitive id="child_DoFencing:3" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="45">
     <action_set>
      <rsc_op id="22" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8">
        <primitive id="child_DoFencing:3" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="46">
     <action_set>
      <rsc_op id="12" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="child_DoFencing:3" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 test02 test03 "/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
  <synapse id="47" priority="1000000">
     <action_set>
      <pseudo_event id="61" operation="running" operation_key="DoFencing_running_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="50" operation="start" operation_key="child_DoFencing:0_start_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947"/>
       </trigger>
       <trigger>
        <rsc_op id="53" operation="start" operation_key="child_DoFencing:1_start_0" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a"/>
       </trigger>
       <trigger>
        <rsc_op id="56" operation="start" operation_key="child_DoFencing:2_start_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
       </trigger>
       <trigger>
        <rsc_op id="58" operation="start" operation_key="child_DoFencing:3_start_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8"/>
       </trigger>
       <trigger>
        <pseudo_event id="60" operation="start" operation_key="DoFencing_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="48">
     <action_set>
      <pseudo_event id="60" operation="start" operation_key="DoFencing_start_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
    <inputs/>
   </synapse>
  <synapse id="49" priority="1000000">
     <action_set>
      <rsc_op id="32" operation="probe_complete" operation_key="probe_complete-test03" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a">
        <attributes CRM_meta_op_no_wait="true" />
      </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="33" operation="monitor" operation_key="rsc_sgi2_monitor_0" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a"/>
       </trigger>
       <trigger>
        <rsc_op id="34" operation="monitor" operation_key="rsc_test02_monitor_0" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a"/>
       </trigger>
       <trigger>
        <rsc_op id="35" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a"/>
       </trigger>
       <trigger>
        <rsc_op id="36" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="50" priority="1000000">
     <action_set>
      <rsc_op id="23" operation="probe_complete" operation_key="probe_complete-test02" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947">
        <attributes CRM_meta_op_no_wait="true" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="24" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947"/>
       </trigger>
       <trigger>
        <rsc_op id="25" operation="monitor" operation_key="rsc_sgi2_monitor_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947"/>
       </trigger>
       <trigger>
        <rsc_op id="26" operation="monitor" operation_key="rsc_ibm1_monitor_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947"/>
       </trigger>
       <trigger>
        <rsc_op id="27" operation="monitor" operation_key="rsc_test02_monitor_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947"/>
       </trigger>
       <trigger>
        <rsc_op id="28" operation="monitor" operation_key="rsc_test03_monitor_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947"/>
       </trigger>
       <trigger>
        <rsc_op id="29" operation="monitor" operation_key="child_DoFencing:1_monitor_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947"/>
       </trigger>
       <trigger>
        <rsc_op id="30" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947"/>
      </trigger>
      <trigger>
        <rsc_op id="31" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="51" priority="1000000">
     <action_set>
      <rsc_op id="13" operation="probe_complete" operation_key="probe_complete-sgi2" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8">
        <attributes CRM_meta_op_no_wait="true" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="14" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8"/>
       </trigger>
       <trigger>
        <rsc_op id="15" operation="monitor" operation_key="rsc_sgi2_monitor_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8"/>
       </trigger>
       <trigger>
        <rsc_op id="16" operation="monitor" operation_key="rsc_ibm1_monitor_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8"/>
       </trigger>
       <trigger>
        <rsc_op id="17" operation="monitor" operation_key="rsc_test02_monitor_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8"/>
       </trigger>
       <trigger>
        <rsc_op id="18" operation="monitor" operation_key="rsc_test03_monitor_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8"/>
       </trigger>
       <trigger>
        <rsc_op id="19" operation="monitor" operation_key="child_DoFencing:0_monitor_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8"/>
       </trigger>
       <trigger>
        <rsc_op id="20" operation="monitor" operation_key="child_DoFencing:1_monitor_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8"/>
       </trigger>
       <trigger>
        <rsc_op id="21" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8"/>
      </trigger>
      <trigger>
        <rsc_op id="22" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="52" priority="1000000">
     <action_set>
      <rsc_op id="3" operation="probe_complete" operation_key="probe_complete-ibm1" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <attributes CRM_meta_op_no_wait="true" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="4" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
      </trigger>
      <trigger>
        <rsc_op id="5" operation="monitor" operation_key="rsc_sgi2_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
      </trigger>
      <trigger>
        <rsc_op id="6" operation="monitor" operation_key="rsc_ibm1_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
      </trigger>
      <trigger>
        <rsc_op id="7" operation="monitor" operation_key="rsc_test02_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
      </trigger>
      <trigger>
        <rsc_op id="8" operation="monitor" operation_key="rsc_test03_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
      </trigger>
      <trigger>
        <rsc_op id="9" operation="monitor" operation_key="child_DoFencing:0_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
       </trigger>
       <trigger>
        <rsc_op id="10" operation="monitor" operation_key="child_DoFencing:1_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
       </trigger>
       <trigger>
        <rsc_op id="11" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
       </trigger>
       <trigger>
        <rsc_op id="12" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
       </trigger>
    </inputs>
  </synapse>
  <synapse id="53">
    <action_set>
      <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
       <trigger>
        <rsc_op id="3" operation="probe_complete" operation_key="probe_complete-ibm1" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
       </trigger>
       <trigger>
        <rsc_op id="13" operation="probe_complete" operation_key="probe_complete-sgi2" on_node="sgi2" on_node_uuid="619e8a37-147a-4782-ac11-46afad7c32b8"/>
       </trigger>
       <trigger>
        <rsc_op id="23" operation="probe_complete" operation_key="probe_complete-test02" on_node="test02" on_node_uuid="f75e684a-be1e-4036-89e5-a14f8dcdc947"/>
       </trigger>
       <trigger>
        <rsc_op id="32" operation="probe_complete" operation_key="probe_complete-test03" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a"/>
       </trigger>
    </inputs>
  </synapse>
  <synapse id="54">
    <action_set>
      <pseudo_event id="1" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
       <trigger>
        <rsc_op id="42" operation="stop" operation_key="rsc_ibm1_stop_0" on_node="test03" on_node_uuid="f9c593eb-ca0d-4ab3-ba88-fde12c02334a"/>
       </trigger>
     </inputs>
   </synapse>
 </transition_graph>

