 <transition_graph cluster-delay="120s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
   <synapse id="0">
     <action_set>
       <rsc_op id="7" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669">
        <primitive id="DcIPaddr" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.10"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="1">
     <action_set>
      <rsc_op id="15" operation="monitor" operation_key="rsc_hadev1_monitor_5000" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669">
        <primitive id="rsc_hadev1" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.11"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <rsc_op id="13" operation="start" operation_key="rsc_hadev1_start_0" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="2">
     <action_set>
      <rsc_op id="14" operation="stop" operation_key="rsc_hadev1_stop_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3">
        <primitive id="rsc_hadev1" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.11"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="3">
     <action_set>
      <rsc_op id="13" operation="start" operation_key="rsc_hadev1_start_0" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669">
        <primitive id="rsc_hadev1" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.11"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="14" operation="stop" operation_key="rsc_hadev1_stop_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="4">
     <action_set>
       <rsc_op id="8" operation="monitor" operation_key="rsc_hadev2_monitor_0" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669">
        <primitive id="rsc_hadev2" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.12"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="5">
     <action_set>
       <rsc_op id="19" operation="monitor" operation_key="rsc_hadev3_monitor_5000" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669">
        <primitive id="rsc_hadev3" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.13"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <rsc_op id="18" operation="start" operation_key="rsc_hadev3_start_0" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="6">
    <action_set>
      <rsc_op id="18" operation="start" operation_key="rsc_hadev3_start_0" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669">
        <primitive id="rsc_hadev3" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.13"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
   <synapse id="7">
     <action_set>
      <rsc_op id="21" operation="monitor" operation_key="child_DoFencing:0_monitor_5000" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3">
        <primitive id="child_DoFencing:0" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_requires="nothing" CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostlist="hadev1 hadev2 hadev3 "/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <rsc_op id="20" operation="start" operation_key="child_DoFencing:0_start_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="8">
     <action_set>
       <rsc_op id="20" operation="start" operation_key="child_DoFencing:0_start_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3">
        <primitive id="child_DoFencing:0" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_requires="nothing" CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostlist="hadev1 hadev2 hadev3 "/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
       </trigger>
       <trigger>
         <pseudo_event id="24" operation="start" operation_key="DoFencing_start_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="9">
     <action_set>
      <rsc_op id="9" operation="monitor" operation_key="child_DoFencing:0_monitor_0" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669">
        <primitive id="child_DoFencing:0" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostlist="hadev1 hadev2 hadev3 "/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="10">
     <action_set>
      <rsc_op id="23" operation="monitor" operation_key="child_DoFencing:1_monitor_5000" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669">
        <primitive id="child_DoFencing:1" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_requires="nothing" CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostlist="hadev1 hadev2 hadev3 "/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="22" operation="start" operation_key="child_DoFencing:1_start_0" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="11">
     <action_set>
      <rsc_op id="22" operation="start" operation_key="child_DoFencing:1_start_0" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669">
        <primitive id="child_DoFencing:1" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_requires="nothing" CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostlist="hadev1 hadev2 hadev3 "/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="24" operation="start" operation_key="DoFencing_start_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="12">
     <action_set>
       <rsc_op id="10" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669">
        <primitive id="child_DoFencing:2" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostlist="hadev1 hadev2 hadev3 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="13" priority="1000000">
     <action_set>
       <pseudo_event id="25" operation="running" operation_key="DoFencing_running_0">
        <attributes CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <rsc_op id="20" operation="start" operation_key="child_DoFencing:0_start_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3"/>
       </trigger>
       <trigger>
         <rsc_op id="22" operation="start" operation_key="child_DoFencing:1_start_0" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669"/>
       </trigger>
       <trigger>
         <pseudo_event id="24" operation="start" operation_key="DoFencing_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="14">
     <action_set>
      <pseudo_event id="24" operation="start" operation_key="DoFencing_start_0">
        <attributes CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
    <inputs/>
  </synapse>
  <synapse id="15" priority="1000000">
    <action_set>
      <rsc_op id="6" operation="probe_complete" operation_key="probe_complete" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
     <inputs>
       <trigger>
        <rsc_op id="7" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669"/>
      </trigger>
      <trigger>
        <rsc_op id="8" operation="monitor" operation_key="rsc_hadev2_monitor_0" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669"/>
      </trigger>
      <trigger>
        <rsc_op id="9" operation="monitor" operation_key="child_DoFencing:0_monitor_0" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669"/>
      </trigger>
      <trigger>
        <rsc_op id="10" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="16">
     <action_set>
       <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete">
        <attributes crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <rsc_op id="6" operation="probe_complete" operation_key="probe_complete" on_node="hadev3" on_node_uuid="879e65f8-4b38-4c56-9552-4752ad436669"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="17">
     <action_set>
      <pseudo_event id="3" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.6"/>
      </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="14" operation="stop" operation_key="rsc_hadev1_stop_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3"/>
       </trigger>
     </inputs>
   </synapse>
 </transition_graph>

