<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0" priority="1000000">
    <action_set>
      <rsc_op id="60" operation="notify" operation_key="rsc1:1_post_notify_demote_0" internal_operation_key="rsc1:0_post_notify_demote_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc1" long-id="rsc1:1" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="rsc1:0 " CRM_meta_notify_demote_uname="node1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="demoted" CRM_meta_notify_key_type="post" CRM_meta_notify_master_resource="rsc1:0 " CRM_meta_notify_master_uname="node1 " CRM_meta_notify_operation="demote" CRM_meta_notify_promote_resource="rsc1:1 " CRM_meta_notify_promote_uname="node2 " CRM_meta_notify_slave_resource="rsc1:1 " CRM_meta_notify_slave_uname="node2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="38" operation="notify" operation_key="ms1_post_notify_demoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="59" operation="notify" operation_key="rsc1:1_pre_notify_demote_0" internal_operation_key="rsc1:0_pre_notify_demote_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc1" long-id="rsc1:1" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="rsc1:0 " CRM_meta_notify_demote_uname="node1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="demote" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource="rsc1:0 " CRM_meta_notify_master_uname="node1 " CRM_meta_notify_operation="demote" CRM_meta_notify_promote_resource="rsc1:1 " CRM_meta_notify_promote_uname="node2 " CRM_meta_notify_slave_resource="rsc1:1 " CRM_meta_notify_slave_uname="node2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="36" operation="notify" operation_key="ms1_pre_notify_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2" priority="1000000">
    <action_set>
      <rsc_op id="56" operation="notify" operation_key="rsc1:1_post_notify_promote_0" internal_operation_key="rsc1:0_post_notify_promote_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc1" long-id="rsc1:1" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="rsc1:0 " CRM_meta_notify_demote_uname="node1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="promoted" CRM_meta_notify_key_type="post" CRM_meta_notify_master_resource="rsc1:0 " CRM_meta_notify_master_uname="node1 " CRM_meta_notify_operation="promote" CRM_meta_notify_promote_resource="rsc1:1 " CRM_meta_notify_promote_uname="node2 " CRM_meta_notify_slave_resource="rsc1:1 " CRM_meta_notify_slave_uname="node2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="32" operation="notify" operation_key="ms1_post_notify_promoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <rsc_op id="55" operation="notify" operation_key="rsc1:1_pre_notify_promote_0" internal_operation_key="rsc1:0_pre_notify_promote_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc1" long-id="rsc1:1" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="rsc1:0 " CRM_meta_notify_demote_uname="node1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="promote" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource="rsc1:0 " CRM_meta_notify_master_uname="node1 " CRM_meta_notify_operation="promote" CRM_meta_notify_promote_resource="rsc1:1 " CRM_meta_notify_promote_uname="node2 " CRM_meta_notify_slave_resource="rsc1:1 " CRM_meta_notify_slave_uname="node2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="30" operation="notify" operation_key="ms1_pre_notify_promote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <rsc_op id="11" operation="monitor" operation_key="rsc1:1_monitor_10000" internal_operation_key="rsc1:0_monitor_10000" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc1" long-id="rsc1:1" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="10000" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="true" CRM_meta_role="Slave" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="9" operation="demote" operation_key="rsc1:1_demote_0" internal_operation_key="rsc1:0_demote_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <pseudo_event id="33" operation="notified" operation_key="ms1_confirmed-post_notify_promoted_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="39" operation="notified" operation_key="ms1_confirmed-post_notify_demoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <rsc_op id="9" operation="demote" operation_key="rsc1:1_demote_0" internal_operation_key="rsc1:0_demote_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc1" long-id="rsc1:1" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="rsc1:0 " CRM_meta_notify_demote_uname="node1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_master_resource="rsc1:0 " CRM_meta_notify_master_uname="node1 " CRM_meta_notify_promote_resource="rsc1:1 " CRM_meta_notify_promote_uname="node2 " CRM_meta_notify_slave_resource="rsc1:1 " CRM_meta_notify_slave_uname="node2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="1" operation="cancel" operation_key="rsc1:1_monitor_5000" internal_operation_key="rsc1:0_monitor_5000" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <pseudo_event id="34" operation="demote" operation_key="ms1_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <rsc_op id="1" operation="cancel" operation_key="rsc1:1_monitor_5000" internal_operation_key="rsc1:0_monitor_5000" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc1" long-id="rsc1:1" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="5000" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="true" CRM_meta_operation="monitor" CRM_meta_role="Master" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="7" priority="1000000">
    <action_set>
      <rsc_op id="62" operation="notify" operation_key="rsc1:0_post_notify_demote_0" internal_operation_key="rsc1:1_post_notify_demote_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc1" long-id="rsc1:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="rsc1:0 " CRM_meta_notify_demote_uname="node1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="demoted" CRM_meta_notify_key_type="post" CRM_meta_notify_master_resource="rsc1:0 " CRM_meta_notify_master_uname="node1 " CRM_meta_notify_operation="demote" CRM_meta_notify_promote_resource="rsc1:1 " CRM_meta_notify_promote_uname="node2 " CRM_meta_notify_slave_resource="rsc1:1 " CRM_meta_notify_slave_uname="node2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="38" operation="notify" operation_key="ms1_post_notify_demoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <rsc_op id="61" operation="notify" operation_key="rsc1:0_pre_notify_demote_0" internal_operation_key="rsc1:1_pre_notify_demote_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc1" long-id="rsc1:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="rsc1:0 " CRM_meta_notify_demote_uname="node1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="demote" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource="rsc1:0 " CRM_meta_notify_master_uname="node1 " CRM_meta_notify_operation="demote" CRM_meta_notify_promote_resource="rsc1:1 " CRM_meta_notify_promote_uname="node2 " CRM_meta_notify_slave_resource="rsc1:1 " CRM_meta_notify_slave_uname="node2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="36" operation="notify" operation_key="ms1_pre_notify_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9" priority="1000000">
    <action_set>
      <rsc_op id="58" operation="notify" operation_key="rsc1:0_post_notify_promote_0" internal_operation_key="rsc1:1_post_notify_promote_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc1" long-id="rsc1:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="rsc1:0 " CRM_meta_notify_demote_uname="node1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="promoted" CRM_meta_notify_key_type="post" CRM_meta_notify_master_resource="rsc1:0 " CRM_meta_notify_master_uname="node1 " CRM_meta_notify_operation="promote" CRM_meta_notify_promote_resource="rsc1:1 " CRM_meta_notify_promote_uname="node2 " CRM_meta_notify_slave_resource="rsc1:1 " CRM_meta_notify_slave_uname="node2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="32" operation="notify" operation_key="ms1_post_notify_promoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="10">
    <action_set>
      <rsc_op id="57" operation="notify" operation_key="rsc1:0_pre_notify_promote_0" internal_operation_key="rsc1:1_pre_notify_promote_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc1" long-id="rsc1:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="rsc1:0 " CRM_meta_notify_demote_uname="node1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="promote" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource="rsc1:0 " CRM_meta_notify_master_uname="node1 " CRM_meta_notify_operation="promote" CRM_meta_notify_promote_resource="rsc1:1 " CRM_meta_notify_promote_uname="node2 " CRM_meta_notify_slave_resource="rsc1:1 " CRM_meta_notify_slave_uname="node2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="30" operation="notify" operation_key="ms1_pre_notify_promote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="11">
    <action_set>
      <rsc_op id="15" operation="monitor" operation_key="rsc1:0_monitor_5000" internal_operation_key="rsc1:1_monitor_5000" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc1" long-id="rsc1:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="5000" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="true" CRM_meta_op_target_rc="8" CRM_meta_role="Master" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="14" operation="promote" operation_key="rsc1:0_promote_0" internal_operation_key="rsc1:1_promote_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
      <trigger>
        <pseudo_event id="33" operation="notified" operation_key="ms1_confirmed-post_notify_promoted_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="39" operation="notified" operation_key="ms1_confirmed-post_notify_demoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="12">
    <action_set>
      <rsc_op id="14" operation="promote" operation_key="rsc1:0_promote_0" internal_operation_key="rsc1:1_promote_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc1" long-id="rsc1:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="rsc1:0 " CRM_meta_notify_demote_uname="node1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_master_resource="rsc1:0 " CRM_meta_notify_master_uname="node1 " CRM_meta_notify_promote_resource="rsc1:1 " CRM_meta_notify_promote_uname="node2 " CRM_meta_notify_slave_resource="rsc1:1 " CRM_meta_notify_slave_uname="node2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="3" operation="cancel" operation_key="rsc1:0_monitor_10000" internal_operation_key="rsc1:1_monitor_10000" on_node="node2" on_node_uuid="node2"/>
      </trigger>
      <trigger>
        <pseudo_event id="28" operation="promote" operation_key="ms1_promote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="13">
    <action_set>
      <rsc_op id="3" operation="cancel" operation_key="rsc1:0_monitor_10000" internal_operation_key="rsc1:1_monitor_10000" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc1" long-id="rsc1:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="10000" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="true" CRM_meta_operation="monitor" CRM_meta_role="Slave" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="14" priority="1000000">
    <action_set>
      <pseudo_event id="39" operation="notified" operation_key="ms1_confirmed-post_notify_demoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="demoted" CRM_meta_notify_key_type="confirmed-post" CRM_meta_notify_operation="demote" CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="38" operation="notify" operation_key="ms1_post_notify_demoted_0"/>
      </trigger>
      <trigger>
        <rsc_op id="60" operation="notify" operation_key="rsc1:1_post_notify_demote_0" internal_operation_key="rsc1:0_post_notify_demote_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <rsc_op id="62" operation="notify" operation_key="rsc1:0_post_notify_demote_0" internal_operation_key="rsc1:1_post_notify_demote_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="15" priority="1000000">
    <action_set>
      <pseudo_event id="38" operation="notify" operation_key="ms1_post_notify_demoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="demoted" CRM_meta_notify_key_type="post" CRM_meta_notify_operation="demote" CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="35" operation="demoted" operation_key="ms1_demoted_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="37" operation="notified" operation_key="ms1_confirmed-pre_notify_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="16">
    <action_set>
      <pseudo_event id="37" operation="notified" operation_key="ms1_confirmed-pre_notify_demote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="demote" CRM_meta_notify_key_type="confirmed-pre" CRM_meta_notify_operation="demote" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="36" operation="notify" operation_key="ms1_pre_notify_demote_0"/>
      </trigger>
      <trigger>
        <rsc_op id="59" operation="notify" operation_key="rsc1:1_pre_notify_demote_0" internal_operation_key="rsc1:0_pre_notify_demote_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <rsc_op id="61" operation="notify" operation_key="rsc1:0_pre_notify_demote_0" internal_operation_key="rsc1:1_pre_notify_demote_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="17">
    <action_set>
      <pseudo_event id="36" operation="notify" operation_key="ms1_pre_notify_demote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="demote" CRM_meta_notify_key_type="pre" CRM_meta_notify_operation="demote" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="18" priority="1000000">
    <action_set>
      <pseudo_event id="35" operation="demoted" operation_key="ms1_demoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="9" operation="demote" operation_key="rsc1:1_demote_0" internal_operation_key="rsc1:0_demote_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <pseudo_event id="34" operation="demote" operation_key="ms1_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="19">
    <action_set>
      <pseudo_event id="34" operation="demote" operation_key="ms1_demote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="37" operation="notified" operation_key="ms1_confirmed-pre_notify_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="20" priority="1000000">
    <action_set>
      <pseudo_event id="33" operation="notified" operation_key="ms1_confirmed-post_notify_promoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="promoted" CRM_meta_notify_key_type="confirmed-post" CRM_meta_notify_operation="promote" CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="32" operation="notify" operation_key="ms1_post_notify_promoted_0"/>
      </trigger>
      <trigger>
        <rsc_op id="56" operation="notify" operation_key="rsc1:1_post_notify_promote_0" internal_operation_key="rsc1:0_post_notify_promote_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <rsc_op id="58" operation="notify" operation_key="rsc1:0_post_notify_promote_0" internal_operation_key="rsc1:1_post_notify_promote_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="21" priority="1000000">
    <action_set>
      <pseudo_event id="32" operation="notify" operation_key="ms1_post_notify_promoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="promoted" CRM_meta_notify_key_type="post" CRM_meta_notify_operation="promote" CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="29" operation="promoted" operation_key="ms1_promoted_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="31" operation="notified" operation_key="ms1_confirmed-pre_notify_promote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="22">
    <action_set>
      <pseudo_event id="31" operation="notified" operation_key="ms1_confirmed-pre_notify_promote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="promote" CRM_meta_notify_key_type="confirmed-pre" CRM_meta_notify_operation="promote" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="30" operation="notify" operation_key="ms1_pre_notify_promote_0"/>
      </trigger>
      <trigger>
        <rsc_op id="55" operation="notify" operation_key="rsc1:1_pre_notify_promote_0" internal_operation_key="rsc1:0_pre_notify_promote_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <rsc_op id="57" operation="notify" operation_key="rsc1:0_pre_notify_promote_0" internal_operation_key="rsc1:1_pre_notify_promote_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="23">
    <action_set>
      <pseudo_event id="30" operation="notify" operation_key="ms1_pre_notify_promote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="promote" CRM_meta_notify_key_type="pre" CRM_meta_notify_operation="promote" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="39" operation="notified" operation_key="ms1_confirmed-post_notify_demoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="24" priority="1000000">
    <action_set>
      <pseudo_event id="29" operation="promoted" operation_key="ms1_promoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="14" operation="promote" operation_key="rsc1:0_promote_0" internal_operation_key="rsc1:1_promote_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="25">
    <action_set>
      <pseudo_event id="28" operation="promote" operation_key="ms1_promote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="2" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="31" operation="notified" operation_key="ms1_confirmed-pre_notify_promote_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="35" operation="demoted" operation_key="ms1_demoted_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="start" operation_key="rsc2_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="26">
    <action_set>
      <rsc_op id="44" operation="migrate_from" operation_key="rsc2_migrate_from_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc2" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_migrate_source="node1" CRM_meta_migrate_target="node2" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="43" operation="migrate_to" operation_key="rsc2_migrate_to_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="27">
    <action_set>
      <rsc_op id="43" operation="migrate_to" operation_key="rsc2_migrate_to_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc2" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_migrate_source="node1" CRM_meta_migrate_target="node2" CRM_meta_record_pending="true" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="39" operation="notified" operation_key="ms1_confirmed-post_notify_demoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="28">
    <action_set>
      <rsc_op id="42" operation="monitor" operation_key="rsc2_monitor_5000" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc2" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="41" operation="start" operation_key="rsc2_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="29">
    <action_set>
      <pseudo_event id="41" operation="start" operation_key="rsc2_start_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="40" operation="stop" operation_key="rsc2_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <rsc_op id="44" operation="migrate_from" operation_key="rsc2_migrate_from_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="30">
    <action_set>
      <rsc_op id="40" operation="stop" operation_key="rsc2_stop_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc2" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="39" operation="notified" operation_key="ms1_confirmed-post_notify_demoted_0"/>
      </trigger>
      <trigger>
        <rsc_op id="44" operation="migrate_from" operation_key="rsc2_migrate_from_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="31" priority="1000000">
    <action_set>
      <rsc_op id="7" operation="probe_complete" operation_key="probe_complete-node2" on_node="node2" on_node_uuid="node2">
        <attributes CRM_meta_op_no_wait="true" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="32" priority="1000000">
    <action_set>
      <rsc_op id="6" operation="probe_complete" operation_key="probe_complete-node1" on_node="node1" on_node_uuid="node1">
        <attributes CRM_meta_op_no_wait="true" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="33">
    <action_set>
      <pseudo_event id="4" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="40" operation="stop" operation_key="rsc2_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>
