<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0" priority="100">
    <action_set>
      <pseudo_event id="12" operation="stopped" operation_key="group1_stopped_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="stop" operation_key="rsc1_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <rsc_op id="7" operation="stop" operation_key="rsc2_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <pseudo_event id="11" operation="stop" operation_key="group1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1" priority="100">
    <action_set>
      <pseudo_event id="11" operation="stop" operation_key="group1_stop_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="2" priority="100">
    <action_set>
      <pseudo_event id="10" operation="running" operation_key="group1_running_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="6" operation="start" operation_key="rsc1_start_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
      <trigger>
        <rsc_op id="8" operation="start" operation_key="rsc2_start_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
      <trigger>
        <pseudo_event id="9" operation="start" operation_key="group1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3" priority="100">
    <action_set>
      <pseudo_event id="9" operation="start" operation_key="group1_start_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="12" operation="stopped" operation_key="group1_stopped_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="18" operation="stopped" operation_key="group2_stopped_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4" priority="100">
    <action_set>
      <rsc_op id="6" operation="start" operation_key="rsc1_start_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc1" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="stop" operation_key="rsc1_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <pseudo_event id="9" operation="start" operation_key="group1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5" priority="100">
    <action_set>
      <rsc_op id="5" operation="stop" operation_key="rsc1_stop_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc1" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="7" operation="stop" operation_key="rsc2_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <pseudo_event id="11" operation="stop" operation_key="group1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6" priority="100">
    <action_set>
      <rsc_op id="8" operation="start" operation_key="rsc2_start_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc2" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="6" operation="start" operation_key="rsc1_start_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
      <trigger>
        <rsc_op id="7" operation="stop" operation_key="rsc2_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <pseudo_event id="9" operation="start" operation_key="group1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7" priority="100">
    <action_set>
      <rsc_op id="7" operation="stop" operation_key="rsc2_stop_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc2" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="11" operation="stop" operation_key="group1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8" priority="10">
    <action_set>
      <pseudo_event id="18" operation="stopped" operation_key="group2_stopped_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="13" operation="stop" operation_key="rsc3_stop_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
      <trigger>
        <rsc_op id="14" operation="stop" operation_key="rsc4_stop_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
      <trigger>
        <pseudo_event id="17" operation="stop" operation_key="group2_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9" priority="10">
    <action_set>
      <pseudo_event id="17" operation="stop" operation_key="group2_stop_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="10" priority="10">
    <action_set>
      <rsc_op id="13" operation="stop" operation_key="rsc3_stop_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc3" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="14" operation="stop" operation_key="rsc4_stop_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
      <trigger>
        <pseudo_event id="17" operation="stop" operation_key="group2_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="11" priority="10">
    <action_set>
      <rsc_op id="14" operation="stop" operation_key="rsc4_stop_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc4" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="17" operation="stop" operation_key="group2_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="12" priority="1000000">
    <action_set>
      <rsc_op id="4" operation="probe_complete" operation_key="probe_complete" on_node="node2" on_node_uuid="node2">
        <attributes CRM_meta_op_no_wait="true" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="13" priority="1000000">
    <action_set>
      <rsc_op id="3" operation="probe_complete" operation_key="probe_complete" on_node="node1" on_node_uuid="node1">
        <attributes CRM_meta_op_no_wait="true" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="14">
    <action_set>
      <pseudo_event id="1" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="stop" operation_key="rsc1_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <rsc_op id="7" operation="stop" operation_key="rsc2_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <rsc_op id="13" operation="stop" operation_key="rsc3_stop_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
      <trigger>
        <rsc_op id="14" operation="stop" operation_key="rsc4_stop_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>
