<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <pseudo_event id="30" operation="start" operation_key="GRP_Web_Server_start_0">
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.2"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="1">
    <action_set>
      <pseudo_event id="31" operation="running" operation_key="GRP_Web_Server_running_0">
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.2"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="28" operation="start" operation_key="PRIM_Web_IP1_start_0" on_node="sles11-ha2" on_node_uuid="sles11-ha2"/>
      </trigger>
      <trigger>
        <pseudo_event id="30" operation="start" operation_key="GRP_Web_Server_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <crm_event id="1" operation="clear_failcount" operation_key="PRIM_Web_IP1_clear_failcount" on_node="sles11-ha1" on_node_uuid="sles11-ha1">
        <primitive id="PRIM_Web_IP1" long-id="GRP_Web_Server:PRIM_Web_IP1" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_no_wait="true" CRM_meta_timeout="20000" crm_feature_set="3.0.2" ip="192.168.2.45"/>
      </crm_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="3">
    <action_set>
      <crm_event id="6" operation="clear_failcount" operation_key="PRIM_Web_IP1_clear_failcount" on_node="sles11-ha2" on_node_uuid="sles11-ha2">
        <primitive id="PRIM_Web_IP1" long-id="GRP_Web_Server:PRIM_Web_IP1" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_no_wait="true" CRM_meta_timeout="20000" crm_feature_set="3.0.2" ip="192.168.2.45"/>
      </crm_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="4">
    <action_set>
      <crm_event id="12" operation="clear_failcount" operation_key="PRIM_Web_IP1_clear_failcount" on_node="sles11-ha3" on_node_uuid="sles11-ha3">
        <primitive id="PRIM_Web_IP1" long-id="GRP_Web_Server:PRIM_Web_IP1" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_no_wait="true" CRM_meta_timeout="20000" crm_feature_set="3.0.2" ip="192.168.2.45"/>
      </crm_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="5">
    <action_set>
      <rsc_op id="28" operation="start" operation_key="PRIM_Web_IP1_start_0" on_node="sles11-ha2" on_node_uuid="sles11-ha2">
        <primitive id="PRIM_Web_IP1" long-id="GRP_Web_Server:PRIM_Web_IP1" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.2" ip="192.168.2.45"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="30" operation="start" operation_key="GRP_Web_Server_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <rsc_op id="29" operation="monitor" operation_key="PRIM_Web_IP1_monitor_5000" on_node="sles11-ha2" on_node_uuid="sles11-ha2">
        <primitive id="PRIM_Web_IP1" long-id="GRP_Web_Server:PRIM_Web_IP1" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_on_fail="restart" CRM_meta_start_delay="1000" CRM_meta_timeout="6000" crm_feature_set="3.0.2" ip="192.168.2.45"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="28" operation="start" operation_key="PRIM_Web_IP1_start_0" on_node="sles11-ha2" on_node_uuid="sles11-ha2"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

