 <transition_graph cluster-delay="180s" stonith-timeout="60s"failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
   <synapse id="0">
     <action_set>
      <pseudo_event id="25" operation="demoted" operation_key="ms-sf_group:1_demoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="120000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="16" operation="demote" operation_key="master_slave_Stateful:1_demote_0" on_node="process1a" on_node_uuid="4dbb8c56-330e-4835-a15e-c0aa632d4e89"/>
      </trigger>
      <trigger>
        <rsc_op id="18" operation="demote" operation_key="master_slave_procdctl:1_demote_0" on_node="process1a" on_node_uuid="4dbb8c56-330e-4835-a15e-c0aa632d4e89"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="1">
     <action_set>
      <pseudo_event id="24" operation="demote" operation_key="ms-sf_group:1_demote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="120000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="34" operation="demote" operation_key="ms-sf_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <pseudo_event id="23" operation="stopped" operation_key="ms-sf_group:1_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="120000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="17" operation="stop" operation_key="master_slave_Stateful:1_stop_0" on_node="process1a" on_node_uuid="4dbb8c56-330e-4835-a15e-c0aa632d4e89"/>
       </trigger>
       <trigger>
        <rsc_op id="19" operation="stop" operation_key="master_slave_procdctl:1_stop_0" on_node="process1a" on_node_uuid="4dbb8c56-330e-4835-a15e-c0aa632d4e89"/>
       </trigger>
       <trigger>
        <pseudo_event id="22" operation="stop" operation_key="ms-sf_group:1_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="3">
     <action_set>
      <pseudo_event id="22" operation="stop" operation_key="ms-sf_group:1_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="120000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="30" operation="stop" operation_key="ms-sf_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="4">
     <action_set>
      <rsc_op id="17" operation="stop" operation_key="master_slave_Stateful:1_stop_0" on_node="process1a" on_node_uuid="4dbb8c56-330e-4835-a15e-c0aa632d4e89">
        <primitive id="master_slave_Stateful:1" long-id="ms-sf:ms-sf_group:1:master_slave_Stateful:1" class="ocf" provider="heartbeat" type="Dummy-statful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="stop" CRM_meta_notify="false" CRM_meta_on_fail="stop" CRM_meta_timeout="60000" crm_feature_set="3.0.6" sleep_time="10000"/>
      </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="16" operation="demote" operation_key="master_slave_Stateful:1_demote_0" on_node="process1a" on_node_uuid="4dbb8c56-330e-4835-a15e-c0aa632d4e89"/>
       </trigger>
       <trigger>
        <pseudo_event id="22" operation="stop" operation_key="ms-sf_group:1_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="5">
     <action_set>
      <rsc_op id="16" operation="demote" operation_key="master_slave_Stateful:1_demote_0" on_node="process1a" on_node_uuid="4dbb8c56-330e-4835-a15e-c0aa632d4e89">
         <primitive id="master_slave_Stateful:1" long-id="ms-sf:ms-sf_group:1:master_slave_Stateful:1" class="ocf" provider="heartbeat" type="Dummy-statful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="120000" crm_feature_set="3.0.6" sleep_time="10000"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="24" operation="demote" operation_key="ms-sf_group:1_demote_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="6">
     <action_set>
      <rsc_op id="19" operation="stop" operation_key="master_slave_procdctl:1_stop_0" on_node="process1a" on_node_uuid="4dbb8c56-330e-4835-a15e-c0aa632d4e89">
        <primitive id="master_slave_procdctl:1" long-id="ms-sf:ms-sf_group:1:master_slave_procdctl:1" class="ocf" provider="heartbeat" type="procdctl"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="stop" CRM_meta_notify="false" CRM_meta_on_fail="stop" CRM_meta_timeout="60000" crm_feature_set="3.0.6" procd="sleep 10000"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="18" operation="demote" operation_key="master_slave_procdctl:1_demote_0" on_node="process1a" on_node_uuid="4dbb8c56-330e-4835-a15e-c0aa632d4e89"/>
       </trigger>
       <trigger>
        <pseudo_event id="22" operation="stop" operation_key="ms-sf_group:1_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="7">
     <action_set>
      <rsc_op id="18" operation="demote" operation_key="master_slave_procdctl:1_demote_0" on_node="process1a" on_node_uuid="4dbb8c56-330e-4835-a15e-c0aa632d4e89">
         <primitive id="master_slave_procdctl:1" long-id="ms-sf:ms-sf_group:1:master_slave_procdctl:1" class="ocf" provider="heartbeat" type="procdctl"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="120000" crm_feature_set="3.0.6" procd="sleep 10000"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="24" operation="demote" operation_key="ms-sf_group:1_demote_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="8" priority="1000000">
     <action_set>
      <pseudo_event id="35" operation="demoted" operation_key="ms-sf_demoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="120000" crm_feature_set="3.0.6"/>
      </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="25" operation="demoted" operation_key="ms-sf_group:1_demoted_0"/>
       </trigger>
       <trigger>
        <pseudo_event id="34" operation="demote" operation_key="ms-sf_demote_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="9">
     <action_set>
      <pseudo_event id="34" operation="demote" operation_key="ms-sf_demote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="120000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
    <inputs/>
   </synapse>
  <synapse id="10" priority="1000000">
     <action_set>
      <pseudo_event id="31" operation="stopped" operation_key="ms-sf_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="120000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="23" operation="stopped" operation_key="ms-sf_group:1_stopped_0"/>
       </trigger>
       <trigger>
        <pseudo_event id="30" operation="stop" operation_key="ms-sf_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="11">
     <action_set>
      <pseudo_event id="30" operation="stop" operation_key="ms-sf_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="120000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="35" operation="demoted" operation_key="ms-sf_demoted_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="12">
     <action_set>
      <crm_event id="38" operation="do_shutdown" operation_key="do_shutdown" on_node="process1a" on_node_uuid="4dbb8c56-330e-4835-a15e-c0aa632d4e89">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.6"/>
      </crm_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="17" operation="stop" operation_key="master_slave_Stateful:1_stop_0" on_node="process1a" on_node_uuid="4dbb8c56-330e-4835-a15e-c0aa632d4e89"/>
       </trigger>
       <trigger>
        <rsc_op id="19" operation="stop" operation_key="master_slave_procdctl:1_stop_0" on_node="process1a" on_node_uuid="4dbb8c56-330e-4835-a15e-c0aa632d4e89"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="13">
     <action_set>
      <pseudo_event id="2" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.6"/>
      </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="17" operation="stop" operation_key="master_slave_Stateful:1_stop_0" on_node="process1a" on_node_uuid="4dbb8c56-330e-4835-a15e-c0aa632d4e89"/>
       </trigger>
       <trigger>
        <rsc_op id="19" operation="stop" operation_key="master_slave_procdctl:1_stop_0" on_node="process1a" on_node_uuid="4dbb8c56-330e-4835-a15e-c0aa632d4e89"/>
       </trigger>
     </inputs>
   </synapse>
 </transition_graph>

