<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <pseudo_event id="7" operation="running" operation_key="group1_running_0">
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="4" operation="start" operation_key="ClusterIP_start_0" on_node="fc16-builder" on_node_uuid="fc16-builder"/>
      </trigger>
      <trigger>
        <pseudo_event id="6" operation="start" operation_key="group1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <pseudo_event id="6" operation="start" operation_key="group1_start_0">
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="5" operation="monitor" operation_key="ClusterIP_monitor_30000" on_node="fc16-builder" on_node_uuid="fc16-builder">
        <primitive id="ClusterIP" long-id="group1:ClusterIP" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_interval="30000" CRM_meta_name="monitor" CRM_meta_timeout="20000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.122.101"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="4" operation="start" operation_key="ClusterIP_start_0" on_node="fc16-builder" on_node_uuid="fc16-builder"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <rsc_op id="4" operation="start" operation_key="ClusterIP_start_0" on_node="fc16-builder" on_node_uuid="fc16-builder">
        <primitive id="ClusterIP" long-id="group1:ClusterIP" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_timeout="20000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.122.101"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="6" operation="start" operation_key="group1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <pseudo_event id="13" operation="running" operation_key="group2_running_0">
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="10" operation="start" operation_key="ClusterIP2_start_0" on_node="fc16-builder" on_node_uuid="fc16-builder"/>
      </trigger>
      <trigger>
        <pseudo_event id="12" operation="start" operation_key="group2_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <pseudo_event id="12" operation="start" operation_key="group2_start_0">
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="7" operation="running" operation_key="group1_running_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <rsc_op id="11" operation="monitor" operation_key="ClusterIP2_monitor_30000" on_node="fc16-builder" on_node_uuid="fc16-builder">
        <primitive id="ClusterIP2" long-id="group2:ClusterIP2" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_interval="30000" CRM_meta_name="monitor" CRM_meta_timeout="20000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.122.102"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="10" operation="start" operation_key="ClusterIP2_start_0" on_node="fc16-builder" on_node_uuid="fc16-builder"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <rsc_op id="10" operation="start" operation_key="ClusterIP2_start_0" on_node="fc16-builder" on_node_uuid="fc16-builder">
        <primitive id="ClusterIP2" long-id="group2:ClusterIP2" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_timeout="20000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.122.102"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="12" operation="start" operation_key="group2_start_0"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

