 <transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
   <synapse id="0">
     <action_set>
      <pseudo_event id="13" operation="stopped" operation_key="group:0_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="9" operation="stop" operation_key="stateful-2:0_stop_0" on_node="node-b" on_node_uuid="9b262633-815c-4e5e-8f63-76486cab9ad2"/>
       </trigger>
       <trigger>
        <pseudo_event id="12" operation="stop" operation_key="group:0_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="1">
     <action_set>
      <pseudo_event id="12" operation="stop" operation_key="group:0_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="35" operation="stop" operation_key="ms-sf_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="2">
     <action_set>
      <pseudo_event id="11" operation="running" operation_key="group:0_running_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="2" operation="start" operation_key="stateful-2:0_start_0" on_node="node-b" on_node_uuid="9b262633-815c-4e5e-8f63-76486cab9ad2"/>
      </trigger>
      <trigger>
        <pseudo_event id="10" operation="start" operation_key="group:0_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="3">
     <action_set>
      <pseudo_event id="10" operation="start" operation_key="group:0_start_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="13" operation="stopped" operation_key="group:0_stopped_0"/>
       </trigger>
       <trigger>
        <pseudo_event id="33" operation="start" operation_key="ms-sf_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="4">
     <action_set>
      <rsc_op id="9" operation="stop" operation_key="stateful-2:0_stop_0" on_node="node-b" on_node_uuid="9b262633-815c-4e5e-8f63-76486cab9ad2">
        <primitive id="stateful-2:0" class="ocf" provider="heartbeat" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6" test1="1" test2="2"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="12" operation="stop" operation_key="group:0_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="5">
     <action_set>
      <rsc_op id="2" operation="start" operation_key="stateful-2:0_start_0" on_node="node-b" on_node_uuid="9b262633-815c-4e5e-8f63-76486cab9ad2">
        <primitive id="stateful-2:0" class="ocf" provider="heartbeat" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6" test1="1" test2="2"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="9" operation="stop" operation_key="stateful-2:0_stop_0" on_node="node-b" on_node_uuid="9b262633-815c-4e5e-8f63-76486cab9ad2"/>
      </trigger>
      <trigger>
        <pseudo_event id="10" operation="start" operation_key="group:0_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="6">
     <action_set>
      <pseudo_event id="32" operation="promoted" operation_key="group:1_promoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="24" operation="promote" operation_key="stateful-2:1_promote_0" on_node="node-a" on_node_uuid="babfee4b-9c89-4df2-8ccb-3de2a3587d8d"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="7">
     <action_set>
      <pseudo_event id="31" operation="promote" operation_key="group:1_promote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="29" operation="demote" operation_key="group:1_demote_0"/>
       </trigger>
       <trigger>
        <pseudo_event id="37" operation="promote" operation_key="ms-sf_promote_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="8">
     <action_set>
      <pseudo_event id="30" operation="demoted" operation_key="group:1_demoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="22" operation="demote" operation_key="stateful-2:1_demote_0" on_node="node-a" on_node_uuid="babfee4b-9c89-4df2-8ccb-3de2a3587d8d"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="9">
     <action_set>
      <pseudo_event id="29" operation="demote" operation_key="group:1_demote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="39" operation="demote" operation_key="ms-sf_demote_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="10">
     <action_set>
      <pseudo_event id="28" operation="stopped" operation_key="group:1_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="23" operation="stop" operation_key="stateful-2:1_stop_0" on_node="node-a" on_node_uuid="babfee4b-9c89-4df2-8ccb-3de2a3587d8d"/>
      </trigger>
      <trigger>
        <pseudo_event id="27" operation="stop" operation_key="group:1_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="11">
     <action_set>
      <pseudo_event id="27" operation="stop" operation_key="group:1_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="35" operation="stop" operation_key="ms-sf_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="12">
     <action_set>
      <pseudo_event id="26" operation="running" operation_key="group:1_running_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="3" operation="start" operation_key="stateful-2:1_start_0" on_node="node-a" on_node_uuid="babfee4b-9c89-4df2-8ccb-3de2a3587d8d"/>
       </trigger>
       <trigger>
        <pseudo_event id="25" operation="start" operation_key="group:1_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="13">
     <action_set>
      <pseudo_event id="25" operation="start" operation_key="group:1_start_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="28" operation="stopped" operation_key="group:1_stopped_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="33" operation="start" operation_key="ms-sf_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="14">
     <action_set>
      <rsc_op id="24" operation="promote" operation_key="stateful-2:1_promote_0" on_node="node-a" on_node_uuid="babfee4b-9c89-4df2-8ccb-3de2a3587d8d">
        <primitive id="stateful-2:1" class="ocf" provider="heartbeat" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6" test1="1" test2="2"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="3" operation="start" operation_key="stateful-2:1_start_0" on_node="node-a" on_node_uuid="babfee4b-9c89-4df2-8ccb-3de2a3587d8d"/>
       </trigger>
       <trigger>
        <pseudo_event id="31" operation="promote" operation_key="group:1_promote_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="15">
     <action_set>
      <rsc_op id="23" operation="stop" operation_key="stateful-2:1_stop_0" on_node="node-a" on_node_uuid="babfee4b-9c89-4df2-8ccb-3de2a3587d8d">
        <primitive id="stateful-2:1" class="ocf" provider="heartbeat" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6" test1="1" test2="2"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="22" operation="demote" operation_key="stateful-2:1_demote_0" on_node="node-a" on_node_uuid="babfee4b-9c89-4df2-8ccb-3de2a3587d8d"/>
      </trigger>
      <trigger>
        <pseudo_event id="27" operation="stop" operation_key="group:1_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="16">
     <action_set>
      <rsc_op id="22" operation="demote" operation_key="stateful-2:1_demote_0" on_node="node-a" on_node_uuid="babfee4b-9c89-4df2-8ccb-3de2a3587d8d">
        <primitive id="stateful-2:1" class="ocf" provider="heartbeat" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6" test1="1" test2="2"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="29" operation="demote" operation_key="group:1_demote_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="17">
     <action_set>
      <rsc_op id="3" operation="start" operation_key="stateful-2:1_start_0" on_node="node-a" on_node_uuid="babfee4b-9c89-4df2-8ccb-3de2a3587d8d">
        <primitive id="stateful-2:1" class="ocf" provider="heartbeat" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6" test1="1" test2="2"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="23" operation="stop" operation_key="stateful-2:1_stop_0" on_node="node-a" on_node_uuid="babfee4b-9c89-4df2-8ccb-3de2a3587d8d"/>
       </trigger>
       <trigger>
        <pseudo_event id="25" operation="start" operation_key="group:1_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="18" priority="1000000">
     <action_set>
      <pseudo_event id="40" operation="demoted" operation_key="ms-sf_demoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="30" operation="demoted" operation_key="group:1_demoted_0"/>
       </trigger>
       <trigger>
        <pseudo_event id="39" operation="demote" operation_key="ms-sf_demote_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="19">
     <action_set>
      <pseudo_event id="39" operation="demote" operation_key="ms-sf_demote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="20" priority="1000000">
    <action_set>
      <pseudo_event id="38" operation="promoted" operation_key="ms-sf_promoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="32" operation="promoted" operation_key="group:1_promoted_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="21">
     <action_set>
      <pseudo_event id="37" operation="promote" operation_key="ms-sf_promote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="34" operation="running" operation_key="ms-sf_running_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="36" operation="stopped" operation_key="ms-sf_stopped_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="40" operation="demoted" operation_key="ms-sf_demoted_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="22" priority="1000000">
     <action_set>
      <pseudo_event id="36" operation="stopped" operation_key="ms-sf_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="13" operation="stopped" operation_key="group:0_stopped_0"/>
       </trigger>
       <trigger>
        <pseudo_event id="28" operation="stopped" operation_key="group:1_stopped_0"/>
       </trigger>
       <trigger>
        <pseudo_event id="35" operation="stop" operation_key="ms-sf_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="23">
     <action_set>
      <pseudo_event id="35" operation="stop" operation_key="ms-sf_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="40" operation="demoted" operation_key="ms-sf_demoted_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="24" priority="1000000">
     <action_set>
      <pseudo_event id="34" operation="running" operation_key="ms-sf_running_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="11" operation="running" operation_key="group:0_running_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="26" operation="running" operation_key="group:1_running_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="33" operation="start" operation_key="ms-sf_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="25">
     <action_set>
      <pseudo_event id="33" operation="start" operation_key="ms-sf_start_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="36" operation="stopped" operation_key="ms-sf_stopped_0"/>
       </trigger>
       <trigger>
        <pseudo_event id="40" operation="demoted" operation_key="ms-sf_demoted_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="26">
     <action_set>
       <pseudo_event id="1" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="9" operation="stop" operation_key="stateful-2:0_stop_0" on_node="node-b" on_node_uuid="9b262633-815c-4e5e-8f63-76486cab9ad2"/>
       </trigger>
       <trigger>
        <rsc_op id="23" operation="stop" operation_key="stateful-2:1_stop_0" on_node="node-a" on_node_uuid="babfee4b-9c89-4df2-8ccb-3de2a3587d8d"/>
       </trigger>
     </inputs>
   </synapse>
 </transition_graph>

