<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <pseudo_event id="10" operation="stopped" operation_key="group1_stopped_0">
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="6" operation="stop" operation_key="ClusterIP_stop_0" on_node="fc16-builder" on_node_uuid="fc16-builder"/>
      </trigger>
      <trigger>
        <pseudo_event id="9" operation="stop" operation_key="group1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <pseudo_event id="9" operation="stop" operation_key="group1_stop_0">
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="6" operation="stop" operation_key="ClusterIP_stop_0" on_node="fc16-builder" on_node_uuid="fc16-builder">
        <primitive id="ClusterIP" long-id="group1:ClusterIP" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_timeout="20000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.122.101"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="9" operation="stop" operation_key="group1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <pseudo_event id="3" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="6" operation="stop" operation_key="ClusterIP_stop_0" on_node="fc16-builder" on_node_uuid="fc16-builder"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

