<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <pseudo_event id="9" operation="running" operation_key="gr-test:0_running_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="7" operation="start" operation_key="test:0_start_0" on_node="web1" on_node_uuid="web1"/>
      </trigger>
      <trigger>
        <pseudo_event id="8" operation="start" operation_key="gr-test:0_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <pseudo_event id="8" operation="start" operation_key="gr-test:0_start_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="25" operation="start" operation_key="cl-test_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="7" operation="start" operation_key="test:0_start_0" on_node="web1" on_node_uuid="web1">
        <primitive id="test:0" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6" device="192.168.55.15:/srv/nfs/web/" directory="/srv/web/" fstype="nfs" options="hard,intr,noatime,rw,nolock,tcp,timeo=50"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="8" operation="start" operation_key="gr-test:0_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <pseudo_event id="14" operation="running" operation_key="gr-test:1_running_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="12" operation="start" operation_key="test:1_start_0" on_node="web2" on_node_uuid="web2"/>
      </trigger>
      <trigger>
        <pseudo_event id="13" operation="start" operation_key="gr-test:1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <pseudo_event id="13" operation="start" operation_key="gr-test:1_start_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="25" operation="start" operation_key="cl-test_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <rsc_op id="12" operation="start" operation_key="test:1_start_0" on_node="web2" on_node_uuid="web2">
        <primitive id="test:1" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6" device="192.168.55.15:/srv/nfs/web/" directory="/srv/web/" fstype="nfs" options="hard,intr,noatime,rw,nolock,tcp,timeo=50"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="13" operation="start" operation_key="gr-test:1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6" priority="1000000">
    <action_set>
      <pseudo_event id="26" operation="running" operation_key="cl-test_running_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="9" operation="running" operation_key="gr-test:0_running_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="14" operation="running" operation_key="gr-test:1_running_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="25" operation="start" operation_key="cl-test_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <pseudo_event id="25" operation="start" operation_key="cl-test_start_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
</transition_graph>

