<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0">
    <action_set>
      <pseudo_event id="23" operation="start" operation_key="base-group:0_start_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="43" operation="start" operation_key="base-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="20" operation="start" operation_key="o2cb:0_start_0" on_node="hex-0" on_node_uuid="hex-0">
        <primitive id="o2cb" long-id="o2cb:0" class="ocf" provider="ocfs2" type="o2cb"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="8" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="23" operation="start" operation_key="base-group:0_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="21" operation="start" operation_key="clvm:0_start_0" on_node="hex-0" on_node_uuid="hex-0">
        <primitive id="clvm" long-id="clvm:0" class="ocf" provider="lvm2" type="clvmd"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000"  daemon_timeout="30"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="8" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <rsc_op id="20" operation="start" operation_key="o2cb:0_start_0" on_node="hex-0" on_node_uuid="hex-0"/>
      </trigger>
      <trigger>
        <pseudo_event id="23" operation="start" operation_key="base-group:0_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <rsc_op id="22" operation="start" operation_key="cmirrord:0_start_0" on_node="hex-0" on_node_uuid="hex-0">
        <primitive id="cmirrord" long-id="cmirrord:0" class="ocf" provider="lvm2" type="cmirrord"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000"  daemon_timeout="60"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="8" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <rsc_op id="21" operation="start" operation_key="clvm:0_start_0" on_node="hex-0" on_node_uuid="hex-0"/>
      </trigger>
      <trigger>
        <pseudo_event id="23" operation="start" operation_key="base-group:0_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <pseudo_event id="31" operation="start" operation_key="base-group:1_start_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="43" operation="start" operation_key="base-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <rsc_op id="27" operation="start" operation_key="dlm:1_start_0" on_node="hex-9" on_node_uuid="hex-9">
        <primitive id="dlm" long-id="dlm:1" class="ocf" provider="pacemaker" type="controld"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="8" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="31" operation="start" operation_key="base-group:1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <rsc_op id="28" operation="start" operation_key="o2cb:1_start_0" on_node="hex-9" on_node_uuid="hex-9">
        <primitive id="o2cb" long-id="o2cb:1" class="ocf" provider="ocfs2" type="o2cb"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="8" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <rsc_op id="27" operation="start" operation_key="dlm:1_start_0" on_node="hex-9" on_node_uuid="hex-9"/>
      </trigger>
      <trigger>
        <pseudo_event id="31" operation="start" operation_key="base-group:1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <rsc_op id="29" operation="start" operation_key="clvm:1_start_0" on_node="hex-9" on_node_uuid="hex-9">
        <primitive id="clvm" long-id="clvm:1" class="ocf" provider="lvm2" type="clvmd"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000"  daemon_timeout="30"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="8" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <rsc_op id="28" operation="start" operation_key="o2cb:1_start_0" on_node="hex-9" on_node_uuid="hex-9"/>
      </trigger>
      <trigger>
        <pseudo_event id="31" operation="start" operation_key="base-group:1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <rsc_op id="30" operation="start" operation_key="cmirrord:1_start_0" on_node="hex-9" on_node_uuid="hex-9">
        <primitive id="cmirrord" long-id="cmirrord:1" class="ocf" provider="lvm2" type="cmirrord"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000"  daemon_timeout="60"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="8" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <rsc_op id="29" operation="start" operation_key="clvm:1_start_0" on_node="hex-9" on_node_uuid="hex-9"/>
      </trigger>
      <trigger>
        <pseudo_event id="31" operation="start" operation_key="base-group:1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9">
    <action_set>
      <rsc_op id="11" operation="monitor" operation_key="vg1:1_monitor_0" on_node="hex-9" on_node_uuid="hex-9">
        <primitive id="vg1" long-id="vg1:1" class="ocf" provider="heartbeat" type="LVM"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_record_pending="false" CRM_meta_timeout="240000"  volgrpname="cluster-vg"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="10">
    <action_set>
      <pseudo_event id="43" operation="start" operation_key="base-clone_start_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="11" priority="1000000">
    <action_set>
      <rsc_op id="10" operation="probe_complete" operation_key="probe_complete" on_node="hex-9" on_node_uuid="hex-9">
        <attributes CRM_meta_op_no_wait="true" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="11" operation="monitor" operation_key="vg1:1_monitor_0" on_node="hex-9" on_node_uuid="hex-9"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="12">
    <action_set>
      <pseudo_event id="8" operation="probe_complete" operation_key="probe_complete">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="10" operation="probe_complete" operation_key="probe_complete" on_node="hex-9" on_node_uuid="hex-9"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="13">
    <action_set>
      <pseudo_event id="7" operation="load_stopped_hex-9" operation_key="load_stopped_hex-9">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="14">
    <action_set>
      <pseudo_event id="6" operation="load_stopped_hex-8" operation_key="load_stopped_hex-8">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="15">
    <action_set>
      <pseudo_event id="5" operation="load_stopped_hex-7" operation_key="load_stopped_hex-7">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="16">
    <action_set>
      <pseudo_event id="4" operation="load_stopped_hex-0" operation_key="load_stopped_hex-0">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
</transition_graph>

