<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="2" operation="monitor" operation_key="pingd:0_monitor_30000" on_node="cl-virt-1" on_node_uuid="cl-virt-1">
        <primitive id="pingd:0" long-id="pingdclone:pingd:0" class="ocf" provider="pacemaker" type="pingd"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_globally_unique="false" CRM_meta_interval="30000" CRM_meta_name="monitor" CRM_meta_timeout="30000" crm_feature_set="3.0.1" dampen="10" host_list="10.2.50.103 10.2.50.11 10.2.50.40 10.2.50.8" interval="5"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="23" operation="start" operation_key="pingd:0_start_0" on_node="cl-virt-1" on_node_uuid="cl-virt-1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="23" operation="start" operation_key="pingd:0_start_0" on_node="cl-virt-1" on_node_uuid="cl-virt-1">
        <primitive id="pingd:0" long-id="pingdclone:pingd:0" class="ocf" provider="pacemaker" type="pingd"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_globally_unique="false" CRM_meta_timeout="20000" crm_feature_set="3.0.1" dampen="10" host_list="10.2.50.103 10.2.50.11 10.2.50.40 10.2.50.8" interval="5"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="30" operation="stop" operation_key="pingd:0_stop_0" on_node="cl-virt-1" on_node_uuid="cl-virt-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="32" operation="start" operation_key="pingdclone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="30" operation="stop" operation_key="pingd:0_stop_0" on_node="cl-virt-1" on_node_uuid="cl-virt-1">
        <primitive id="pingd:0" long-id="pingdclone:pingd:0" class="ocf" provider="pacemaker" type="pingd"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_globally_unique="false" CRM_meta_timeout="20000" crm_feature_set="3.0.1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="34" operation="stop" operation_key="pingdclone_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <rsc_op id="9" operation="monitor" operation_key="pingd:0_monitor_30000" internal_operation_key="pingd:1_monitor_30000" on_node="cl-virt-2" on_node_uuid="cl-virt-2">
        <primitive id="pingd:0" long-id="pingd:1" class="ocf" provider="pacemaker" type="pingd"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_globally_unique="false" CRM_meta_interval="30000" CRM_meta_name="monitor" CRM_meta_timeout="30000" crm_feature_set="3.0.1" dampen="10" host_list="10.2.50.103 10.2.50.11 10.2.50.40 10.2.50.8" interval="5"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="24" operation="start" operation_key="pingd:0_start_0" internal_operation_key="pingd:1_start_0" on_node="cl-virt-2" on_node_uuid="cl-virt-2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <rsc_op id="24" operation="start" operation_key="pingd:0_start_0" internal_operation_key="pingd:1_start_0" on_node="cl-virt-2" on_node_uuid="cl-virt-2">
        <primitive id="pingd:0" long-id="pingd:1" class="ocf" provider="pacemaker" type="pingd"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_globally_unique="false" CRM_meta_timeout="20000" crm_feature_set="3.0.1" dampen="10" host_list="10.2.50.103 10.2.50.11 10.2.50.40 10.2.50.8" interval="5"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="31" operation="stop" operation_key="pingd:0_stop_0" internal_operation_key="pingd:1_stop_0" on_node="cl-virt-2" on_node_uuid="cl-virt-2"/>
      </trigger>
      <trigger>
        <pseudo_event id="32" operation="start" operation_key="pingdclone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <rsc_op id="31" operation="stop" operation_key="pingd:0_stop_0" internal_operation_key="pingd:1_stop_0" on_node="cl-virt-2" on_node_uuid="cl-virt-2">
        <primitive id="pingd:0" long-id="pingd:1" class="ocf" provider="pacemaker" type="pingd"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_globally_unique="false" CRM_meta_timeout="20000" crm_feature_set="3.0.1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="34" operation="stop" operation_key="pingdclone_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <pseudo_event id="32" operation="start" operation_key="pingdclone_start_0">
        <attributes CRM_meta_globally_unique="false" CRM_meta_timeout="20000" crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="34" operation="stop" operation_key="pingdclone_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="35" operation="stopped" operation_key="pingdclone_stopped_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7" priority="1000000">
    <action_set>
      <pseudo_event id="33" operation="running" operation_key="pingdclone_running_0">
        <attributes CRM_meta_globally_unique="false" CRM_meta_timeout="20000" crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="23" operation="start" operation_key="pingd:0_start_0" on_node="cl-virt-1" on_node_uuid="cl-virt-1"/>
      </trigger>
      <trigger>
        <rsc_op id="24" operation="start" operation_key="pingd:0_start_0" internal_operation_key="pingd:1_start_0" on_node="cl-virt-2" on_node_uuid="cl-virt-2"/>
      </trigger>
      <trigger>
        <pseudo_event id="32" operation="start" operation_key="pingdclone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <pseudo_event id="34" operation="stop" operation_key="pingdclone_stop_0">
        <attributes CRM_meta_globally_unique="false" CRM_meta_timeout="20000" crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="9" priority="1000000">
    <action_set>
      <pseudo_event id="35" operation="stopped" operation_key="pingdclone_stopped_0">
        <attributes CRM_meta_globally_unique="false" CRM_meta_timeout="20000" crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="30" operation="stop" operation_key="pingd:0_stop_0" on_node="cl-virt-1" on_node_uuid="cl-virt-1"/>
      </trigger>
      <trigger>
        <rsc_op id="31" operation="stop" operation_key="pingd:0_stop_0" internal_operation_key="pingd:1_stop_0" on_node="cl-virt-2" on_node_uuid="cl-virt-2"/>
      </trigger>
      <trigger>
        <pseudo_event id="34" operation="stop" operation_key="pingdclone_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="10">
    <action_set>
      <pseudo_event id="22" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="30" operation="stop" operation_key="pingd:0_stop_0" on_node="cl-virt-1" on_node_uuid="cl-virt-1"/>
      </trigger>
      <trigger>
        <rsc_op id="31" operation="stop" operation_key="pingd:0_stop_0" internal_operation_key="pingd:1_stop_0" on_node="cl-virt-2" on_node_uuid="cl-virt-2"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

