 <transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
   <synapse id="0">
     <action_set>
       <pseudo_event id="13" operation="stopped" operation_key="group_common_stopped_0">
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <rsc_op id="2" operation="stop" operation_key="resource_idvscommon_stop_0" on_node="ih02" on_node_uuid="57226bfc-310f-409b-8b3d-49d93498e4b5"/>
       </trigger>
       <trigger>
         <pseudo_event id="12" operation="stop" operation_key="group_common_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="1">
    <action_set>
      <pseudo_event id="12" operation="stop" operation_key="group_common_stop_0">
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
   <synapse id="2">
     <action_set>
       <rsc_op id="2" operation="stop" operation_key="resource_idvscommon_stop_0" on_node="ih02" on_node_uuid="57226bfc-310f-409b-8b3d-49d93498e4b5">
        <primitive id="resource_idvscommon" class="ocf" provider="dfs" type="idvs"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6" site="common"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="12" operation="stop" operation_key="group_common_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="3">
     <action_set>
       <pseudo_event id="4" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <rsc_op id="2" operation="stop" operation_key="resource_idvscommon_stop_0" on_node="ih02" on_node_uuid="57226bfc-310f-409b-8b3d-49d93498e4b5"/>
       </trigger>
     </inputs>
   </synapse>
 </transition_graph>

