<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="5" operation="stop" operation_key="child1-service_stop_0" on_node="ha2.test.anchor.net.au" on_node_uuid="3232235522">
        <primitive id="child1-service" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="1">
    <action_set>
      <pseudo_event id="1" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="stop" operation_key="child1-service_stop_0" on_node="ha2.test.anchor.net.au" on_node_uuid="3232235522"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>
