<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="17" operation="stop" operation_key="A_stop_0" internal_operation_key="A:0_stop_0" on_node="rhel7-auto1" on_node_uuid="1">
        <primitive id="A" long-id="A:0" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_name="stop" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="23" operation="stop" operation_key="A-clone_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="20" operation="stop" operation_key="A_stop_0" internal_operation_key="A:2_stop_0" on_node="rhel7-auto3" on_node_uuid="3">
        <primitive id="A" long-id="A:2" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_name="stop" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="23" operation="stop" operation_key="A-clone_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2" priority="1000000">
    <action_set>
      <pseudo_event id="24" operation="stopped" operation_key="A-clone_stopped_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="17" operation="stop" operation_key="A_stop_0" internal_operation_key="A:0_stop_0" on_node="rhel7-auto1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="20" operation="stop" operation_key="A_stop_0" internal_operation_key="A:2_stop_0" on_node="rhel7-auto3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <pseudo_event id="23" operation="stop" operation_key="A-clone_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <pseudo_event id="23" operation="stop" operation_key="A-clone_stop_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="4" priority="1000000">
    <action_set>
      <pseudo_event id="22" operation="running" operation_key="A-clone_running_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="21" operation="start" operation_key="A-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <pseudo_event id="21" operation="start" operation_key="A-clone_start_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="24" operation="stopped" operation_key="A-clone_stopped_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <pseudo_event id="9" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="17" operation="stop" operation_key="A_stop_0" internal_operation_key="A:0_stop_0" on_node="rhel7-auto1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="20" operation="stop" operation_key="A_stop_0" internal_operation_key="A:2_stop_0" on_node="rhel7-auto3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>
