<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <pseudo_event id="30" operation="stopped" operation_key="svc_stopped_0">
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="15" operation="stop" operation_key="ipv6_dem_tas_dns_stop_0" on_node="DEM-1" on_node_uuid="DEM-1"/>
      </trigger>
      <trigger>
        <rsc_op id="18" operation="stop" operation_key="d_bird_subnet_state_stop_0" on_node="DEM-1" on_node_uuid="DEM-1"/>
      </trigger>
      <trigger>
        <rsc_op id="21" operation="stop" operation_key="ip_mgmt_stop_0" on_node="DEM-1" on_node_uuid="DEM-1"/>
      </trigger>
      <trigger>
        <rsc_op id="24" operation="stop" operation_key="ip_trf_tas_stop_0" on_node="DEM-1" on_node_uuid="DEM-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="29" operation="stop" operation_key="svc_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <pseudo_event id="29" operation="stop" operation_key="svc_stop_0">
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="2">
    <action_set>
      <pseudo_event id="28" operation="running" operation_key="svc_running_0">
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="16" operation="start" operation_key="ipv6_dem_tas_dns_start_0" on_node="DEM-2" on_node_uuid="DEM-2"/>
      </trigger>
      <trigger>
        <rsc_op id="19" operation="start" operation_key="d_bird_subnet_state_start_0" on_node="DEM-2" on_node_uuid="DEM-2"/>
      </trigger>
      <trigger>
        <rsc_op id="22" operation="start" operation_key="ip_mgmt_start_0" on_node="DEM-2" on_node_uuid="DEM-2"/>
      </trigger>
      <trigger>
        <rsc_op id="25" operation="start" operation_key="ip_trf_tas_start_0" on_node="DEM-2" on_node_uuid="DEM-2"/>
      </trigger>
      <trigger>
        <pseudo_event id="27" operation="start" operation_key="svc_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <pseudo_event id="27" operation="start" operation_key="svc_start_0">
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="30" operation="stopped" operation_key="svc_stopped_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <rsc_op id="17" operation="monitor" operation_key="ipv6_dem_tas_dns_monitor_10000" on_node="DEM-2" on_node_uuid="DEM-2">
        <primitive id="ipv6_dem_tas_dns" class="ocf" provider="heartbeat" type="IPv6addr"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_timeout="20000" cidr_netmask="112" crm_feature_set="3.0.7" ipv6addr="fd15:a2c:8660:c828:172:16:10:241" nic="bond0.3010"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="16" operation="start" operation_key="ipv6_dem_tas_dns_start_0" on_node="DEM-2" on_node_uuid="DEM-2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <rsc_op id="16" operation="start" operation_key="ipv6_dem_tas_dns_start_0" on_node="DEM-2" on_node_uuid="DEM-2">
        <primitive id="ipv6_dem_tas_dns" class="ocf" provider="heartbeat" type="IPv6addr"/>
        <attributes CRM_meta_timeout="20000" cidr_netmask="112" crm_feature_set="3.0.7" ipv6addr="fd15:a2c:8660:c828:172:16:10:241" nic="bond0.3010"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="15" operation="stop" operation_key="ipv6_dem_tas_dns_stop_0" on_node="DEM-1" on_node_uuid="DEM-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="27" operation="start" operation_key="svc_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <rsc_op id="15" operation="stop" operation_key="ipv6_dem_tas_dns_stop_0" on_node="DEM-1" on_node_uuid="DEM-1">
        <primitive id="ipv6_dem_tas_dns" class="ocf" provider="heartbeat" type="IPv6addr"/>
        <attributes CRM_meta_timeout="20000" cidr_netmask="112" crm_feature_set="3.0.7" ipv6addr="fd15:a2c:8660:c828:172:16:10:241" nic="bond0.3010"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="18" operation="stop" operation_key="d_bird_subnet_state_stop_0" on_node="DEM-1" on_node_uuid="DEM-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="29" operation="stop" operation_key="svc_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <rsc_op id="20" operation="monitor" operation_key="d_bird_subnet_state_monitor_10000" on_node="DEM-2" on_node_uuid="DEM-2">
        <primitive id="d_bird_subnet_state" class="lsb" type="bird_subnet_state"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="19" operation="start" operation_key="d_bird_subnet_state_start_0" on_node="DEM-2" on_node_uuid="DEM-2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <rsc_op id="19" operation="start" operation_key="d_bird_subnet_state_start_0" on_node="DEM-2" on_node_uuid="DEM-2">
        <primitive id="d_bird_subnet_state" class="lsb" type="bird_subnet_state"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="16" operation="start" operation_key="ipv6_dem_tas_dns_start_0" on_node="DEM-2" on_node_uuid="DEM-2"/>
      </trigger>
      <trigger>
        <rsc_op id="18" operation="stop" operation_key="d_bird_subnet_state_stop_0" on_node="DEM-1" on_node_uuid="DEM-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="27" operation="start" operation_key="svc_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9">
    <action_set>
      <rsc_op id="18" operation="stop" operation_key="d_bird_subnet_state_stop_0" on_node="DEM-1" on_node_uuid="DEM-1">
        <primitive id="d_bird_subnet_state" class="lsb" type="bird_subnet_state"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="21" operation="stop" operation_key="ip_mgmt_stop_0" on_node="DEM-1" on_node_uuid="DEM-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="29" operation="stop" operation_key="svc_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="10">
    <action_set>
      <rsc_op id="23" operation="monitor" operation_key="ip_mgmt_monitor_10000" on_node="DEM-2" on_node_uuid="DEM-2">
        <primitive id="ip_mgmt" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_timeout="20000" broadcast="172.20.1.241" crm_feature_set="3.0.7" iflabel="ha" ip="172.20.1.241" nic="bond0"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="22" operation="start" operation_key="ip_mgmt_start_0" on_node="DEM-2" on_node_uuid="DEM-2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="11">
    <action_set>
      <rsc_op id="22" operation="start" operation_key="ip_mgmt_start_0" on_node="DEM-2" on_node_uuid="DEM-2">
        <primitive id="ip_mgmt" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_timeout="20000" broadcast="172.20.1.241" crm_feature_set="3.0.7" iflabel="ha" ip="172.20.1.241" nic="bond0"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="19" operation="start" operation_key="d_bird_subnet_state_start_0" on_node="DEM-2" on_node_uuid="DEM-2"/>
      </trigger>
      <trigger>
        <rsc_op id="21" operation="stop" operation_key="ip_mgmt_stop_0" on_node="DEM-1" on_node_uuid="DEM-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="27" operation="start" operation_key="svc_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="12">
    <action_set>
      <rsc_op id="21" operation="stop" operation_key="ip_mgmt_stop_0" on_node="DEM-1" on_node_uuid="DEM-1">
        <primitive id="ip_mgmt" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_timeout="20000" broadcast="172.20.1.241" crm_feature_set="3.0.7" iflabel="ha" ip="172.20.1.241" nic="bond0"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="24" operation="stop" operation_key="ip_trf_tas_stop_0" on_node="DEM-1" on_node_uuid="DEM-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="29" operation="stop" operation_key="svc_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="13">
    <action_set>
      <rsc_op id="26" operation="monitor" operation_key="ip_trf_tas_monitor_10000" on_node="DEM-2" on_node_uuid="DEM-2">
        <primitive id="ip_trf_tas" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_timeout="20000" broadcast="172.16.10.241" crm_feature_set="3.0.7" iflabel="ha" ip="172.16.10.241" nic="bond0.3010"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="25" operation="start" operation_key="ip_trf_tas_start_0" on_node="DEM-2" on_node_uuid="DEM-2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="14">
    <action_set>
      <rsc_op id="25" operation="start" operation_key="ip_trf_tas_start_0" on_node="DEM-2" on_node_uuid="DEM-2">
        <primitive id="ip_trf_tas" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_timeout="20000" broadcast="172.16.10.241" crm_feature_set="3.0.7" iflabel="ha" ip="172.16.10.241" nic="bond0.3010"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="22" operation="start" operation_key="ip_mgmt_start_0" on_node="DEM-2" on_node_uuid="DEM-2"/>
      </trigger>
      <trigger>
        <rsc_op id="24" operation="stop" operation_key="ip_trf_tas_stop_0" on_node="DEM-1" on_node_uuid="DEM-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="27" operation="start" operation_key="svc_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="15">
    <action_set>
      <rsc_op id="24" operation="stop" operation_key="ip_trf_tas_stop_0" on_node="DEM-1" on_node_uuid="DEM-1">
        <primitive id="ip_trf_tas" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_timeout="20000" broadcast="172.16.10.241" crm_feature_set="3.0.7" iflabel="ha" ip="172.16.10.241" nic="bond0.3010"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="29" operation="stop" operation_key="svc_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="16">
    <action_set>
      <pseudo_event id="11" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="15" operation="stop" operation_key="ipv6_dem_tas_dns_stop_0" on_node="DEM-1" on_node_uuid="DEM-1"/>
      </trigger>
      <trigger>
        <rsc_op id="18" operation="stop" operation_key="d_bird_subnet_state_stop_0" on_node="DEM-1" on_node_uuid="DEM-1"/>
      </trigger>
      <trigger>
        <rsc_op id="21" operation="stop" operation_key="ip_mgmt_stop_0" on_node="DEM-1" on_node_uuid="DEM-1"/>
      </trigger>
      <trigger>
        <rsc_op id="24" operation="stop" operation_key="ip_trf_tas_stop_0" on_node="DEM-1" on_node_uuid="DEM-1"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>
