<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="14" operation="monitor" operation_key="stonith-1_monitor_0" on_node="wc01" on_node_uuid="31de4ab3-2d05-476e-8f9a-627ad6cd94ca">
        <primitive id="stonith-1" long-id="stonith-1" class="stonith" type="dummy"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.2"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="16" operation="monitor" operation_key="stonith-1_monitor_0" on_node="wc02" on_node_uuid="f36760d8-d84a-46b2-b452-4c8cac8b3396">
        <primitive id="stonith-1" long-id="stonith-1" class="stonith" type="dummy"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.2"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="18" operation="monitor" operation_key="stonith-1_monitor_0" on_node="wc03" on_node_uuid="f61edb1d-6f49-4ffa-a46a-42ceef796f6e">
        <primitive id="stonith-1" long-id="stonith-1" class="stonith" type="dummy"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.2"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="3">
    <action_set>
      <rsc_op id="19" operation="start" operation_key="stonith-1_start_0" on_node="wc01" on_node_uuid="31de4ab3-2d05-476e-8f9a-627ad6cd94ca">
        <primitive id="stonith-1" long-id="stonith-1" class="stonith" type="dummy"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.2"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="12" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <crm_event id="1" operation="clear_failcount" operation_key="fs_www:0_clear_failcount" on_node="wc02" on_node_uuid="f36760d8-d84a-46b2-b452-4c8cac8b3396">
        <primitive id="fs_www:0" long-id="clone_webservice:group_webservice:0:fs_www:0" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_op_no_wait="true" CRM_meta_timeout="20000" clone-max="2" clone-node-max="1" crm_feature_set="3.0.2" device="wcnfs:/share/drbd_www/data/" directory="/data/www" fstype="nfs"/>
      </crm_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="5">
    <action_set>
      <crm_event id="5" operation="clear_failcount" operation_key="fs_www:0_clear_failcount" on_node="wc01" on_node_uuid="31de4ab3-2d05-476e-8f9a-627ad6cd94ca">
        <primitive id="fs_www:0" long-id="clone_webservice:group_webservice:0:fs_www:0" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_op_no_wait="true" CRM_meta_timeout="20000" clone-max="2" clone-node-max="1" crm_feature_set="3.0.2" device="wcnfs:/share/drbd_www/data/" directory="/data/www" fstype="nfs"/>
      </crm_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="6">
    <action_set>
      <crm_event id="7" operation="clear_failcount" operation_key="apache2:0_clear_failcount" on_node="wc01" on_node_uuid="31de4ab3-2d05-476e-8f9a-627ad6cd94ca">
        <primitive id="apache2:0" long-id="clone_webservice:group_webservice:0:apache2:0" class="ocf" provider="heartbeat" type="apache"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_op_no_wait="true" CRM_meta_timeout="20000" clone-max="2" clone-node-max="1" configfile="/etc/apache2/apache2.conf" crm_feature_set="3.0.2" envfiles="/etc/apache2/envvars" httpd="/usr/sbin/apache2" options="-k start" statusurl="http://localhost/server-status/"/>
      </crm_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="7">
    <action_set>
      <pseudo_event id="39" operation="stop" operation_key="group_webservice:2_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.2"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="47" operation="stop" operation_key="clone_webservice_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <pseudo_event id="40" operation="stopped" operation_key="group_webservice:2_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.2"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="36" operation="stop" operation_key="apache2:0_stop_0" internal_operation_key="apache2:2_stop_0" on_node="wc02" on_node_uuid="f36760d8-d84a-46b2-b452-4c8cac8b3396"/>
      </trigger>
      <trigger>
        <pseudo_event id="39" operation="stop" operation_key="group_webservice:2_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9">
    <action_set>
      <crm_event id="9" operation="clear_failcount" operation_key="fs_www:2_clear_failcount" on_node="wc03" on_node_uuid="f61edb1d-6f49-4ffa-a46a-42ceef796f6e">
        <primitive id="fs_www:2" long-id="clone_webservice:group_webservice:2:fs_www:2" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_op_no_wait="true" CRM_meta_timeout="20000" clone-max="2" clone-node-max="1" crm_feature_set="3.0.2" device="wcnfs:/share/drbd_www/data/" directory="/data/www" fstype="nfs"/>
      </crm_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="10">
    <action_set>
      <crm_event id="4" operation="clear_failcount" operation_key="apache2:0_clear_failcount_0" internal_operation_key="apache2:2_clear_failcount" on_node="wc02" on_node_uuid="f36760d8-d84a-46b2-b452-4c8cac8b3396">
        <primitive id="apache2:0" long-id="apache2:2" class="ocf" provider="heartbeat" type="apache"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_op_no_wait="true" CRM_meta_timeout="20000" clone-max="2" clone-node-max="1" configfile="/etc/apache2/apache2.conf" crm_feature_set="3.0.2" envfiles="/etc/apache2/envvars" httpd="/usr/sbin/apache2" options="-k start" statusurl="http://localhost/server-status/"/>
      </crm_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="11">
    <action_set>
      <rsc_op id="36" operation="stop" operation_key="apache2:0_stop_0" internal_operation_key="apache2:2_stop_0" on_node="wc02" on_node_uuid="f36760d8-d84a-46b2-b452-4c8cac8b3396">
        <primitive id="apache2:0" long-id="apache2:2" class="ocf" provider="heartbeat" type="apache"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.2"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="39" operation="stop" operation_key="group_webservice:2_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="12">
    <action_set>
      <crm_event id="10" operation="clear_failcount" operation_key="apache2:3_clear_failcount" on_node="wc03" on_node_uuid="f61edb1d-6f49-4ffa-a46a-42ceef796f6e">
        <primitive id="apache2:3" long-id="clone_webservice:group_webservice:3:apache2:3" class="ocf" provider="heartbeat" type="apache"/>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_op_no_wait="true" CRM_meta_timeout="20000" clone-max="2" clone-node-max="1" configfile="/etc/apache2/apache2.conf" crm_feature_set="3.0.2" envfiles="/etc/apache2/envvars" httpd="/usr/sbin/apache2" options="-k start" statusurl="http://localhost/server-status/"/>
      </crm_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="13">
    <action_set>
      <pseudo_event id="47" operation="stop" operation_key="clone_webservice_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.2"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="14" priority="1000000">
    <action_set>
      <pseudo_event id="48" operation="stopped" operation_key="clone_webservice_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.2"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="40" operation="stopped" operation_key="group_webservice:2_stopped_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="47" operation="stop" operation_key="clone_webservice_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="15">
    <action_set>
      <pseudo_event id="11" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.2"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="36" operation="stop" operation_key="apache2:0_stop_0" internal_operation_key="apache2:2_stop_0" on_node="wc02" on_node_uuid="f36760d8-d84a-46b2-b452-4c8cac8b3396"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="16">
    <action_set>
      <pseudo_event id="12" operation="probe_complete" operation_key="probe_complete">
        <attributes crm_feature_set="3.0.2"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="13" operation="probe_complete" operation_key="probe_complete" on_node="wc01" on_node_uuid="31de4ab3-2d05-476e-8f9a-627ad6cd94ca"/>
      </trigger>
      <trigger>
        <rsc_op id="15" operation="probe_complete" operation_key="probe_complete" on_node="wc02" on_node_uuid="f36760d8-d84a-46b2-b452-4c8cac8b3396"/>
      </trigger>
      <trigger>
        <rsc_op id="17" operation="probe_complete" operation_key="probe_complete" on_node="wc03" on_node_uuid="f61edb1d-6f49-4ffa-a46a-42ceef796f6e"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="17" priority="1000000">
    <action_set>
      <rsc_op id="13" operation="probe_complete" operation_key="probe_complete" on_node="wc01" on_node_uuid="31de4ab3-2d05-476e-8f9a-627ad6cd94ca">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.2"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="14" operation="monitor" operation_key="stonith-1_monitor_0" on_node="wc01" on_node_uuid="31de4ab3-2d05-476e-8f9a-627ad6cd94ca"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="18" priority="1000000">
    <action_set>
      <rsc_op id="15" operation="probe_complete" operation_key="probe_complete" on_node="wc02" on_node_uuid="f36760d8-d84a-46b2-b452-4c8cac8b3396">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.2"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="16" operation="monitor" operation_key="stonith-1_monitor_0" on_node="wc02" on_node_uuid="f36760d8-d84a-46b2-b452-4c8cac8b3396"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="19" priority="1000000">
    <action_set>
      <rsc_op id="17" operation="probe_complete" operation_key="probe_complete" on_node="wc03" on_node_uuid="f61edb1d-6f49-4ffa-a46a-42ceef796f6e">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.2"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="18" operation="monitor" operation_key="stonith-1_monitor_0" on_node="wc03" on_node_uuid="f61edb1d-6f49-4ffa-a46a-42ceef796f6e"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

