<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="12" operation="monitor" operation_key="A_monitor_10000" internal_operation_key="A:0_monitor_10000" on_node="rhel7-auto3" on_node_uuid="3">
        <primitive id="A" long-id="A:0" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="11" operation="start" operation_key="A_start_0" internal_operation_key="A:0_start_0" on_node="rhel7-auto3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="11" operation="start" operation_key="A_start_0" internal_operation_key="A:0_start_0" on_node="rhel7-auto3" on_node_uuid="3">
        <primitive id="A" long-id="A:0" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="13" operation="start" operation_key="A-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2" priority="1000000">
    <action_set>
      <pseudo_event id="14" operation="running" operation_key="A-clone_running_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="11" operation="start" operation_key="A_start_0" internal_operation_key="A:0_start_0" on_node="rhel7-auto3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <pseudo_event id="13" operation="start" operation_key="A-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <pseudo_event id="13" operation="start" operation_key="A-clone_start_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="4">
    <action_set>
      <rsc_op id="18" operation="monitor" operation_key="B_monitor_10000" internal_operation_key="B:0_monitor_10000" on_node="rhel7-auto3" on_node_uuid="3">
        <primitive id="B" long-id="B:0" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="17" operation="start" operation_key="B_start_0" internal_operation_key="B:0_start_0" on_node="rhel7-auto3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <rsc_op id="17" operation="start" operation_key="B_start_0" internal_operation_key="B:0_start_0" on_node="rhel7-auto3" on_node_uuid="3">
        <primitive id="B" long-id="B:0" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="19" operation="start" operation_key="B-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6" priority="1000000">
    <action_set>
      <pseudo_event id="20" operation="running" operation_key="B-clone_running_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="17" operation="start" operation_key="B_start_0" internal_operation_key="B:0_start_0" on_node="rhel7-auto3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <pseudo_event id="19" operation="start" operation_key="B-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <pseudo_event id="19" operation="start" operation_key="B-clone_start_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="14" operation="running" operation_key="A-clone_running_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <rsc_op id="24" operation="monitor" operation_key="C_monitor_10000" internal_operation_key="C:0_monitor_10000" on_node="rhel7-auto2" on_node_uuid="2">
        <primitive id="C" long-id="C:0" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="23" operation="start" operation_key="C_start_0" internal_operation_key="C:0_start_0" on_node="rhel7-auto2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9">
    <action_set>
      <rsc_op id="23" operation="start" operation_key="C_start_0" internal_operation_key="C:0_start_0" on_node="rhel7-auto2" on_node_uuid="2">
        <primitive id="C" long-id="C:0" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="29" operation="start" operation_key="C-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="10">
    <action_set>
      <rsc_op id="26" operation="monitor" operation_key="C:1_monitor_10000" on_node="rhel7-auto1" on_node_uuid="1">
        <primitive id="C" long-id="C:1" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="25" operation="start" operation_key="C:1_start_0" on_node="rhel7-auto1" on_node_uuid="1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="11">
    <action_set>
      <rsc_op id="25" operation="start" operation_key="C:1_start_0" on_node="rhel7-auto1" on_node_uuid="1">
        <primitive id="C" long-id="C:1" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="29" operation="start" operation_key="C-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="12">
    <action_set>
      <rsc_op id="28" operation="monitor" operation_key="C:2_monitor_10000" on_node="rhel7-auto3" on_node_uuid="3">
        <primitive id="C" long-id="C:2" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="27" operation="start" operation_key="C:2_start_0" on_node="rhel7-auto3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="13">
    <action_set>
      <rsc_op id="27" operation="start" operation_key="C:2_start_0" on_node="rhel7-auto3" on_node_uuid="3">
        <primitive id="C" long-id="C:2" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="29" operation="start" operation_key="C-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="14" priority="1000000">
    <action_set>
      <pseudo_event id="30" operation="running" operation_key="C-clone_running_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="23" operation="start" operation_key="C_start_0" internal_operation_key="C:0_start_0" on_node="rhel7-auto2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="25" operation="start" operation_key="C:1_start_0" on_node="rhel7-auto1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="27" operation="start" operation_key="C:2_start_0" on_node="rhel7-auto3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <pseudo_event id="29" operation="start" operation_key="C-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="15">
    <action_set>
      <pseudo_event id="29" operation="start" operation_key="C-clone_start_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="2" operation="clone-one-or-more:order-B-clone-C-clone-mandatory" operation_key="clone-one-or-more:order-B-clone-C-clone-mandatory"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="16">
    <action_set>
      <pseudo_event id="2" operation="clone-one-or-more:order-B-clone-C-clone-mandatory" operation_key="clone-one-or-more:order-B-clone-C-clone-mandatory">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="17" operation="start" operation_key="B_start_0" internal_operation_key="B:0_start_0" on_node="rhel7-auto3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>
