 <transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
   <synapse id="0">
     <action_set>
       <rsc_op id="7" operation="start" operation_key="drbd0:1_start_0" on_node="mysql-01" on_node_uuid="3f3eb909-e719-4bc4-a700-d7aa91a65098">
        <primitive id="drbd0" long-id="drbd0:1" class="ocf" provider="heartbeat" type="drbd"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000"  drbd_resource="r0"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="8" operation="start" operation_key="ms-drbd0_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="1" priority="1000000">
     <action_set>
       <pseudo_event id="9" operation="running" operation_key="ms-drbd0_running_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <rsc_op id="7" operation="start" operation_key="drbd0:1_start_0" on_node="mysql-01" on_node_uuid="3f3eb909-e719-4bc4-a700-d7aa91a65098"/>
       </trigger>
       <trigger>
         <pseudo_event id="8" operation="start" operation_key="ms-drbd0_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="2">
    <action_set>
      <pseudo_event id="8" operation="start" operation_key="ms-drbd0_start_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
 </transition_graph>

