 <transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
   <synapse id="0">
     <action_set>
      <pseudo_event id="56" operation="running" operation_key="group-1_running_0">
        <attributes CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="49" operation="start" operation_key="fs-1_start_0" on_node="pollux" on_node_uuid="26cfbecf-dc25-42e1-84de-325ca9e457b5"/>
       </trigger>
       <trigger>
        <rsc_op id="51" operation="start" operation_key="ip-198_start_0" on_node="pollux" on_node_uuid="26cfbecf-dc25-42e1-84de-325ca9e457b5"/>
       </trigger>
       <trigger>
        <rsc_op id="53" operation="start" operation_key="apache_start_0" on_node="pollux" on_node_uuid="26cfbecf-dc25-42e1-84de-325ca9e457b5"/>
       </trigger>
       <trigger>
        <pseudo_event id="55" operation="start" operation_key="group-1_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="1">
    <action_set>
      <pseudo_event id="55" operation="start" operation_key="group-1_start_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
   <synapse id="2">
     <action_set>
      <rsc_op id="50" operation="monitor" operation_key="fs-1_monitor_20000" on_node="pollux" on_node_uuid="26cfbecf-dc25-42e1-84de-325ca9e457b5">
        <primitive id="fs-1" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_interval="20000" CRM_meta_name="monitor" CRM_meta_start_delay="10000" CRM_meta_timeout="20000"  device="/dev/drbd0" directory="/drbd" fstype="xfs" options="noatime,exec,nosuid,nodev"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="49" operation="start" operation_key="fs-1_start_0" on_node="pollux" on_node_uuid="26cfbecf-dc25-42e1-84de-325ca9e457b5"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="3">
     <action_set>
      <rsc_op id="49" operation="start" operation_key="fs-1_start_0" on_node="pollux" on_node_uuid="26cfbecf-dc25-42e1-84de-325ca9e457b5">
        <primitive id="fs-1" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_name="start" CRM_meta_timeout="10000"  device="/dev/drbd0" directory="/drbd" fstype="xfs" options="noatime,exec,nosuid,nodev"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="55" operation="start" operation_key="group-1_start_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="4">
     <action_set>
      <rsc_op id="52" operation="monitor" operation_key="ip-198_monitor_30000" on_node="pollux" on_node_uuid="26cfbecf-dc25-42e1-84de-325ca9e457b5">
        <primitive id="ip-198" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_interval="30000" CRM_meta_name="monitor" CRM_meta_start_delay="10000" CRM_meta_timeout="25000" cidr_netmask="28"  iflabel="198" ip="80.237.189.198" nic="eth1"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="51" operation="start" operation_key="ip-198_start_0" on_node="pollux" on_node_uuid="26cfbecf-dc25-42e1-84de-325ca9e457b5"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="5">
     <action_set>
      <rsc_op id="51" operation="start" operation_key="ip-198_start_0" on_node="pollux" on_node_uuid="26cfbecf-dc25-42e1-84de-325ca9e457b5">
        <primitive id="ip-198" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_name="start" CRM_meta_timeout="10000" cidr_netmask="28"  iflabel="198" ip="80.237.189.198" nic="eth1"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="49" operation="start" operation_key="fs-1_start_0" on_node="pollux" on_node_uuid="26cfbecf-dc25-42e1-84de-325ca9e457b5"/>
      </trigger>
      <trigger>
        <pseudo_event id="55" operation="start" operation_key="group-1_start_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="6">
     <action_set>
      <rsc_op id="54" operation="monitor" operation_key="apache_monitor_60000" on_node="pollux" on_node_uuid="26cfbecf-dc25-42e1-84de-325ca9e457b5">
        <primitive id="apache" class="ocf" provider="custom" type="apache2"/>
        <attributes CRM_meta_interval="60000" CRM_meta_name="monitor" CRM_meta_start_delay="10000" CRM_meta_timeout="40000" apache2_bin="/usr/sbin/apache2" apache2_config="/etc/apache2/httpd.conf" apache2_listening_check="80.237.189.198:80" apache2_opts="-D STATUS -D INFO -D LANGUAGE -D SSL -D SUEXEC -D PHP5" apache2_pidfile="/var/run/apache2.pid" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="53" operation="start" operation_key="apache_start_0" on_node="pollux" on_node_uuid="26cfbecf-dc25-42e1-84de-325ca9e457b5"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="7">
     <action_set>
      <rsc_op id="53" operation="start" operation_key="apache_start_0" on_node="pollux" on_node_uuid="26cfbecf-dc25-42e1-84de-325ca9e457b5">
        <primitive id="apache" class="ocf" provider="custom" type="apache2"/>
        <attributes CRM_meta_name="start" CRM_meta_timeout="30000" apache2_bin="/usr/sbin/apache2" apache2_config="/etc/apache2/httpd.conf" apache2_listening_check="80.237.189.198:80" apache2_opts="-D STATUS -D INFO -D LANGUAGE -D SSL -D SUEXEC -D PHP5" apache2_pidfile="/var/run/apache2.pid" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="51" operation="start" operation_key="ip-198_start_0" on_node="pollux" on_node_uuid="26cfbecf-dc25-42e1-84de-325ca9e457b5"/>
      </trigger>
      <trigger>
        <pseudo_event id="55" operation="start" operation_key="group-1_start_0"/>
       </trigger>
     </inputs>
   </synapse>
 </transition_graph>

