<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="35" operation="notify" operation_key="NATIVE_RSC_A:0_pre_notify_stop_0" on_node="fc16-builder" on_node_uuid="fc16-builder">
        <primitive id="NATIVE_RSC_A" long-id="NATIVE_RSC_A:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="1" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="0" CRM_meta_master_node_max="0" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="stop" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="stop" CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource="NATIVE_RSC_A:0 " CRM_meta_notify_slave_uname="fc16-builder " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource="NATIVE_RSC_A:0 " CRM_meta_notify_stop_uname="fc16-builder " CRM_meta_notify_type="pre" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="14" operation="notify" operation_key="MASTER_RSC_A_pre_notify_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="5" operation="stop" operation_key="NATIVE_RSC_A:0_stop_0" on_node="fc16-builder" on_node_uuid="fc16-builder">
        <primitive id="NATIVE_RSC_A" long-id="NATIVE_RSC_A:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="1" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="0" CRM_meta_master_node_max="0" CRM_meta_name="stop" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource="NATIVE_RSC_A:0 " CRM_meta_notify_slave_uname="fc16-builder " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource="NATIVE_RSC_A:0 " CRM_meta_notify_stop_uname="fc16-builder " CRM_meta_timeout="100000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="12" operation="stop" operation_key="MASTER_RSC_A_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2" priority="1000000">
    <action_set>
      <pseudo_event id="17" operation="notified" operation_key="MASTER_RSC_A_confirmed-post_notify_stopped_0">
        <attributes CRM_meta_clone_max="1" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="0" CRM_meta_master_node_max="0" CRM_meta_notify="true" CRM_meta_notify_key_operation="stopped" CRM_meta_notify_key_type="confirmed-post" CRM_meta_notify_operation="stop" CRM_meta_notify_type="post" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="16" operation="notify" operation_key="MASTER_RSC_A_post_notify_stopped_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3" priority="1000000">
    <action_set>
      <pseudo_event id="16" operation="notify" operation_key="MASTER_RSC_A_post_notify_stopped_0">
        <attributes CRM_meta_clone_max="1" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="0" CRM_meta_master_node_max="0" CRM_meta_notify="true" CRM_meta_notify_key_operation="stopped" CRM_meta_notify_key_type="post" CRM_meta_notify_operation="stop" CRM_meta_notify_type="post" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="13" operation="stopped" operation_key="MASTER_RSC_A_stopped_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="15" operation="notified" operation_key="MASTER_RSC_A_confirmed-pre_notify_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <pseudo_event id="15" operation="notified" operation_key="MASTER_RSC_A_confirmed-pre_notify_stop_0">
        <attributes CRM_meta_clone_max="1" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="0" CRM_meta_master_node_max="0" CRM_meta_notify="true" CRM_meta_notify_key_operation="stop" CRM_meta_notify_key_type="confirmed-pre" CRM_meta_notify_operation="stop" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="14" operation="notify" operation_key="MASTER_RSC_A_pre_notify_stop_0"/>
      </trigger>
      <trigger>
        <rsc_op id="35" operation="notify" operation_key="NATIVE_RSC_A:0_pre_notify_stop_0" on_node="fc16-builder" on_node_uuid="fc16-builder"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <pseudo_event id="14" operation="notify" operation_key="MASTER_RSC_A_pre_notify_stop_0">
        <attributes CRM_meta_clone_max="1" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="0" CRM_meta_master_node_max="0" CRM_meta_notify="true" CRM_meta_notify_key_operation="stop" CRM_meta_notify_key_type="pre" CRM_meta_notify_operation="stop" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="6" priority="1000000">
    <action_set>
      <pseudo_event id="13" operation="stopped" operation_key="MASTER_RSC_A_stopped_0">
        <attributes CRM_meta_clone_max="1" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="0" CRM_meta_master_node_max="0" CRM_meta_notify="true" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="stop" operation_key="NATIVE_RSC_A:0_stop_0" on_node="fc16-builder" on_node_uuid="fc16-builder"/>
      </trigger>
      <trigger>
        <pseudo_event id="12" operation="stop" operation_key="MASTER_RSC_A_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <pseudo_event id="12" operation="stop" operation_key="MASTER_RSC_A_stop_0">
        <attributes CRM_meta_clone_max="1" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="0" CRM_meta_master_node_max="0" CRM_meta_notify="true" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="15" operation="notified" operation_key="MASTER_RSC_A_confirmed-pre_notify_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <rsc_op id="30" operation="stop" operation_key="NATIVE_RSC_B_stop_0" on_node="fc16-builder" on_node_uuid="fc16-builder">
        <primitive id="NATIVE_RSC_B" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_name="stop" CRM_meta_timeout="100000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="9">
    <action_set>
      <pseudo_event id="2" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="stop" operation_key="NATIVE_RSC_A:0_stop_0" on_node="fc16-builder" on_node_uuid="fc16-builder"/>
      </trigger>
      <trigger>
        <pseudo_event id="17" operation="notified" operation_key="MASTER_RSC_A_confirmed-post_notify_stopped_0"/>
      </trigger>
      <trigger>
        <rsc_op id="30" operation="stop" operation_key="NATIVE_RSC_B_stop_0" on_node="fc16-builder" on_node_uuid="fc16-builder"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

