 <transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
   <synapse id="0">
     <action_set>
      <rsc_op id="4" operation="monitor" operation_key="rsc1_monitor_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc1" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="1">
     <action_set>
      <rsc_op id="5" operation="monitor" operation_key="rsc2_monitor_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc2" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="2">
     <action_set>
      <pseudo_event id="24" operation="stopped" operation_key="foo_stopped_0">
        <attributes CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="1" operation="stop" operation_key="rsc4_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <rsc_op id="19" operation="stop" operation_key="rsc5_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <pseudo_event id="23" operation="stop" operation_key="foo_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="3">
     <action_set>
      <pseudo_event id="23" operation="stop" operation_key="foo_stop_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="4">
    <action_set>
      <pseudo_event id="22" operation="running" operation_key="foo_running_0">
        <attributes CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="18" operation="start" operation_key="rsc4_start_0" on_node="node1" on_node_uuid="node1"/>
       </trigger>
       <trigger>
        <rsc_op id="20" operation="start" operation_key="rsc5_start_0" on_node="node1" on_node_uuid="node1"/>
       </trigger>
       <trigger>
        <pseudo_event id="21" operation="start" operation_key="foo_start_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="5">
     <action_set>
      <pseudo_event id="21" operation="start" operation_key="foo_start_0">
        <attributes CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="24" operation="stopped" operation_key="foo_stopped_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="6">
     <action_set>
      <rsc_op id="6" operation="monitor" operation_key="rsc3_monitor_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc3" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="7">
     <action_set>
      <rsc_op id="18" operation="start" operation_key="rsc4_start_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc4" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="1" operation="stop" operation_key="rsc4_stop_0" on_node="node1" on_node_uuid="node1"/>
       </trigger>
       <trigger>
        <rsc_op id="7" operation="monitor" operation_key="rsc4_monitor_0" on_node="node2" on_node_uuid="node2"/>
       </trigger>
       <trigger>
        <pseudo_event id="21" operation="start" operation_key="foo_start_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="8">
     <action_set>
      <rsc_op id="7" operation="monitor" operation_key="rsc4_monitor_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc4" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="9">
     <action_set>
      <rsc_op id="1" operation="stop" operation_key="rsc4_stop_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc4" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="7" operation="monitor" operation_key="rsc4_monitor_0" on_node="node2" on_node_uuid="node2"/>
       </trigger>
       <trigger>
        <rsc_op id="19" operation="stop" operation_key="rsc5_stop_0" on_node="node1" on_node_uuid="node1"/>
       </trigger>
       <trigger>
        <pseudo_event id="23" operation="stop" operation_key="foo_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="10">
     <action_set>
      <rsc_op id="20" operation="start" operation_key="rsc5_start_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc5" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <rsc_op id="8" operation="monitor" operation_key="rsc5_monitor_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
      <trigger>
        <rsc_op id="18" operation="start" operation_key="rsc4_start_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <rsc_op id="19" operation="stop" operation_key="rsc5_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <pseudo_event id="21" operation="start" operation_key="foo_start_0"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="11">
     <action_set>
      <rsc_op id="19" operation="stop" operation_key="rsc5_stop_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc5" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="8" operation="monitor" operation_key="rsc5_monitor_0" on_node="node2" on_node_uuid="node2"/>
       </trigger>
       <trigger>
        <pseudo_event id="23" operation="stop" operation_key="foo_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="12">
     <action_set>
      <rsc_op id="8" operation="monitor" operation_key="rsc5_monitor_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc5" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
    <inputs/>
  </synapse>
  <synapse id="13">
    <action_set>
      <pseudo_event id="33" operation="stopped" operation_key="bar_stopped_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
     <inputs>
       <trigger>
        <rsc_op id="2" operation="stop" operation_key="rsc7_stop_0" on_node="node1" on_node_uuid="node1"/>
       </trigger>
       <trigger>
        <rsc_op id="25" operation="stop" operation_key="rsc6_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <rsc_op id="28" operation="stop" operation_key="rsc8_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <pseudo_event id="32" operation="stop" operation_key="bar_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="14">
     <action_set>
      <pseudo_event id="32" operation="stop" operation_key="bar_stop_0">
        <attributes CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
    <inputs/>
   </synapse>
  <synapse id="15">
     <action_set>
      <pseudo_event id="31" operation="running" operation_key="bar_running_0">
        <attributes CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="26" operation="start" operation_key="rsc6_start_0" on_node="node2" on_node_uuid="node2"/>
       </trigger>
       <trigger>
        <rsc_op id="27" operation="start" operation_key="rsc7_start_0" on_node="node2" on_node_uuid="node2"/>
       </trigger>
       <trigger>
        <rsc_op id="29" operation="start" operation_key="rsc8_start_0" on_node="node2" on_node_uuid="node2"/>
       </trigger>
       <trigger>
        <pseudo_event id="30" operation="start" operation_key="bar_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="16">
     <action_set>
      <pseudo_event id="30" operation="start" operation_key="bar_start_0">
        <attributes CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="33" operation="stopped" operation_key="bar_stopped_0"/>
      </trigger>
    </inputs>
   </synapse>
  <synapse id="17">
     <action_set>
      <rsc_op id="26" operation="start" operation_key="rsc6_start_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc6" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="9" operation="monitor" operation_key="rsc6_monitor_0" on_node="node2" on_node_uuid="node2"/>
       </trigger>
       <trigger>
        <rsc_op id="25" operation="stop" operation_key="rsc6_stop_0" on_node="node1" on_node_uuid="node1"/>
       </trigger>
       <trigger>
        <pseudo_event id="30" operation="start" operation_key="bar_start_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="18">
     <action_set>
      <rsc_op id="25" operation="stop" operation_key="rsc6_stop_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc6" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="2" operation="stop" operation_key="rsc7_stop_0" on_node="node1" on_node_uuid="node1"/>
       </trigger>
       <trigger>
        <rsc_op id="9" operation="monitor" operation_key="rsc6_monitor_0" on_node="node2" on_node_uuid="node2"/>
       </trigger>
       <trigger>
        <pseudo_event id="32" operation="stop" operation_key="bar_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="19">
     <action_set>
      <rsc_op id="9" operation="monitor" operation_key="rsc6_monitor_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc6" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="20">
     <action_set>
      <rsc_op id="27" operation="start" operation_key="rsc7_start_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc7" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="2" operation="stop" operation_key="rsc7_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <rsc_op id="10" operation="monitor" operation_key="rsc7_monitor_0" on_node="node2" on_node_uuid="node2"/>
       </trigger>
       <trigger>
        <rsc_op id="26" operation="start" operation_key="rsc6_start_0" on_node="node2" on_node_uuid="node2"/>
       </trigger>
       <trigger>
        <pseudo_event id="30" operation="start" operation_key="bar_start_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="21">
     <action_set>
      <rsc_op id="10" operation="monitor" operation_key="rsc7_monitor_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc7" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="22">
     <action_set>
      <rsc_op id="2" operation="stop" operation_key="rsc7_stop_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc7" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="10" operation="monitor" operation_key="rsc7_monitor_0" on_node="node2" on_node_uuid="node2"/>
       </trigger>
       <trigger>
        <rsc_op id="28" operation="stop" operation_key="rsc8_stop_0" on_node="node1" on_node_uuid="node1"/>
       </trigger>
       <trigger>
        <pseudo_event id="32" operation="stop" operation_key="bar_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="23">
     <action_set>
      <rsc_op id="29" operation="start" operation_key="rsc8_start_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc8" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <rsc_op id="11" operation="monitor" operation_key="rsc8_monitor_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
      <trigger>
        <rsc_op id="27" operation="start" operation_key="rsc7_start_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
      <trigger>
        <rsc_op id="28" operation="stop" operation_key="rsc8_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <pseudo_event id="30" operation="start" operation_key="bar_start_0"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="24">
     <action_set>
      <rsc_op id="28" operation="stop" operation_key="rsc8_stop_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc8" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="11" operation="monitor" operation_key="rsc8_monitor_0" on_node="node2" on_node_uuid="node2"/>
       </trigger>
       <trigger>
        <pseudo_event id="32" operation="stop" operation_key="bar_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="25">
     <action_set>
      <rsc_op id="11" operation="monitor" operation_key="rsc8_monitor_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc8" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="26">
     <action_set>
      <pseudo_event id="3" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="1" operation="stop" operation_key="rsc4_stop_0" on_node="node1" on_node_uuid="node1"/>
       </trigger>
       <trigger>
        <rsc_op id="2" operation="stop" operation_key="rsc7_stop_0" on_node="node1" on_node_uuid="node1"/>
       </trigger>
       <trigger>
        <rsc_op id="19" operation="stop" operation_key="rsc5_stop_0" on_node="node1" on_node_uuid="node1"/>
       </trigger>
       <trigger>
        <rsc_op id="25" operation="stop" operation_key="rsc6_stop_0" on_node="node1" on_node_uuid="node1"/>
       </trigger>
       <trigger>
        <rsc_op id="28" operation="stop" operation_key="rsc8_stop_0" on_node="node1" on_node_uuid="node1"/>
       </trigger>
     </inputs>
   </synapse>
 </transition_graph>

