<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0" priority="10">
    <action_set>
      <pseudo_event id="44" operation="stopped" operation_key="voip_stopped_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="21" operation="stop" operation_key="mysqld_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="26" operation="stop" operation_key="dahdi_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <pseudo_event id="43" operation="stop" operation_key="voip_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1" priority="10">
    <action_set>
      <pseudo_event id="43" operation="stop" operation_key="voip_stop_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="2" priority="10">
    <action_set>
      <pseudo_event id="42" operation="running" operation_key="voip_running_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="22" operation="start" operation_key="mysqld_start_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="27" operation="start" operation_key="dahdi_start_0"/>
      </trigger>
      <trigger>
        <rsc_op id="31" operation="start" operation_key="fonulator_start_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <rsc_op id="33" operation="start" operation_key="asterisk_start_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <rsc_op id="35" operation="start" operation_key="iax2_mon_start_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <rsc_op id="37" operation="start" operation_key="httpd_start_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <rsc_op id="39" operation="start" operation_key="tftp_start_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="start" operation_key="voip_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3" priority="10">
    <action_set>
      <pseudo_event id="41" operation="start" operation_key="voip_start_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="44" operation="stopped" operation_key="voip_stopped_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="56" operation="running" operation_key="ip_voip_routes_running_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4" priority="10">
    <action_set>
      <rsc_op id="25" operation="migrate_from" operation_key="mysqld_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="mysqld" class="lsb" type="mysql"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="24" operation="migrate_to" operation_key="mysqld_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5" priority="10">
    <action_set>
      <rsc_op id="24" operation="migrate_to" operation_key="mysqld_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="mysqld" class="lsb" type="mysql"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_record_pending="true" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="6" priority="10">
    <action_set>
      <rsc_op id="23" operation="monitor" operation_key="mysqld_monitor_1000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="mysqld" class="lsb" type="mysql"/>
        <attributes CRM_meta_interval="1000" CRM_meta_name="monitor" CRM_meta_start_delay="10000" CRM_meta_timeout="25000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="22" operation="start" operation_key="mysqld_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7" priority="10">
    <action_set>
      <pseudo_event id="22" operation="start" operation_key="mysqld_start_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="21" operation="stop" operation_key="mysqld_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="25" operation="migrate_from" operation_key="mysqld_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="start" operation_key="voip_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8" priority="10">
    <action_set>
      <rsc_op id="21" operation="stop" operation_key="mysqld_stop_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="mysqld" class="lsb" type="mysql"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="25" operation="migrate_from" operation_key="mysqld_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <rsc_op id="26" operation="stop" operation_key="dahdi_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <pseudo_event id="43" operation="stop" operation_key="voip_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9" priority="10">
    <action_set>
      <rsc_op id="30" operation="migrate_from" operation_key="dahdi_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="dahdi" class="lsb" type="dahdi"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="29" operation="migrate_to" operation_key="dahdi_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="10" priority="10">
    <action_set>
      <rsc_op id="29" operation="migrate_to" operation_key="dahdi_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="dahdi" class="lsb" type="dahdi"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_record_pending="true" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="25" operation="migrate_from" operation_key="mysqld_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="11" priority="10">
    <action_set>
      <rsc_op id="28" operation="monitor" operation_key="dahdi_monitor_1000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="dahdi" class="lsb" type="dahdi"/>
        <attributes CRM_meta_interval="1000" CRM_meta_name="monitor" CRM_meta_timeout="15000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="27" operation="start" operation_key="dahdi_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="12" priority="10">
    <action_set>
      <pseudo_event id="27" operation="start" operation_key="dahdi_start_0">
        <attributes CRM_meta_name="start" CRM_meta_timeout="15000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="22" operation="start" operation_key="mysqld_start_0"/>
      </trigger>
      <trigger>
        <rsc_op id="26" operation="stop" operation_key="dahdi_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="30" operation="migrate_from" operation_key="dahdi_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="start" operation_key="voip_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="13" priority="10">
    <action_set>
      <rsc_op id="26" operation="stop" operation_key="dahdi_stop_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="dahdi" class="lsb" type="dahdi"/>
        <attributes CRM_meta_name="stop" CRM_meta_timeout="15000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="30" operation="migrate_from" operation_key="dahdi_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="43" operation="stop" operation_key="voip_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="14" priority="10">
    <action_set>
      <rsc_op id="32" operation="monitor" operation_key="fonulator_monitor_1000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="fonulator" class="lsb" type="fonulator"/>
        <attributes CRM_meta_interval="1000" CRM_meta_name="monitor" CRM_meta_start_delay="30000" CRM_meta_timeout="50000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="31" operation="start" operation_key="fonulator_start_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="15" priority="10">
    <action_set>
      <rsc_op id="31" operation="start" operation_key="fonulator_start_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="fonulator" class="lsb" type="fonulator"/>
        <attributes CRM_meta_name="start" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="27" operation="start" operation_key="dahdi_start_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="start" operation_key="voip_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="16" priority="10">
    <action_set>
      <rsc_op id="34" operation="monitor" operation_key="asterisk_monitor_1000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="asterisk" class="lsb" type="asterisk-11.0.1"/>
        <attributes CRM_meta_interval="1000" CRM_meta_name="monitor" CRM_meta_start_delay="10000" CRM_meta_timeout="25000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="33" operation="start" operation_key="asterisk_start_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="17" priority="10">
    <action_set>
      <rsc_op id="33" operation="start" operation_key="asterisk_start_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="asterisk" class="lsb" type="asterisk-11.0.1"/>
        <attributes CRM_meta_name="start" CRM_meta_timeout="15000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="31" operation="start" operation_key="fonulator_start_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="start" operation_key="voip_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="18" priority="10">
    <action_set>
      <rsc_op id="36" operation="monitor" operation_key="iax2_mon_monitor_60000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="iax2_mon" class="lsb" type="iax2_mon"/>
        <attributes CRM_meta_interval="60000" CRM_meta_name="monitor" CRM_meta_start_delay="30000" CRM_meta_timeout="50000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="35" operation="start" operation_key="iax2_mon_start_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="19" priority="10">
    <action_set>
      <rsc_op id="35" operation="start" operation_key="iax2_mon_start_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="iax2_mon" class="lsb" type="iax2_mon"/>
        <attributes CRM_meta_name="start" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="33" operation="start" operation_key="asterisk_start_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="start" operation_key="voip_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="20" priority="10">
    <action_set>
      <rsc_op id="38" operation="monitor" operation_key="httpd_monitor_1000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="httpd" class="lsb" type="apache2"/>
        <attributes CRM_meta_interval="1000" CRM_meta_name="monitor" CRM_meta_start_delay="10000" CRM_meta_timeout="30000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="37" operation="start" operation_key="httpd_start_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="21" priority="10">
    <action_set>
      <rsc_op id="37" operation="start" operation_key="httpd_start_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="httpd" class="lsb" type="apache2"/>
        <attributes CRM_meta_name="start" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="35" operation="start" operation_key="iax2_mon_start_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="start" operation_key="voip_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="22" priority="10">
    <action_set>
      <rsc_op id="40" operation="monitor" operation_key="tftp_monitor_60000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="tftp" class="lsb" type="tftp-srce"/>
        <attributes CRM_meta_interval="60000" CRM_meta_name="monitor" CRM_meta_start_delay="10000" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="39" operation="start" operation_key="tftp_start_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="23" priority="10">
    <action_set>
      <rsc_op id="39" operation="start" operation_key="tftp_start_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="tftp" class="lsb" type="tftp-srce"/>
        <attributes CRM_meta_name="start" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="37" operation="start" operation_key="httpd_start_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="start" operation_key="voip_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="24" priority="9">
    <action_set>
      <pseudo_event id="58" operation="stopped" operation_key="ip_voip_routes_stopped_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="45" operation="stop" operation_key="ip_voip_route_test1_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="50" operation="stop" operation_key="ip_voip_route_test2_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <pseudo_event id="57" operation="stop" operation_key="ip_voip_routes_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="25" priority="9">
    <action_set>
      <pseudo_event id="57" operation="stop" operation_key="ip_voip_routes_stop_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="44" operation="stopped" operation_key="voip_stopped_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="26" priority="9">
    <action_set>
      <pseudo_event id="56" operation="running" operation_key="ip_voip_routes_running_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="46" operation="start" operation_key="ip_voip_route_test1_start_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="51" operation="start" operation_key="ip_voip_route_test2_start_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="55" operation="start" operation_key="ip_voip_routes_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="27" priority="9">
    <action_set>
      <pseudo_event id="55" operation="start" operation_key="ip_voip_routes_start_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="58" operation="stopped" operation_key="ip_voip_routes_stopped_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="100" operation="running" operation_key="ip_voip_addresses_p_running_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="28" priority="9">
    <action_set>
      <rsc_op id="49" operation="migrate_from" operation_key="ip_voip_route_test1_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_route_test1" class="ocf" provider="heartbeat" type="Route"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_timeout="20000"  destination="161.53.3.69/32" gateway="10.2.4.1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="48" operation="migrate_to" operation_key="ip_voip_route_test1_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="29" priority="9">
    <action_set>
      <rsc_op id="48" operation="migrate_to" operation_key="ip_voip_route_test1_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_route_test1" class="ocf" provider="heartbeat" type="Route"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_record_pending="true" CRM_meta_timeout="20000"  destination="161.53.3.69/32" gateway="10.2.4.1"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="30" priority="9">
    <action_set>
      <rsc_op id="47" operation="monitor" operation_key="ip_voip_route_test1_monitor_1000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_route_test1" class="ocf" provider="heartbeat" type="Route"/>
        <attributes CRM_meta_interval="1000" CRM_meta_name="monitor" CRM_meta_timeout="20000"  destination="161.53.3.69/32" gateway="10.2.4.1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="46" operation="start" operation_key="ip_voip_route_test1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="31" priority="9">
    <action_set>
      <pseudo_event id="46" operation="start" operation_key="ip_voip_route_test1_start_0">
        <attributes CRM_meta_timeout="20000"  destination="161.53.3.69/32" gateway="10.2.4.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="45" operation="stop" operation_key="ip_voip_route_test1_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="49" operation="migrate_from" operation_key="ip_voip_route_test1_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="55" operation="start" operation_key="ip_voip_routes_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="32" priority="9">
    <action_set>
      <rsc_op id="45" operation="stop" operation_key="ip_voip_route_test1_stop_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_route_test1" class="ocf" provider="heartbeat" type="Route"/>
        <attributes CRM_meta_timeout="20000"  destination="161.53.3.69/32" gateway="10.2.4.1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="49" operation="migrate_from" operation_key="ip_voip_route_test1_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="57" operation="stop" operation_key="ip_voip_routes_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="33" priority="9">
    <action_set>
      <rsc_op id="54" operation="migrate_from" operation_key="ip_voip_route_test2_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_route_test2" class="ocf" provider="heartbeat" type="Route"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_timeout="20000"  destination="161.53.3.70/32" gateway="10.2.4.1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="53" operation="migrate_to" operation_key="ip_voip_route_test2_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="34" priority="9">
    <action_set>
      <rsc_op id="53" operation="migrate_to" operation_key="ip_voip_route_test2_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_route_test2" class="ocf" provider="heartbeat" type="Route"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_record_pending="true" CRM_meta_timeout="20000"  destination="161.53.3.70/32" gateway="10.2.4.1"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="35" priority="9">
    <action_set>
      <rsc_op id="52" operation="monitor" operation_key="ip_voip_route_test2_monitor_1000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_route_test2" class="ocf" provider="heartbeat" type="Route"/>
        <attributes CRM_meta_interval="1000" CRM_meta_name="monitor" CRM_meta_timeout="20000"  destination="161.53.3.70/32" gateway="10.2.4.1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="51" operation="start" operation_key="ip_voip_route_test2_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="36" priority="9">
    <action_set>
      <pseudo_event id="51" operation="start" operation_key="ip_voip_route_test2_start_0">
        <attributes CRM_meta_timeout="20000"  destination="161.53.3.70/32" gateway="10.2.4.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="50" operation="stop" operation_key="ip_voip_route_test2_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="54" operation="migrate_from" operation_key="ip_voip_route_test2_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="55" operation="start" operation_key="ip_voip_routes_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="37" priority="9">
    <action_set>
      <rsc_op id="50" operation="stop" operation_key="ip_voip_route_test2_stop_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_route_test2" class="ocf" provider="heartbeat" type="Route"/>
        <attributes CRM_meta_timeout="20000"  destination="161.53.3.70/32" gateway="10.2.4.1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="54" operation="migrate_from" operation_key="ip_voip_route_test2_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="57" operation="stop" operation_key="ip_voip_routes_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="38" priority="8">
    <action_set>
      <pseudo_event id="102" operation="stopped" operation_key="ip_voip_addresses_p_stopped_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="59" operation="stop" operation_key="ip_voip_vlan850_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="64" operation="stop" operation_key="ip_voip_vlan998_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="69" operation="stop" operation_key="ip_voip_vlan851_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="74" operation="stop" operation_key="ip_voip_vlan852_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="79" operation="stop" operation_key="ip_voip_vlan853_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="84" operation="stop" operation_key="ip_voip_vlan854_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="89" operation="stop" operation_key="ip_voip_vlan855_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="94" operation="stop" operation_key="ip_voip_vlan856_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <pseudo_event id="101" operation="stop" operation_key="ip_voip_addresses_p_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="39" priority="8">
    <action_set>
      <pseudo_event id="101" operation="stop" operation_key="ip_voip_addresses_p_stop_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="58" operation="stopped" operation_key="ip_voip_routes_stopped_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="40" priority="8">
    <action_set>
      <pseudo_event id="100" operation="running" operation_key="ip_voip_addresses_p_running_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="60" operation="start" operation_key="ip_voip_vlan850_start_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="65" operation="start" operation_key="ip_voip_vlan998_start_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="70" operation="start" operation_key="ip_voip_vlan851_start_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="75" operation="start" operation_key="ip_voip_vlan852_start_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="80" operation="start" operation_key="ip_voip_vlan853_start_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="85" operation="start" operation_key="ip_voip_vlan854_start_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="90" operation="start" operation_key="ip_voip_vlan855_start_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="95" operation="start" operation_key="ip_voip_vlan856_start_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="99" operation="start" operation_key="ip_voip_addresses_p_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="41" priority="8">
    <action_set>
      <pseudo_event id="99" operation="start" operation_key="ip_voip_addresses_p_start_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="102" operation="stopped" operation_key="ip_voip_addresses_p_stopped_0"/>
      </trigger>
      <trigger>
        <rsc_op id="112" operation="start" operation_key="fs_drbd_start_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="42" priority="8">
    <action_set>
      <rsc_op id="63" operation="migrate_from" operation_key="ip_voip_vlan850_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_vlan850" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="1" ip="10.2.4.13" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="62" operation="migrate_to" operation_key="ip_voip_vlan850_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="43" priority="8">
    <action_set>
      <rsc_op id="62" operation="migrate_to" operation_key="ip_voip_vlan850_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_vlan850" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_record_pending="true" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="1" ip="10.2.4.13" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="44" priority="8">
    <action_set>
      <rsc_op id="61" operation="monitor" operation_key="ip_voip_vlan850_monitor_1000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_vlan850" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_interval="1000" CRM_meta_name="monitor" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="1" ip="10.2.4.13" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="60" operation="start" operation_key="ip_voip_vlan850_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="45" priority="8">
    <action_set>
      <pseudo_event id="60" operation="start" operation_key="ip_voip_vlan850_start_0">
        <attributes CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="1" ip="10.2.4.13" nic="vlan850"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="59" operation="stop" operation_key="ip_voip_vlan850_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="63" operation="migrate_from" operation_key="ip_voip_vlan850_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="99" operation="start" operation_key="ip_voip_addresses_p_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="46" priority="8">
    <action_set>
      <rsc_op id="59" operation="stop" operation_key="ip_voip_vlan850_stop_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_vlan850" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="1" ip="10.2.4.13" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="63" operation="migrate_from" operation_key="ip_voip_vlan850_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="101" operation="stop" operation_key="ip_voip_addresses_p_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="47" priority="8">
    <action_set>
      <rsc_op id="68" operation="migrate_from" operation_key="ip_voip_vlan998_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_vlan998" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="1" ip="10.224.4.13" nic="vlan998"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="67" operation="migrate_to" operation_key="ip_voip_vlan998_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="48" priority="8">
    <action_set>
      <rsc_op id="67" operation="migrate_to" operation_key="ip_voip_vlan998_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_vlan998" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_record_pending="true" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="1" ip="10.224.4.13" nic="vlan998"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="49" priority="8">
    <action_set>
      <rsc_op id="66" operation="monitor" operation_key="ip_voip_vlan998_monitor_1000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_vlan998" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_interval="1000" CRM_meta_name="monitor" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="1" ip="10.224.4.13" nic="vlan998"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="65" operation="start" operation_key="ip_voip_vlan998_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="50" priority="8">
    <action_set>
      <pseudo_event id="65" operation="start" operation_key="ip_voip_vlan998_start_0">
        <attributes CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="1" ip="10.224.4.13" nic="vlan998"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="64" operation="stop" operation_key="ip_voip_vlan998_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="68" operation="migrate_from" operation_key="ip_voip_vlan998_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="99" operation="start" operation_key="ip_voip_addresses_p_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="51" priority="8">
    <action_set>
      <rsc_op id="64" operation="stop" operation_key="ip_voip_vlan998_stop_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_vlan998" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="1" ip="10.224.4.13" nic="vlan998"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="68" operation="migrate_from" operation_key="ip_voip_vlan998_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="101" operation="stop" operation_key="ip_voip_addresses_p_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="52" priority="8">
    <action_set>
      <rsc_op id="73" operation="migrate_from" operation_key="ip_voip_vlan851_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_vlan851" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="2" ip="10.2.4.44" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="72" operation="migrate_to" operation_key="ip_voip_vlan851_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="53" priority="8">
    <action_set>
      <rsc_op id="72" operation="migrate_to" operation_key="ip_voip_vlan851_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_vlan851" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_record_pending="true" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="2" ip="10.2.4.44" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="54" priority="8">
    <action_set>
      <rsc_op id="71" operation="monitor" operation_key="ip_voip_vlan851_monitor_1000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_vlan851" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_interval="1000" CRM_meta_name="monitor" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="2" ip="10.2.4.44" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="70" operation="start" operation_key="ip_voip_vlan851_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="55" priority="8">
    <action_set>
      <pseudo_event id="70" operation="start" operation_key="ip_voip_vlan851_start_0">
        <attributes CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="2" ip="10.2.4.44" nic="vlan850"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="69" operation="stop" operation_key="ip_voip_vlan851_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="73" operation="migrate_from" operation_key="ip_voip_vlan851_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="99" operation="start" operation_key="ip_voip_addresses_p_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="56" priority="8">
    <action_set>
      <rsc_op id="69" operation="stop" operation_key="ip_voip_vlan851_stop_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_vlan851" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="2" ip="10.2.4.44" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="73" operation="migrate_from" operation_key="ip_voip_vlan851_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="101" operation="stop" operation_key="ip_voip_addresses_p_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="57" priority="8">
    <action_set>
      <rsc_op id="78" operation="migrate_from" operation_key="ip_voip_vlan852_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_vlan852" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="3" ip="10.2.4.45" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="77" operation="migrate_to" operation_key="ip_voip_vlan852_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="58" priority="8">
    <action_set>
      <rsc_op id="77" operation="migrate_to" operation_key="ip_voip_vlan852_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_vlan852" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_record_pending="true" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="3" ip="10.2.4.45" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="59" priority="8">
    <action_set>
      <rsc_op id="76" operation="monitor" operation_key="ip_voip_vlan852_monitor_1000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_vlan852" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_interval="1000" CRM_meta_name="monitor" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="3" ip="10.2.4.45" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="75" operation="start" operation_key="ip_voip_vlan852_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="60" priority="8">
    <action_set>
      <pseudo_event id="75" operation="start" operation_key="ip_voip_vlan852_start_0">
        <attributes CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="3" ip="10.2.4.45" nic="vlan850"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="74" operation="stop" operation_key="ip_voip_vlan852_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="78" operation="migrate_from" operation_key="ip_voip_vlan852_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="99" operation="start" operation_key="ip_voip_addresses_p_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="61" priority="8">
    <action_set>
      <rsc_op id="74" operation="stop" operation_key="ip_voip_vlan852_stop_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_vlan852" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="3" ip="10.2.4.45" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="78" operation="migrate_from" operation_key="ip_voip_vlan852_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="101" operation="stop" operation_key="ip_voip_addresses_p_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="62" priority="8">
    <action_set>
      <rsc_op id="83" operation="migrate_from" operation_key="ip_voip_vlan853_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_vlan853" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="4" ip="10.2.4.46" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="82" operation="migrate_to" operation_key="ip_voip_vlan853_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="63" priority="8">
    <action_set>
      <rsc_op id="82" operation="migrate_to" operation_key="ip_voip_vlan853_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_vlan853" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_record_pending="true" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="4" ip="10.2.4.46" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="64" priority="8">
    <action_set>
      <rsc_op id="81" operation="monitor" operation_key="ip_voip_vlan853_monitor_1000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_vlan853" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_interval="1000" CRM_meta_name="monitor" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="4" ip="10.2.4.46" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="80" operation="start" operation_key="ip_voip_vlan853_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="65" priority="8">
    <action_set>
      <pseudo_event id="80" operation="start" operation_key="ip_voip_vlan853_start_0">
        <attributes CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="4" ip="10.2.4.46" nic="vlan850"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="79" operation="stop" operation_key="ip_voip_vlan853_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="83" operation="migrate_from" operation_key="ip_voip_vlan853_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="99" operation="start" operation_key="ip_voip_addresses_p_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="66" priority="8">
    <action_set>
      <rsc_op id="79" operation="stop" operation_key="ip_voip_vlan853_stop_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_vlan853" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="4" ip="10.2.4.46" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="83" operation="migrate_from" operation_key="ip_voip_vlan853_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="101" operation="stop" operation_key="ip_voip_addresses_p_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="67" priority="8">
    <action_set>
      <rsc_op id="88" operation="migrate_from" operation_key="ip_voip_vlan854_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_vlan854" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="5" ip="10.2.4.47" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="87" operation="migrate_to" operation_key="ip_voip_vlan854_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="68" priority="8">
    <action_set>
      <rsc_op id="87" operation="migrate_to" operation_key="ip_voip_vlan854_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_vlan854" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_record_pending="true" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="5" ip="10.2.4.47" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="69" priority="8">
    <action_set>
      <rsc_op id="86" operation="monitor" operation_key="ip_voip_vlan854_monitor_1000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_vlan854" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_interval="1000" CRM_meta_name="monitor" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="5" ip="10.2.4.47" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="85" operation="start" operation_key="ip_voip_vlan854_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="70" priority="8">
    <action_set>
      <pseudo_event id="85" operation="start" operation_key="ip_voip_vlan854_start_0">
        <attributes CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="5" ip="10.2.4.47" nic="vlan850"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="84" operation="stop" operation_key="ip_voip_vlan854_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="88" operation="migrate_from" operation_key="ip_voip_vlan854_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="99" operation="start" operation_key="ip_voip_addresses_p_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="71" priority="8">
    <action_set>
      <rsc_op id="84" operation="stop" operation_key="ip_voip_vlan854_stop_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_vlan854" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="5" ip="10.2.4.47" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="88" operation="migrate_from" operation_key="ip_voip_vlan854_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="101" operation="stop" operation_key="ip_voip_addresses_p_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="72" priority="8">
    <action_set>
      <rsc_op id="93" operation="migrate_from" operation_key="ip_voip_vlan855_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_vlan855" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="6" ip="10.2.4.54" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="92" operation="migrate_to" operation_key="ip_voip_vlan855_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="73" priority="8">
    <action_set>
      <rsc_op id="92" operation="migrate_to" operation_key="ip_voip_vlan855_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_vlan855" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_record_pending="true" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="6" ip="10.2.4.54" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="74" priority="8">
    <action_set>
      <rsc_op id="91" operation="monitor" operation_key="ip_voip_vlan855_monitor_1000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_vlan855" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_interval="1000" CRM_meta_name="monitor" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="6" ip="10.2.4.54" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="90" operation="start" operation_key="ip_voip_vlan855_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="75" priority="8">
    <action_set>
      <pseudo_event id="90" operation="start" operation_key="ip_voip_vlan855_start_0">
        <attributes CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="6" ip="10.2.4.54" nic="vlan850"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="89" operation="stop" operation_key="ip_voip_vlan855_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="93" operation="migrate_from" operation_key="ip_voip_vlan855_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="99" operation="start" operation_key="ip_voip_addresses_p_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="76" priority="8">
    <action_set>
      <rsc_op id="89" operation="stop" operation_key="ip_voip_vlan855_stop_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_vlan855" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="6" ip="10.2.4.54" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="93" operation="migrate_from" operation_key="ip_voip_vlan855_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="101" operation="stop" operation_key="ip_voip_addresses_p_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="77" priority="8">
    <action_set>
      <rsc_op id="98" operation="migrate_from" operation_key="ip_voip_vlan856_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_vlan856" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="7" ip="10.2.4.55" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="97" operation="migrate_to" operation_key="ip_voip_vlan856_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="78" priority="8">
    <action_set>
      <rsc_op id="97" operation="migrate_to" operation_key="ip_voip_vlan856_migrate_to_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_vlan856" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_migrate_source="asttest1" CRM_meta_migrate_target="asttest2" CRM_meta_record_pending="true" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="7" ip="10.2.4.55" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="79" priority="8">
    <action_set>
      <rsc_op id="96" operation="monitor" operation_key="ip_voip_vlan856_monitor_1000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="ip_voip_vlan856" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_interval="1000" CRM_meta_name="monitor" CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="7" ip="10.2.4.55" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="95" operation="start" operation_key="ip_voip_vlan856_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="80" priority="8">
    <action_set>
      <pseudo_event id="95" operation="start" operation_key="ip_voip_vlan856_start_0">
        <attributes CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="7" ip="10.2.4.55" nic="vlan850"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="94" operation="stop" operation_key="ip_voip_vlan856_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="98" operation="migrate_from" operation_key="ip_voip_vlan856_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="99" operation="start" operation_key="ip_voip_addresses_p_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="81" priority="8">
    <action_set>
      <rsc_op id="94" operation="stop" operation_key="ip_voip_vlan856_stop_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="ip_voip_vlan856" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_timeout="20000" cidr_netmask="24"  iflabel="7" ip="10.2.4.55" nic="vlan850"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="98" operation="migrate_from" operation_key="ip_voip_vlan856_migrate_from_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="101" operation="stop" operation_key="ip_voip_addresses_p_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="82">
    <action_set>
      <rsc_op id="113" operation="monitor" operation_key="fs_drbd_monitor_1000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="fs_drbd" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_interval="1000" CRM_meta_name="monitor" CRM_meta_start_delay="30000" CRM_meta_timeout="70000"  device="/dev/drbd/by-res/r0" directory="/mnt/drbd" fstype="ext3"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="112" operation="start" operation_key="fs_drbd_start_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="83">
    <action_set>
      <rsc_op id="112" operation="start" operation_key="fs_drbd_start_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="fs_drbd" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_name="start" CRM_meta_start_delay="1000" CRM_meta_timeout="61000"  device="/dev/drbd/by-res/r0" directory="/mnt/drbd" fstype="ext3"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="111" operation="stop" operation_key="fs_drbd_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <pseudo_event id="138" operation="notified" operation_key="ms_drbd_confirmed-post_notify_promoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="84">
    <action_set>
      <rsc_op id="111" operation="stop" operation_key="fs_drbd_stop_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="fs_drbd" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_name="stop" CRM_meta_start_delay="1000" CRM_meta_timeout="61000"  device="/dev/drbd/by-res/r0" directory="/mnt/drbd" fstype="ext3"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="102" operation="stopped" operation_key="ip_voip_addresses_p_stopped_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="85" priority="1000000">
    <action_set>
      <rsc_op id="166" operation="notify" operation_key="drbd:0_post_notify_demote_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="drbd" long-id="drbd:0" class="ocf" provider="linbit" type="drbd"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="drbd:0 " CRM_meta_notify_demote_uname="asttest1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="demoted" CRM_meta_notify_key_type="post" CRM_meta_notify_master_resource="drbd:0 " CRM_meta_notify_master_uname="asttest1 " CRM_meta_notify_operation="demote" CRM_meta_notify_promote_resource="drbd:1 " CRM_meta_notify_promote_uname="asttest2 " CRM_meta_notify_slave_resource="drbd:1 " CRM_meta_notify_slave_uname="asttest2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="post" CRM_meta_timeout="20000"  drbd_resource="r0"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="143" operation="notify" operation_key="ms_drbd_post_notify_demoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="86">
    <action_set>
      <rsc_op id="165" operation="notify" operation_key="drbd:0_pre_notify_demote_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="drbd" long-id="drbd:0" class="ocf" provider="linbit" type="drbd"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="drbd:0 " CRM_meta_notify_demote_uname="asttest1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="demote" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource="drbd:0 " CRM_meta_notify_master_uname="asttest1 " CRM_meta_notify_operation="demote" CRM_meta_notify_promote_resource="drbd:1 " CRM_meta_notify_promote_uname="asttest2 " CRM_meta_notify_slave_resource="drbd:1 " CRM_meta_notify_slave_uname="asttest2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="pre" CRM_meta_timeout="20000"  drbd_resource="r0"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="141" operation="notify" operation_key="ms_drbd_pre_notify_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="87" priority="1000000">
    <action_set>
      <rsc_op id="162" operation="notify" operation_key="drbd:0_post_notify_promote_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="drbd" long-id="drbd:0" class="ocf" provider="linbit" type="drbd"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="drbd:0 " CRM_meta_notify_demote_uname="asttest1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="promoted" CRM_meta_notify_key_type="post" CRM_meta_notify_master_resource="drbd:0 " CRM_meta_notify_master_uname="asttest1 " CRM_meta_notify_operation="promote" CRM_meta_notify_promote_resource="drbd:1 " CRM_meta_notify_promote_uname="asttest2 " CRM_meta_notify_slave_resource="drbd:1 " CRM_meta_notify_slave_uname="asttest2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="post" CRM_meta_timeout="20000"  drbd_resource="r0"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="137" operation="notify" operation_key="ms_drbd_post_notify_promoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="88">
    <action_set>
      <rsc_op id="161" operation="notify" operation_key="drbd:0_pre_notify_promote_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="drbd" long-id="drbd:0" class="ocf" provider="linbit" type="drbd"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="drbd:0 " CRM_meta_notify_demote_uname="asttest1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="promote" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource="drbd:0 " CRM_meta_notify_master_uname="asttest1 " CRM_meta_notify_operation="promote" CRM_meta_notify_promote_resource="drbd:1 " CRM_meta_notify_promote_uname="asttest2 " CRM_meta_notify_slave_resource="drbd:1 " CRM_meta_notify_slave_uname="asttest2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="pre" CRM_meta_timeout="20000"  drbd_resource="r0"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="135" operation="notify" operation_key="ms_drbd_pre_notify_promote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="89">
    <action_set>
      <rsc_op id="117" operation="monitor" operation_key="drbd:0_monitor_31000" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="drbd" long-id="drbd:0" class="ocf" provider="linbit" type="drbd"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="31000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="true" CRM_meta_start_delay="0" CRM_meta_timeout="20000"  drbd_resource="r0"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="115" operation="demote" operation_key="drbd:0_demote_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <pseudo_event id="138" operation="notified" operation_key="ms_drbd_confirmed-post_notify_promoted_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="144" operation="notified" operation_key="ms_drbd_confirmed-post_notify_demoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="90">
    <action_set>
      <rsc_op id="115" operation="demote" operation_key="drbd:0_demote_0" on_node="asttest1" on_node_uuid="asttest1">
        <primitive id="drbd" long-id="drbd:0" class="ocf" provider="linbit" type="drbd"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="drbd:0 " CRM_meta_notify_demote_uname="asttest1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_master_resource="drbd:0 " CRM_meta_notify_master_uname="asttest1 " CRM_meta_notify_promote_resource="drbd:1 " CRM_meta_notify_promote_uname="asttest2 " CRM_meta_notify_slave_resource="drbd:1 " CRM_meta_notify_slave_uname="asttest2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_timeout="20000"  drbd_resource="r0"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="139" operation="demote" operation_key="ms_drbd_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="91" priority="1000000">
    <action_set>
      <rsc_op id="168" operation="notify" operation_key="drbd:1_post_notify_demote_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="drbd" long-id="drbd:1" class="ocf" provider="linbit" type="drbd"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="drbd:0 " CRM_meta_notify_demote_uname="asttest1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="demoted" CRM_meta_notify_key_type="post" CRM_meta_notify_master_resource="drbd:0 " CRM_meta_notify_master_uname="asttest1 " CRM_meta_notify_operation="demote" CRM_meta_notify_promote_resource="drbd:1 " CRM_meta_notify_promote_uname="asttest2 " CRM_meta_notify_slave_resource="drbd:1 " CRM_meta_notify_slave_uname="asttest2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="post" CRM_meta_timeout="20000"  drbd_resource="r0"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="143" operation="notify" operation_key="ms_drbd_post_notify_demoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="92">
    <action_set>
      <rsc_op id="167" operation="notify" operation_key="drbd:1_pre_notify_demote_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="drbd" long-id="drbd:1" class="ocf" provider="linbit" type="drbd"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="drbd:0 " CRM_meta_notify_demote_uname="asttest1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="demote" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource="drbd:0 " CRM_meta_notify_master_uname="asttest1 " CRM_meta_notify_operation="demote" CRM_meta_notify_promote_resource="drbd:1 " CRM_meta_notify_promote_uname="asttest2 " CRM_meta_notify_slave_resource="drbd:1 " CRM_meta_notify_slave_uname="asttest2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="pre" CRM_meta_timeout="20000"  drbd_resource="r0"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="141" operation="notify" operation_key="ms_drbd_pre_notify_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="93" priority="1000000">
    <action_set>
      <rsc_op id="164" operation="notify" operation_key="drbd:1_post_notify_promote_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="drbd" long-id="drbd:1" class="ocf" provider="linbit" type="drbd"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="drbd:0 " CRM_meta_notify_demote_uname="asttest1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="promoted" CRM_meta_notify_key_type="post" CRM_meta_notify_master_resource="drbd:0 " CRM_meta_notify_master_uname="asttest1 " CRM_meta_notify_operation="promote" CRM_meta_notify_promote_resource="drbd:1 " CRM_meta_notify_promote_uname="asttest2 " CRM_meta_notify_slave_resource="drbd:1 " CRM_meta_notify_slave_uname="asttest2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="post" CRM_meta_timeout="20000"  drbd_resource="r0"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="137" operation="notify" operation_key="ms_drbd_post_notify_promoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="94">
    <action_set>
      <rsc_op id="163" operation="notify" operation_key="drbd:1_pre_notify_promote_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="drbd" long-id="drbd:1" class="ocf" provider="linbit" type="drbd"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="drbd:0 " CRM_meta_notify_demote_uname="asttest1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="promote" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource="drbd:0 " CRM_meta_notify_master_uname="asttest1 " CRM_meta_notify_operation="promote" CRM_meta_notify_promote_resource="drbd:1 " CRM_meta_notify_promote_uname="asttest2 " CRM_meta_notify_slave_resource="drbd:1 " CRM_meta_notify_slave_uname="asttest2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="pre" CRM_meta_timeout="20000"  drbd_resource="r0"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="135" operation="notify" operation_key="ms_drbd_pre_notify_promote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="95">
    <action_set>
      <rsc_op id="120" operation="promote" operation_key="drbd:1_promote_0" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="drbd" long-id="drbd:1" class="ocf" provider="linbit" type="drbd"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource="drbd:0 " CRM_meta_notify_demote_uname="asttest1 " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_master_resource="drbd:0 " CRM_meta_notify_master_uname="asttest1 " CRM_meta_notify_promote_resource="drbd:1 " CRM_meta_notify_promote_uname="asttest2 " CRM_meta_notify_slave_resource="drbd:1 " CRM_meta_notify_slave_uname="asttest2 " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_timeout="20000"  drbd_resource="r0"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="16" operation="cancel" operation_key="drbd:1_monitor_31000" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
      <trigger>
        <pseudo_event id="133" operation="promote" operation_key="ms_drbd_promote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="96">
    <action_set>
      <rsc_op id="16" operation="cancel" operation_key="drbd:1_monitor_31000" on_node="asttest2" on_node_uuid="asttest2">
        <primitive id="drbd" long-id="drbd:1" class="ocf" provider="linbit" type="drbd"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="31000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="true" CRM_meta_operation="monitor" CRM_meta_start_delay="0" CRM_meta_timeout="20000"  drbd_resource="r0"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="97" priority="1000000">
    <action_set>
      <pseudo_event id="144" operation="notified" operation_key="ms_drbd_confirmed-post_notify_demoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="demoted" CRM_meta_notify_key_type="confirmed-post" CRM_meta_notify_operation="demote" CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="143" operation="notify" operation_key="ms_drbd_post_notify_demoted_0"/>
      </trigger>
      <trigger>
        <rsc_op id="166" operation="notify" operation_key="drbd:0_post_notify_demote_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="168" operation="notify" operation_key="drbd:1_post_notify_demote_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="98" priority="1000000">
    <action_set>
      <pseudo_event id="143" operation="notify" operation_key="ms_drbd_post_notify_demoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="demoted" CRM_meta_notify_key_type="post" CRM_meta_notify_operation="demote" CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="140" operation="demoted" operation_key="ms_drbd_demoted_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="142" operation="notified" operation_key="ms_drbd_confirmed-pre_notify_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="99">
    <action_set>
      <pseudo_event id="142" operation="notified" operation_key="ms_drbd_confirmed-pre_notify_demote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="demote" CRM_meta_notify_key_type="confirmed-pre" CRM_meta_notify_operation="demote" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="141" operation="notify" operation_key="ms_drbd_pre_notify_demote_0"/>
      </trigger>
      <trigger>
        <rsc_op id="165" operation="notify" operation_key="drbd:0_pre_notify_demote_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="167" operation="notify" operation_key="drbd:1_pre_notify_demote_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="100">
    <action_set>
      <pseudo_event id="141" operation="notify" operation_key="ms_drbd_pre_notify_demote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="demote" CRM_meta_notify_key_type="pre" CRM_meta_notify_operation="demote" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="101" priority="1000000">
    <action_set>
      <pseudo_event id="140" operation="demoted" operation_key="ms_drbd_demoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="115" operation="demote" operation_key="drbd:0_demote_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <pseudo_event id="139" operation="demote" operation_key="ms_drbd_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="102">
    <action_set>
      <pseudo_event id="139" operation="demote" operation_key="ms_drbd_demote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="111" operation="stop" operation_key="fs_drbd_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <pseudo_event id="142" operation="notified" operation_key="ms_drbd_confirmed-pre_notify_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="103" priority="1000000">
    <action_set>
      <pseudo_event id="138" operation="notified" operation_key="ms_drbd_confirmed-post_notify_promoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="promoted" CRM_meta_notify_key_type="confirmed-post" CRM_meta_notify_operation="promote" CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="137" operation="notify" operation_key="ms_drbd_post_notify_promoted_0"/>
      </trigger>
      <trigger>
        <rsc_op id="162" operation="notify" operation_key="drbd:0_post_notify_promote_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="164" operation="notify" operation_key="drbd:1_post_notify_promote_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="104" priority="1000000">
    <action_set>
      <pseudo_event id="137" operation="notify" operation_key="ms_drbd_post_notify_promoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="promoted" CRM_meta_notify_key_type="post" CRM_meta_notify_operation="promote" CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="134" operation="promoted" operation_key="ms_drbd_promoted_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="136" operation="notified" operation_key="ms_drbd_confirmed-pre_notify_promote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="105">
    <action_set>
      <pseudo_event id="136" operation="notified" operation_key="ms_drbd_confirmed-pre_notify_promote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="promote" CRM_meta_notify_key_type="confirmed-pre" CRM_meta_notify_operation="promote" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="135" operation="notify" operation_key="ms_drbd_pre_notify_promote_0"/>
      </trigger>
      <trigger>
        <rsc_op id="161" operation="notify" operation_key="drbd:0_pre_notify_promote_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="163" operation="notify" operation_key="drbd:1_pre_notify_promote_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="106">
    <action_set>
      <pseudo_event id="135" operation="notify" operation_key="ms_drbd_pre_notify_promote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="promote" CRM_meta_notify_key_type="pre" CRM_meta_notify_operation="promote" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="144" operation="notified" operation_key="ms_drbd_confirmed-post_notify_demoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="107" priority="1000000">
    <action_set>
      <pseudo_event id="134" operation="promoted" operation_key="ms_drbd_promoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="120" operation="promote" operation_key="drbd:1_promote_0" on_node="asttest2" on_node_uuid="asttest2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="108">
    <action_set>
      <pseudo_event id="133" operation="promote" operation_key="ms_drbd_promote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="136" operation="notified" operation_key="ms_drbd_confirmed-pre_notify_promote_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="140" operation="demoted" operation_key="ms_drbd_demoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="109">
    <action_set>
      <pseudo_event id="17" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="21" operation="stop" operation_key="mysqld_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="26" operation="stop" operation_key="dahdi_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="45" operation="stop" operation_key="ip_voip_route_test1_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="50" operation="stop" operation_key="ip_voip_route_test2_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="59" operation="stop" operation_key="ip_voip_vlan850_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="64" operation="stop" operation_key="ip_voip_vlan998_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="69" operation="stop" operation_key="ip_voip_vlan851_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="74" operation="stop" operation_key="ip_voip_vlan852_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="79" operation="stop" operation_key="ip_voip_vlan853_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="84" operation="stop" operation_key="ip_voip_vlan854_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="89" operation="stop" operation_key="ip_voip_vlan855_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="94" operation="stop" operation_key="ip_voip_vlan856_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
      <trigger>
        <rsc_op id="111" operation="stop" operation_key="fs_drbd_stop_0" on_node="asttest1" on_node_uuid="asttest1"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>
