<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="1"  transition_id="0">
  <synapse id="0">
    <action_set>
      <pseudo_event id="15" operation="stopped" operation_key="group-1_stopped_0">
        <attributes CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="11" operation="stop" operation_key="r192.168.122.115_stop_0" on_node="pcmk-1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <pseudo_event id="14" operation="stop" operation_key="group-1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <pseudo_event id="14" operation="stop" operation_key="group-1_stop_0">
        <attributes CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="11" operation="stop" operation_key="r192.168.122.115_stop_0" on_node="pcmk-1" on_node_uuid="1">
        <primitive id="r192.168.122.115" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_timeout="90000" cidr_netmask="32"  ip="192.168.122.115"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="14" operation="stop" operation_key="group-1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3" priority="1000000">
    <action_set>
      <rsc_op id="7" operation="probe_complete" operation_key="probe_complete-pcmk-2" on_node="pcmk-2" on_node_uuid="2">
        <attributes CRM_meta_op_no_wait="true" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="4" priority="1000000">
    <action_set>
      <rsc_op id="6" operation="probe_complete" operation_key="probe_complete-pcmk-1" on_node="pcmk-1" on_node_uuid="1">
        <attributes CRM_meta_op_no_wait="true" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="5">
    <action_set>
      <pseudo_event id="4" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="11" operation="stop" operation_key="r192.168.122.115_stop_0" on_node="pcmk-1" on_node_uuid="1"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>
