 <transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
   <synapse id="0">
     <action_set>
      <rsc_op id="27" operation="start" operation_key="rsc1_start_0" on_node="node1" on_node_uuid="uuid1">
        <primitive id="rsc1" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="1">
     <action_set>
      <rsc_op id="20" operation="monitor" operation_key="rsc1_monitor_0" on_node="node3" on_node_uuid="uuid3">
        <primitive id="rsc1" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="2">
     <action_set>
      <rsc_op id="12" operation="monitor" operation_key="rsc1_monitor_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="rsc1" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="3">
     <action_set>
      <rsc_op id="4" operation="monitor" operation_key="rsc1_monitor_0" on_node="node1" on_node_uuid="uuid1">
        <primitive id="rsc1" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
  <synapse id="4">
     <action_set>
       <pseudo_event id="32" operation="running" operation_key="rsc2_running_0">
        <attributes CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <rsc_op id="28" operation="start" operation_key="child_rsc1_start_0" on_node="node2" on_node_uuid="uuid2"/>
       </trigger>
       <trigger>
         <rsc_op id="29" operation="start" operation_key="child_rsc2_start_0" on_node="node2" on_node_uuid="uuid2"/>
       </trigger>
       <trigger>
         <rsc_op id="30" operation="start" operation_key="child_rsc3_start_0" on_node="node2" on_node_uuid="uuid2"/>
       </trigger>
       <trigger>
         <pseudo_event id="31" operation="start" operation_key="rsc2_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="5">
    <action_set>
      <pseudo_event id="31" operation="start" operation_key="rsc2_start_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
   <synapse id="6">
     <action_set>
      <rsc_op id="28" operation="start" operation_key="child_rsc1_start_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="child_rsc1" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="31" operation="start" operation_key="rsc2_start_0"/>
      </trigger>
    </inputs>
   </synapse>
  <synapse id="7">
     <action_set>
      <rsc_op id="21" operation="monitor" operation_key="child_rsc1_monitor_0" on_node="node3" on_node_uuid="uuid3">
        <primitive id="child_rsc1" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="8">
     <action_set>
      <rsc_op id="13" operation="monitor" operation_key="child_rsc1_monitor_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="child_rsc1" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="9">
     <action_set>
      <rsc_op id="5" operation="monitor" operation_key="child_rsc1_monitor_0" on_node="node1" on_node_uuid="uuid1">
        <primitive id="child_rsc1" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="10">
    <action_set>
      <rsc_op id="29" operation="start" operation_key="child_rsc2_start_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="child_rsc2" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
       </trigger>
       <trigger>
        <rsc_op id="28" operation="start" operation_key="child_rsc1_start_0" on_node="node2" on_node_uuid="uuid2"/>
      </trigger>
      <trigger>
         <pseudo_event id="31" operation="start" operation_key="rsc2_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="11">
     <action_set>
      <rsc_op id="22" operation="monitor" operation_key="child_rsc2_monitor_0" on_node="node3" on_node_uuid="uuid3">
        <primitive id="child_rsc2" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="12">
     <action_set>
       <rsc_op id="14" operation="monitor" operation_key="child_rsc2_monitor_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="child_rsc2" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="13">
     <action_set>
      <rsc_op id="6" operation="monitor" operation_key="child_rsc2_monitor_0" on_node="node1" on_node_uuid="uuid1">
        <primitive id="child_rsc2" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="14">
     <action_set>
      <rsc_op id="30" operation="start" operation_key="child_rsc3_start_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="child_rsc3" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
       </trigger>
       <trigger>
        <rsc_op id="29" operation="start" operation_key="child_rsc2_start_0" on_node="node2" on_node_uuid="uuid2"/>
       </trigger>
       <trigger>
         <pseudo_event id="31" operation="start" operation_key="rsc2_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="15">
     <action_set>
      <rsc_op id="23" operation="monitor" operation_key="child_rsc3_monitor_0" on_node="node3" on_node_uuid="uuid3">
        <primitive id="child_rsc3" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="16">
     <action_set>
       <rsc_op id="15" operation="monitor" operation_key="child_rsc3_monitor_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="child_rsc3" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="17">
     <action_set>
      <rsc_op id="7" operation="monitor" operation_key="child_rsc3_monitor_0" on_node="node1" on_node_uuid="uuid1">
        <primitive id="child_rsc3" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="18">
     <action_set>
      <pseudo_event id="39" operation="running" operation_key="rsc3_running_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="35" operation="start" operation_key="child_rsc4_start_0" on_node="node2" on_node_uuid="uuid2"/>
       </trigger>
       <trigger>
        <rsc_op id="36" operation="start" operation_key="child_rsc5_start_0" on_node="node2" on_node_uuid="uuid2"/>
       </trigger>
       <trigger>
        <rsc_op id="37" operation="start" operation_key="child_rsc6_start_0" on_node="node2" on_node_uuid="uuid2"/>
      </trigger>
      <trigger>
        <pseudo_event id="38" operation="start" operation_key="rsc3_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="19">
     <action_set>
       <pseudo_event id="38" operation="start" operation_key="rsc3_start_0">
        <attributes CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="32" operation="running" operation_key="rsc2_running_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="20">
     <action_set>
      <rsc_op id="35" operation="start" operation_key="child_rsc4_start_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="child_rsc4" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
       </trigger>
       <trigger>
         <pseudo_event id="38" operation="start" operation_key="rsc3_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="21">
     <action_set>
      <rsc_op id="24" operation="monitor" operation_key="child_rsc4_monitor_0" on_node="node3" on_node_uuid="uuid3">
        <primitive id="child_rsc4" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="22">
     <action_set>
       <rsc_op id="16" operation="monitor" operation_key="child_rsc4_monitor_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="child_rsc4" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="23">
     <action_set>
      <rsc_op id="8" operation="monitor" operation_key="child_rsc4_monitor_0" on_node="node1" on_node_uuid="uuid1">
        <primitive id="child_rsc4" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="24">
     <action_set>
      <rsc_op id="36" operation="start" operation_key="child_rsc5_start_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="child_rsc5" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
       </trigger>
       <trigger>
        <rsc_op id="35" operation="start" operation_key="child_rsc4_start_0" on_node="node2" on_node_uuid="uuid2"/>
      </trigger>
      <trigger>
         <pseudo_event id="38" operation="start" operation_key="rsc3_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="25">
     <action_set>
      <rsc_op id="25" operation="monitor" operation_key="child_rsc5_monitor_0" on_node="node3" on_node_uuid="uuid3">
        <primitive id="child_rsc5" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="26">
     <action_set>
       <rsc_op id="17" operation="monitor" operation_key="child_rsc5_monitor_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="child_rsc5" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="27">
     <action_set>
      <rsc_op id="9" operation="monitor" operation_key="child_rsc5_monitor_0" on_node="node1" on_node_uuid="uuid1">
        <primitive id="child_rsc5" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="28">
     <action_set>
      <rsc_op id="37" operation="start" operation_key="child_rsc6_start_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="child_rsc6" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
       </trigger>
       <trigger>
        <rsc_op id="36" operation="start" operation_key="child_rsc5_start_0" on_node="node2" on_node_uuid="uuid2"/>
       </trigger>
       <trigger>
         <pseudo_event id="38" operation="start" operation_key="rsc3_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="29">
     <action_set>
      <rsc_op id="26" operation="monitor" operation_key="child_rsc6_monitor_0" on_node="node3" on_node_uuid="uuid3">
        <primitive id="child_rsc6" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="30">
     <action_set>
       <rsc_op id="18" operation="monitor" operation_key="child_rsc6_monitor_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="child_rsc6" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="31">
     <action_set>
      <rsc_op id="10" operation="monitor" operation_key="child_rsc6_monitor_0" on_node="node1" on_node_uuid="uuid1">
        <primitive id="child_rsc6" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="32" priority="1000000">
     <action_set>
      <rsc_op id="19" operation="probe_complete" operation_key="probe_complete" on_node="node3" on_node_uuid="uuid3">
        <attributes CRM_meta_op_no_wait="true" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="20" operation="monitor" operation_key="rsc1_monitor_0" on_node="node3" on_node_uuid="uuid3"/>
       </trigger>
       <trigger>
        <rsc_op id="21" operation="monitor" operation_key="child_rsc1_monitor_0" on_node="node3" on_node_uuid="uuid3"/>
       </trigger>
       <trigger>
        <rsc_op id="22" operation="monitor" operation_key="child_rsc2_monitor_0" on_node="node3" on_node_uuid="uuid3"/>
       </trigger>
       <trigger>
        <rsc_op id="23" operation="monitor" operation_key="child_rsc3_monitor_0" on_node="node3" on_node_uuid="uuid3"/>
       </trigger>
       <trigger>
        <rsc_op id="24" operation="monitor" operation_key="child_rsc4_monitor_0" on_node="node3" on_node_uuid="uuid3"/>
       </trigger>
       <trigger>
        <rsc_op id="25" operation="monitor" operation_key="child_rsc5_monitor_0" on_node="node3" on_node_uuid="uuid3"/>
      </trigger>
      <trigger>
        <rsc_op id="26" operation="monitor" operation_key="child_rsc6_monitor_0" on_node="node3" on_node_uuid="uuid3"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="33" priority="1000000">
     <action_set>
      <rsc_op id="11" operation="probe_complete" operation_key="probe_complete" on_node="node2" on_node_uuid="uuid2">
        <attributes CRM_meta_op_no_wait="true" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="12" operation="monitor" operation_key="rsc1_monitor_0" on_node="node2" on_node_uuid="uuid2"/>
       </trigger>
       <trigger>
        <rsc_op id="13" operation="monitor" operation_key="child_rsc1_monitor_0" on_node="node2" on_node_uuid="uuid2"/>
       </trigger>
       <trigger>
        <rsc_op id="14" operation="monitor" operation_key="child_rsc2_monitor_0" on_node="node2" on_node_uuid="uuid2"/>
       </trigger>
       <trigger>
        <rsc_op id="15" operation="monitor" operation_key="child_rsc3_monitor_0" on_node="node2" on_node_uuid="uuid2"/>
       </trigger>
       <trigger>
        <rsc_op id="16" operation="monitor" operation_key="child_rsc4_monitor_0" on_node="node2" on_node_uuid="uuid2"/>
       </trigger>
       <trigger>
        <rsc_op id="17" operation="monitor" operation_key="child_rsc5_monitor_0" on_node="node2" on_node_uuid="uuid2"/>
       </trigger>
       <trigger>
        <rsc_op id="18" operation="monitor" operation_key="child_rsc6_monitor_0" on_node="node2" on_node_uuid="uuid2"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="34" priority="1000000">
     <action_set>
      <rsc_op id="3" operation="probe_complete" operation_key="probe_complete" on_node="node1" on_node_uuid="uuid1">
        <attributes CRM_meta_op_no_wait="true" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="4" operation="monitor" operation_key="rsc1_monitor_0" on_node="node1" on_node_uuid="uuid1"/>
       </trigger>
       <trigger>
        <rsc_op id="5" operation="monitor" operation_key="child_rsc1_monitor_0" on_node="node1" on_node_uuid="uuid1"/>
       </trigger>
       <trigger>
        <rsc_op id="6" operation="monitor" operation_key="child_rsc2_monitor_0" on_node="node1" on_node_uuid="uuid1"/>
       </trigger>
       <trigger>
        <rsc_op id="7" operation="monitor" operation_key="child_rsc3_monitor_0" on_node="node1" on_node_uuid="uuid1"/>
       </trigger>
       <trigger>
        <rsc_op id="8" operation="monitor" operation_key="child_rsc4_monitor_0" on_node="node1" on_node_uuid="uuid1"/>
       </trigger>
       <trigger>
        <rsc_op id="9" operation="monitor" operation_key="child_rsc5_monitor_0" on_node="node1" on_node_uuid="uuid1"/>
       </trigger>
       <trigger>
        <rsc_op id="10" operation="monitor" operation_key="child_rsc6_monitor_0" on_node="node1" on_node_uuid="uuid1"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="35">
     <action_set>
      <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete">
        <attributes />
      </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="3" operation="probe_complete" operation_key="probe_complete" on_node="node1" on_node_uuid="uuid1"/>
       </trigger>
       <trigger>
        <rsc_op id="11" operation="probe_complete" operation_key="probe_complete" on_node="node2" on_node_uuid="uuid2"/>
       </trigger>
       <trigger>
        <rsc_op id="19" operation="probe_complete" operation_key="probe_complete" on_node="node3" on_node_uuid="uuid3"/>
       </trigger>
     </inputs>
   </synapse>
 </transition_graph>

