<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="7" operation="start" operation_key="S_A:0_start_0" on_node="fc16-builder" on_node_uuid="fc16-builder">
        <primitive id="S_A" long-id="S_A:0" class="stonith" type="fence_xvm"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="1" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="8" operation="start" operation_key="S_CLONE_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="4" operation="monitor" operation_key="S_A:0_monitor_0" on_node="fc16-builder" on_node_uuid="fc16-builder">
        <primitive id="S_A" long-id="S_A:0" class="stonith" type="fence_xvm"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="1" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="2" priority="1000000">
    <action_set>
      <pseudo_event id="9" operation="running" operation_key="S_CLONE_running_0">
        <attributes CRM_meta_clone_max="1" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="7" operation="start" operation_key="S_A:0_start_0" on_node="fc16-builder" on_node_uuid="fc16-builder"/>
      </trigger>
      <trigger>
        <pseudo_event id="8" operation="start" operation_key="S_CLONE_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <pseudo_event id="8" operation="start" operation_key="S_CLONE_start_0">
        <attributes CRM_meta_clone_max="1" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="14" operation="running" operation_key="S_GROUP_running_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <pseudo_event id="14" operation="running" operation_key="S_GROUP_running_0">
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="12" operation="start" operation_key="S_B_start_0" on_node="fc16-builder" on_node_uuid="fc16-builder"/>
      </trigger>
      <trigger>
        <pseudo_event id="13" operation="start" operation_key="S_GROUP_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <pseudo_event id="13" operation="start" operation_key="S_GROUP_start_0">
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="6">
    <action_set>
      <rsc_op id="12" operation="start" operation_key="S_B_start_0" on_node="fc16-builder" on_node_uuid="fc16-builder">
        <primitive id="S_B" class="stonith" type="fence_xvm"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="13" operation="start" operation_key="S_GROUP_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <rsc_op id="5" operation="monitor" operation_key="S_B_monitor_0" on_node="fc16-builder" on_node_uuid="fc16-builder">
        <primitive id="S_B" class="stonith" type="fence_xvm"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="8">
    <action_set>
      <rsc_op id="17" operation="start" operation_key="A_start_0" on_node="fc16-builder" on_node_uuid="fc16-builder">
        <primitive id="A" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9">
    <action_set>
      <rsc_op id="6" operation="monitor" operation_key="A_monitor_0" on_node="fc16-builder" on_node_uuid="fc16-builder">
        <primitive id="A" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="10" priority="1000000">
    <action_set>
      <rsc_op id="3" operation="probe_complete" operation_key="probe_complete" on_node="fc16-builder" on_node_uuid="fc16-builder">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="4" operation="monitor" operation_key="S_A:0_monitor_0" on_node="fc16-builder" on_node_uuid="fc16-builder"/>
      </trigger>
      <trigger>
        <rsc_op id="5" operation="monitor" operation_key="S_B_monitor_0" on_node="fc16-builder" on_node_uuid="fc16-builder"/>
      </trigger>
      <trigger>
        <rsc_op id="6" operation="monitor" operation_key="A_monitor_0" on_node="fc16-builder" on_node_uuid="fc16-builder"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="11">
    <action_set>
      <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete">
        <attributes crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="3" operation="probe_complete" operation_key="probe_complete" on_node="fc16-builder" on_node_uuid="fc16-builder"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

