<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="13" operation="monitor" operation_key="single:0_monitor_60000" on_node="rhel7-auto2" on_node_uuid="2">
        <primitive id="single" long-id="single:0" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_interval="60000" CRM_meta_isolation_host="rhel7-auto2" CRM_meta_isolation_instance="single-clone_0" CRM_meta_isolation_wrapper="docker-wrapper" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_timeout="20000"  pcmk_docker_image="centos:isolation"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="12" operation="start" operation_key="single:0_start_0" on_node="rhel7-auto2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="12" operation="start" operation_key="single:0_start_0" on_node="rhel7-auto2" on_node_uuid="2">
        <primitive id="single" long-id="single:0" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_isolation_host="rhel7-auto2" CRM_meta_isolation_instance="single-clone_0" CRM_meta_isolation_wrapper="docker-wrapper" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_timeout="120000"  pcmk_docker_image="centos:isolation"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="3" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="16" operation="start" operation_key="single-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="8" operation="monitor" operation_key="single:0_monitor_0" on_node="rhel7-auto2" on_node_uuid="2">
        <primitive id="single" long-id="single:0" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_isolation_host="rhel7-auto2" CRM_meta_isolation_instance="single-clone_0" CRM_meta_isolation_wrapper="docker-wrapper" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  pcmk_docker_image="centos:isolation"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="3">
    <action_set>
      <rsc_op id="5" operation="monitor" operation_key="single:0_monitor_0" on_node="rhel7-auto1" on_node_uuid="1">
        <primitive id="single" long-id="single:0" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_isolation_host="rhel7-auto1" CRM_meta_isolation_instance="single-clone_0" CRM_meta_isolation_wrapper="docker-wrapper" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  pcmk_docker_image="centos:isolation"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="4">
    <action_set>
      <rsc_op id="15" operation="monitor" operation_key="single:1_monitor_60000" on_node="rhel7-auto1" on_node_uuid="1">
        <primitive id="single" long-id="single:1" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_interval="60000" CRM_meta_isolation_host="rhel7-auto1" CRM_meta_isolation_instance="single-clone_1" CRM_meta_isolation_wrapper="docker-wrapper" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_timeout="20000"  pcmk_docker_image="centos:isolation"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="14" operation="start" operation_key="single:1_start_0" on_node="rhel7-auto1" on_node_uuid="1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <rsc_op id="14" operation="start" operation_key="single:1_start_0" on_node="rhel7-auto1" on_node_uuid="1">
        <primitive id="single" long-id="single:1" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_isolation_host="rhel7-auto1" CRM_meta_isolation_instance="single-clone_1" CRM_meta_isolation_wrapper="docker-wrapper" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_timeout="120000"  pcmk_docker_image="centos:isolation"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="3" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="16" operation="start" operation_key="single-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <rsc_op id="9" operation="monitor" operation_key="single:1_monitor_0" on_node="rhel7-auto2" on_node_uuid="2">
        <primitive id="single" long-id="single:1" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_isolation_host="rhel7-auto2" CRM_meta_isolation_instance="single-clone_1" CRM_meta_isolation_wrapper="docker-wrapper" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  pcmk_docker_image="centos:isolation"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="7">
    <action_set>
      <rsc_op id="6" operation="monitor" operation_key="single:1_monitor_0" on_node="rhel7-auto1" on_node_uuid="1">
        <primitive id="single" long-id="single:1" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_isolation_host="rhel7-auto1" CRM_meta_isolation_instance="single-clone_1" CRM_meta_isolation_wrapper="docker-wrapper" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  pcmk_docker_image="centos:isolation"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="8" priority="1000000">
    <action_set>
      <pseudo_event id="17" operation="running" operation_key="single-clone_running_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="12" operation="start" operation_key="single:0_start_0" on_node="rhel7-auto2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="14" operation="start" operation_key="single:1_start_0" on_node="rhel7-auto1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <pseudo_event id="16" operation="start" operation_key="single-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9">
    <action_set>
      <pseudo_event id="16" operation="start" operation_key="single-clone_start_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="10" priority="1000000">
    <action_set>
      <rsc_op id="7" operation="probe_complete" operation_key="probe_complete-rhel7-auto2" on_node="rhel7-auto2" on_node_uuid="2">
        <attributes CRM_meta_op_no_wait="true" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="8" operation="monitor" operation_key="single:0_monitor_0" on_node="rhel7-auto2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="9" operation="monitor" operation_key="single:1_monitor_0" on_node="rhel7-auto2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="11" priority="1000000">
    <action_set>
      <rsc_op id="4" operation="probe_complete" operation_key="probe_complete-rhel7-auto1" on_node="rhel7-auto1" on_node_uuid="1">
        <attributes CRM_meta_op_no_wait="true" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="monitor" operation_key="single:0_monitor_0" on_node="rhel7-auto1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="6" operation="monitor" operation_key="single:1_monitor_0" on_node="rhel7-auto1" on_node_uuid="1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="12">
    <action_set>
      <pseudo_event id="3" operation="probe_complete" operation_key="probe_complete">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="4" operation="probe_complete" operation_key="probe_complete-rhel7-auto1" on_node="rhel7-auto1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="7" operation="probe_complete" operation_key="probe_complete-rhel7-auto2" on_node="rhel7-auto2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>
