 <transition_graph cluster-delay="3m" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
   <synapse id="0">
     <action_set>
       <rsc_op id="48" operation="stop" operation_key="child_DoFencing:1_stop_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="child_DoFencing:1" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_timeout="20000"  hostlist="sgi2 ibm1 va1 test02 "/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="51" operation="stop" operation_key="DoFencing_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="15" operation="monitor" operation_key="child_DoFencing:1_monitor_0" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b">
        <primitive id="child_DoFencing:1" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="40000"  hostlist="sgi2 ibm1 va1 test02 "/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
   <synapse id="2">
     <action_set>
      <rsc_op id="16" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b">
        <primitive id="child_DoFencing:2" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="40000"  hostlist="sgi2 ibm1 va1 test02 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="3">
     <action_set>
      <rsc_op id="6" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="child_DoFencing:2" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="40000"  hostlist="sgi2 ibm1 va1 test02 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="4">
     <action_set>
      <rsc_op id="17" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b">
        <primitive id="child_DoFencing:3" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="40000"  hostlist="sgi2 ibm1 va1 test02 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="5">
     <action_set>
      <rsc_op id="7" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="child_DoFencing:3" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="40000"  hostlist="sgi2 ibm1 va1 test02 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="6" priority="1000000">
     <action_set>
       <pseudo_event id="52" operation="stopped" operation_key="DoFencing_stopped_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <rsc_op id="48" operation="stop" operation_key="child_DoFencing:1_stop_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
       </trigger>
       <trigger>
         <pseudo_event id="51" operation="stop" operation_key="DoFencing_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="7">
    <action_set>
      <pseudo_event id="51" operation="stop" operation_key="DoFencing_stop_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
   <synapse id="8">
     <action_set>
      <rsc_op id="18" operation="monitor" operation_key="ocf_msdummy:2_monitor_0" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b">
        <primitive id="ocf_msdummy:2" class="ocf" provider="heartbeat" type="/usr/lib64/heartbeat/cts/OCFMSDummy"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="8" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_master_max="4" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="10000"  logfile="/var/log/cts_ocfdummy.log"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="9">
     <action_set>
      <rsc_op id="8" operation="monitor" operation_key="ocf_msdummy:2_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="ocf_msdummy:2" class="ocf" provider="heartbeat" type="/usr/lib64/heartbeat/cts/OCFMSDummy"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="8" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_master_max="4" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="10000"  logfile="/var/log/cts_ocfdummy.log"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="10">
     <action_set>
      <rsc_op id="19" operation="monitor" operation_key="ocf_msdummy:3_monitor_0" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b">
        <primitive id="ocf_msdummy:3" class="ocf" provider="heartbeat" type="/usr/lib64/heartbeat/cts/OCFMSDummy"/>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="8" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_master_max="4" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="10000"  logfile="/var/log/cts_ocfdummy.log"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="11">
     <action_set>
      <rsc_op id="9" operation="monitor" operation_key="ocf_msdummy:3_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="ocf_msdummy:3" class="ocf" provider="heartbeat" type="/usr/lib64/heartbeat/cts/OCFMSDummy"/>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="8" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_master_max="4" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="10000"  logfile="/var/log/cts_ocfdummy.log"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="12">
     <action_set>
      <rsc_op id="20" operation="monitor" operation_key="ocf_msdummy:4_monitor_0" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b">
        <primitive id="ocf_msdummy:4" class="ocf" provider="heartbeat" type="/usr/lib64/heartbeat/cts/OCFMSDummy"/>
        <attributes CRM_meta_clone="4" CRM_meta_clone_max="8" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_master_max="4" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="10000"  logfile="/var/log/cts_ocfdummy.log"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="13">
     <action_set>
      <rsc_op id="10" operation="monitor" operation_key="ocf_msdummy:4_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="ocf_msdummy:4" class="ocf" provider="heartbeat" type="/usr/lib64/heartbeat/cts/OCFMSDummy"/>
        <attributes CRM_meta_clone="4" CRM_meta_clone_max="8" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_master_max="4" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="10000"  logfile="/var/log/cts_ocfdummy.log"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="14">
     <action_set>
      <rsc_op id="21" operation="monitor" operation_key="ocf_msdummy:5_monitor_0" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b">
        <primitive id="ocf_msdummy:5" class="ocf" provider="heartbeat" type="/usr/lib64/heartbeat/cts/OCFMSDummy"/>
        <attributes CRM_meta_clone="5" CRM_meta_clone_max="8" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_master_max="4" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="10000"  logfile="/var/log/cts_ocfdummy.log"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="15">
     <action_set>
      <rsc_op id="11" operation="monitor" operation_key="ocf_msdummy:5_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="ocf_msdummy:5" class="ocf" provider="heartbeat" type="/usr/lib64/heartbeat/cts/OCFMSDummy"/>
        <attributes CRM_meta_clone="5" CRM_meta_clone_max="8" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_master_max="4" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="10000"  logfile="/var/log/cts_ocfdummy.log"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="16">
     <action_set>
      <rsc_op id="22" operation="monitor" operation_key="ocf_msdummy:6_monitor_0" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b">
        <primitive id="ocf_msdummy:6" class="ocf" provider="heartbeat" type="/usr/lib64/heartbeat/cts/OCFMSDummy"/>
        <attributes CRM_meta_clone="6" CRM_meta_clone_max="8" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_master_max="4" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="10000"  logfile="/var/log/cts_ocfdummy.log"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="17">
     <action_set>
      <rsc_op id="12" operation="monitor" operation_key="ocf_msdummy:6_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="ocf_msdummy:6" class="ocf" provider="heartbeat" type="/usr/lib64/heartbeat/cts/OCFMSDummy"/>
        <attributes CRM_meta_clone="6" CRM_meta_clone_max="8" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_master_max="4" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="10000"  logfile="/var/log/cts_ocfdummy.log"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="18">
     <action_set>
      <rsc_op id="23" operation="monitor" operation_key="ocf_msdummy:7_monitor_0" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b">
        <primitive id="ocf_msdummy:7" class="ocf" provider="heartbeat" type="/usr/lib64/heartbeat/cts/OCFMSDummy"/>
        <attributes CRM_meta_clone="7" CRM_meta_clone_max="8" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_master_max="4" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="10000"  logfile="/var/log/cts_ocfdummy.log"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="19">
     <action_set>
      <rsc_op id="13" operation="monitor" operation_key="ocf_msdummy:7_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <primitive id="ocf_msdummy:7" class="ocf" provider="heartbeat" type="/usr/lib64/heartbeat/cts/OCFMSDummy"/>
        <attributes CRM_meta_clone="7" CRM_meta_clone_max="8" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_master_max="4" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="10000"  logfile="/var/log/cts_ocfdummy.log"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="20">
     <action_set>
      <crm_event id="66" operation="do_shutdown" operation_key="do_shutdown-ibm1" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <attributes CRM_meta_op_no_wait="true" />
      </crm_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="48" operation="stop" operation_key="child_DoFencing:1_stop_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="21" priority="1000000">
     <action_set>
      <rsc_op id="14" operation="probe_complete" operation_key="probe_complete-va1" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b">
        <attributes CRM_meta_op_no_wait="true" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="15" operation="monitor" operation_key="child_DoFencing:1_monitor_0" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b"/>
       </trigger>
       <trigger>
        <rsc_op id="16" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b"/>
       </trigger>
       <trigger>
        <rsc_op id="17" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b"/>
       </trigger>
       <trigger>
        <rsc_op id="18" operation="monitor" operation_key="ocf_msdummy:2_monitor_0" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b"/>
       </trigger>
       <trigger>
        <rsc_op id="19" operation="monitor" operation_key="ocf_msdummy:3_monitor_0" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b"/>
       </trigger>
       <trigger>
        <rsc_op id="20" operation="monitor" operation_key="ocf_msdummy:4_monitor_0" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b"/>
       </trigger>
       <trigger>
        <rsc_op id="21" operation="monitor" operation_key="ocf_msdummy:5_monitor_0" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b"/>
       </trigger>
       <trigger>
        <rsc_op id="22" operation="monitor" operation_key="ocf_msdummy:6_monitor_0" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b"/>
      </trigger>
      <trigger>
        <rsc_op id="23" operation="monitor" operation_key="ocf_msdummy:7_monitor_0" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="22" priority="1000000">
     <action_set>
      <rsc_op id="5" operation="probe_complete" operation_key="probe_complete-ibm1" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638">
        <attributes CRM_meta_op_no_wait="true" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="6" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
       </trigger>
       <trigger>
        <rsc_op id="7" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
       </trigger>
       <trigger>
        <rsc_op id="8" operation="monitor" operation_key="ocf_msdummy:2_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
       </trigger>
       <trigger>
        <rsc_op id="9" operation="monitor" operation_key="ocf_msdummy:3_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
       </trigger>
       <trigger>
        <rsc_op id="10" operation="monitor" operation_key="ocf_msdummy:4_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
       </trigger>
       <trigger>
        <rsc_op id="11" operation="monitor" operation_key="ocf_msdummy:5_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
       </trigger>
       <trigger>
        <rsc_op id="12" operation="monitor" operation_key="ocf_msdummy:6_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
      </trigger>
      <trigger>
        <rsc_op id="13" operation="monitor" operation_key="ocf_msdummy:7_monitor_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="23">
     <action_set>
      <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete">
        <attributes />
      </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="5" operation="probe_complete" operation_key="probe_complete-ibm1" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
      </trigger>
      <trigger>
        <rsc_op id="14" operation="probe_complete" operation_key="probe_complete-va1" on_node="va1" on_node_uuid="b8f81462-2d65-42bf-bbb1-70db0ea29e5b"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="24">
    <action_set>
      <pseudo_event id="3" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="48" operation="stop" operation_key="child_DoFencing:1_stop_0" on_node="ibm1" on_node_uuid="d0d76dd9-7a01-4c12-bbec-98aa2a669638"/>
      </trigger>
    </inputs>
  </synapse>
 </transition_graph>

