 <transition_graph cluster-delay="180s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
   <synapse id="0">
     <action_set>
      <pseudo_event id="35" operation="promoted" operation_key="grp_ms_sf:1_promoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="120000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="26" operation="promote" operation_key="master_slave_Stateful:1_promote_0" on_node="rh44-1" on_node_uuid="782b1222-d1b9-4993-8f0d-b8b67801a2c8"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="1">
     <action_set>
      <pseudo_event id="34" operation="promote" operation_key="grp_ms_sf:1_promote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="120000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="40" operation="promote" operation_key="ms-sf_promote_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="2">
     <action_set>
      <rsc_op id="27" operation="monitor" operation_key="master_slave_Stateful:1_monitor_6000" on_node="rh44-1" on_node_uuid="782b1222-d1b9-4993-8f0d-b8b67801a2c8">
        <primitive id="master_slave_Stateful:1" class="ocf" provider="heartbeat" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_interval="6000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_op_target_rc="8" CRM_meta_role="Master" CRM_meta_timeout="30000" crm_feature_set="3.0.6"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <rsc_op id="26" operation="promote" operation_key="master_slave_Stateful:1_promote_0" on_node="rh44-1" on_node_uuid="782b1222-d1b9-4993-8f0d-b8b67801a2c8"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="3">
     <action_set>
      <rsc_op id="26" operation="promote" operation_key="master_slave_Stateful:1_promote_0" on_node="rh44-1" on_node_uuid="782b1222-d1b9-4993-8f0d-b8b67801a2c8">
        <primitive id="master_slave_Stateful:1" class="ocf" provider="heartbeat" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="120000" crm_feature_set="3.0.6"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <rsc_op id="1" operation="cancel" operation_key="master_slave_Stateful:1_monitor_5000" on_node="rh44-1" on_node_uuid="782b1222-d1b9-4993-8f0d-b8b67801a2c8"/>
       </trigger>
       <trigger>
        <pseudo_event id="34" operation="promote" operation_key="grp_ms_sf:1_promote_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="4">
     <action_set>
      <rsc_op id="1" operation="cancel" operation_key="master_slave_Stateful:1_monitor_5000" on_node="rh44-1" on_node_uuid="782b1222-d1b9-4993-8f0d-b8b67801a2c8">
        <primitive id="master_slave_Stateful:1" class="ocf" provider="heartbeat" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_interval="5000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_operation="monitor" CRM_meta_timeout="30000" crm_feature_set="3.0.6"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="5" priority="1000000">
     <action_set>
      <pseudo_event id="41" operation="promoted" operation_key="ms-sf_promoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="120000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="35" operation="promoted" operation_key="grp_ms_sf:1_promoted_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="6">
    <action_set>
      <pseudo_event id="40" operation="promote" operation_key="ms-sf_promote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="120000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
 </transition_graph>

