<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="9" operation="monitor" operation_key="dummy:1_monitor_20000" on_node="dl380g5d" on_node_uuid="3f6ec88d-ee47-4f63-bfeb-652b8dd96027">
        <primitive id="dummy" long-id="dummy:1" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="20000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_on_fail="restart" CRM_meta_role="Slave" CRM_meta_timeout="100000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
</transition_graph>

