<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0" priority="1000000">
    <action_set>
      <rsc_op id="56" operation="notify" operation_key="fake_post_notify_promote_0" internal_operation_key="fake:0_post_notify_promote_0" on_node="rhel7-auto1" on_node_uuid="1">
        <primitive id="fake" long-id="fake:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="promoted" CRM_meta_notify_key_type="post" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="promote" CRM_meta_notify_promote_resource="fake:0" CRM_meta_notify_promote_uname="rhel7-auto1" CRM_meta_notify_slave_resource="fake:0 fake:1 fake:2" CRM_meta_notify_slave_uname="rhel7-auto1 rhel7-auto3 rhel7-auto2" CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="32" operation="notify" operation_key="fake-master_post_notify_promoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="55" operation="notify" operation_key="fake_pre_notify_promote_0" internal_operation_key="fake:0_pre_notify_promote_0" on_node="rhel7-auto1" on_node_uuid="1">
        <primitive id="fake" long-id="fake:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="promote" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="promote" CRM_meta_notify_promote_resource="fake:0" CRM_meta_notify_promote_uname="rhel7-auto1" CRM_meta_notify_slave_resource="fake:0 fake:1 fake:2" CRM_meta_notify_slave_uname="rhel7-auto1 rhel7-auto3 rhel7-auto2" CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="30" operation="notify" operation_key="fake-master_pre_notify_promote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="11" operation="promote" operation_key="fake_promote_0" internal_operation_key="fake:0_promote_0" on_node="rhel7-auto1" on_node_uuid="1">
        <primitive id="fake" long-id="fake:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_promote_resource="fake:0" CRM_meta_notify_promote_uname="rhel7-auto1" CRM_meta_notify_slave_resource="fake:0 fake:1 fake:2" CRM_meta_notify_slave_uname="rhel7-auto1 rhel7-auto3 rhel7-auto2" CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="28" operation="promote" operation_key="fake-master_promote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3" priority="1000000">
    <action_set>
      <rsc_op id="58" operation="notify" operation_key="fake_post_notify_promote_0" internal_operation_key="fake:1_post_notify_promote_0" on_node="rhel7-auto3" on_node_uuid="3">
        <primitive id="fake" long-id="fake:1" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="promoted" CRM_meta_notify_key_type="post" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="promote" CRM_meta_notify_promote_resource="fake:0" CRM_meta_notify_promote_uname="rhel7-auto1" CRM_meta_notify_slave_resource="fake:0 fake:1 fake:2" CRM_meta_notify_slave_uname="rhel7-auto1 rhel7-auto3 rhel7-auto2" CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="32" operation="notify" operation_key="fake-master_post_notify_promoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <rsc_op id="57" operation="notify" operation_key="fake_pre_notify_promote_0" internal_operation_key="fake:1_pre_notify_promote_0" on_node="rhel7-auto3" on_node_uuid="3">
        <primitive id="fake" long-id="fake:1" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="promote" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="promote" CRM_meta_notify_promote_resource="fake:0" CRM_meta_notify_promote_uname="rhel7-auto1" CRM_meta_notify_slave_resource="fake:0 fake:1 fake:2" CRM_meta_notify_slave_uname="rhel7-auto1 rhel7-auto3 rhel7-auto2" CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="30" operation="notify" operation_key="fake-master_pre_notify_promote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5" priority="1000000">
    <action_set>
      <rsc_op id="60" operation="notify" operation_key="fake_post_notify_promote_0" internal_operation_key="fake:2_post_notify_promote_0" on_node="rhel7-auto2" on_node_uuid="2">
        <primitive id="fake" long-id="fake:2" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="promoted" CRM_meta_notify_key_type="post" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="promote" CRM_meta_notify_promote_resource="fake:0" CRM_meta_notify_promote_uname="rhel7-auto1" CRM_meta_notify_slave_resource="fake:0 fake:1 fake:2" CRM_meta_notify_slave_uname="rhel7-auto1 rhel7-auto3 rhel7-auto2" CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="32" operation="notify" operation_key="fake-master_post_notify_promoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <rsc_op id="59" operation="notify" operation_key="fake_pre_notify_promote_0" internal_operation_key="fake:2_pre_notify_promote_0" on_node="rhel7-auto2" on_node_uuid="2">
        <primitive id="fake" long-id="fake:2" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="promote" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="promote" CRM_meta_notify_promote_resource="fake:0" CRM_meta_notify_promote_uname="rhel7-auto1" CRM_meta_notify_slave_resource="fake:0 fake:1 fake:2" CRM_meta_notify_slave_uname="rhel7-auto1 rhel7-auto3 rhel7-auto2" CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="30" operation="notify" operation_key="fake-master_pre_notify_promote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7" priority="1000000">
    <action_set>
      <pseudo_event id="33" operation="notified" operation_key="fake-master_confirmed-post_notify_promoted_0">
        <attributes CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="promoted" CRM_meta_notify_key_type="confirmed-post" CRM_meta_notify_operation="promote" CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="32" operation="notify" operation_key="fake-master_post_notify_promoted_0"/>
      </trigger>
      <trigger>
        <rsc_op id="56" operation="notify" operation_key="fake_post_notify_promote_0" internal_operation_key="fake:0_post_notify_promote_0" on_node="rhel7-auto1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="58" operation="notify" operation_key="fake_post_notify_promote_0" internal_operation_key="fake:1_post_notify_promote_0" on_node="rhel7-auto3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="60" operation="notify" operation_key="fake_post_notify_promote_0" internal_operation_key="fake:2_post_notify_promote_0" on_node="rhel7-auto2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8" priority="1000000">
    <action_set>
      <pseudo_event id="32" operation="notify" operation_key="fake-master_post_notify_promoted_0">
        <attributes CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="promoted" CRM_meta_notify_key_type="post" CRM_meta_notify_operation="promote" CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="29" operation="promoted" operation_key="fake-master_promoted_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="31" operation="notified" operation_key="fake-master_confirmed-pre_notify_promote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9">
    <action_set>
      <pseudo_event id="31" operation="notified" operation_key="fake-master_confirmed-pre_notify_promote_0">
        <attributes CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="promote" CRM_meta_notify_key_type="confirmed-pre" CRM_meta_notify_operation="promote" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="30" operation="notify" operation_key="fake-master_pre_notify_promote_0"/>
      </trigger>
      <trigger>
        <rsc_op id="55" operation="notify" operation_key="fake_pre_notify_promote_0" internal_operation_key="fake:0_pre_notify_promote_0" on_node="rhel7-auto1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="57" operation="notify" operation_key="fake_pre_notify_promote_0" internal_operation_key="fake:1_pre_notify_promote_0" on_node="rhel7-auto3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="59" operation="notify" operation_key="fake_pre_notify_promote_0" internal_operation_key="fake:2_pre_notify_promote_0" on_node="rhel7-auto2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="10">
    <action_set>
      <pseudo_event id="30" operation="notify" operation_key="fake-master_pre_notify_promote_0">
        <attributes CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_notify_key_operation="promote" CRM_meta_notify_key_type="pre" CRM_meta_notify_operation="promote" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="11" priority="1000000">
    <action_set>
      <pseudo_event id="29" operation="promoted" operation_key="fake-master_promoted_0">
        <attributes CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="11" operation="promote" operation_key="fake_promote_0" internal_operation_key="fake:0_promote_0" on_node="rhel7-auto1" on_node_uuid="1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="12">
    <action_set>
      <pseudo_event id="28" operation="promote" operation_key="fake-master_promote_0">
        <attributes CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="true" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="31" operation="notified" operation_key="fake-master_confirmed-pre_notify_promote_0"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>
