<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="1" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="5" operation="migrate_to" operation_key="domU-test01_migrate_to_0" on_node="dom0-02" on_node_uuid="dom0-02">
        <primitive id="domU-test01" long-id="domU-test01" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_migrate_source="dom0-02" CRM_meta_migrate_target="dom0-01" CRM_meta_timeout="20000" allow_migrate="true" crm_feature_set="3.0.1" xmfile="/etc/xen/test01.cfg"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="6" operation="migrate_from" operation_key="domU-test01_migrate_from_0" on_node="dom0-01" on_node_uuid="dom0-01">
        <primitive id="domU-test01" long-id="domU-test01" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_migrate_source="dom0-02" CRM_meta_migrate_source_uuid="dom0-02" CRM_meta_migrate_target="dom0-01" CRM_meta_timeout="20000" allow_migrate="true" crm_feature_set="3.0.1" xmfile="/etc/xen/test01.cfg"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="migrate_to" operation_key="domU-test01_migrate_to_0" on_node="dom0-02" on_node_uuid="dom0-02"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <pseudo_event id="10" operation="stop" operation_key="dom0-iscsi1:0_stop_0">
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_timeout="20000" crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="20" operation="stop" operation_key="clone-dom0-iscsi1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <pseudo_event id="11" operation="stopped" operation_key="dom0-iscsi1:0_stopped_0">
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_timeout="20000" crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="7" operation="stop" operation_key="dom0-iscsi1-cnx1:0_stop_0" on_node="dom0-02" on_node_uuid="dom0-02"/>
      </trigger>
      <trigger>
        <pseudo_event id="10" operation="stop" operation_key="dom0-iscsi1:0_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <rsc_op id="7" operation="stop" operation_key="dom0-iscsi1-cnx1:0_stop_0" on_node="dom0-02" on_node_uuid="dom0-02">
        <primitive id="dom0-iscsi1-cnx1:0" long-id="clone-dom0-iscsi1:dom0-iscsi1:0:dom0-iscsi1-cnx1:0" class="ocf" provider="heartbeat" type="iscsi"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_timeout="20000" crm_feature_set="3.0.1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="10" operation="stop" operation_key="dom0-iscsi1:0_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <pseudo_event id="20" operation="stop" operation_key="clone-dom0-iscsi1_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_timeout="20000" crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="migrate_to" operation_key="domU-test01_migrate_to_0" on_node="dom0-02" on_node_uuid="dom0-02"/>
      </trigger>
      <trigger>
        <rsc_op id="6" operation="migrate_from" operation_key="domU-test01_migrate_from_0" on_node="dom0-01" on_node_uuid="dom0-01"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6" priority="1000000">
    <action_set>
      <pseudo_event id="21" operation="stopped" operation_key="clone-dom0-iscsi1_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_timeout="20000" crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="11" operation="stopped" operation_key="dom0-iscsi1:0_stopped_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="20" operation="stop" operation_key="clone-dom0-iscsi1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <pseudo_event id="1" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="migrate_to" operation_key="domU-test01_migrate_to_0" on_node="dom0-02" on_node_uuid="dom0-02"/>
      </trigger>
      <trigger>
        <rsc_op id="7" operation="stop" operation_key="dom0-iscsi1-cnx1:0_stop_0" on_node="dom0-02" on_node_uuid="dom0-02"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

