<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="37" operation="stop" operation_key="fs-libvirt-VM-xcm_stop_0" internal_operation_key="fs-libvirt-VM-xcm:0_stop_0" on_node="cvmh04" on_node_uuid="cvmh04">
        <primitive id="fs-libvirt-VM-xcm" long-id="fs-libvirt-VM-xcm:0" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_name="stop" CRM_meta_notify="false" CRM_meta_timeout="110000"  device="cvmstorage-ib:/libvirt/VM-xcm" directory="/srv/libvirt/VM-xcm" fstype="nfs" options="rw,relatime"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="40" operation="stop" operation_key="fs-libvirt-VM-xcm_stop_0" internal_operation_key="fs-libvirt-VM-xcm:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
      <trigger>
        <pseudo_event id="45" operation="stop" operation_key="c-fs-libvirt-VM-xcm_stop_0"/>
      </trigger>
      <trigger>
        <rsc_op id="75" operation="stop" operation_key="p-libvirtd_stop_0" internal_operation_key="p-libvirtd:0_stop_0" on_node="cvmh04" on_node_uuid="cvmh04"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="40" operation="stop" operation_key="fs-libvirt-VM-xcm_stop_0" internal_operation_key="fs-libvirt-VM-xcm:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03">
        <primitive id="fs-libvirt-VM-xcm" long-id="fs-libvirt-VM-xcm:2" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_name="stop" CRM_meta_notify="false" CRM_meta_timeout="110000"  device="cvmstorage-ib:/libvirt/VM-xcm" directory="/srv/libvirt/VM-xcm" fstype="nfs" options="rw,relatime"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="45" operation="stop" operation_key="c-fs-libvirt-VM-xcm_stop_0"/>
      </trigger>
      <trigger>
        <rsc_op id="78" operation="stop" operation_key="p-libvirtd_stop_0" internal_operation_key="p-libvirtd:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2" priority="1000000">
    <action_set>
      <pseudo_event id="46" operation="stopped" operation_key="c-fs-libvirt-VM-xcm_stopped_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="37" operation="stop" operation_key="fs-libvirt-VM-xcm_stop_0" internal_operation_key="fs-libvirt-VM-xcm:0_stop_0" on_node="cvmh04" on_node_uuid="cvmh04"/>
      </trigger>
      <trigger>
        <rsc_op id="40" operation="stop" operation_key="fs-libvirt-VM-xcm_stop_0" internal_operation_key="fs-libvirt-VM-xcm:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
      <trigger>
        <pseudo_event id="45" operation="stop" operation_key="c-fs-libvirt-VM-xcm_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <pseudo_event id="45" operation="stop" operation_key="c-fs-libvirt-VM-xcm_stop_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="84" operation="stopped" operation_key="c-p-libvirtd_stopped_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <rsc_op id="47" operation="stop" operation_key="p-watch-ib0_stop_0" internal_operation_key="p-watch-ib0:0_stop_0" on_node="cvmh04" on_node_uuid="cvmh04">
        <primitive id="p-watch-ib0" long-id="p-watch-ib0:0" class="ocf" provider="heartbeat" type="ethmonitor"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000"  interface="ib0"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="50" operation="stop" operation_key="p-watch-ib0_stop_0" internal_operation_key="p-watch-ib0:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
      <trigger>
        <pseudo_event id="55" operation="stop" operation_key="c-watch-ib0_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <rsc_op id="50" operation="stop" operation_key="p-watch-ib0_stop_0" internal_operation_key="p-watch-ib0:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03">
        <primitive id="p-watch-ib0" long-id="p-watch-ib0:2" class="ocf" provider="heartbeat" type="ethmonitor"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000"  interface="ib0"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="55" operation="stop" operation_key="c-watch-ib0_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6" priority="1000000">
    <action_set>
      <pseudo_event id="56" operation="stopped" operation_key="c-watch-ib0_stopped_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="47" operation="stop" operation_key="p-watch-ib0_stop_0" internal_operation_key="p-watch-ib0:0_stop_0" on_node="cvmh04" on_node_uuid="cvmh04"/>
      </trigger>
      <trigger>
        <rsc_op id="50" operation="stop" operation_key="p-watch-ib0_stop_0" internal_operation_key="p-watch-ib0:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
      <trigger>
        <pseudo_event id="55" operation="stop" operation_key="c-watch-ib0_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <pseudo_event id="55" operation="stop" operation_key="c-watch-ib0_stop_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="8">
    <action_set>
      <rsc_op id="57" operation="stop" operation_key="p-fs-gpfs_stop_0" internal_operation_key="p-fs-gpfs:0_stop_0" on_node="cvmh04" on_node_uuid="cvmh04">
        <primitive id="p-fs-gpfs" long-id="p-fs-gpfs:0" class="ocf" provider="ccni" type="gpfs"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_name="stop" CRM_meta_notify="false" CRM_meta_timeout="120000"  fspath="/gpfs/lb/utility"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="60" operation="stop" operation_key="p-fs-gpfs_stop_0" internal_operation_key="p-fs-gpfs:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
      <trigger>
        <pseudo_event id="65" operation="stop" operation_key="c-fs-gpfs_stop_0"/>
      </trigger>
      <trigger>
        <rsc_op id="85" operation="stop" operation_key="fs-bind-libvirt-VM-cvmh_stop_0" internal_operation_key="fs-bind-libvirt-VM-cvmh:0_stop_0" on_node="cvmh04" on_node_uuid="cvmh04"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9">
    <action_set>
      <rsc_op id="60" operation="stop" operation_key="p-fs-gpfs_stop_0" internal_operation_key="p-fs-gpfs:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03">
        <primitive id="p-fs-gpfs" long-id="p-fs-gpfs:2" class="ocf" provider="ccni" type="gpfs"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_name="stop" CRM_meta_notify="false" CRM_meta_timeout="120000"  fspath="/gpfs/lb/utility"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="65" operation="stop" operation_key="c-fs-gpfs_stop_0"/>
      </trigger>
      <trigger>
        <rsc_op id="88" operation="stop" operation_key="fs-bind-libvirt-VM-cvmh_stop_0" internal_operation_key="fs-bind-libvirt-VM-cvmh:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="10" priority="1000000">
    <action_set>
      <pseudo_event id="66" operation="stopped" operation_key="c-fs-gpfs_stopped_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="57" operation="stop" operation_key="p-fs-gpfs_stop_0" internal_operation_key="p-fs-gpfs:0_stop_0" on_node="cvmh04" on_node_uuid="cvmh04"/>
      </trigger>
      <trigger>
        <rsc_op id="60" operation="stop" operation_key="p-fs-gpfs_stop_0" internal_operation_key="p-fs-gpfs:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
      <trigger>
        <pseudo_event id="65" operation="stop" operation_key="c-fs-gpfs_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="11">
    <action_set>
      <pseudo_event id="65" operation="stop" operation_key="c-fs-gpfs_stop_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="94" operation="stopped" operation_key="c-fs-bind-libvirt-VM-cvmh_stopped_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="12">
    <action_set>
      <rsc_op id="75" operation="stop" operation_key="p-libvirtd_stop_0" internal_operation_key="p-libvirtd:0_stop_0" on_node="cvmh04" on_node_uuid="cvmh04">
        <primitive id="p-libvirtd" long-id="p-libvirtd:0" class="lsb" type="libvirtd"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="78" operation="stop" operation_key="p-libvirtd_stop_0" internal_operation_key="p-libvirtd:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
      <trigger>
        <pseudo_event id="83" operation="stop" operation_key="c-p-libvirtd_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="13">
    <action_set>
      <rsc_op id="78" operation="stop" operation_key="p-libvirtd_stop_0" internal_operation_key="p-libvirtd:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03">
        <primitive id="p-libvirtd" long-id="p-libvirtd:2" class="lsb" type="libvirtd"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="83" operation="stop" operation_key="c-p-libvirtd_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="14" priority="1000000">
    <action_set>
      <pseudo_event id="84" operation="stopped" operation_key="c-p-libvirtd_stopped_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="75" operation="stop" operation_key="p-libvirtd_stop_0" internal_operation_key="p-libvirtd:0_stop_0" on_node="cvmh04" on_node_uuid="cvmh04"/>
      </trigger>
      <trigger>
        <rsc_op id="78" operation="stop" operation_key="p-libvirtd_stop_0" internal_operation_key="p-libvirtd:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
      <trigger>
        <pseudo_event id="83" operation="stop" operation_key="c-p-libvirtd_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="15">
    <action_set>
      <pseudo_event id="83" operation="stop" operation_key="c-p-libvirtd_stop_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="95" operation="stop" operation_key="vm-compute-test_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
      <trigger>
        <rsc_op id="98" operation="stop" operation_key="vm-swbuildsl6_stop_0" on_node="cvmh04" on_node_uuid="cvmh04"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="16">
    <action_set>
      <rsc_op id="85" operation="stop" operation_key="fs-bind-libvirt-VM-cvmh_stop_0" internal_operation_key="fs-bind-libvirt-VM-cvmh:0_stop_0" on_node="cvmh04" on_node_uuid="cvmh04">
        <primitive id="fs-bind-libvirt-VM-cvmh" long-id="fs-bind-libvirt-VM-cvmh:0" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_name="stop" CRM_meta_notify="false" CRM_meta_timeout="120000"  device="/gpfs/lb/utility/VM-cvmh" directory="/srv/libvirt/VM-cvmh" fstype="none" options="bind"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="75" operation="stop" operation_key="p-libvirtd_stop_0" internal_operation_key="p-libvirtd:0_stop_0" on_node="cvmh04" on_node_uuid="cvmh04"/>
      </trigger>
      <trigger>
        <rsc_op id="88" operation="stop" operation_key="fs-bind-libvirt-VM-cvmh_stop_0" internal_operation_key="fs-bind-libvirt-VM-cvmh:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
      <trigger>
        <pseudo_event id="93" operation="stop" operation_key="c-fs-bind-libvirt-VM-cvmh_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="17">
    <action_set>
      <rsc_op id="88" operation="stop" operation_key="fs-bind-libvirt-VM-cvmh_stop_0" internal_operation_key="fs-bind-libvirt-VM-cvmh:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03">
        <primitive id="fs-bind-libvirt-VM-cvmh" long-id="fs-bind-libvirt-VM-cvmh:2" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_name="stop" CRM_meta_notify="false" CRM_meta_timeout="120000"  device="/gpfs/lb/utility/VM-cvmh" directory="/srv/libvirt/VM-cvmh" fstype="none" options="bind"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="78" operation="stop" operation_key="p-libvirtd_stop_0" internal_operation_key="p-libvirtd:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
      <trigger>
        <pseudo_event id="93" operation="stop" operation_key="c-fs-bind-libvirt-VM-cvmh_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="18" priority="1000000">
    <action_set>
      <pseudo_event id="94" operation="stopped" operation_key="c-fs-bind-libvirt-VM-cvmh_stopped_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="85" operation="stop" operation_key="fs-bind-libvirt-VM-cvmh_stop_0" internal_operation_key="fs-bind-libvirt-VM-cvmh:0_stop_0" on_node="cvmh04" on_node_uuid="cvmh04"/>
      </trigger>
      <trigger>
        <rsc_op id="88" operation="stop" operation_key="fs-bind-libvirt-VM-cvmh_stop_0" internal_operation_key="fs-bind-libvirt-VM-cvmh:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
      <trigger>
        <pseudo_event id="93" operation="stop" operation_key="c-fs-bind-libvirt-VM-cvmh_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="19">
    <action_set>
      <pseudo_event id="93" operation="stop" operation_key="c-fs-bind-libvirt-VM-cvmh_stop_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="84" operation="stopped" operation_key="c-p-libvirtd_stopped_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="20" priority="1000000">
    <action_set>
      <rsc_op id="113" operation="migrate_from" operation_key="vm-compute-test_migrate_from_0" on_node="cvmh01" on_node_uuid="cvmh01">
        <primitive id="vm-compute-test" class="ocf" provider="ccni" type="xcatVirtualDomain"/>
        <attributes CRM_meta_migrate_source="cvmh03" CRM_meta_migrate_target="cvmh01" CRM_meta_timeout="20000"  migration_network_suffix="-ib" migration_transport="ssh" nodename="compute-test"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="112" operation="migrate_to" operation_key="vm-compute-test_migrate_to_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="21">
    <action_set>
      <rsc_op id="112" operation="migrate_to" operation_key="vm-compute-test_migrate_to_0" on_node="cvmh03" on_node_uuid="cvmh03">
        <primitive id="vm-compute-test" class="ocf" provider="ccni" type="xcatVirtualDomain"/>
        <attributes CRM_meta_migrate_source="cvmh03" CRM_meta_migrate_target="cvmh01" CRM_meta_record_pending="true" CRM_meta_timeout="20000"  migration_network_suffix="-ib" migration_transport="ssh" nodename="compute-test"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="22">
    <action_set>
      <rsc_op id="97" operation="monitor" operation_key="vm-compute-test_monitor_45000" on_node="cvmh01" on_node_uuid="cvmh01">
        <primitive id="vm-compute-test" class="ocf" provider="ccni" type="xcatVirtualDomain"/>
        <attributes CRM_meta_interval="45000" CRM_meta_name="monitor" CRM_meta_timeout="30000"  migration_network_suffix="-ib" migration_transport="ssh" nodename="compute-test"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="96" operation="start" operation_key="vm-compute-test_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="23">
    <action_set>
      <pseudo_event id="96" operation="start" operation_key="vm-compute-test_start_0">
        <attributes CRM_meta_name="start" CRM_meta_timeout="90000"  migration_network_suffix="-ib" migration_transport="ssh" nodename="compute-test"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="31" operation="load_stopped_cvmh01" operation_key="load_stopped_cvmh01"/>
      </trigger>
      <trigger>
        <rsc_op id="95" operation="stop" operation_key="vm-compute-test_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="24">
    <action_set>
      <rsc_op id="95" operation="stop" operation_key="vm-compute-test_stop_0" on_node="cvmh03" on_node_uuid="cvmh03">
        <primitive id="vm-compute-test" class="ocf" provider="ccni" type="xcatVirtualDomain"/>
        <attributes CRM_meta_name="stop" CRM_meta_timeout="90000"  migration_network_suffix="-ib" migration_transport="ssh" nodename="compute-test"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="113" operation="migrate_from" operation_key="vm-compute-test_migrate_from_0" on_node="cvmh01" on_node_uuid="cvmh01"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="25" priority="1000000">
    <action_set>
      <rsc_op id="115" operation="migrate_from" operation_key="vm-swbuildsl6_migrate_from_0" on_node="cvmh02" on_node_uuid="cvmh02">
        <primitive id="vm-swbuildsl6" class="ocf" provider="ccni" type="xcatVirtualDomain"/>
        <attributes CRM_meta_migrate_source="cvmh04" CRM_meta_migrate_target="cvmh02" CRM_meta_timeout="20000"  migration_network_suffix="-ib" migration_transport="ssh" nodename="swbuildsl6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="114" operation="migrate_to" operation_key="vm-swbuildsl6_migrate_to_0" on_node="cvmh04" on_node_uuid="cvmh04"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="26">
    <action_set>
      <rsc_op id="114" operation="migrate_to" operation_key="vm-swbuildsl6_migrate_to_0" on_node="cvmh04" on_node_uuid="cvmh04">
        <primitive id="vm-swbuildsl6" class="ocf" provider="ccni" type="xcatVirtualDomain"/>
        <attributes CRM_meta_migrate_source="cvmh04" CRM_meta_migrate_target="cvmh02" CRM_meta_record_pending="true" CRM_meta_timeout="20000"  migration_network_suffix="-ib" migration_transport="ssh" nodename="swbuildsl6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="96" operation="start" operation_key="vm-compute-test_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="27">
    <action_set>
      <rsc_op id="100" operation="monitor" operation_key="vm-swbuildsl6_monitor_45000" on_node="cvmh02" on_node_uuid="cvmh02">
        <primitive id="vm-swbuildsl6" class="ocf" provider="ccni" type="xcatVirtualDomain"/>
        <attributes CRM_meta_interval="45000" CRM_meta_name="monitor" CRM_meta_timeout="30000"  migration_network_suffix="-ib" migration_transport="ssh" nodename="swbuildsl6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="99" operation="start" operation_key="vm-swbuildsl6_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="28">
    <action_set>
      <pseudo_event id="99" operation="start" operation_key="vm-swbuildsl6_start_0">
        <attributes CRM_meta_name="start" CRM_meta_timeout="90000"  migration_network_suffix="-ib" migration_transport="ssh" nodename="swbuildsl6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="29" operation="load_stopped_cvmh02" operation_key="load_stopped_cvmh02"/>
      </trigger>
      <trigger>
        <pseudo_event id="96" operation="start" operation_key="vm-compute-test_start_0"/>
      </trigger>
      <trigger>
        <rsc_op id="98" operation="stop" operation_key="vm-swbuildsl6_stop_0" on_node="cvmh04" on_node_uuid="cvmh04"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="29">
    <action_set>
      <rsc_op id="98" operation="stop" operation_key="vm-swbuildsl6_stop_0" on_node="cvmh04" on_node_uuid="cvmh04">
        <primitive id="vm-swbuildsl6" class="ocf" provider="ccni" type="xcatVirtualDomain"/>
        <attributes CRM_meta_name="stop" CRM_meta_timeout="90000"  migration_network_suffix="-ib" migration_transport="ssh" nodename="swbuildsl6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="115" operation="migrate_from" operation_key="vm-swbuildsl6_migrate_from_0" on_node="cvmh02" on_node_uuid="cvmh02"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="30">
    <action_set>
      <pseudo_event id="31" operation="load_stopped_cvmh01" operation_key="load_stopped_cvmh01">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="31">
    <action_set>
      <pseudo_event id="30" operation="load_stopped_cvmh04" operation_key="load_stopped_cvmh04">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="98" operation="stop" operation_key="vm-swbuildsl6_stop_0" on_node="cvmh04" on_node_uuid="cvmh04"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="32">
    <action_set>
      <pseudo_event id="29" operation="load_stopped_cvmh02" operation_key="load_stopped_cvmh02">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="33">
    <action_set>
      <pseudo_event id="28" operation="load_stopped_cvmh03" operation_key="load_stopped_cvmh03">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="95" operation="stop" operation_key="vm-compute-test_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="34">
    <action_set>
      <pseudo_event id="27" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="37" operation="stop" operation_key="fs-libvirt-VM-xcm_stop_0" internal_operation_key="fs-libvirt-VM-xcm:0_stop_0" on_node="cvmh04" on_node_uuid="cvmh04"/>
      </trigger>
      <trigger>
        <rsc_op id="40" operation="stop" operation_key="fs-libvirt-VM-xcm_stop_0" internal_operation_key="fs-libvirt-VM-xcm:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
      <trigger>
        <rsc_op id="47" operation="stop" operation_key="p-watch-ib0_stop_0" internal_operation_key="p-watch-ib0:0_stop_0" on_node="cvmh04" on_node_uuid="cvmh04"/>
      </trigger>
      <trigger>
        <rsc_op id="50" operation="stop" operation_key="p-watch-ib0_stop_0" internal_operation_key="p-watch-ib0:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
      <trigger>
        <rsc_op id="57" operation="stop" operation_key="p-fs-gpfs_stop_0" internal_operation_key="p-fs-gpfs:0_stop_0" on_node="cvmh04" on_node_uuid="cvmh04"/>
      </trigger>
      <trigger>
        <rsc_op id="60" operation="stop" operation_key="p-fs-gpfs_stop_0" internal_operation_key="p-fs-gpfs:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
      <trigger>
        <rsc_op id="75" operation="stop" operation_key="p-libvirtd_stop_0" internal_operation_key="p-libvirtd:0_stop_0" on_node="cvmh04" on_node_uuid="cvmh04"/>
      </trigger>
      <trigger>
        <rsc_op id="78" operation="stop" operation_key="p-libvirtd_stop_0" internal_operation_key="p-libvirtd:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
      <trigger>
        <rsc_op id="85" operation="stop" operation_key="fs-bind-libvirt-VM-cvmh_stop_0" internal_operation_key="fs-bind-libvirt-VM-cvmh:0_stop_0" on_node="cvmh04" on_node_uuid="cvmh04"/>
      </trigger>
      <trigger>
        <rsc_op id="88" operation="stop" operation_key="fs-bind-libvirt-VM-cvmh_stop_0" internal_operation_key="fs-bind-libvirt-VM-cvmh:2_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
      <trigger>
        <rsc_op id="95" operation="stop" operation_key="vm-compute-test_stop_0" on_node="cvmh03" on_node_uuid="cvmh03"/>
      </trigger>
      <trigger>
        <rsc_op id="98" operation="stop" operation_key="vm-swbuildsl6_stop_0" on_node="cvmh04" on_node_uuid="cvmh04"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>
