<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="1" batch-limit="10" transition_id="0">
  <synapse id="0">
    <action_set>
      <pseudo_event id="24" operation="stop" operation_key="FencingChild:0_stop_0">
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_name="stop" CRM_meta_notify="false" CRM_meta_timeout="180000" crm_feature_set="3.0.6" pcmk_arg_map="domain:uname"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="33" operation="stop" operation_key="Fencing_stop_0"/>
      </trigger>
      <trigger>
        <crm_event id="95" operation="stonith" operation_key="stonith-pcmk-4" on_node="pcmk-4" on_node_uuid="pcmk-4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1" priority="1000000">
    <action_set>
      <pseudo_event id="34" operation="stopped" operation_key="Fencing_stopped_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="24" operation="stop" operation_key="FencingChild:0_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="33" operation="stop" operation_key="Fencing_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <pseudo_event id="33" operation="stop" operation_key="Fencing_stop_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <crm_event id="95" operation="stonith" operation_key="stonith-pcmk-4" on_node="pcmk-4" on_node_uuid="pcmk-4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <pseudo_event id="47" operation="stopped" operation_key="group-1_stopped_0">
        <attributes CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="35" operation="stop" operation_key="r192.168.101.181_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="38" operation="stop" operation_key="r192.168.101.182_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="stop" operation_key="r192.168.101.183_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="46" operation="stop" operation_key="group-1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <pseudo_event id="46" operation="stop" operation_key="group-1_stop_0">
        <attributes CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="57" operation="stop" operation_key="lsb-dummy_stop_0"/>
      </trigger>
      <trigger>
        <crm_event id="95" operation="stonith" operation_key="stonith-pcmk-4" on_node="pcmk-4" on_node_uuid="pcmk-4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <pseudo_event id="45" operation="running" operation_key="group-1_running_0">
        <attributes CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="36" operation="start" operation_key="r192.168.101.181_start_0" on_node="pcmk-1" on_node_uuid="pcmk-1"/>
      </trigger>
      <trigger>
        <rsc_op id="39" operation="start" operation_key="r192.168.101.182_start_0" on_node="pcmk-1" on_node_uuid="pcmk-1"/>
      </trigger>
      <trigger>
        <rsc_op id="42" operation="start" operation_key="r192.168.101.183_start_0" on_node="pcmk-1" on_node_uuid="pcmk-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="44" operation="start" operation_key="group-1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <pseudo_event id="44" operation="start" operation_key="group-1_start_0">
        <attributes CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="47" operation="stopped" operation_key="group-1_stopped_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="91" operation="promoted" operation_key="master-1_promoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <rsc_op id="37" operation="monitor" operation_key="r192.168.101.181_monitor_5000" on_node="pcmk-1" on_node_uuid="pcmk-1">
        <primitive id="r192.168.101.181" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_timeout="60000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.101.181"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="36" operation="start" operation_key="r192.168.101.181_start_0" on_node="pcmk-1" on_node_uuid="pcmk-1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <rsc_op id="36" operation="start" operation_key="r192.168.101.181_start_0" on_node="pcmk-1" on_node_uuid="pcmk-1">
        <primitive id="r192.168.101.181" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="60000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.101.181"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="35" operation="stop" operation_key="r192.168.101.181_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="44" operation="start" operation_key="group-1_start_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="94" operation="stonith_complete" operation_key="stonith_complete"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9">
    <action_set>
      <pseudo_event id="35" operation="stop" operation_key="r192.168.101.181_stop_0">
        <attributes CRM_meta_timeout="60000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.101.181"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="38" operation="stop" operation_key="r192.168.101.182_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="46" operation="stop" operation_key="group-1_stop_0"/>
      </trigger>
      <trigger>
        <crm_event id="95" operation="stonith" operation_key="stonith-pcmk-4" on_node="pcmk-4" on_node_uuid="pcmk-4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="10">
    <action_set>
      <rsc_op id="40" operation="monitor" operation_key="r192.168.101.182_monitor_5000" on_node="pcmk-1" on_node_uuid="pcmk-1">
        <primitive id="r192.168.101.182" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_timeout="60000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.101.182"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="39" operation="start" operation_key="r192.168.101.182_start_0" on_node="pcmk-1" on_node_uuid="pcmk-1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="11">
    <action_set>
      <rsc_op id="39" operation="start" operation_key="r192.168.101.182_start_0" on_node="pcmk-1" on_node_uuid="pcmk-1">
        <primitive id="r192.168.101.182" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="60000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.101.182"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="36" operation="start" operation_key="r192.168.101.181_start_0" on_node="pcmk-1" on_node_uuid="pcmk-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="38" operation="stop" operation_key="r192.168.101.182_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="44" operation="start" operation_key="group-1_start_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="94" operation="stonith_complete" operation_key="stonith_complete"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="12">
    <action_set>
      <pseudo_event id="38" operation="stop" operation_key="r192.168.101.182_stop_0">
        <attributes CRM_meta_timeout="60000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.101.182"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="41" operation="stop" operation_key="r192.168.101.183_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="46" operation="stop" operation_key="group-1_stop_0"/>
      </trigger>
      <trigger>
        <crm_event id="95" operation="stonith" operation_key="stonith-pcmk-4" on_node="pcmk-4" on_node_uuid="pcmk-4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="13">
    <action_set>
      <rsc_op id="43" operation="monitor" operation_key="r192.168.101.183_monitor_5000" on_node="pcmk-1" on_node_uuid="pcmk-1">
        <primitive id="r192.168.101.183" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_timeout="60000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.101.183"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="42" operation="start" operation_key="r192.168.101.183_start_0" on_node="pcmk-1" on_node_uuid="pcmk-1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="14">
    <action_set>
      <rsc_op id="42" operation="start" operation_key="r192.168.101.183_start_0" on_node="pcmk-1" on_node_uuid="pcmk-1">
        <primitive id="r192.168.101.183" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="60000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.101.183"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="39" operation="start" operation_key="r192.168.101.182_start_0" on_node="pcmk-1" on_node_uuid="pcmk-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="stop" operation_key="r192.168.101.183_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="44" operation="start" operation_key="group-1_start_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="94" operation="stonith_complete" operation_key="stonith_complete"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="15">
    <action_set>
      <pseudo_event id="41" operation="stop" operation_key="r192.168.101.183_stop_0">
        <attributes CRM_meta_timeout="60000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.101.183"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="46" operation="stop" operation_key="group-1_stop_0"/>
      </trigger>
      <trigger>
        <crm_event id="95" operation="stonith" operation_key="stonith-pcmk-4" on_node="pcmk-4" on_node_uuid="pcmk-4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="16">
    <action_set>
      <rsc_op id="56" operation="monitor" operation_key="rsc_pcmk-4_monitor_5000" on_node="pcmk-2" on_node_uuid="pcmk-2">
        <primitive id="rsc_pcmk-4" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_timeout="60000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.101.187"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="55" operation="start" operation_key="rsc_pcmk-4_start_0" on_node="pcmk-2" on_node_uuid="pcmk-2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="17">
    <action_set>
      <rsc_op id="55" operation="start" operation_key="rsc_pcmk-4_start_0" on_node="pcmk-2" on_node_uuid="pcmk-2">
        <primitive id="rsc_pcmk-4" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="60000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.101.187"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="54" operation="stop" operation_key="rsc_pcmk-4_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="94" operation="stonith_complete" operation_key="stonith_complete"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="18">
    <action_set>
      <pseudo_event id="54" operation="stop" operation_key="rsc_pcmk-4_stop_0">
        <attributes CRM_meta_timeout="60000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.101.187"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <crm_event id="95" operation="stonith" operation_key="stonith-pcmk-4" on_node="pcmk-4" on_node_uuid="pcmk-4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="19">
    <action_set>
      <rsc_op id="59" operation="monitor" operation_key="lsb-dummy_monitor_5000" on_node="pcmk-1" on_node_uuid="pcmk-1">
        <primitive id="lsb-dummy" class="lsb" type="/usr/share/pacemaker/tests/cts/LSBDummy"/>
        <attributes CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="58" operation="start" operation_key="lsb-dummy_start_0" on_node="pcmk-1" on_node_uuid="pcmk-1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="20">
    <action_set>
      <rsc_op id="58" operation="start" operation_key="lsb-dummy_start_0" on_node="pcmk-1" on_node_uuid="pcmk-1">
        <primitive id="lsb-dummy" class="lsb" type="/usr/share/pacemaker/tests/cts/LSBDummy"/>
        <attributes CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="45" operation="running" operation_key="group-1_running_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="57" operation="stop" operation_key="lsb-dummy_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="94" operation="stonith_complete" operation_key="stonith_complete"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="21">
    <action_set>
      <pseudo_event id="57" operation="stop" operation_key="lsb-dummy_stop_0">
        <attributes CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <crm_event id="95" operation="stonith" operation_key="stonith-pcmk-4" on_node="pcmk-4" on_node_uuid="pcmk-4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="22" priority="1000000">
    <action_set>
      <rsc_op id="106" operation="migrate_from" operation_key="migrator_migrate_from_0" on_node="pcmk-3" on_node_uuid="pcmk-3">
        <primitive id="migrator" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_migrate_source="pcmk-1" CRM_meta_migrate_target="pcmk-3" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="105" operation="migrate_to" operation_key="migrator_migrate_to_0" on_node="pcmk-1" on_node_uuid="pcmk-1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="23">
    <action_set>
      <rsc_op id="105" operation="migrate_to" operation_key="migrator_migrate_to_0" on_node="pcmk-1" on_node_uuid="pcmk-1">
        <primitive id="migrator" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_migrate_source="pcmk-1" CRM_meta_migrate_target="pcmk-3" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="94" operation="stonith_complete" operation_key="stonith_complete"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="24">
    <action_set>
      <rsc_op id="62" operation="monitor" operation_key="migrator_monitor_10000" on_node="pcmk-3" on_node_uuid="pcmk-3">
        <primitive id="migrator" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="61" operation="start" operation_key="migrator_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="25">
    <action_set>
      <pseudo_event id="61" operation="start" operation_key="migrator_start_0">
        <attributes CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="60" operation="stop" operation_key="migrator_stop_0" on_node="pcmk-1" on_node_uuid="pcmk-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="94" operation="stonith_complete" operation_key="stonith_complete"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="26">
    <action_set>
      <rsc_op id="60" operation="stop" operation_key="migrator_stop_0" on_node="pcmk-1" on_node_uuid="pcmk-1">
        <primitive id="migrator" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="106" operation="migrate_from" operation_key="migrator_migrate_from_0" on_node="pcmk-3" on_node_uuid="pcmk-3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="27">
    <action_set>
      <pseudo_event id="63" operation="stop" operation_key="ping-1:0_stop_0">
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6" debug="true" host_list="192.168.9.161" name="connected"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="72" operation="stop" operation_key="Connectivity_stop_0"/>
      </trigger>
      <trigger>
        <crm_event id="95" operation="stonith" operation_key="stonith-pcmk-4" on_node="pcmk-4" on_node_uuid="pcmk-4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="28" priority="1000000">
    <action_set>
      <pseudo_event id="73" operation="stopped" operation_key="Connectivity_stopped_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="63" operation="stop" operation_key="ping-1:0_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="72" operation="stop" operation_key="Connectivity_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="29">
    <action_set>
      <pseudo_event id="72" operation="stop" operation_key="Connectivity_stop_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <crm_event id="95" operation="stonith" operation_key="stonith-pcmk-4" on_node="pcmk-4" on_node_uuid="pcmk-4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="30">
    <action_set>
      <pseudo_event id="75" operation="stop" operation_key="stateful-1:0_stop_0">
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="74" operation="demote" operation_key="stateful-1:0_demote_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="88" operation="stop" operation_key="master-1_stop_0"/>
      </trigger>
      <trigger>
        <crm_event id="95" operation="stonith" operation_key="stonith-pcmk-4" on_node="pcmk-4" on_node_uuid="pcmk-4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="31">
    <action_set>
      <pseudo_event id="74" operation="demote" operation_key="stateful-1:0_demote_0">
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="92" operation="demote" operation_key="master-1_demote_0"/>
      </trigger>
      <trigger>
        <crm_event id="95" operation="stonith" operation_key="stonith-pcmk-4" on_node="pcmk-4" on_node_uuid="pcmk-4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="32">
    <action_set>
      <rsc_op id="79" operation="monitor" operation_key="stateful-1:1_monitor_16000" on_node="pcmk-1" on_node_uuid="pcmk-1">
        <primitive id="stateful-1" long-id="stateful-1:1" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="16000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_op_target_rc="8" CRM_meta_role="Master" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="78" operation="promote" operation_key="stateful-1:1_promote_0" on_node="pcmk-1" on_node_uuid="pcmk-1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="33">
    <action_set>
      <rsc_op id="78" operation="promote" operation_key="stateful-1:1_promote_0" on_node="pcmk-1" on_node_uuid="pcmk-1">
        <primitive id="stateful-1" long-id="stateful-1:1" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="90" operation="promote" operation_key="master-1_promote_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="94" operation="stonith_complete" operation_key="stonith_complete"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="34">
    <action_set>
      <rsc_op id="82" operation="monitor" operation_key="stateful-1:3_monitor_15000" internal_operation_key="stateful-1:2_monitor_15000" on_node="pcmk-3" on_node_uuid="pcmk-3">
        <primitive id="stateful-1" long-id="stateful-1:3" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="15000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="35">
    <action_set>
      <rsc_op id="85" operation="monitor" operation_key="stateful-1:2_monitor_15000" internal_operation_key="stateful-1:3_monitor_15000" on_node="pcmk-2" on_node_uuid="pcmk-2">
        <primitive id="stateful-1" long-id="stateful-1:2" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="15000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="36" priority="1000000">
    <action_set>
      <pseudo_event id="93" operation="demoted" operation_key="master-1_demoted_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="74" operation="demote" operation_key="stateful-1:0_demote_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="92" operation="demote" operation_key="master-1_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="37">
    <action_set>
      <pseudo_event id="92" operation="demote" operation_key="master-1_demote_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="47" operation="stopped" operation_key="group-1_stopped_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="38" priority="1000000">
    <action_set>
      <pseudo_event id="91" operation="promoted" operation_key="master-1_promoted_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="78" operation="promote" operation_key="stateful-1:1_promote_0" on_node="pcmk-1" on_node_uuid="pcmk-1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="39">
    <action_set>
      <pseudo_event id="90" operation="promote" operation_key="master-1_promote_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="89" operation="stopped" operation_key="master-1_stopped_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="93" operation="demoted" operation_key="master-1_demoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="40" priority="1000000">
    <action_set>
      <pseudo_event id="89" operation="stopped" operation_key="master-1_stopped_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="75" operation="stop" operation_key="stateful-1:0_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="88" operation="stop" operation_key="master-1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="41">
    <action_set>
      <pseudo_event id="88" operation="stop" operation_key="master-1_stop_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="93" operation="demoted" operation_key="master-1_demoted_0"/>
      </trigger>
      <trigger>
        <crm_event id="95" operation="stonith" operation_key="stonith-pcmk-4" on_node="pcmk-4" on_node_uuid="pcmk-4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="42">
    <action_set>
      <crm_event id="95" operation="stonith" operation_key="stonith-pcmk-4" on_node="pcmk-4" on_node_uuid="pcmk-4">
        <attributes CRM_meta_connected="1" CRM_meta_on_node="pcmk-4" CRM_meta_on_node_uuid="pcmk-4" CRM_meta_op_no_wait="true" CRM_meta_probe_complete="true" CRM_meta_standby="off" CRM_meta_stonith_action="reboot" CRM_meta_terminate="1" crm_feature_set="3.0.6"/>
      </crm_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="43">
    <action_set>
      <pseudo_event id="94" operation="stonith_complete" operation_key="stonith_complete">
        <attributes crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <crm_event id="95" operation="stonith" operation_key="stonith-pcmk-4" on_node="pcmk-4" on_node_uuid="pcmk-4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="44">
    <action_set>
      <pseudo_event id="19" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="24" operation="stop" operation_key="FencingChild:0_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="35" operation="stop" operation_key="r192.168.101.181_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="38" operation="stop" operation_key="r192.168.101.182_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="stop" operation_key="r192.168.101.183_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="54" operation="stop" operation_key="rsc_pcmk-4_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="57" operation="stop" operation_key="lsb-dummy_stop_0"/>
      </trigger>
      <trigger>
        <rsc_op id="60" operation="stop" operation_key="migrator_stop_0" on_node="pcmk-1" on_node_uuid="pcmk-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="63" operation="stop" operation_key="ping-1:0_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="75" operation="stop" operation_key="stateful-1:0_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="94" operation="stonith_complete" operation_key="stonith_complete"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

