<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <pseudo_event id="3" operation="load_stopped_hex-14" operation_key="load_stopped_hex-14">
        <attributes crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="1">
    <action_set>
      <pseudo_event id="2" operation="load_stopped_hex-13" operation_key="load_stopped_hex-13">
        <attributes crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
</transition_graph>

