<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="1" batch-limit="10" transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="22" operation="stop" operation_key="Fencing_stop_0" on_node="pcmk-1" on_node_uuid="101">
        <primitive id="Fencing" class="stonith" type="fence_xvm"/>
        <attributes CRM_meta_name="stop" CRM_meta_timeout="180000" crm_feature_set="3.0.6" pcmk_arg_map="domain:uname"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="16" operation="all_stopped" operation_key="all_stopped"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <pseudo_event id="29" operation="stopped" operation_key="group-1_stopped_0">
        <attributes CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="23" operation="stop" operation_key="r192.168.122.105_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <rsc_op id="24" operation="stop" operation_key="r192.168.122.106_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <rsc_op id="25" operation="stop" operation_key="r192.168.122.107_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <pseudo_event id="28" operation="stop" operation_key="group-1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <pseudo_event id="28" operation="stop" operation_key="group-1_stop_0">
        <attributes CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="33" operation="stop" operation_key="lsb-dummy_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <rsc_op id="23" operation="stop" operation_key="r192.168.122.105_stop_0" on_node="pcmk-2" on_node_uuid="102">
        <primitive id="r192.168.122.105" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="60000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.122.105"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="24" operation="stop" operation_key="r192.168.122.106_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <pseudo_event id="28" operation="stop" operation_key="group-1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <rsc_op id="24" operation="stop" operation_key="r192.168.122.106_stop_0" on_node="pcmk-2" on_node_uuid="102">
        <primitive id="r192.168.122.106" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="60000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.122.106"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="25" operation="stop" operation_key="r192.168.122.107_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <pseudo_event id="28" operation="stop" operation_key="group-1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <rsc_op id="25" operation="stop" operation_key="r192.168.122.107_stop_0" on_node="pcmk-2" on_node_uuid="102">
        <primitive id="r192.168.122.107" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="60000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.122.107"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="28" operation="stop" operation_key="group-1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <rsc_op id="30" operation="stop" operation_key="rsc_pcmk-1_stop_0" on_node="pcmk-1" on_node_uuid="101">
        <primitive id="rsc_pcmk-1" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="60000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.122.108"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="7">
    <action_set>
      <rsc_op id="31" operation="stop" operation_key="rsc_pcmk-2_stop_0" on_node="pcmk-2" on_node_uuid="102">
        <primitive id="rsc_pcmk-2" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="60000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.122.109"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="8">
    <action_set>
      <rsc_op id="32" operation="stop" operation_key="rsc_pcmk-4_stop_0" on_node="pcmk-4" on_node_uuid="104">
        <primitive id="rsc_pcmk-4" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="60000" cidr_netmask="32" crm_feature_set="3.0.6" ip="192.168.122.111"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="9">
    <action_set>
      <rsc_op id="33" operation="stop" operation_key="lsb-dummy_stop_0" on_node="pcmk-2" on_node_uuid="102">
        <primitive id="lsb-dummy" class="lsb" type="/usr/share/pacemaker/tests/cts/LSBDummy"/>
        <attributes CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="10">
    <action_set>
      <rsc_op id="35" operation="stop" operation_key="migrator_stop_0" on_node="pcmk-1" on_node_uuid="101">
        <primitive id="migrator" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="11">
    <action_set>
      <rsc_op id="34" operation="stop" operation_key="migrator_stop_0" on_node="pcmk-3" on_node_uuid="103">
        <primitive id="migrator" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="12">
    <action_set>
      <rsc_op id="36" operation="stop" operation_key="ping-1:0_stop_0" on_node="pcmk-1" on_node_uuid="101">
        <primitive id="ping-1:0" class="ocf" provider="pacemaker" type="ping"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6" debug="true" host_list="10.0.0.6" name="connected"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="41" operation="stop" operation_key="Connectivity_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="13">
    <action_set>
      <rsc_op id="37" operation="stop" operation_key="ping-1:1_stop_0" on_node="pcmk-2" on_node_uuid="102">
        <primitive id="ping-1:1" class="ocf" provider="pacemaker" type="ping"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6" debug="true" host_list="10.0.0.6" name="connected"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="41" operation="stop" operation_key="Connectivity_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="14">
    <action_set>
      <rsc_op id="38" operation="stop" operation_key="ping-1:3_stop_0" on_node="pcmk-4" on_node_uuid="104">
        <primitive id="ping-1:3" class="ocf" provider="pacemaker" type="ping"/>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6" debug="true" host_list="10.0.0.6" name="connected"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="41" operation="stop" operation_key="Connectivity_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="15" priority="1000000">
    <action_set>
      <pseudo_event id="42" operation="stopped" operation_key="Connectivity_stopped_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="36" operation="stop" operation_key="ping-1:0_stop_0" on_node="pcmk-1" on_node_uuid="101"/>
      </trigger>
      <trigger>
        <rsc_op id="37" operation="stop" operation_key="ping-1:1_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <rsc_op id="38" operation="stop" operation_key="ping-1:3_stop_0" on_node="pcmk-4" on_node_uuid="104"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="stop" operation_key="Connectivity_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="16">
    <action_set>
      <pseudo_event id="41" operation="stop" operation_key="Connectivity_stop_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="17">
    <action_set>
      <rsc_op id="44" operation="stop" operation_key="stateful-1:0_stop_0" on_node="pcmk-2" on_node_uuid="102">
        <primitive id="stateful-1:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="43" operation="demote" operation_key="stateful-1:0_demote_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <pseudo_event id="49" operation="stop" operation_key="master-1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="18">
    <action_set>
      <rsc_op id="43" operation="demote" operation_key="stateful-1:0_demote_0" on_node="pcmk-2" on_node_uuid="102">
        <primitive id="stateful-1:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="53" operation="demote" operation_key="master-1_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="19">
    <action_set>
      <rsc_op id="45" operation="stop" operation_key="stateful-1:2_stop_0" on_node="pcmk-1" on_node_uuid="101">
        <primitive id="stateful-1:2" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="49" operation="stop" operation_key="master-1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="20">
    <action_set>
      <rsc_op id="46" operation="stop" operation_key="stateful-1:3_stop_0" on_node="pcmk-4" on_node_uuid="104">
        <primitive id="stateful-1:3" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="49" operation="stop" operation_key="master-1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="21" priority="1000000">
    <action_set>
      <pseudo_event id="54" operation="demoted" operation_key="master-1_demoted_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="43" operation="demote" operation_key="stateful-1:0_demote_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <pseudo_event id="53" operation="demote" operation_key="master-1_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="22">
    <action_set>
      <pseudo_event id="53" operation="demote" operation_key="master-1_demote_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="29" operation="stopped" operation_key="group-1_stopped_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="23" priority="1000000">
    <action_set>
      <pseudo_event id="50" operation="stopped" operation_key="master-1_stopped_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="44" operation="stop" operation_key="stateful-1:0_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <rsc_op id="45" operation="stop" operation_key="stateful-1:2_stop_0" on_node="pcmk-1" on_node_uuid="101"/>
      </trigger>
      <trigger>
        <rsc_op id="46" operation="stop" operation_key="stateful-1:3_stop_0" on_node="pcmk-4" on_node_uuid="104"/>
      </trigger>
      <trigger>
        <pseudo_event id="49" operation="stop" operation_key="master-1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="24">
    <action_set>
      <pseudo_event id="49" operation="stop" operation_key="master-1_stop_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="60000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="54" operation="demoted" operation_key="master-1_demoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="25">
    <action_set>
      <crm_event id="60" operation="do_shutdown" operation_key="do_shutdown" on_node="pcmk-4" on_node_uuid="104">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.6"/>
      </crm_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="32" operation="stop" operation_key="rsc_pcmk-4_stop_0" on_node="pcmk-4" on_node_uuid="104"/>
      </trigger>
      <trigger>
        <rsc_op id="38" operation="stop" operation_key="ping-1:3_stop_0" on_node="pcmk-4" on_node_uuid="104"/>
      </trigger>
      <trigger>
        <rsc_op id="46" operation="stop" operation_key="stateful-1:3_stop_0" on_node="pcmk-4" on_node_uuid="104"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="26">
    <action_set>
      <crm_event id="59" operation="do_shutdown" operation_key="do_shutdown" on_node="pcmk-3" on_node_uuid="103">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.6"/>
      </crm_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="34" operation="stop" operation_key="migrator_stop_0" on_node="pcmk-3" on_node_uuid="103"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="27">
    <action_set>
      <crm_event id="58" operation="do_shutdown" operation_key="do_shutdown" on_node="pcmk-2" on_node_uuid="102">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.6"/>
      </crm_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="23" operation="stop" operation_key="r192.168.122.105_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <rsc_op id="24" operation="stop" operation_key="r192.168.122.106_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <rsc_op id="25" operation="stop" operation_key="r192.168.122.107_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <rsc_op id="31" operation="stop" operation_key="rsc_pcmk-2_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <rsc_op id="33" operation="stop" operation_key="lsb-dummy_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <rsc_op id="37" operation="stop" operation_key="ping-1:1_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <rsc_op id="44" operation="stop" operation_key="stateful-1:0_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="28">
    <action_set>
      <crm_event id="57" operation="do_shutdown" operation_key="do_shutdown" on_node="pcmk-1" on_node_uuid="101">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.6"/>
      </crm_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="22" operation="stop" operation_key="Fencing_stop_0" on_node="pcmk-1" on_node_uuid="101"/>
      </trigger>
      <trigger>
        <rsc_op id="30" operation="stop" operation_key="rsc_pcmk-1_stop_0" on_node="pcmk-1" on_node_uuid="101"/>
      </trigger>
      <trigger>
        <rsc_op id="35" operation="stop" operation_key="migrator_stop_0" on_node="pcmk-1" on_node_uuid="101"/>
      </trigger>
      <trigger>
        <rsc_op id="36" operation="stop" operation_key="ping-1:0_stop_0" on_node="pcmk-1" on_node_uuid="101"/>
      </trigger>
      <trigger>
        <rsc_op id="45" operation="stop" operation_key="stateful-1:2_stop_0" on_node="pcmk-1" on_node_uuid="101"/>
      </trigger>
      <trigger>
        <crm_event id="58" operation="do_shutdown" operation_key="do_shutdown" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <crm_event id="59" operation="do_shutdown" operation_key="do_shutdown" on_node="pcmk-3" on_node_uuid="103"/>
      </trigger>
      <trigger>
        <crm_event id="60" operation="do_shutdown" operation_key="do_shutdown" on_node="pcmk-4" on_node_uuid="104"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="29">
    <action_set>
      <pseudo_event id="16" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="23" operation="stop" operation_key="r192.168.122.105_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <rsc_op id="24" operation="stop" operation_key="r192.168.122.106_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <rsc_op id="25" operation="stop" operation_key="r192.168.122.107_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <rsc_op id="30" operation="stop" operation_key="rsc_pcmk-1_stop_0" on_node="pcmk-1" on_node_uuid="101"/>
      </trigger>
      <trigger>
        <rsc_op id="31" operation="stop" operation_key="rsc_pcmk-2_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <rsc_op id="32" operation="stop" operation_key="rsc_pcmk-4_stop_0" on_node="pcmk-4" on_node_uuid="104"/>
      </trigger>
      <trigger>
        <rsc_op id="33" operation="stop" operation_key="lsb-dummy_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <rsc_op id="34" operation="stop" operation_key="migrator_stop_0" on_node="pcmk-3" on_node_uuid="103"/>
      </trigger>
      <trigger>
        <rsc_op id="35" operation="stop" operation_key="migrator_stop_0" on_node="pcmk-1" on_node_uuid="101"/>
      </trigger>
      <trigger>
        <rsc_op id="36" operation="stop" operation_key="ping-1:0_stop_0" on_node="pcmk-1" on_node_uuid="101"/>
      </trigger>
      <trigger>
        <rsc_op id="37" operation="stop" operation_key="ping-1:1_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <rsc_op id="38" operation="stop" operation_key="ping-1:3_stop_0" on_node="pcmk-4" on_node_uuid="104"/>
      </trigger>
      <trigger>
        <rsc_op id="44" operation="stop" operation_key="stateful-1:0_stop_0" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
      <trigger>
        <rsc_op id="45" operation="stop" operation_key="stateful-1:2_stop_0" on_node="pcmk-1" on_node_uuid="101"/>
      </trigger>
      <trigger>
        <rsc_op id="46" operation="stop" operation_key="stateful-1:3_stop_0" on_node="pcmk-4" on_node_uuid="104"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

