<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="45" operation="monitor" operation_key="sle12-kvm_monitor_10000" on_node="kimball" on_node_uuid="178325681">
        <primitive id="sle12-kvm" class="ocf" provider="heartbeat" type="VirtualDomain"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_record_pending="true" CRM_meta_timeout="30000" CRM_meta_trace_ra="1" config="/etc/vm/sle12-kvm.xml"  migrate_options="--migrateuri=qemu+ssh://%n/system" migration_transport="ssh" save_config_on_stop="1" sync_config_on_stop="1" trace_ra="1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="44" operation="start" operation_key="sle12-kvm_start_0" on_node="kimball" on_node_uuid="178325681"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="44" operation="start" operation_key="sle12-kvm_start_0" on_node="kimball" on_node_uuid="178325681">
        <primitive id="sle12-kvm" class="ocf" provider="heartbeat" type="VirtualDomain"/>
        <attributes CRM_meta_name="start" CRM_meta_record_pending="true" CRM_meta_timeout="90000" CRM_meta_trace_ra="1" config="/etc/vm/sle12-kvm.xml"  migrate_options="--migrateuri=qemu+ssh://%n/system" migration_transport="ssh" save_config_on_stop="1" sync_config_on_stop="1" trace_ra="1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="9" operation="stop" operation_key="sle12-kvm_stop_0" on_node="castor" on_node_uuid="178325584"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="9" operation="stop" operation_key="sle12-kvm_stop_0" on_node="castor" on_node_uuid="178325584">
        <primitive id="sle12-kvm" class="ocf" provider="heartbeat" type="VirtualDomain"/>
        <attributes CRM_meta_name="stop" CRM_meta_record_pending="true" CRM_meta_timeout="90000" CRM_meta_trace_ra="1" config="/etc/vm/sle12-kvm.xml"  migrate_options="--migrateuri=qemu+ssh://%n/system" migration_transport="ssh" save_config_on_stop="1" sync_config_on_stop="1" trace_ra="1"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="3">
    <action_set>
      <pseudo_event id="10" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="9" operation="stop" operation_key="sle12-kvm_stop_0" on_node="castor" on_node_uuid="178325584"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>
