 <transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0" priority="1000000">
     <action_set>
      <rsc_op id="38" operation="notify" operation_key="child_rsc1:0_post_notify_start_0" on_node="node1" on_node_uuid="uuid1">
        <primitive id="child_rsc1:0" class="heartbeat" type="apache"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_notify_active_resource="child_rsc1:0 " CRM_meta_notify_active_uname="node1 " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource="child_rsc1:1 " CRM_meta_notify_key_operation="running" CRM_meta_notify_key_type="post" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="start" CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource="child_rsc1:1 " CRM_meta_notify_start_uname="node1 " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="post" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="13" operation="notify" operation_key="rsc1_post_notify_running_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="1">
     <action_set>
      <rsc_op id="37" operation="notify" operation_key="child_rsc1:0_pre_notify_start_0" on_node="node1" on_node_uuid="uuid1">
        <primitive id="child_rsc1:0" class="heartbeat" type="apache"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_notify_active_resource="child_rsc1:0 " CRM_meta_notify_active_uname="node1 " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource="child_rsc1:1 " CRM_meta_notify_key_operation="start" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="start" CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource="child_rsc1:1 " CRM_meta_notify_start_uname="node1 " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="pre" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="11" operation="notify" operation_key="rsc1_pre_notify_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="2" priority="1000000">
     <action_set>
      <rsc_op id="39" operation="notify" operation_key="child_rsc1:1_post_notify_start_0" on_node="node1" on_node_uuid="uuid1">
        <primitive id="child_rsc1:1" class="heartbeat" type="apache"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_notify_active_resource="child_rsc1:0 " CRM_meta_notify_active_uname="node1 " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource="child_rsc1:1 " CRM_meta_notify_key_operation="running" CRM_meta_notify_key_type="post" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="start" CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource="child_rsc1:1 " CRM_meta_notify_start_uname="node1 " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="post" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="13" operation="notify" operation_key="rsc1_post_notify_running_0"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="3">
     <action_set>
       <rsc_op id="8" operation="start" operation_key="child_rsc1:1_start_0" on_node="node1" on_node_uuid="uuid1">
        <primitive id="child_rsc1:1" class="heartbeat" type="apache"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_notify_active_resource="child_rsc1:0 " CRM_meta_notify_active_uname="node1 " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource="child_rsc1:1 " CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource="child_rsc1:1 " CRM_meta_notify_start_uname="node1 " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
       </trigger>
       <trigger>
         <pseudo_event id="9" operation="start" operation_key="rsc1_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="4">
     <action_set>
      <rsc_op id="4" operation="monitor" operation_key="child_rsc1:1_monitor_0" on_node="node1" on_node_uuid="uuid1">
        <primitive id="child_rsc1:1" class="heartbeat" type="apache"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
  <synapse id="5" priority="1000000">
     <action_set>
      <pseudo_event id="14" operation="notified" operation_key="rsc1_confirmed-post_notify_running_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_notify_key_operation="running" CRM_meta_notify_key_type="confirmed-post" CRM_meta_notify_operation="start" CRM_meta_notify_type="post" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="13" operation="notify" operation_key="rsc1_post_notify_running_0"/>
      </trigger>
      <trigger>
        <rsc_op id="38" operation="notify" operation_key="child_rsc1:0_post_notify_start_0" on_node="node1" on_node_uuid="uuid1"/>
      </trigger>
      <trigger>
        <rsc_op id="39" operation="notify" operation_key="child_rsc1:1_post_notify_start_0" on_node="node1" on_node_uuid="uuid1"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="6" priority="1000000">
     <action_set>
      <pseudo_event id="13" operation="notify" operation_key="rsc1_post_notify_running_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_notify_key_operation="running" CRM_meta_notify_key_type="post" CRM_meta_notify_operation="start" CRM_meta_notify_type="post" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="10" operation="running" operation_key="rsc1_running_0"/>
       </trigger>
       <trigger>
        <pseudo_event id="12" operation="notified" operation_key="rsc1_confirmed-pre_notify_start_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="7">
     <action_set>
       <pseudo_event id="12" operation="notified" operation_key="rsc1_confirmed-pre_notify_start_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_notify_key_operation="start" CRM_meta_notify_key_type="confirmed-pre" CRM_meta_notify_operation="start" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="11" operation="notify" operation_key="rsc1_pre_notify_start_0"/>
       </trigger>
       <trigger>
        <rsc_op id="37" operation="notify" operation_key="child_rsc1:0_pre_notify_start_0" on_node="node1" on_node_uuid="uuid1"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="8">
    <action_set>
      <pseudo_event id="11" operation="notify" operation_key="rsc1_pre_notify_start_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_notify_key_operation="start" CRM_meta_notify_key_type="pre" CRM_meta_notify_operation="start" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
   <synapse id="9" priority="1000000">
     <action_set>
      <pseudo_event id="10" operation="running" operation_key="rsc1_running_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="8" operation="start" operation_key="child_rsc1:1_start_0" on_node="node1" on_node_uuid="uuid1"/>
       </trigger>
      <trigger>
        <pseudo_event id="9" operation="start" operation_key="rsc1_start_0"/>
      </trigger>
     </inputs>
   </synapse>
  <synapse id="10">
     <action_set>
      <pseudo_event id="9" operation="start" operation_key="rsc1_start_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="12" operation="notified" operation_key="rsc1_confirmed-pre_notify_start_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="11">
     <action_set>
      <rsc_op id="42" operation="notify" operation_key="child_rsc2:0_pre_notify_stop_0" on_node="node1" on_node_uuid="uuid1">
        <primitive id="child_rsc2:0" class="heartbeat" type="apache"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_notify_active_resource="child_rsc2:0 " CRM_meta_notify_active_uname="node1 " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource="child_rsc2:1 " CRM_meta_notify_key_operation="stop" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="stop" CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource="child_rsc2:0 " CRM_meta_notify_stop_uname="node1 " CRM_meta_notify_type="pre" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="30" operation="notify" operation_key="rsc2_pre_notify_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="12">
     <action_set>
      <rsc_op id="21" operation="stop" operation_key="child_rsc2:0_stop_0" on_node="node1" on_node_uuid="uuid1">
        <primitive id="child_rsc2:0" class="heartbeat" type="apache"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_notify_active_resource="child_rsc2:0 " CRM_meta_notify_active_uname="node1 " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource="child_rsc2:1 " CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource="child_rsc2:0 " CRM_meta_notify_stop_uname="node1 " CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="28" operation="stop" operation_key="rsc2_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="13">
     <action_set>
       <rsc_op id="5" operation="monitor" operation_key="child_rsc2:1_monitor_0" on_node="node1" on_node_uuid="uuid1">
        <primitive id="child_rsc2:1" class="heartbeat" type="apache"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="14" priority="1000000">
     <action_set>
      <pseudo_event id="33" operation="notified" operation_key="rsc2_confirmed-post_notify_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_notify_key_operation="stopped" CRM_meta_notify_key_type="confirmed-post" CRM_meta_notify_operation="stop" CRM_meta_notify_type="post" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="32" operation="notify" operation_key="rsc2_post_notify_stopped_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="15" priority="1000000">
     <action_set>
      <pseudo_event id="32" operation="notify" operation_key="rsc2_post_notify_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_notify_key_operation="stopped" CRM_meta_notify_key_type="post" CRM_meta_notify_operation="stop" CRM_meta_notify_type="post" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="29" operation="stopped" operation_key="rsc2_stopped_0"/>
       </trigger>
       <trigger>
        <pseudo_event id="31" operation="notified" operation_key="rsc2_confirmed-pre_notify_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="16">
     <action_set>
       <pseudo_event id="31" operation="notified" operation_key="rsc2_confirmed-pre_notify_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_notify_key_operation="stop" CRM_meta_notify_key_type="confirmed-pre" CRM_meta_notify_operation="stop" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="30" operation="notify" operation_key="rsc2_pre_notify_stop_0"/>
       </trigger>
       <trigger>
        <rsc_op id="42" operation="notify" operation_key="child_rsc2:0_pre_notify_stop_0" on_node="node1" on_node_uuid="uuid1"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="17">
    <action_set>
      <pseudo_event id="30" operation="notify" operation_key="rsc2_pre_notify_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_notify_key_operation="stop" CRM_meta_notify_key_type="pre" CRM_meta_notify_operation="stop" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
   <synapse id="18" priority="1000000">
     <action_set>
      <pseudo_event id="29" operation="stopped" operation_key="rsc2_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="21" operation="stop" operation_key="child_rsc2:0_stop_0" on_node="node1" on_node_uuid="uuid1"/>
       </trigger>
      <trigger>
        <pseudo_event id="28" operation="stop" operation_key="rsc2_stop_0"/>
      </trigger>
     </inputs>
   </synapse>
  <synapse id="19">
     <action_set>
      <pseudo_event id="28" operation="stop" operation_key="rsc2_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="2" CRM_meta_globally_unique="true" CRM_meta_notify="true" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="31" operation="notified" operation_key="rsc2_confirmed-pre_notify_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="20" priority="1000000">
     <action_set>
      <rsc_op id="3" operation="probe_complete" operation_key="probe_complete" on_node="node1" on_node_uuid="uuid1">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.7"/>
      </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="4" operation="monitor" operation_key="child_rsc1:1_monitor_0" on_node="node1" on_node_uuid="uuid1"/>
       </trigger>
      <trigger>
        <rsc_op id="5" operation="monitor" operation_key="child_rsc2:1_monitor_0" on_node="node1" on_node_uuid="uuid1"/>
      </trigger>
     </inputs>
   </synapse>
   <synapse id="21">
     <action_set>
       <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete">
        <attributes crm_feature_set="3.0.7"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <rsc_op id="3" operation="probe_complete" operation_key="probe_complete" on_node="node1" on_node_uuid="uuid1"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="22">
     <action_set>
      <pseudo_event id="1" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.7"/>
      </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="21" operation="stop" operation_key="child_rsc2:0_stop_0" on_node="node1" on_node_uuid="uuid1"/>
       </trigger>
       <trigger>
        <pseudo_event id="33" operation="notified" operation_key="rsc2_confirmed-post_notify_stopped_0"/>
       </trigger>
     </inputs>
   </synapse>
 </transition_graph>

