 <transition_graph cluster-delay="60" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
   <synapse id="0">
     <action_set>
       <rsc_op id="16" operation="stop" operation_key="stonithclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321">
        <primitive id="stonithclone" long-id="stonithclone:1" class="stonith" type="external/ssh"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000"  hostlist="node1,node2"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="19" operation="stop" operation_key="stonithcloneset_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="1" priority="1000000">
     <action_set>
       <pseudo_event id="20" operation="stopped" operation_key="stonithcloneset_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <rsc_op id="16" operation="stop" operation_key="stonithclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
       <trigger>
         <pseudo_event id="19" operation="stop" operation_key="stonithcloneset_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="2">
    <action_set>
      <pseudo_event id="19" operation="stop" operation_key="stonithcloneset_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
   <synapse id="3">
     <action_set>
       <rsc_op id="23" operation="stop" operation_key="evmsdclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321">
        <primitive id="evmsdclone" long-id="evmsdclone:1" class="ocf" provider="heartbeat" type="Evmsd"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="26" operation="stop" operation_key="evmsdcloneset_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="4" priority="1000000">
     <action_set>
      <pseudo_event id="27" operation="stopped" operation_key="evmsdcloneset_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="23" operation="stop" operation_key="evmsdclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
      </trigger>
      <trigger>
        <pseudo_event id="26" operation="stop" operation_key="evmsdcloneset_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="5">
     <action_set>
      <pseudo_event id="26" operation="stop" operation_key="evmsdcloneset_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="42" operation="notified" operation_key="evmscloneset_confirmed-post_notify_stopped_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="6" priority="1000000">
     <action_set>
      <rsc_op id="88" operation="notify" operation_key="evmsclone:0_post_notify_stop_0" on_node="node2" on_node_uuid="997c3f45-7e3f-4c70-8d9a-623ba1678a6e">
        <primitive id="evmsclone" long-id="evmsclone:0" class="ocf" provider="heartbeat" type="EvmsSCC"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_active_resource="evmsclone:0 evmsclone:1 " CRM_meta_notify_active_uname="node2 node1 " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="stopped" CRM_meta_notify_key_type="post" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="stop" CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource="evmsclone:1 " CRM_meta_notify_stop_uname="node1 " CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="41" operation="notify" operation_key="evmscloneset_post_notify_stopped_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="7">
     <action_set>
      <rsc_op id="87" operation="notify" operation_key="evmsclone:0_pre_notify_stop_0" on_node="node2" on_node_uuid="997c3f45-7e3f-4c70-8d9a-623ba1678a6e">
        <primitive id="evmsclone" long-id="evmsclone:0" class="ocf" provider="heartbeat" type="EvmsSCC"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_active_resource="evmsclone:0 evmsclone:1 " CRM_meta_notify_active_uname="node2 node1 " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="stop" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="stop" CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource="evmsclone:1 " CRM_meta_notify_stop_uname="node1 " CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="39" operation="notify" operation_key="evmscloneset_pre_notify_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="8">
     <action_set>
      <rsc_op id="89" operation="notify" operation_key="evmsclone:1_pre_notify_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321">
        <primitive id="evmsclone" long-id="evmsclone:1" class="ocf" provider="heartbeat" type="EvmsSCC"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_active_resource="evmsclone:0 evmsclone:1 " CRM_meta_notify_active_uname="node2 node1 " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="stop" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="stop" CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource="evmsclone:1 " CRM_meta_notify_stop_uname="node1 " CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="39" operation="notify" operation_key="evmscloneset_pre_notify_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="9">
     <action_set>
      <rsc_op id="30" operation="stop" operation_key="evmsclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321">
        <primitive id="evmsclone" long-id="evmsclone:1" class="ocf" provider="heartbeat" type="EvmsSCC"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_active_resource="evmsclone:0 evmsclone:1 " CRM_meta_notify_active_uname="node2 node1 " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource="evmsclone:1 " CRM_meta_notify_stop_uname="node1 " CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="37" operation="stop" operation_key="evmscloneset_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="10" priority="1000000">
     <action_set>
      <pseudo_event id="42" operation="notified" operation_key="evmscloneset_confirmed-post_notify_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_key_operation="stopped" CRM_meta_notify_key_type="confirmed-post" CRM_meta_notify_operation="stop" CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="41" operation="notify" operation_key="evmscloneset_post_notify_stopped_0"/>
       </trigger>
       <trigger>
        <rsc_op id="88" operation="notify" operation_key="evmsclone:0_post_notify_stop_0" on_node="node2" on_node_uuid="997c3f45-7e3f-4c70-8d9a-623ba1678a6e"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="11" priority="1000000">
     <action_set>
      <pseudo_event id="41" operation="notify" operation_key="evmscloneset_post_notify_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_key_operation="stopped" CRM_meta_notify_key_type="post" CRM_meta_notify_operation="stop" CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="38" operation="stopped" operation_key="evmscloneset_stopped_0"/>
       </trigger>
       <trigger>
        <pseudo_event id="40" operation="notified" operation_key="evmscloneset_confirmed-pre_notify_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="12">
     <action_set>
       <pseudo_event id="40" operation="notified" operation_key="evmscloneset_confirmed-pre_notify_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_key_operation="stop" CRM_meta_notify_key_type="confirmed-pre" CRM_meta_notify_operation="stop" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="39" operation="notify" operation_key="evmscloneset_pre_notify_stop_0"/>
       </trigger>
       <trigger>
        <rsc_op id="87" operation="notify" operation_key="evmsclone:0_pre_notify_stop_0" on_node="node2" on_node_uuid="997c3f45-7e3f-4c70-8d9a-623ba1678a6e"/>
       </trigger>
       <trigger>
        <rsc_op id="89" operation="notify" operation_key="evmsclone:1_pre_notify_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="13">
    <action_set>
      <pseudo_event id="39" operation="notify" operation_key="evmscloneset_pre_notify_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_key_operation="stop" CRM_meta_notify_key_type="pre" CRM_meta_notify_operation="stop" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
   <synapse id="14" priority="1000000">
     <action_set>
      <pseudo_event id="38" operation="stopped" operation_key="evmscloneset_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="30" operation="stop" operation_key="evmsclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
      <trigger>
        <pseudo_event id="37" operation="stop" operation_key="evmscloneset_stop_0"/>
      </trigger>
     </inputs>
   </synapse>
  <synapse id="15">
     <action_set>
      <pseudo_event id="37" operation="stop" operation_key="evmscloneset_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="40" operation="notified" operation_key="evmscloneset_confirmed-pre_notify_stop_0"/>
       </trigger>
       <trigger>
        <pseudo_event id="57" operation="notified" operation_key="imagestorecloneset_confirmed-post_notify_stopped_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="72" operation="notified" operation_key="configstorecloneset_confirmed-post_notify_stopped_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="16" priority="1000000">
     <action_set>
      <rsc_op id="93" operation="notify" operation_key="imagestoreclone:0_post_notify_stop_0" on_node="node2" on_node_uuid="997c3f45-7e3f-4c70-8d9a-623ba1678a6e">
        <primitive id="imagestoreclone" long-id="imagestoreclone:0" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_active_resource="imagestoreclone:0 imagestoreclone:1 " CRM_meta_notify_active_uname="node2 node1 " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="stopped" CRM_meta_notify_key_type="post" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="stop" CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource="imagestoreclone:1 " CRM_meta_notify_stop_uname="node1 " CRM_meta_notify_type="post" CRM_meta_timeout="20000"  device="/dev/evms/vmsharedclustercontainer/imagestore" directory="/var/lib/xen/images" fstype="ocfs2"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="56" operation="notify" operation_key="imagestorecloneset_post_notify_stopped_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="17">
     <action_set>
      <rsc_op id="92" operation="notify" operation_key="imagestoreclone:0_pre_notify_stop_0" on_node="node2" on_node_uuid="997c3f45-7e3f-4c70-8d9a-623ba1678a6e">
        <primitive id="imagestoreclone" long-id="imagestoreclone:0" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_active_resource="imagestoreclone:0 imagestoreclone:1 " CRM_meta_notify_active_uname="node2 node1 " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="stop" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="stop" CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource="imagestoreclone:1 " CRM_meta_notify_stop_uname="node1 " CRM_meta_notify_type="pre" CRM_meta_timeout="20000"  device="/dev/evms/vmsharedclustercontainer/imagestore" directory="/var/lib/xen/images" fstype="ocfs2"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="54" operation="notify" operation_key="imagestorecloneset_pre_notify_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="18">
     <action_set>
      <rsc_op id="94" operation="notify" operation_key="imagestoreclone:0_pre_notify_stop_0" internal_operation_key="imagestoreclone:1_pre_notify_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321">
        <primitive id="imagestoreclone" long-id="imagestoreclone:0" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_active_resource="imagestoreclone:0 imagestoreclone:1 " CRM_meta_notify_active_uname="node2 node1 " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="stop" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="stop" CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource="imagestoreclone:1 " CRM_meta_notify_stop_uname="node1 " CRM_meta_notify_type="pre" CRM_meta_timeout="20000"  device="/dev/evms/vmsharedclustercontainer/imagestore" directory="/var/lib/xen/images" fstype="ocfs2"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="54" operation="notify" operation_key="imagestorecloneset_pre_notify_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="19">
     <action_set>
      <rsc_op id="45" operation="stop" operation_key="imagestoreclone:0_stop_0" internal_operation_key="imagestoreclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321">
        <primitive id="imagestoreclone" long-id="imagestoreclone:0" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_active_resource="imagestoreclone:0 imagestoreclone:1 " CRM_meta_notify_active_uname="node2 node1 " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource="imagestoreclone:1 " CRM_meta_notify_stop_uname="node1 " CRM_meta_timeout="20000"  device="/dev/evms/vmsharedclustercontainer/imagestore" directory="/var/lib/xen/images" fstype="ocfs2"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="52" operation="stop" operation_key="imagestorecloneset_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="20" priority="1000000">
     <action_set>
      <pseudo_event id="57" operation="notified" operation_key="imagestorecloneset_confirmed-post_notify_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_key_operation="stopped" CRM_meta_notify_key_type="confirmed-post" CRM_meta_notify_operation="stop" CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="56" operation="notify" operation_key="imagestorecloneset_post_notify_stopped_0"/>
       </trigger>
       <trigger>
        <rsc_op id="93" operation="notify" operation_key="imagestoreclone:0_post_notify_stop_0" on_node="node2" on_node_uuid="997c3f45-7e3f-4c70-8d9a-623ba1678a6e"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="21" priority="1000000">
     <action_set>
      <pseudo_event id="56" operation="notify" operation_key="imagestorecloneset_post_notify_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_key_operation="stopped" CRM_meta_notify_key_type="post" CRM_meta_notify_operation="stop" CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="53" operation="stopped" operation_key="imagestorecloneset_stopped_0"/>
       </trigger>
       <trigger>
        <pseudo_event id="55" operation="notified" operation_key="imagestorecloneset_confirmed-pre_notify_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="22">
     <action_set>
       <pseudo_event id="55" operation="notified" operation_key="imagestorecloneset_confirmed-pre_notify_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_key_operation="stop" CRM_meta_notify_key_type="confirmed-pre" CRM_meta_notify_operation="stop" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="54" operation="notify" operation_key="imagestorecloneset_pre_notify_stop_0"/>
       </trigger>
       <trigger>
        <rsc_op id="92" operation="notify" operation_key="imagestoreclone:0_pre_notify_stop_0" on_node="node2" on_node_uuid="997c3f45-7e3f-4c70-8d9a-623ba1678a6e"/>
       </trigger>
       <trigger>
        <rsc_op id="94" operation="notify" operation_key="imagestoreclone:0_pre_notify_stop_0" internal_operation_key="imagestoreclone:1_pre_notify_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="23">
    <action_set>
      <pseudo_event id="54" operation="notify" operation_key="imagestorecloneset_pre_notify_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_key_operation="stop" CRM_meta_notify_key_type="pre" CRM_meta_notify_operation="stop" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
   <synapse id="24" priority="1000000">
     <action_set>
      <pseudo_event id="53" operation="stopped" operation_key="imagestorecloneset_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="45" operation="stop" operation_key="imagestoreclone:0_stop_0" internal_operation_key="imagestoreclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
      <trigger>
        <pseudo_event id="52" operation="stop" operation_key="imagestorecloneset_stop_0"/>
      </trigger>
     </inputs>
   </synapse>
  <synapse id="25">
     <action_set>
      <pseudo_event id="52" operation="stop" operation_key="imagestorecloneset_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="55" operation="notified" operation_key="imagestorecloneset_confirmed-pre_notify_stop_0"/>
       </trigger>
       <trigger>
        <rsc_op id="73" operation="stop" operation_key="sles10_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="26" priority="1000000">
     <action_set>
      <rsc_op id="98" operation="notify" operation_key="configstoreclone:0_post_notify_stop_0" on_node="node2" on_node_uuid="997c3f45-7e3f-4c70-8d9a-623ba1678a6e">
        <primitive id="configstoreclone" long-id="configstoreclone:0" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_active_resource="configstoreclone:0 configstoreclone:1 " CRM_meta_notify_active_uname="node2 node1 " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="stopped" CRM_meta_notify_key_type="post" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="stop" CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource="configstoreclone:1 " CRM_meta_notify_stop_uname="node1 " CRM_meta_notify_type="post" CRM_meta_timeout="20000"  device="/dev/evms/vmsharedclustercontainer/configstore" directory="/etc/xen/vm" fstype="ocfs2"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="71" operation="notify" operation_key="configstorecloneset_post_notify_stopped_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="27">
     <action_set>
      <rsc_op id="97" operation="notify" operation_key="configstoreclone:0_pre_notify_stop_0" on_node="node2" on_node_uuid="997c3f45-7e3f-4c70-8d9a-623ba1678a6e">
        <primitive id="configstoreclone" long-id="configstoreclone:0" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_active_resource="configstoreclone:0 configstoreclone:1 " CRM_meta_notify_active_uname="node2 node1 " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="stop" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="stop" CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource="configstoreclone:1 " CRM_meta_notify_stop_uname="node1 " CRM_meta_notify_type="pre" CRM_meta_timeout="20000"  device="/dev/evms/vmsharedclustercontainer/configstore" directory="/etc/xen/vm" fstype="ocfs2"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="69" operation="notify" operation_key="configstorecloneset_pre_notify_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="28">
     <action_set>
      <rsc_op id="99" operation="notify" operation_key="configstoreclone:0_pre_notify_stop_0" internal_operation_key="configstoreclone:1_pre_notify_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321">
        <primitive id="configstoreclone" long-id="configstoreclone:0" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_active_resource="configstoreclone:0 configstoreclone:1 " CRM_meta_notify_active_uname="node2 node1 " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_key_operation="stop" CRM_meta_notify_key_type="pre" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="stop" CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource="configstoreclone:1 " CRM_meta_notify_stop_uname="node1 " CRM_meta_notify_type="pre" CRM_meta_timeout="20000"  device="/dev/evms/vmsharedclustercontainer/configstore" directory="/etc/xen/vm" fstype="ocfs2"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="69" operation="notify" operation_key="configstorecloneset_pre_notify_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="29">
     <action_set>
      <rsc_op id="60" operation="stop" operation_key="configstoreclone:0_stop_0" internal_operation_key="configstoreclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321">
        <primitive id="configstoreclone" long-id="configstoreclone:0" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_active_resource="configstoreclone:0 configstoreclone:1 " CRM_meta_notify_active_uname="node2 node1 " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource=" " CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource=" " CRM_meta_notify_start_uname=" " CRM_meta_notify_stop_resource="configstoreclone:1 " CRM_meta_notify_stop_uname="node1 " CRM_meta_timeout="20000"  device="/dev/evms/vmsharedclustercontainer/configstore" directory="/etc/xen/vm" fstype="ocfs2"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="67" operation="stop" operation_key="configstorecloneset_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="30" priority="1000000">
     <action_set>
      <pseudo_event id="72" operation="notified" operation_key="configstorecloneset_confirmed-post_notify_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_key_operation="stopped" CRM_meta_notify_key_type="confirmed-post" CRM_meta_notify_operation="stop" CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="71" operation="notify" operation_key="configstorecloneset_post_notify_stopped_0"/>
       </trigger>
       <trigger>
        <rsc_op id="98" operation="notify" operation_key="configstoreclone:0_post_notify_stop_0" on_node="node2" on_node_uuid="997c3f45-7e3f-4c70-8d9a-623ba1678a6e"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="31" priority="1000000">
     <action_set>
      <pseudo_event id="71" operation="notify" operation_key="configstorecloneset_post_notify_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_key_operation="stopped" CRM_meta_notify_key_type="post" CRM_meta_notify_operation="stop" CRM_meta_notify_type="post" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="68" operation="stopped" operation_key="configstorecloneset_stopped_0"/>
       </trigger>
       <trigger>
        <pseudo_event id="70" operation="notified" operation_key="configstorecloneset_confirmed-pre_notify_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="32">
     <action_set>
       <pseudo_event id="70" operation="notified" operation_key="configstorecloneset_confirmed-pre_notify_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_key_operation="stop" CRM_meta_notify_key_type="confirmed-pre" CRM_meta_notify_operation="stop" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="69" operation="notify" operation_key="configstorecloneset_pre_notify_stop_0"/>
       </trigger>
       <trigger>
        <rsc_op id="97" operation="notify" operation_key="configstoreclone:0_pre_notify_stop_0" on_node="node2" on_node_uuid="997c3f45-7e3f-4c70-8d9a-623ba1678a6e"/>
       </trigger>
       <trigger>
        <rsc_op id="99" operation="notify" operation_key="configstoreclone:0_pre_notify_stop_0" internal_operation_key="configstoreclone:1_pre_notify_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="33">
    <action_set>
      <pseudo_event id="69" operation="notify" operation_key="configstorecloneset_pre_notify_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_key_operation="stop" CRM_meta_notify_key_type="pre" CRM_meta_notify_operation="stop" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
   <synapse id="34" priority="1000000">
     <action_set>
      <pseudo_event id="68" operation="stopped" operation_key="configstorecloneset_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="60" operation="stop" operation_key="configstoreclone:0_stop_0" internal_operation_key="configstoreclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
      <trigger>
        <pseudo_event id="67" operation="stop" operation_key="configstorecloneset_stop_0"/>
      </trigger>
     </inputs>
   </synapse>
  <synapse id="35">
     <action_set>
      <pseudo_event id="67" operation="stop" operation_key="configstorecloneset_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="70" operation="notified" operation_key="configstorecloneset_confirmed-pre_notify_stop_0"/>
       </trigger>
       <trigger>
        <rsc_op id="73" operation="stop" operation_key="sles10_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="36" priority="1000000">
     <action_set>
      <rsc_op id="84" operation="migrate_from" operation_key="sles10_migrate_from_0" on_node="node2" on_node_uuid="997c3f45-7e3f-4c70-8d9a-623ba1678a6e">
        <primitive id="sles10" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_migrate_source="node1" CRM_meta_migrate_target="node2" CRM_meta_name="migrate" CRM_meta_timeout="120000"  xmfile="/etc/xen/vm/sles10"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <rsc_op id="83" operation="migrate_to" operation_key="sles10_migrate_to_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="37">
     <action_set>
      <rsc_op id="83" operation="migrate_to" operation_key="sles10_migrate_to_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321">
        <primitive id="sles10" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_migrate_source="node1" CRM_meta_migrate_target="node2" CRM_meta_name="migrate" CRM_meta_timeout="120000"  xmfile="/etc/xen/vm/sles10"/>
      </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="38">
     <action_set>
       <rsc_op id="75" operation="monitor" operation_key="sles10_monitor_10000" on_node="node2" on_node_uuid="997c3f45-7e3f-4c70-8d9a-623ba1678a6e">
        <primitive id="sles10" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_requires="nothing" CRM_meta_timeout="60000"  xmfile="/etc/xen/vm/sles10"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="74" operation="start" operation_key="sles10_start_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="39">
     <action_set>
      <pseudo_event id="74" operation="start" operation_key="sles10_start_0">
        <attributes CRM_meta_timeout="20000"  xmfile="/etc/xen/vm/sles10"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="73" operation="stop" operation_key="sles10_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="40">
    <action_set>
      <rsc_op id="73" operation="stop" operation_key="sles10_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321">
        <primitive id="sles10" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_name="stop" CRM_meta_timeout="60000"  xmfile="/etc/xen/vm/sles10"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="84" operation="migrate_from" operation_key="sles10_migrate_from_0" on_node="node2" on_node_uuid="997c3f45-7e3f-4c70-8d9a-623ba1678a6e"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="41">
    <action_set>
      <crm_event id="77" operation="do_shutdown" operation_key="do_shutdown" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321">
        <attributes CRM_meta_op_no_wait="true" />
      </crm_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="16" operation="stop" operation_key="stonithclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
       <trigger>
        <rsc_op id="23" operation="stop" operation_key="evmsdclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
       <trigger>
        <rsc_op id="30" operation="stop" operation_key="evmsclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
      </trigger>
      <trigger>
         <rsc_op id="45" operation="stop" operation_key="imagestoreclone:0_stop_0" internal_operation_key="imagestoreclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
       <trigger>
         <rsc_op id="60" operation="stop" operation_key="configstoreclone:0_stop_0" internal_operation_key="configstoreclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
       <trigger>
        <rsc_op id="73" operation="stop" operation_key="sles10_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="42">
     <action_set>
      <pseudo_event id="10" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="16" operation="stop" operation_key="stonithclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
      </trigger>
      <trigger>
         <rsc_op id="23" operation="stop" operation_key="evmsdclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
       <trigger>
         <rsc_op id="30" operation="stop" operation_key="evmsclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
       <trigger>
        <pseudo_event id="42" operation="notified" operation_key="evmscloneset_confirmed-post_notify_stopped_0"/>
      </trigger>
      <trigger>
         <rsc_op id="45" operation="stop" operation_key="imagestoreclone:0_stop_0" internal_operation_key="imagestoreclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
       <trigger>
        <pseudo_event id="57" operation="notified" operation_key="imagestorecloneset_confirmed-post_notify_stopped_0"/>
      </trigger>
      <trigger>
         <rsc_op id="60" operation="stop" operation_key="configstoreclone:0_stop_0" internal_operation_key="configstoreclone:1_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
       <trigger>
        <pseudo_event id="72" operation="notified" operation_key="configstorecloneset_confirmed-post_notify_stopped_0"/>
      </trigger>
      <trigger>
        <rsc_op id="73" operation="stop" operation_key="sles10_stop_0" on_node="node1" on_node_uuid="3d8227f0-31dd-4801-b0db-987909d4a321"/>
       </trigger>
     </inputs>
   </synapse>
 </transition_graph>

