<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="5" operation="start" operation_key="rsc1_child:0_start_0" on_node="yingying.site" on_node_uuid="yingying.site">
        <primitive id="rsc1_child" long-id="rsc1_child:0" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="1" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="6" operation="start" operation_key="rsc1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="4" operation="monitor" operation_key="rsc1_child:0_monitor_0" on_node="yingying.site" on_node_uuid="yingying.site">
        <primitive id="rsc1_child" long-id="rsc1_child:0" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="1" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="2" priority="1000000">
    <action_set>
      <pseudo_event id="7" operation="running" operation_key="rsc1_running_0">
        <attributes CRM_meta_clone_max="1" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="start" operation_key="rsc1_child:0_start_0" on_node="yingying.site" on_node_uuid="yingying.site"/>
      </trigger>
      <trigger>
        <pseudo_event id="6" operation="start" operation_key="rsc1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <pseudo_event id="6" operation="start" operation_key="rsc1_start_0">
        <attributes CRM_meta_clone_max="1" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="4" priority="1000000">
    <action_set>
      <rsc_op id="3" operation="probe_complete" operation_key="probe_complete" on_node="yingying.site" on_node_uuid="yingying.site">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="4" operation="monitor" operation_key="rsc1_child:0_monitor_0" on_node="yingying.site" on_node_uuid="yingying.site"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete">
        <attributes crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="3" operation="probe_complete" operation_key="probe_complete" on_node="yingying.site" on_node_uuid="yingying.site"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

