<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="16" operation="stop" operation_key="xen-a-fencing_stop_0" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331">
        <primitive id="xen-a-fencing" class="stonith" type="external/ipmi"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostname="xen-a" interface="lanplus" ipaddr="217.148.178.55" passwd="****" userid="root"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="12" operation="start" operation_key="xen-a-fencing_start_0" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331">
        <primitive id="xen-a-fencing" class="stonith" type="external/ipmi"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostname="xen-a" interface="lanplus" ipaddr="217.148.178.55" passwd="****" userid="root"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="16" operation="stop" operation_key="xen-a-fencing_stop_0" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="7" operation="monitor" operation_key="xen-a-fencing_monitor_60000" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331">
        <primitive id="xen-a-fencing" class="stonith" type="external/ipmi"/>
        <attributes CRM_meta_interval="60000" CRM_meta_name="monitor" CRM_meta_start_delay="15000" CRM_meta_timeout="75000" crm_feature_set="3.0.6" hostname="xen-a" interface="lanplus" ipaddr="217.148.178.55" passwd="****" userid="root"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="12" operation="start" operation_key="xen-a-fencing_start_0" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <rsc_op id="17" operation="stop" operation_key="xen-b-fencing_stop_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7">
        <primitive id="xen-b-fencing" class="stonith" type="external/ipmi"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6" hostname="xen-b" interface="lanplus" ipaddr="217.148.178.56" passwd="****" userid="root"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="11" operation="all_stopped" operation_key="all_stopped"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4" priority="1000000">
    <action_set>
      <rsc_op id="42" operation="migrate_from" operation_key="db_migrate_from_0" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331">
        <primitive id="db" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_migrate_source="xen-a" CRM_meta_migrate_target="xen-b" CRM_meta_name="migrate_from" CRM_meta_timeout="400000" crm_feature_set="3.0.6" name="db" xmfile="/etc/xen/db.cfg"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="41" operation="migrate_to" operation_key="db_migrate_to_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <rsc_op id="41" operation="migrate_to" operation_key="db_migrate_to_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7">
        <primitive id="db" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_migrate_source="xen-a" CRM_meta_migrate_target="xen-b" CRM_meta_name="migrate_to" CRM_meta_timeout="400000" crm_feature_set="3.0.6" name="db" xmfile="/etc/xen/db.cfg"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="6">
    <action_set>
      <rsc_op id="20" operation="monitor" operation_key="db_monitor_10000" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331">
        <primitive id="db" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_timeout="20000" crm_feature_set="3.0.6" name="db" xmfile="/etc/xen/db.cfg"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="19" operation="start" operation_key="db_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <pseudo_event id="19" operation="start" operation_key="db_start_0">
        <attributes CRM_meta_name="start" CRM_meta_timeout="45000" crm_feature_set="3.0.6" name="db" xmfile="/etc/xen/db.cfg"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="18" operation="stop" operation_key="db_stop_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <rsc_op id="18" operation="stop" operation_key="db_stop_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7">
        <primitive id="db" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_name="stop" CRM_meta_timeout="300000" crm_feature_set="3.0.6" name="db" xmfile="/etc/xen/db.cfg"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="42" operation="migrate_from" operation_key="db_migrate_from_0" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9" priority="1000000">
    <action_set>
      <rsc_op id="44" operation="migrate_from" operation_key="core-101_migrate_from_0" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331">
        <primitive id="core-101" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_migrate_source="xen-a" CRM_meta_migrate_target="xen-b" CRM_meta_name="migrate_from" CRM_meta_timeout="400000" crm_feature_set="3.0.6" name="core-101" xmfile="/etc/xen/core-101.cfg"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="43" operation="migrate_to" operation_key="core-101_migrate_to_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="10">
    <action_set>
      <rsc_op id="43" operation="migrate_to" operation_key="core-101_migrate_to_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7">
        <primitive id="core-101" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_migrate_source="xen-a" CRM_meta_migrate_target="xen-b" CRM_meta_name="migrate_to" CRM_meta_timeout="400000" crm_feature_set="3.0.6" name="core-101" xmfile="/etc/xen/core-101.cfg"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="11">
    <action_set>
      <rsc_op id="25" operation="monitor" operation_key="core-101_monitor_10000" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331">
        <primitive id="core-101" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_timeout="30000" crm_feature_set="3.0.6" name="core-101" xmfile="/etc/xen/core-101.cfg"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="24" operation="start" operation_key="core-101_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="12">
    <action_set>
      <pseudo_event id="24" operation="start" operation_key="core-101_start_0">
        <attributes CRM_meta_name="start" CRM_meta_timeout="45000" crm_feature_set="3.0.6" name="core-101" xmfile="/etc/xen/core-101.cfg"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="23" operation="stop" operation_key="core-101_stop_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="13">
    <action_set>
      <rsc_op id="23" operation="stop" operation_key="core-101_stop_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7">
        <primitive id="core-101" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_name="stop" CRM_meta_timeout="300000" crm_feature_set="3.0.6" name="core-101" xmfile="/etc/xen/core-101.cfg"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="44" operation="migrate_from" operation_key="core-101_migrate_from_0" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="14" priority="1000000">
    <action_set>
      <rsc_op id="46" operation="migrate_from" operation_key="core-200_migrate_from_0" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331">
        <primitive id="core-200" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_migrate_source="xen-a" CRM_meta_migrate_target="xen-b" CRM_meta_name="migrate_from" CRM_meta_timeout="400000" crm_feature_set="3.0.6" name="core-200" xmfile="/etc/xen/core-200.cfg"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="45" operation="migrate_to" operation_key="core-200_migrate_to_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="15">
    <action_set>
      <rsc_op id="45" operation="migrate_to" operation_key="core-200_migrate_to_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7">
        <primitive id="core-200" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_migrate_source="xen-a" CRM_meta_migrate_target="xen-b" CRM_meta_name="migrate_to" CRM_meta_timeout="400000" crm_feature_set="3.0.6" name="core-200" xmfile="/etc/xen/core-200.cfg"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="24" operation="start" operation_key="core-101_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="16">
    <action_set>
      <rsc_op id="28" operation="monitor" operation_key="core-200_monitor_10000" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331">
        <primitive id="core-200" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_timeout="20000" crm_feature_set="3.0.6" name="core-200" xmfile="/etc/xen/core-200.cfg"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="27" operation="start" operation_key="core-200_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="17">
    <action_set>
      <pseudo_event id="27" operation="start" operation_key="core-200_start_0">
        <attributes CRM_meta_name="start" CRM_meta_timeout="45000" crm_feature_set="3.0.6" name="core-200" xmfile="/etc/xen/core-200.cfg"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="24" operation="start" operation_key="core-101_start_0"/>
      </trigger>
      <trigger>
        <rsc_op id="26" operation="stop" operation_key="core-200_stop_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="18">
    <action_set>
      <rsc_op id="26" operation="stop" operation_key="core-200_stop_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7">
        <primitive id="core-200" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_name="stop" CRM_meta_timeout="300000" crm_feature_set="3.0.6" name="core-200" xmfile="/etc/xen/core-200.cfg"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="46" operation="migrate_from" operation_key="core-200_migrate_from_0" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="19" priority="1000000">
    <action_set>
      <rsc_op id="48" operation="migrate_from" operation_key="edge_migrate_from_0" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331">
        <primitive id="edge" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_migrate_source="xen-a" CRM_meta_migrate_target="xen-b" CRM_meta_name="migrate_from" CRM_meta_timeout="400000" crm_feature_set="3.0.6" name="edge" xmfile="/etc/xen/edge.cfg"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="47" operation="migrate_to" operation_key="edge_migrate_to_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="20">
    <action_set>
      <rsc_op id="47" operation="migrate_to" operation_key="edge_migrate_to_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7">
        <primitive id="edge" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_migrate_source="xen-a" CRM_meta_migrate_target="xen-b" CRM_meta_name="migrate_to" CRM_meta_timeout="400000" crm_feature_set="3.0.6" name="edge" xmfile="/etc/xen/edge.cfg"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="21">
    <action_set>
      <rsc_op id="33" operation="monitor" operation_key="edge_monitor_10000" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331">
        <primitive id="edge" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_timeout="20000" crm_feature_set="3.0.6" name="edge" xmfile="/etc/xen/edge.cfg"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="32" operation="start" operation_key="edge_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="22">
    <action_set>
      <pseudo_event id="32" operation="start" operation_key="edge_start_0">
        <attributes CRM_meta_name="start" CRM_meta_timeout="45000" crm_feature_set="3.0.6" name="edge" xmfile="/etc/xen/edge.cfg"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="31" operation="stop" operation_key="edge_stop_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="23">
    <action_set>
      <rsc_op id="31" operation="stop" operation_key="edge_stop_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7">
        <primitive id="edge" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_name="stop" CRM_meta_timeout="300000" crm_feature_set="3.0.6" name="edge" xmfile="/etc/xen/edge.cfg"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="48" operation="migrate_from" operation_key="edge_migrate_from_0" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="24" priority="1000000">
    <action_set>
      <rsc_op id="50" operation="migrate_from" operation_key="base_migrate_from_0" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331">
        <primitive id="base" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_migrate_source="xen-a" CRM_meta_migrate_target="xen-b" CRM_meta_name="migrate_from" CRM_meta_timeout="400000" crm_feature_set="3.0.6" name="base" xmfile="/etc/xen/base.cfg"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="49" operation="migrate_to" operation_key="base_migrate_to_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="25">
    <action_set>
      <rsc_op id="49" operation="migrate_to" operation_key="base_migrate_to_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7">
        <primitive id="base" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_migrate_source="xen-a" CRM_meta_migrate_target="xen-b" CRM_meta_name="migrate_to" CRM_meta_timeout="400000" crm_feature_set="3.0.6" name="base" xmfile="/etc/xen/base.cfg"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="32" operation="start" operation_key="edge_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="26">
    <action_set>
      <rsc_op id="36" operation="monitor" operation_key="base_monitor_10000" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331">
        <primitive id="base" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_timeout="20000" crm_feature_set="3.0.6" name="base" xmfile="/etc/xen/base.cfg"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="35" operation="start" operation_key="base_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="27">
    <action_set>
      <pseudo_event id="35" operation="start" operation_key="base_start_0">
        <attributes CRM_meta_name="start" CRM_meta_timeout="45000" crm_feature_set="3.0.6" name="base" xmfile="/etc/xen/base.cfg"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="32" operation="start" operation_key="edge_start_0"/>
      </trigger>
      <trigger>
        <rsc_op id="34" operation="stop" operation_key="base_stop_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="28">
    <action_set>
      <rsc_op id="34" operation="stop" operation_key="base_stop_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7">
        <primitive id="base" class="ocf" provider="heartbeat" type="Xen"/>
        <attributes CRM_meta_name="stop" CRM_meta_timeout="300000" crm_feature_set="3.0.6" name="base" xmfile="/etc/xen/base.cfg"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="50" operation="migrate_from" operation_key="base_migrate_from_0" on_node="xen-b" on_node_uuid="9cb7f556-e0a7-4073-8845-2d7c1d54e331"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="29">
    <action_set>
      <pseudo_event id="11" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="18" operation="stop" operation_key="db_stop_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7"/>
      </trigger>
      <trigger>
        <rsc_op id="23" operation="stop" operation_key="core-101_stop_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7"/>
      </trigger>
      <trigger>
        <rsc_op id="26" operation="stop" operation_key="core-200_stop_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7"/>
      </trigger>
      <trigger>
        <rsc_op id="31" operation="stop" operation_key="edge_stop_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7"/>
      </trigger>
      <trigger>
        <rsc_op id="34" operation="stop" operation_key="base_stop_0" on_node="xen-a" on_node_uuid="445a93d5-655e-430b-b45d-47d79a2f78c7"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

