<transition_graph cluster-delay="5s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="11" operation="monitor" operation_key="world1_monitor_10000" on_node="ubuntu_1" on_node_uuid="ubuntu_1">
        <primitive id="world1" class="ocf" provider="bbnd" type="world1test"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_on_fail="restart" CRM_meta_requires="nothing" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="10" operation="start" operation_key="world1_start_0" on_node="ubuntu_1" on_node_uuid="ubuntu_1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="10" operation="start" operation_key="world1_start_0" on_node="ubuntu_1" on_node_uuid="ubuntu_1">
        <primitive id="world1" class="ocf" provider="bbnd" type="world1test"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="9" operation="stop" operation_key="world1_stop_0" on_node="ubuntu_2" on_node_uuid="ubuntu_2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="9" operation="stop" operation_key="world1_stop_0" on_node="ubuntu_2" on_node_uuid="ubuntu_2">
        <primitive id="world1" class="ocf" provider="bbnd" type="world1test"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="12" operation="stop" operation_key="world2_stop_0" on_node="ubuntu_2" on_node_uuid="ubuntu_2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <rsc_op id="14" operation="monitor" operation_key="world2_monitor_10000" on_node="ubuntu_1" on_node_uuid="ubuntu_1">
        <primitive id="world2" class="ocf" provider="bbnd" type="world2test"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_on_fail="restart" CRM_meta_requires="nothing" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="13" operation="start" operation_key="world2_start_0" on_node="ubuntu_1" on_node_uuid="ubuntu_1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <rsc_op id="13" operation="start" operation_key="world2_start_0" on_node="ubuntu_1" on_node_uuid="ubuntu_1">
        <primitive id="world2" class="ocf" provider="bbnd" type="world2test"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="10" operation="start" operation_key="world1_start_0" on_node="ubuntu_1" on_node_uuid="ubuntu_1"/>
      </trigger>
      <trigger>
        <rsc_op id="12" operation="stop" operation_key="world2_stop_0" on_node="ubuntu_2" on_node_uuid="ubuntu_2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <rsc_op id="12" operation="stop" operation_key="world2_stop_0" on_node="ubuntu_2" on_node_uuid="ubuntu_2">
        <primitive id="world2" class="ocf" provider="bbnd" type="world2test"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="15" operation="stop" operation_key="world3_stop_0" on_node="ubuntu_2" on_node_uuid="ubuntu_2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <rsc_op id="17" operation="monitor" operation_key="world3_monitor_10000" on_node="ubuntu_1" on_node_uuid="ubuntu_1">
        <primitive id="world3" class="ocf" provider="bbnd" type="world3test"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_on_fail="restart" CRM_meta_requires="nothing" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="16" operation="start" operation_key="world3_start_0" on_node="ubuntu_1" on_node_uuid="ubuntu_1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <rsc_op id="16" operation="start" operation_key="world3_start_0" on_node="ubuntu_1" on_node_uuid="ubuntu_1">
        <primitive id="world3" class="ocf" provider="bbnd" type="world3test"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="13" operation="start" operation_key="world2_start_0" on_node="ubuntu_1" on_node_uuid="ubuntu_1"/>
      </trigger>
      <trigger>
        <rsc_op id="15" operation="stop" operation_key="world3_stop_0" on_node="ubuntu_2" on_node_uuid="ubuntu_2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <rsc_op id="15" operation="stop" operation_key="world3_stop_0" on_node="ubuntu_2" on_node_uuid="ubuntu_2">
        <primitive id="world3" class="ocf" provider="bbnd" type="world3test"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="18" operation="stop" operation_key="world4_stop_0" on_node="ubuntu_2" on_node_uuid="ubuntu_2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9">
    <action_set>
      <rsc_op id="20" operation="monitor" operation_key="world4_monitor_10000" on_node="ubuntu_1" on_node_uuid="ubuntu_1">
        <primitive id="world4" class="ocf" provider="bbnd" type="world4test"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_on_fail="restart" CRM_meta_requires="nothing" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="19" operation="start" operation_key="world4_start_0" on_node="ubuntu_1" on_node_uuid="ubuntu_1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="10">
    <action_set>
      <rsc_op id="19" operation="start" operation_key="world4_start_0" on_node="ubuntu_1" on_node_uuid="ubuntu_1">
        <primitive id="world4" class="ocf" provider="bbnd" type="world4test"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="16" operation="start" operation_key="world3_start_0" on_node="ubuntu_1" on_node_uuid="ubuntu_1"/>
      </trigger>
      <trigger>
        <rsc_op id="18" operation="stop" operation_key="world4_stop_0" on_node="ubuntu_2" on_node_uuid="ubuntu_2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="11">
    <action_set>
      <rsc_op id="18" operation="stop" operation_key="world4_stop_0" on_node="ubuntu_2" on_node_uuid="ubuntu_2">
        <primitive id="world4" class="ocf" provider="bbnd" type="world4test"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="12">
    <action_set>
      <pseudo_event id="5" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="9" operation="stop" operation_key="world1_stop_0" on_node="ubuntu_2" on_node_uuid="ubuntu_2"/>
      </trigger>
      <trigger>
        <rsc_op id="12" operation="stop" operation_key="world2_stop_0" on_node="ubuntu_2" on_node_uuid="ubuntu_2"/>
      </trigger>
      <trigger>
        <rsc_op id="15" operation="stop" operation_key="world3_stop_0" on_node="ubuntu_2" on_node_uuid="ubuntu_2"/>
      </trigger>
      <trigger>
        <rsc_op id="18" operation="stop" operation_key="world4_stop_0" on_node="ubuntu_2" on_node_uuid="ubuntu_2"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

