<transition_graph cluster-delay="3m" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
   <synapse id="0">
     <action_set>
      <rsc_op id="28" operation="stop" operation_key="DcIPaddr_stop_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f">
        <primitive id="DcIPaddr" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.20"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="8" operation="probe_complete" operation_key="probe_complete"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="1">
     <action_set>
      <rsc_op id="24" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="c001n01" on_node_uuid="de937e3d-0309-4b5d-b85c-f96edc1ed8e3">
        <primitive id="DcIPaddr" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.20"/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="2">
     <action_set>
      <rsc_op id="19" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193">
        <primitive id="DcIPaddr" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.20"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="3">
     <action_set>
      <rsc_op id="10" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="c001n08" on_node_uuid="6427cb5a-c7a5-4bdf-9892-a04ce56f4e6b">
        <primitive id="DcIPaddr" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.20"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="4">
     <action_set>
      <rsc_op id="7" operation="start" operation_key="DcIPaddr_start_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f">
        <primitive id="DcIPaddr" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.20"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="8" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <rsc_op id="28" operation="stop" operation_key="DcIPaddr_stop_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="5">
     <action_set>
      <rsc_op id="2" operation="monitor" operation_key="DcIPaddr_monitor_5000" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f">
        <primitive id="DcIPaddr" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.20"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="7" operation="start" operation_key="DcIPaddr_start_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="6">
     <action_set>
      <rsc_op id="25" operation="monitor" operation_key="rsc_c001n08_monitor_0" on_node="c001n01" on_node_uuid="de937e3d-0309-4b5d-b85c-f96edc1ed8e3">
        <primitive id="rsc_c001n08" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.11"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="7">
     <action_set>
      <rsc_op id="20" operation="monitor" operation_key="rsc_c001n08_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193">
        <primitive id="rsc_c001n08" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.11"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="8">
     <action_set>
      <rsc_op id="15" operation="monitor" operation_key="rsc_c001n08_monitor_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f">
        <primitive id="rsc_c001n08" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.11"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="9">
     <action_set>
      <rsc_op id="1" operation="monitor" operation_key="rsc_c001n08_monitor_5000" on_node="c001n08" on_node_uuid="6427cb5a-c7a5-4bdf-9892-a04ce56f4e6b">
        <primitive id="rsc_c001n08" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_new_attr="some_value" CRM_meta_timeout="21000" crm_feature_set="3.0.6" ip="127.0.0.11" new_attr="some_value"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="10">
     <action_set>
      <rsc_op id="33" operation="monitor" operation_key="rsc_c001n02_monitor_6000" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f">
        <primitive id="rsc_c001n02" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_interval="6000" CRM_meta_name="monitor" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.12"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="11">
     <action_set>
      <rsc_op id="26" operation="monitor" operation_key="rsc_c001n02_monitor_0" on_node="c001n01" on_node_uuid="de937e3d-0309-4b5d-b85c-f96edc1ed8e3">
        <primitive id="rsc_c001n02" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.12"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="12">
     <action_set>
       <rsc_op id="21" operation="monitor" operation_key="rsc_c001n02_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193">
        <primitive id="rsc_c001n02" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.12"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="13">
     <action_set>
      <rsc_op id="11" operation="monitor" operation_key="rsc_c001n02_monitor_0" on_node="c001n08" on_node_uuid="6427cb5a-c7a5-4bdf-9892-a04ce56f4e6b">
        <primitive id="rsc_c001n02" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.12"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="14">
     <action_set>
      <rsc_op id="3" operation="cancel" operation_key="rsc_c001n02_monitor_5000" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f">
        <primitive id="rsc_c001n02" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_call_id="6" CRM_meta_interval="5000" CRM_meta_operation="monitor" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.12"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="15">
     <action_set>
      <rsc_op id="27" operation="monitor" operation_key="rsc_c001n03_monitor_0" on_node="c001n01" on_node_uuid="de937e3d-0309-4b5d-b85c-f96edc1ed8e3">
        <primitive id="rsc_c001n03" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.13"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="16">
     <action_set>
       <rsc_op id="16" operation="monitor" operation_key="rsc_c001n03_monitor_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f">
        <primitive id="rsc_c001n03" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.13"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="17">
     <action_set>
      <rsc_op id="12" operation="monitor" operation_key="rsc_c001n03_monitor_0" on_node="c001n08" on_node_uuid="6427cb5a-c7a5-4bdf-9892-a04ce56f4e6b">
        <primitive id="rsc_c001n03" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.13"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="18">
     <action_set>
      <rsc_op id="22" operation="monitor" operation_key="rsc_c001n01_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193">
        <primitive id="rsc_c001n01" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.14"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="19">
     <action_set>
       <rsc_op id="17" operation="monitor" operation_key="rsc_c001n01_monitor_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f">
        <primitive id="rsc_c001n01" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.14"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="20">
     <action_set>
      <rsc_op id="13" operation="monitor" operation_key="rsc_c001n01_monitor_0" on_node="c001n08" on_node_uuid="6427cb5a-c7a5-4bdf-9892-a04ce56f4e6b">
        <primitive id="rsc_c001n01" class="ocf" provider="heartbeat" type="IPaddr"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" ip="127.0.0.14"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="21" priority="1000000">
     <action_set>
      <rsc_op id="23" operation="probe_complete" operation_key="probe_complete" on_node="c001n01" on_node_uuid="de937e3d-0309-4b5d-b85c-f96edc1ed8e3">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.6"/>
      </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="24" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="c001n01" on_node_uuid="de937e3d-0309-4b5d-b85c-f96edc1ed8e3"/>
       </trigger>
       <trigger>
        <rsc_op id="25" operation="monitor" operation_key="rsc_c001n08_monitor_0" on_node="c001n01" on_node_uuid="de937e3d-0309-4b5d-b85c-f96edc1ed8e3"/>
       </trigger>
       <trigger>
        <rsc_op id="26" operation="monitor" operation_key="rsc_c001n02_monitor_0" on_node="c001n01" on_node_uuid="de937e3d-0309-4b5d-b85c-f96edc1ed8e3"/>
       </trigger>
       <trigger>
        <rsc_op id="27" operation="monitor" operation_key="rsc_c001n03_monitor_0" on_node="c001n01" on_node_uuid="de937e3d-0309-4b5d-b85c-f96edc1ed8e3"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="22" priority="1000000">
     <action_set>
      <rsc_op id="18" operation="probe_complete" operation_key="probe_complete" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.6"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="19" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193"/>
       </trigger>
       <trigger>
        <rsc_op id="20" operation="monitor" operation_key="rsc_c001n08_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193"/>
       </trigger>
       <trigger>
        <rsc_op id="21" operation="monitor" operation_key="rsc_c001n02_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193"/>
       </trigger>
       <trigger>
        <rsc_op id="22" operation="monitor" operation_key="rsc_c001n01_monitor_0" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="23" priority="1000000">
     <action_set>
       <rsc_op id="14" operation="probe_complete" operation_key="probe_complete" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.6"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <rsc_op id="15" operation="monitor" operation_key="rsc_c001n08_monitor_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f"/>
       </trigger>
       <trigger>
         <rsc_op id="16" operation="monitor" operation_key="rsc_c001n03_monitor_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f"/>
       </trigger>
       <trigger>
         <rsc_op id="17" operation="monitor" operation_key="rsc_c001n01_monitor_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="24" priority="1000000">
     <action_set>
      <rsc_op id="9" operation="probe_complete" operation_key="probe_complete" on_node="c001n08" on_node_uuid="6427cb5a-c7a5-4bdf-9892-a04ce56f4e6b">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.6"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="10" operation="monitor" operation_key="DcIPaddr_monitor_0" on_node="c001n08" on_node_uuid="6427cb5a-c7a5-4bdf-9892-a04ce56f4e6b"/>
       </trigger>
       <trigger>
        <rsc_op id="11" operation="monitor" operation_key="rsc_c001n02_monitor_0" on_node="c001n08" on_node_uuid="6427cb5a-c7a5-4bdf-9892-a04ce56f4e6b"/>
       </trigger>
       <trigger>
        <rsc_op id="12" operation="monitor" operation_key="rsc_c001n03_monitor_0" on_node="c001n08" on_node_uuid="6427cb5a-c7a5-4bdf-9892-a04ce56f4e6b"/>
       </trigger>
       <trigger>
        <rsc_op id="13" operation="monitor" operation_key="rsc_c001n01_monitor_0" on_node="c001n08" on_node_uuid="6427cb5a-c7a5-4bdf-9892-a04ce56f4e6b"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="25">
     <action_set>
      <pseudo_event id="8" operation="probe_complete" operation_key="probe_complete">
        <attributes crm_feature_set="3.0.6"/>
      </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="9" operation="probe_complete" operation_key="probe_complete" on_node="c001n08" on_node_uuid="6427cb5a-c7a5-4bdf-9892-a04ce56f4e6b"/>
       </trigger>
       <trigger>
        <rsc_op id="14" operation="probe_complete" operation_key="probe_complete" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f"/>
       </trigger>
       <trigger>
        <rsc_op id="18" operation="probe_complete" operation_key="probe_complete" on_node="c001n03" on_node_uuid="5d9a8c11-8684-43ea-91.0.6e221530c193"/>
       </trigger>
       <trigger>
        <rsc_op id="23" operation="probe_complete" operation_key="probe_complete" on_node="c001n01" on_node_uuid="de937e3d-0309-4b5d-b85c-f96edc1ed8e3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="26">
    <action_set>
      <pseudo_event id="6" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.6"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="28" operation="stop" operation_key="DcIPaddr_stop_0" on_node="c001n02" on_node_uuid="e9bdfde9-01b0-421f-acd8-8a65a53e775f"/>
       </trigger>
     </inputs>
   </synapse>
 </transition_graph>

