 <transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
   <synapse id="0">
     <action_set>
      <rsc_op id="16" operation="stop" operation_key="rsc1_stop_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc1" class="lsb" type="apache"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="1">
     <action_set>
       <rsc_op id="14" operation="monitor" operation_key="rsc1_monitor_0" on_node="node3" on_node_uuid="node3">
        <primitive id="rsc1" class="lsb" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="2">
     <action_set>
      <rsc_op id="11" operation="monitor" operation_key="rsc1_monitor_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc1" class="lsb" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="3">
     <action_set>
      <rsc_op id="15" operation="monitor" operation_key="rsc2_monitor_0" on_node="node3" on_node_uuid="node3">
        <primitive id="rsc2" class="lsb" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="4">
     <action_set>
      <rsc_op id="8" operation="monitor" operation_key="rsc2_monitor_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc2" class="lsb" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="5">
     <action_set>
       <rsc_op id="5" operation="start" operation_key="rsc2_start_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc2" class="lsb" type="apache"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <rsc_op id="2" operation="stop" operation_key="rsc2_stop_0" on_node="node2" on_node_uuid="node2"/>
       </trigger>
       <trigger>
         <rsc_op id="3" operation="delete" operation_key="rsc2_delete_0" on_node="node2" on_node_uuid="node2"/>
       </trigger>
       <trigger>
         <pseudo_event id="6" operation="probe_complete" operation_key="probe_complete"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="6">
     <action_set>
      <rsc_op id="3" operation="delete" operation_key="rsc2_delete_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc2" class="lsb" type="apache"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <rsc_op id="2" operation="stop" operation_key="rsc2_stop_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="7">
     <action_set>
      <rsc_op id="2" operation="stop" operation_key="rsc2_stop_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc2" class="lsb" type="apache"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="6" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="8">
     <action_set>
      <rsc_op id="17" operation="start" operation_key="rsc3_start_0" on_node="node3" on_node_uuid="node3">
        <primitive id="rsc3" class="lsb" type="apache"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="6" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="9">
     <action_set>
       <rsc_op id="12" operation="monitor" operation_key="rsc3_monitor_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc3" class="lsb" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="10">
     <action_set>
      <rsc_op id="9" operation="monitor" operation_key="rsc3_monitor_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc3" class="lsb" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="11">
     <action_set>
      <crm_event id="19" operation="do_shutdown" operation_key="do_shutdown" on_node="node1" on_node_uuid="node1">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.7"/>
      </crm_event>
     </action_set>
     <inputs>
       <trigger>
         <rsc_op id="16" operation="stop" operation_key="rsc1_stop_0" on_node="node1" on_node_uuid="node1"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="12" priority="1000000">
     <action_set>
      <rsc_op id="13" operation="probe_complete" operation_key="probe_complete" on_node="node3" on_node_uuid="node3">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.7"/>
      </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="14" operation="monitor" operation_key="rsc1_monitor_0" on_node="node3" on_node_uuid="node3"/>
      </trigger>
      <trigger>
        <rsc_op id="15" operation="monitor" operation_key="rsc2_monitor_0" on_node="node3" on_node_uuid="node3"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="13" priority="1000000">
     <action_set>
      <rsc_op id="10" operation="probe_complete" operation_key="probe_complete" on_node="node2" on_node_uuid="node2">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.7"/>
      </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="11" operation="monitor" operation_key="rsc1_monitor_0" on_node="node2" on_node_uuid="node2"/>
       </trigger>
       <trigger>
        <rsc_op id="12" operation="monitor" operation_key="rsc3_monitor_0" on_node="node2" on_node_uuid="node2"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="14" priority="1000000">
     <action_set>
       <rsc_op id="7" operation="probe_complete" operation_key="probe_complete" on_node="node1" on_node_uuid="node1">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.7"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <rsc_op id="8" operation="monitor" operation_key="rsc2_monitor_0" on_node="node1" on_node_uuid="node1"/>
       </trigger>
       <trigger>
         <rsc_op id="9" operation="monitor" operation_key="rsc3_monitor_0" on_node="node1" on_node_uuid="node1"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="15">
     <action_set>
      <pseudo_event id="6" operation="probe_complete" operation_key="probe_complete">
        <attributes crm_feature_set="3.0.7"/>
      </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="7" operation="probe_complete" operation_key="probe_complete" on_node="node1" on_node_uuid="node1"/>
       </trigger>
       <trigger>
        <rsc_op id="10" operation="probe_complete" operation_key="probe_complete" on_node="node2" on_node_uuid="node2"/>
      </trigger>
      <trigger>
        <rsc_op id="13" operation="probe_complete" operation_key="probe_complete" on_node="node3" on_node_uuid="node3"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="16">
     <action_set>
      <crm_event id="4" operation="lrm_refresh" operation_key="lrm_refresh" on_node="node2" on_node_uuid="node2">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.7"/>
      </crm_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="3" operation="delete" operation_key="rsc2_delete_0" on_node="node2" on_node_uuid="node2"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="17">
     <action_set>
      <pseudo_event id="1" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.7"/>
      </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="2" operation="stop" operation_key="rsc2_stop_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
      <trigger>
         <rsc_op id="16" operation="stop" operation_key="rsc1_stop_0" on_node="node1" on_node_uuid="node1"/>
       </trigger>
     </inputs>
   </synapse>
 </transition_graph>

