 <transition_graph cluster-delay="60" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0" priority="1000000">
     <action_set>
      <rsc_op id="57" operation="notify" operation_key="configstoreclone:0_post_notify_start_0" on_node="x32c47" on_node_uuid="a1dbc8cc-4d33-41e7-a75a-cd4f93b26410">
        <primitive id="configstoreclone" long-id="configstoreclone:0" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource="configstoreclone:0 configstoreclone:1 " CRM_meta_notify_key_operation="running" CRM_meta_notify_key_type="post" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="start" CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource="configstoreclone:0 configstoreclone:1 " CRM_meta_notify_start_uname="x32c47 x32c48 " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="post" CRM_meta_timeout="20000" crm_feature_set="3.0.6" device="/dev/sdb2" directory="/vm" fstype="ocfs2"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="39" operation="notify" operation_key="configstorecloneset_post_notify_running_0"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="1">
     <action_set>
      <rsc_op id="33" operation="start" operation_key="configstoreclone:0_start_0" on_node="x32c47" on_node_uuid="a1dbc8cc-4d33-41e7-a75a-cd4f93b26410">
        <primitive id="configstoreclone" long-id="configstoreclone:0" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource="configstoreclone:0 configstoreclone:1 " CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource="configstoreclone:0 configstoreclone:1 " CRM_meta_notify_start_uname="x32c47 x32c48 " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_timeout="20000" crm_feature_set="3.0.6" device="/dev/sdb2" directory="/vm" fstype="ocfs2"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
       </trigger>
       <trigger>
         <pseudo_event id="35" operation="start" operation_key="configstorecloneset_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="2">
     <action_set>
      <rsc_op id="8" operation="monitor" operation_key="configstoreclone:0_monitor_0" on_node="x32c47" on_node_uuid="a1dbc8cc-4d33-41e7-a75a-cd4f93b26410">
        <primitive id="configstoreclone" long-id="configstoreclone:0" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" device="/dev/sdb2" directory="/vm" fstype="ocfs2"/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
  <synapse id="3" priority="1000000">
     <action_set>
      <rsc_op id="58" operation="notify" operation_key="configstoreclone:1_post_notify_start_0" on_node="x32c48" on_node_uuid="ca93fea5-67c9-473d-9ce0-7ed7fb823872">
        <primitive id="configstoreclone" long-id="configstoreclone:1" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource="configstoreclone:0 configstoreclone:1 " CRM_meta_notify_key_operation="running" CRM_meta_notify_key_type="post" CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_operation="start" CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource="configstoreclone:0 configstoreclone:1 " CRM_meta_notify_start_uname="x32c47 x32c48 " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_notify_type="post" CRM_meta_timeout="20000" crm_feature_set="3.0.6" device="/dev/sdb2" directory="/vm" fstype="ocfs2"/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="39" operation="notify" operation_key="configstorecloneset_post_notify_running_0"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="4">
     <action_set>
      <rsc_op id="34" operation="start" operation_key="configstoreclone:1_start_0" on_node="x32c48" on_node_uuid="ca93fea5-67c9-473d-9ce0-7ed7fb823872">
        <primitive id="configstoreclone" long-id="configstoreclone:1" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_active_resource=" " CRM_meta_notify_active_uname=" " CRM_meta_notify_demote_resource=" " CRM_meta_notify_demote_uname=" " CRM_meta_notify_inactive_resource="configstoreclone:0 configstoreclone:1 " CRM_meta_notify_master_resource=" " CRM_meta_notify_master_uname=" " CRM_meta_notify_promote_resource=" " CRM_meta_notify_promote_uname=" " CRM_meta_notify_slave_resource=" " CRM_meta_notify_slave_uname=" " CRM_meta_notify_start_resource="configstoreclone:0 configstoreclone:1 " CRM_meta_notify_start_uname="x32c47 x32c48 " CRM_meta_notify_stop_resource=" " CRM_meta_notify_stop_uname=" " CRM_meta_timeout="20000" crm_feature_set="3.0.6" device="/dev/sdb2" directory="/vm" fstype="ocfs2"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
       </trigger>
       <trigger>
         <pseudo_event id="35" operation="start" operation_key="configstorecloneset_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="5">
     <action_set>
      <rsc_op id="6" operation="monitor" operation_key="configstoreclone:1_monitor_0" on_node="x32c48" on_node_uuid="ca93fea5-67c9-473d-9ce0-7ed7fb823872">
        <primitive id="configstoreclone" long-id="configstoreclone:1" class="ocf" provider="heartbeat" type="Filesystem"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.6" device="/dev/sdb2" directory="/vm" fstype="ocfs2"/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
  <synapse id="6" priority="1000000">
     <action_set>
      <pseudo_event id="40" operation="notified" operation_key="configstorecloneset_confirmed-post_notify_running_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_key_operation="running" CRM_meta_notify_key_type="confirmed-post" CRM_meta_notify_operation="start" CRM_meta_notify_type="post" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="39" operation="notify" operation_key="configstorecloneset_post_notify_running_0"/>
      </trigger>
      <trigger>
        <rsc_op id="57" operation="notify" operation_key="configstoreclone:0_post_notify_start_0" on_node="x32c47" on_node_uuid="a1dbc8cc-4d33-41e7-a75a-cd4f93b26410"/>
      </trigger>
      <trigger>
        <rsc_op id="58" operation="notify" operation_key="configstoreclone:1_post_notify_start_0" on_node="x32c48" on_node_uuid="ca93fea5-67c9-473d-9ce0-7ed7fb823872"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="7" priority="1000000">
     <action_set>
      <pseudo_event id="39" operation="notify" operation_key="configstorecloneset_post_notify_running_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_key_operation="running" CRM_meta_notify_key_type="post" CRM_meta_notify_operation="start" CRM_meta_notify_type="post" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="36" operation="running" operation_key="configstorecloneset_running_0"/>
       </trigger>
       <trigger>
        <pseudo_event id="38" operation="notified" operation_key="configstorecloneset_confirmed-pre_notify_start_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="8">
     <action_set>
       <pseudo_event id="38" operation="notified" operation_key="configstorecloneset_confirmed-pre_notify_start_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_key_operation="start" CRM_meta_notify_key_type="confirmed-pre" CRM_meta_notify_operation="start" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="37" operation="notify" operation_key="configstorecloneset_pre_notify_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="9">
     <action_set>
      <pseudo_event id="37" operation="notify" operation_key="configstorecloneset_pre_notify_start_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_notify_key_operation="start" CRM_meta_notify_key_type="pre" CRM_meta_notify_operation="start" CRM_meta_notify_type="pre" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
    <inputs/>
   </synapse>
  <synapse id="10" priority="1000000">
     <action_set>
      <pseudo_event id="36" operation="running" operation_key="configstorecloneset_running_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="33" operation="start" operation_key="configstoreclone:0_start_0" on_node="x32c47" on_node_uuid="a1dbc8cc-4d33-41e7-a75a-cd4f93b26410"/>
       </trigger>
       <trigger>
        <rsc_op id="34" operation="start" operation_key="configstoreclone:1_start_0" on_node="x32c48" on_node_uuid="ca93fea5-67c9-473d-9ce0-7ed7fb823872"/>
       </trigger>
       <trigger>
        <pseudo_event id="35" operation="start" operation_key="configstorecloneset_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="11">
     <action_set>
      <pseudo_event id="35" operation="start" operation_key="configstorecloneset_start_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="true" CRM_meta_timeout="20000" crm_feature_set="3.0.6"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="38" operation="notified" operation_key="configstorecloneset_confirmed-pre_notify_start_0"/>
       </trigger>
    </inputs>
  </synapse>
  <synapse id="12" priority="1000000">
    <action_set>
      <rsc_op id="7" operation="probe_complete" operation_key="probe_complete" on_node="x32c47" on_node_uuid="a1dbc8cc-4d33-41e7-a75a-cd4f93b26410">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.6"/>
      </rsc_op>
    </action_set>
    <inputs>
       <trigger>
        <rsc_op id="8" operation="monitor" operation_key="configstoreclone:0_monitor_0" on_node="x32c47" on_node_uuid="a1dbc8cc-4d33-41e7-a75a-cd4f93b26410"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="13" priority="1000000">
     <action_set>
       <rsc_op id="5" operation="probe_complete" operation_key="probe_complete" on_node="x32c48" on_node_uuid="ca93fea5-67c9-473d-9ce0-7ed7fb823872">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.6"/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="6" operation="monitor" operation_key="configstoreclone:1_monitor_0" on_node="x32c48" on_node_uuid="ca93fea5-67c9-473d-9ce0-7ed7fb823872"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="14">
     <action_set>
      <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete">
        <attributes crm_feature_set="3.0.6"/>
      </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="5" operation="probe_complete" operation_key="probe_complete" on_node="x32c48" on_node_uuid="ca93fea5-67c9-473d-9ce0-7ed7fb823872"/>
      </trigger>
      <trigger>
        <rsc_op id="7" operation="probe_complete" operation_key="probe_complete" on_node="x32c47" on_node_uuid="a1dbc8cc-4d33-41e7-a75a-cd4f93b26410"/>
       </trigger>
     </inputs>
   </synapse>
 </transition_graph>

