<transition_graph cluster-delay="120s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
   <synapse id="0">
     <action_set>
      <rsc_op id="13" operation="monitor" operation_key="child_DoFencing:0_monitor_5000" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3">
        <primitive id="child_DoFencing:0" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="8" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_timeout="20000"  hostlist="hadev1 hadev2 hadev3 "/>
       </rsc_op>
     </action_set>
    <inputs>
      <trigger>
        <rsc_op id="12" operation="start" operation_key="child_DoFencing:0_start_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3"/>
      </trigger>
    </inputs>
   </synapse>
   <synapse id="1">
     <action_set>
      <rsc_op id="12" operation="start" operation_key="child_DoFencing:0_start_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3">
        <primitive id="child_DoFencing:0" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="8" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_requires="nothing" CRM_meta_timeout="20000"  hostlist="hadev1 hadev2 hadev3 "/>
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
       </trigger>
       <trigger>
        <pseudo_event id="14" operation="start" operation_key="DoFencing_start_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="2">
     <action_set>
      <rsc_op id="4" operation="monitor" operation_key="child_DoFencing:0_monitor_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3">
        <primitive id="child_DoFencing:0" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="8" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="hadev1 hadev2 hadev3 "/>
       </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="3">
     <action_set>
      <rsc_op id="5" operation="monitor" operation_key="child_DoFencing:1_monitor_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3">
        <primitive id="child_DoFencing:1" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="8" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="hadev1 hadev2 hadev3 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="4">
     <action_set>
      <rsc_op id="6" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3">
        <primitive id="child_DoFencing:2" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="8" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="hadev1 hadev2 hadev3 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="5">
     <action_set>
      <rsc_op id="7" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3">
        <primitive id="child_DoFencing:3" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="8" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="hadev1 hadev2 hadev3 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="6">
     <action_set>
      <rsc_op id="8" operation="monitor" operation_key="child_DoFencing:4_monitor_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3">
        <primitive id="child_DoFencing:4" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="4" CRM_meta_clone_max="8" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="hadev1 hadev2 hadev3 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="7">
     <action_set>
      <rsc_op id="9" operation="monitor" operation_key="child_DoFencing:5_monitor_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3">
        <primitive id="child_DoFencing:5" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="5" CRM_meta_clone_max="8" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="hadev1 hadev2 hadev3 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="8">
     <action_set>
      <rsc_op id="10" operation="monitor" operation_key="child_DoFencing:6_monitor_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3">
        <primitive id="child_DoFencing:6" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="6" CRM_meta_clone_max="8" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="hadev1 hadev2 hadev3 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="9">
     <action_set>
      <rsc_op id="11" operation="monitor" operation_key="child_DoFencing:7_monitor_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3">
        <primitive id="child_DoFencing:7" class="stonith" type="ssh"/>
        <attributes CRM_meta_clone="7" CRM_meta_clone_max="8" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  hostlist="hadev1 hadev2 hadev3 "/>
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="10" priority="1000000">
     <action_set>
      <pseudo_event id="15" operation="running" operation_key="DoFencing_running_0">
        <attributes CRM_meta_clone_max="8" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="12" operation="start" operation_key="child_DoFencing:0_start_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3"/>
       </trigger>
       <trigger>
        <pseudo_event id="14" operation="start" operation_key="DoFencing_start_0"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="11">
     <action_set>
      <pseudo_event id="14" operation="start" operation_key="DoFencing_start_0">
        <attributes CRM_meta_clone_max="8" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="true" CRM_meta_notify="false" CRM_meta_timeout="20000" />
       </pseudo_event>
     </action_set>
    <inputs/>
   </synapse>
  <synapse id="12" priority="1000000">
     <action_set>
      <rsc_op id="3" operation="probe_complete" operation_key="probe_complete-hadev2" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3">
        <attributes CRM_meta_op_no_wait="true" />
       </rsc_op>
     </action_set>
     <inputs>
       <trigger>
        <rsc_op id="4" operation="monitor" operation_key="child_DoFencing:0_monitor_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3"/>
       </trigger>
       <trigger>
        <rsc_op id="5" operation="monitor" operation_key="child_DoFencing:1_monitor_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3"/>
       </trigger>
       <trigger>
        <rsc_op id="6" operation="monitor" operation_key="child_DoFencing:2_monitor_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3"/>
       </trigger>
       <trigger>
        <rsc_op id="7" operation="monitor" operation_key="child_DoFencing:3_monitor_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3"/>
       </trigger>
       <trigger>
        <rsc_op id="8" operation="monitor" operation_key="child_DoFencing:4_monitor_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3"/>
       </trigger>
       <trigger>
        <rsc_op id="9" operation="monitor" operation_key="child_DoFencing:5_monitor_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3"/>
       </trigger>
       <trigger>
        <rsc_op id="10" operation="monitor" operation_key="child_DoFencing:6_monitor_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3"/>
       </trigger>
       <trigger>
        <rsc_op id="11" operation="monitor" operation_key="child_DoFencing:7_monitor_0" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="13">
    <action_set>
      <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="3" operation="probe_complete" operation_key="probe_complete-hadev2" on_node="hadev2" on_node_uuid="190b75b6-5585-42d9-8cde-eb6041843ae3"/>
      </trigger>
    </inputs>
  </synapse>
 </transition_graph>

