<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="7" operation="start" operation_key="stonith-1_start_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="stonith-1" class="stonith" type="dummy"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="18" operation="stonith_complete" operation_key="stonith_complete"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="4" operation="monitor" operation_key="stonith-1_monitor_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="stonith-1" class="stonith" type="dummy"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="2">
    <action_set>
      <pseudo_event id="15" operation="stopped" operation_key="group1_stopped_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="8" operation="stop" operation_key="rsc1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="10" operation="stop" operation_key="rsc2_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="14" operation="stop" operation_key="group1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <pseudo_event id="14" operation="stop" operation_key="group1_stop_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <crm_event id="19" operation="stonith" operation_key="stonith-node1-reboot" on_node="node1" on_node_uuid="uuid1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <pseudo_event id="13" operation="running" operation_key="group1_running_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="9" operation="start" operation_key="rsc1_start_0" on_node="node2" on_node_uuid="uuid2"/>
      </trigger>
      <trigger>
        <rsc_op id="11" operation="start" operation_key="rsc2_start_0" on_node="node2" on_node_uuid="uuid2"/>
      </trigger>
      <trigger>
        <pseudo_event id="12" operation="start" operation_key="group1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <pseudo_event id="12" operation="start" operation_key="group1_start_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="15" operation="stopped" operation_key="group1_stopped_0"/>
      </trigger>
      <trigger>
        <rsc_op id="17" operation="start" operation_key="rsc3_start_0" on_node="node2" on_node_uuid="uuid2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <rsc_op id="9" operation="start" operation_key="rsc1_start_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="rsc1" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="8" operation="stop" operation_key="rsc1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="12" operation="start" operation_key="group1_start_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="18" operation="stonith_complete" operation_key="stonith_complete"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <pseudo_event id="8" operation="stop" operation_key="rsc1_stop_0">
        <attributes CRM_meta_name="stop" CRM_meta_on_fail="block" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="10" operation="stop" operation_key="rsc2_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="14" operation="stop" operation_key="group1_stop_0"/>
      </trigger>
      <trigger>
        <crm_event id="19" operation="stonith" operation_key="stonith-node1-reboot" on_node="node1" on_node_uuid="uuid1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <rsc_op id="5" operation="monitor" operation_key="rsc1_monitor_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="rsc1" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="9">
    <action_set>
      <rsc_op id="11" operation="start" operation_key="rsc2_start_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="rsc2" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <rsc_op id="9" operation="start" operation_key="rsc1_start_0" on_node="node2" on_node_uuid="uuid2"/>
      </trigger>
      <trigger>
        <pseudo_event id="10" operation="stop" operation_key="rsc2_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="12" operation="start" operation_key="group1_start_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="18" operation="stonith_complete" operation_key="stonith_complete"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="10">
    <action_set>
      <pseudo_event id="10" operation="stop" operation_key="rsc2_stop_0">
        <attributes CRM_meta_name="stop" CRM_meta_on_fail="block" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="14" operation="stop" operation_key="group1_stop_0"/>
      </trigger>
      <trigger>
        <crm_event id="19" operation="stonith" operation_key="stonith-node1-reboot" on_node="node1" on_node_uuid="uuid1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="11">
    <action_set>
      <rsc_op id="6" operation="monitor" operation_key="rsc2_monitor_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="rsc2" class="heartbeat" type="apache"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="12">
    <action_set>
      <rsc_op id="17" operation="start" operation_key="rsc3_start_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="rsc3" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="16" operation="stop" operation_key="rsc3_stop_0" on_node="node2" on_node_uuid="uuid2"/>
      </trigger>
      <trigger>
        <pseudo_event id="18" operation="stonith_complete" operation_key="stonith_complete"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="13">
    <action_set>
      <rsc_op id="16" operation="stop" operation_key="rsc3_stop_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="rsc3" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="15" operation="stopped" operation_key="group1_stopped_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="14">
    <action_set>
      <crm_event id="19" operation="stonith" operation_key="stonith-node1-reboot" on_node="node1" on_node_uuid="uuid1">
        <attributes CRM_meta_on_node="node1" CRM_meta_on_node_uuid="uuid1" CRM_meta_stonith_action="reboot" />
      </crm_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="15">
    <action_set>
      <pseudo_event id="18" operation="stonith_complete" operation_key="stonith_complete">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <crm_event id="19" operation="stonith" operation_key="stonith-node1-reboot" on_node="node1" on_node_uuid="uuid1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="16" priority="1000000">
    <action_set>
      <rsc_op id="3" operation="probe_complete" operation_key="probe_complete-node2" on_node="node2" on_node_uuid="uuid2">
        <attributes CRM_meta_op_no_wait="true" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="4" operation="monitor" operation_key="stonith-1_monitor_0" on_node="node2" on_node_uuid="uuid2"/>
      </trigger>
      <trigger>
        <rsc_op id="5" operation="monitor" operation_key="rsc1_monitor_0" on_node="node2" on_node_uuid="uuid2"/>
      </trigger>
      <trigger>
        <rsc_op id="6" operation="monitor" operation_key="rsc2_monitor_0" on_node="node2" on_node_uuid="uuid2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="17">
    <action_set>
      <pseudo_event id="2" operation="probe_complete" operation_key="probe_complete">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="3" operation="probe_complete" operation_key="probe_complete-node2" on_node="node2" on_node_uuid="uuid2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="18">
    <action_set>
      <pseudo_event id="1" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="8" operation="stop" operation_key="rsc1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="10" operation="stop" operation_key="rsc2_stop_0"/>
      </trigger>
      <trigger>
        <rsc_op id="16" operation="stop" operation_key="rsc3_stop_0" on_node="node2" on_node_uuid="uuid2"/>
      </trigger>
      <trigger>
        <pseudo_event id="18" operation="stonith_complete" operation_key="stonith_complete"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

