 <transition_graph cluster-delay="3m" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
   <synapse id="0">
     <action_set>
       <pseudo_event id="2" operation="stop" operation_key="ocf_msdummy:6_stop_0">
         <attributes CRM_meta_clone="6" CRM_meta_clone_max="12" CRM_meta_clone_node_max="2" CRM_meta_master_max="6" CRM_meta_master_node_max="1" CRM_meta_timeout="20000" crm_feature_set="3.0"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="82" operation="stop" operation_key="master_rsc_1_stop_0"/>
       </trigger>
       <trigger>
         <crm_event id="89" operation="stonith" operation_key="stonith" on_node="c001n04" on_node_uuid="9e080e6d-7a25-4dac-be89-f6f4f128623d"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="1">
     <action_set>
       <pseudo_event id="82" operation="stop" operation_key="master_rsc_1_stop_0">
         <attributes CRM_meta_clone_max="12" CRM_meta_clone_node_max="2" CRM_meta_master_max="6" CRM_meta_master_node_max="1" CRM_meta_timeout="20000" crm_feature_set="3.0"/>
       </pseudo_event>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="2" priority="1000000">
     <action_set>
       <pseudo_event id="83" operation="stopped" operation_key="master_rsc_1_stopped_0">
         <attributes CRM_meta_clone_max="12" CRM_meta_clone_node_max="2" CRM_meta_master_max="6" CRM_meta_master_node_max="1" CRM_meta_stateful="true" CRM_meta_timeout="20000" crm_feature_set="3.0"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="2" operation="stop" operation_key="ocf_msdummy:6_stop_0"/>
       </trigger>
       <trigger>
         <pseudo_event id="82" operation="stop" operation_key="master_rsc_1_stop_0"/>
       </trigger>
     </inputs>
   </synapse>
   <synapse id="3">
     <action_set>
       <pseudo_event id="22" operation="all_stopped" operation_key="all_stopped">
         <attributes crm_feature_set="3.0"/>
       </pseudo_event>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="2" operation="stop" operation_key="ocf_msdummy:6_stop_0"/>
       </trigger>
       <trigger>
        <rsc_op id="67" operation="stop" operation_key="ocf_msdummy:0_stop_0" on_node="c001n02" on_node_uuid="e8973f32-1c97-40cb-a84a-c489f49664a5"/>
      </trigger>
      <trigger>
        <rsc_op id="70" operation="stop" operation_key="ocf_msdummy:10_stop_0" on_node="c001n06" on_node_uuid="169e4673-93fb-4c0a-8082-d3408bae9431"/>
      </trigger>
      <trigger>
        <rsc_op id="72" operation="stop" operation_key="ocf_msdummy:11_stop_0" on_node="c001n07" on_node_uuid="6637ebb5-ab11-4728-b69e-b61222af9a0c"/>
      </trigger>
      <trigger>
        <rsc_op id="74" operation="stop" operation_key="ocf_msdummy:4_stop_0" on_node="c001n02" on_node_uuid="e8973f32-1c97-40cb-a84a-c489f49664a5"/>
      </trigger>
      <trigger>
        <rsc_op id="76" operation="stop" operation_key="ocf_msdummy:8_stop_0" on_node="c001n06" on_node_uuid="169e4673-93fb-4c0a-8082-d3408bae9431"/>
      </trigger>
      <trigger>
        <rsc_op id="78" operation="stop" operation_key="ocf_msdummy:9_stop_0" on_node="c001n07" on_node_uuid="6637ebb5-ab11-4728-b69e-b61222af9a0c"/>
      </trigger>
      <trigger>
         <crm_event id="89" operation="stonith" operation_key="stonith" on_node="c001n04" on_node_uuid="9e080e6d-7a25-4dac-be89-f6f4f128623d"/>
       </trigger>
     </inputs>
   </synapse>
  <synapse id="48">
     <action_set>
       <pseudo_event id="88" operation="stonith_up" operation_key="stonith_up">
         <attributes crm_feature_set="3.0"/>
       </pseudo_event>
     </action_set>
    <inputs>
      <trigger>
        <rsc_op id="24" operation="start" operation_key="child_DoFencing:3_start_0" on_node="c001n02" on_node_uuid="e8973f32-1c97-40cb-a84a-c489f49664a5"/>
      </trigger>
      <trigger>
        <rsc_op id="28" operation="start" operation_key="child_DoFencing:5_start_0" on_node="c001n07" on_node_uuid="6637ebb5-ab11-4728-b69e-b61222af9a0c"/>
      </trigger>
      <trigger>
        <rsc_op id="31" operation="start" operation_key="child_DoFencing:4_start_0" on_node="c001n06" on_node_uuid="169e4673-93fb-4c0a-8082-d3408bae9431"/>
      </trigger>
    </inputs>
   </synapse>
  <synapse id="49">
     <action_set>
       <crm_event id="89" operation="stonith" operation_key="stonith" on_node="c001n04" on_node_uuid="9e080e6d-7a25-4dac-be89-f6f4f128623d">
         <attributes CRM_meta_on_node="c001n04" CRM_meta_on_node_uuid="9e080e6d-7a25-4dac-be89-f6f4f128623d" CRM_meta_op_no_wait="true" CRM_meta_stonith_action="reboot" crm_feature_set="3.0"/>
       </crm_event>
     </action_set>
     <inputs>
       <trigger>
         <pseudo_event id="88" operation="stonith_up" operation_key="stonith_up"/>
       </trigger>
     </inputs>
   </synapse>
 </transition_graph>

