 <transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
   <synapse id="0">
     <action_set>
      <rsc_op id="2" operation="stop" operation_key="rsc1_stop_0" on_node="node2" on_node_uuid="uuid2">
        <primitive id="rsc1" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
   <synapse id="1">
     <action_set>
      <rsc_op id="1" operation="stop" operation_key="rsc1_stop_0" on_node="node1" on_node_uuid="uuid1">
        <primitive id="rsc1" class="heartbeat" type="apache"/>
        <attributes CRM_meta_timeout="20000" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="2" priority="1000000">
     <action_set>
      <rsc_op id="6" operation="probe_complete" operation_key="probe_complete-node2" on_node="node2" on_node_uuid="uuid2">
        <attributes CRM_meta_op_no_wait="true" />
      </rsc_op>
     </action_set>
    <inputs/>
   </synapse>
   <synapse id="3" priority="1000000">
     <action_set>
      <rsc_op id="5" operation="probe_complete" operation_key="probe_complete-node1" on_node="node1" on_node_uuid="uuid1">
        <attributes CRM_meta_op_no_wait="true" />
       </rsc_op>
     </action_set>
     <inputs/>
   </synapse>
  <synapse id="4">
     <action_set>
      <pseudo_event id="3" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
     </action_set>
    <inputs>
      <trigger>
        <rsc_op id="1" operation="stop" operation_key="rsc1_stop_0" on_node="node1" on_node_uuid="uuid1"/>
      </trigger>
      <trigger>
        <rsc_op id="2" operation="stop" operation_key="rsc1_stop_0" on_node="node2" on_node_uuid="uuid2"/>
      </trigger>
    </inputs>
   </synapse>
 </transition_graph>

