<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="5" operation="stop" operation_key="c7auto4_stop_0" on_node="c7auto1" on_node_uuid="1">
        <primitive id="c7auto4" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_name="stop" CRM_meta_on_node="c7auto1" CRM_meta_on_node_uuid="1" CRM_meta_timeout="60000"  reconnect_interval="1m"/>
        <downed>
          <node id="c7auto4"/>
        </downed>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="14" operation="stop" operation_key="fake2_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="16" operation="monitor" operation_key="fake2_monitor_10000" on_node="c7auto1" on_node_uuid="1">
        <primitive id="fake2" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_on_node="c7auto1" CRM_meta_on_node_uuid="1" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="15" operation="start" operation_key="fake2_start_0" on_node="c7auto1" on_node_uuid="1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="15" operation="start" operation_key="fake2_start_0" on_node="c7auto1" on_node_uuid="1">
        <primitive id="fake2" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_name="start" CRM_meta_on_node="c7auto1" CRM_meta_on_node_uuid="1" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="14" operation="stop" operation_key="fake2_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="23" operation="stonith_complete" operation_key="stonith_complete"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <pseudo_event id="14" operation="stop" operation_key="fake2_stop_0">
        <attributes CRM_meta_name="stop" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <crm_event id="4" operation="stonith" operation_key="stonith-c7auto4-reboot" on_node="c7auto4" on_node_uuid="c7auto4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <pseudo_event id="23" operation="stonith_complete" operation_key="stonith_complete">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <crm_event id="4" operation="stonith" operation_key="stonith-c7auto4-reboot" on_node="c7auto4" on_node_uuid="c7auto4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <pseudo_event id="9" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="stop" operation_key="c7auto4_stop_0" on_node="c7auto1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <pseudo_event id="14" operation="stop" operation_key="fake2_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="23" operation="stonith_complete" operation_key="stonith_complete"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <crm_event id="4" operation="stonith" operation_key="stonith-c7auto4-reboot" on_node="c7auto4" on_node_uuid="c7auto4">
        <attributes CRM_meta_on_node="c7auto4" CRM_meta_on_node_uuid="c7auto4" CRM_meta_probe_complete="true" CRM_meta_stonith_action="reboot" />
        <downed>
          <node id="c7auto4"/>
        </downed>
      </crm_event>
    </action_set>
    <inputs/>
  </synapse>
</transition_graph>
