<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="1" batch-limit="10" transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="33" operation="monitor" operation_key="rsc_18node2_monitor_5000" on_node="18node1" on_node_uuid="1">
        <primitive id="rsc_18node2" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_interval="5000" CRM_meta_name="monitor" CRM_meta_timeout="90000" cidr_netmask="32" crm_feature_set="3.0.7" ip="192.168.122.85"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="32" operation="start" operation_key="rsc_18node2_start_0" on_node="18node1" on_node_uuid="1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="32" operation="start" operation_key="rsc_18node2_start_0" on_node="18node1" on_node_uuid="1">
        <primitive id="rsc_18node2" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_timeout="90000" cidr_netmask="32" crm_feature_set="3.0.7" ip="192.168.122.85"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="31" operation="stop" operation_key="rsc_18node2_stop_0" on_node="remote1" on_node_uuid="remote1" router_node="18node1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="31" operation="stop" operation_key="rsc_18node2_stop_0" on_node="remote1" on_node_uuid="remote1" router_node="18node1">
        <primitive id="rsc_18node2" class="ocf" provider="heartbeat" type="IPaddr2"/>
        <attributes CRM_meta_timeout="90000" cidr_netmask="32" crm_feature_set="3.0.7" ip="192.168.122.85"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="3">
    <action_set>
      <rsc_op id="42" operation="stop" operation_key="ping-1_stop_0" internal_operation_key="ping-1:2_stop_0" on_node="remote1" on_node_uuid="remote1" router_node="18node1">
        <primitive id="ping-1" long-id="ping-1:2" class="ocf" provider="pacemaker" type="ping"/>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="90000" crm_feature_set="3.0.7" debug="true" host_list="192.168.122.80" name="connected"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="45" operation="stop" operation_key="Connectivity_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4" priority="1000000">
    <action_set>
      <pseudo_event id="46" operation="stopped" operation_key="Connectivity_stopped_0">
        <attributes CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="90000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="42" operation="stop" operation_key="ping-1_stop_0" internal_operation_key="ping-1:2_stop_0" on_node="remote1" on_node_uuid="remote1" router_node="18node1"/>
      </trigger>
      <trigger>
        <pseudo_event id="45" operation="stop" operation_key="Connectivity_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <pseudo_event id="45" operation="stop" operation_key="Connectivity_stop_0">
        <attributes CRM_meta_clone_max="3" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="90000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="6">
    <action_set>
      <rsc_op id="73" operation="stop" operation_key="remote1_stop_0" on_node="18node1" on_node_uuid="1">
        <primitive id="remote1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_timeout="90000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="31" operation="stop" operation_key="rsc_18node2_stop_0" on_node="remote1" on_node_uuid="remote1" router_node="18node1"/>
      </trigger>
      <trigger>
        <rsc_op id="42" operation="stop" operation_key="ping-1_stop_0" internal_operation_key="ping-1:2_stop_0" on_node="remote1" on_node_uuid="remote1" router_node="18node1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <rsc_op id="17" operation="delete" operation_key="remote1_delete_0" on_node="18node3" on_node_uuid="3">
        <primitive id="remote1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_timeout="90000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="73" operation="stop" operation_key="remote1_stop_0" on_node="18node1" on_node_uuid="1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <rsc_op id="16" operation="delete" operation_key="remote1_delete_0" on_node="18node1" on_node_uuid="1">
        <primitive id="remote1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_timeout="90000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="73" operation="stop" operation_key="remote1_stop_0" on_node="18node1" on_node_uuid="1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9">
    <action_set>
      <pseudo_event id="15" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="31" operation="stop" operation_key="rsc_18node2_stop_0" on_node="remote1" on_node_uuid="remote1" router_node="18node1"/>
      </trigger>
      <trigger>
        <rsc_op id="42" operation="stop" operation_key="ping-1_stop_0" internal_operation_key="ping-1:2_stop_0" on_node="remote1" on_node_uuid="remote1" router_node="18node1"/>
      </trigger>
      <trigger>
        <rsc_op id="73" operation="stop" operation_key="remote1_stop_0" on_node="18node1" on_node_uuid="1"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>
