 <transition_graph global_timeout="60s" transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="1" rsc_id="rsc2" operation="start" on_node="node2" on_node_uuid="node2" allow_fail="false">
         <primitive id="rsc2" class="heartbeat" type="apache"/>
         <attributes>
           <nvpair name="priority" value="2.0"/>
         </attributes>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="2" rsc_id="rsc1" operation="stop" on_node="node2" on_node_uuid="node2" allow_fail="false">
         <primitive id="rsc1" class="heartbeat" type="apache"/>
         <attributes>
           <nvpair name="priority" value="1.0"/>
         </attributes>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="3" rsc_id="rsc1" operation="start" on_node="node1" on_node_uuid="node1" allow_fail="false">
         <primitive id="rsc1" class="heartbeat" type="apache"/>
         <attributes>
           <nvpair name="priority" value="1.0"/>
         </attributes>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="2" rsc_id="rsc1" operation="stop" on_node="node2" on_node_uuid="node2" allow_fail="false"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

