<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0">
    <action_set>
      <pseudo_event id="9" operation="stop" operation_key="clvm_stop_0" internal_operation_key="clvm:0_stop_0">
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="14" operation="stop" operation_key="clvm-clone_stop_0"/>
      </trigger>
      <trigger>
        <crm_event id="20" operation="stonith" operation_key="stonith-pcmk-2-reboot" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1" priority="1000000">
    <action_set>
      <pseudo_event id="15" operation="stopped" operation_key="clvm-clone_stopped_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="9" operation="stop" operation_key="clvm_stop_0" internal_operation_key="clvm:0_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="14" operation="stop" operation_key="clvm-clone_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <pseudo_event id="14" operation="stop" operation_key="clvm-clone_stop_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <crm_event id="20" operation="stonith" operation_key="stonith-pcmk-2-reboot" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <rsc_op id="2" operation="monitor" operation_key="Fencing_monitor_0" on_node="pcmk-1" on_node_uuid="101">
        <primitive id="Fencing" class="stonith" type="fence_xvm"/>
        <attributes CRM_meta_on_node="pcmk-1" CRM_meta_on_node_uuid="101" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="4">
    <action_set>
      <crm_event id="20" operation="stonith" operation_key="stonith-pcmk-2-reboot" on_node="pcmk-2" on_node_uuid="102">
        <attributes CRM_meta_fail_count_clvm="INFINITY" CRM_meta_last_failure_clvm="1371014555" CRM_meta_on_node="pcmk-2" CRM_meta_on_node_uuid="102" CRM_meta_probe_complete="true" CRM_meta_shutdown="1371014551" CRM_meta_stonith_action="reboot" />
        <downed>
          <node id="102"/>
        </downed>
      </crm_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="5">
    <action_set>
      <pseudo_event id="19" operation="stonith_complete" operation_key="stonith_complete">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <crm_event id="20" operation="stonith" operation_key="stonith-pcmk-2-reboot" on_node="pcmk-2" on_node_uuid="102"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <pseudo_event id="1" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="9" operation="stop" operation_key="clvm_stop_0" internal_operation_key="clvm:0_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="19" operation="stonith_complete" operation_key="stonith_complete"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>
