<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="4" operation="monitor" operation_key="Fencing_monitor_0" on_node="node3" on_node_uuid="3">
        <primitive id="Fencing" class="stonith" type="fence_xvm"/>
        <attributes CRM_meta_on_node="node3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="120000"  multicast_address="239.255.100.100" pcmk_host_list="node1 node2 node3"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="3" operation="monitor" operation_key="Fencing_monitor_0" on_node="node2" on_node_uuid="2">
        <primitive id="Fencing" class="stonith" type="fence_xvm"/>
        <attributes CRM_meta_on_node="node2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="120000"  multicast_address="239.255.100.100" pcmk_host_list="node1 node2 node3"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="2" operation="monitor" operation_key="Fencing_monitor_0" on_node="node1" on_node_uuid="1">
        <primitive id="Fencing" class="stonith" type="fence_xvm"/>
        <attributes CRM_meta_on_node="node1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="120000"  multicast_address="239.255.100.100" pcmk_host_list="node1 node2 node3"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
</transition_graph>
