<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <pseudo_event id="4" operation="stop" operation_key="rsc_stonith_stop_0">
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <crm_event id="12" operation="stonith" operation_key="stonith-node1" on_node="node1" on_node_uuid="node1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <pseudo_event id="5" operation="stop" operation_key="rsc1:1_stop_0" internal_operation_key="rsc1:0_stop_0">
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="9" operation="stop" operation_key="clone1_stop_0"/>
      </trigger>
      <trigger>
        <crm_event id="12" operation="stonith" operation_key="stonith-node1" on_node="node1" on_node_uuid="node1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <pseudo_event id="6" operation="stop" operation_key="rsc1:0_stop_0" internal_operation_key="rsc1:1_stop_0">
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="9" operation="stop" operation_key="clone1_stop_0"/>
      </trigger>
      <trigger>
        <crm_event id="13" operation="stonith" operation_key="stonith-node2" on_node="node2" on_node_uuid="node2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3" priority="1000000">
    <action_set>
      <pseudo_event id="10" operation="stopped" operation_key="clone1_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="5" operation="stop" operation_key="rsc1:1_stop_0" internal_operation_key="rsc1:0_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="6" operation="stop" operation_key="rsc1:0_stop_0" internal_operation_key="rsc1:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="9" operation="stop" operation_key="clone1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <pseudo_event id="9" operation="stop" operation_key="clone1_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <crm_event id="12" operation="stonith" operation_key="stonith-node1" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <crm_event id="13" operation="stonith" operation_key="stonith-node2" on_node="node2" on_node_uuid="node2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <crm_event id="13" operation="stonith" operation_key="stonith-node2" on_node="node2" on_node_uuid="node2">
        <attributes CRM_meta_on_node="node2" CRM_meta_on_node_uuid="node2" CRM_meta_stonith_action="reboot" crm_feature_set="3.0.7"/>
      </crm_event>
    </action_set>
    <inputs>
      <trigger>
        <crm_event id="12" operation="stonith" operation_key="stonith-node1" on_node="node1" on_node_uuid="node1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <crm_event id="12" operation="stonith" operation_key="stonith-node1" on_node="node1" on_node_uuid="node1">
        <attributes CRM_meta_on_node="node1" CRM_meta_on_node_uuid="node1" CRM_meta_stonith_action="reboot" crm_feature_set="3.0.7"/>
      </crm_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="7">
    <action_set>
      <pseudo_event id="11" operation="stonith_complete" operation_key="stonith_complete">
        <attributes crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <crm_event id="13" operation="stonith" operation_key="stonith-node2" on_node="node2" on_node_uuid="node2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <pseudo_event id="3" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="stop" operation_key="rsc_stonith_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="5" operation="stop" operation_key="rsc1:1_stop_0" internal_operation_key="rsc1:0_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="6" operation="stop" operation_key="rsc1:0_stop_0" internal_operation_key="rsc1:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="11" operation="stonith_complete" operation_key="stonith_complete"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

