<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="9" operation="stop" operation_key="rsc1_stop_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc1" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_on_node="node2" CRM_meta_on_node_uuid="node2" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="1">
    <action_set>
      <pseudo_event id="15" operation="stopped" operation_key="group2_stopped_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="10" operation="stop" operation_key="rsc2_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <rsc_op id="11" operation="stop" operation_key="rsc3_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <pseudo_event id="14" operation="stop" operation_key="group2_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <pseudo_event id="14" operation="stop" operation_key="group2_stop_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="3">
    <action_set>
      <rsc_op id="10" operation="stop" operation_key="rsc2_stop_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc2" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_on_node="node1" CRM_meta_on_node_uuid="node1" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="11" operation="stop" operation_key="rsc3_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <pseudo_event id="14" operation="stop" operation_key="group2_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <rsc_op id="11" operation="stop" operation_key="rsc3_stop_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc3" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_on_node="node1" CRM_meta_on_node_uuid="node1" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="14" operation="stop" operation_key="group2_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <rsc_op id="16" operation="stop" operation_key="rsc4:1_stop_0" internal_operation_key="rsc4:0_stop_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc4" long-id="rsc4:1" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_on_node="node1" CRM_meta_on_node_uuid="node1" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="20" operation="stop" operation_key="clone4_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <rsc_op id="17" operation="stop" operation_key="rsc4:0_stop_0" internal_operation_key="rsc4:1_stop_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc4" long-id="rsc4:0" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_on_node="node2" CRM_meta_on_node_uuid="node2" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="20" operation="stop" operation_key="clone4_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7" priority="1000000">
    <action_set>
      <pseudo_event id="21" operation="stopped" operation_key="clone4_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="16" operation="stop" operation_key="rsc4:1_stop_0" internal_operation_key="rsc4:0_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <rsc_op id="17" operation="stop" operation_key="rsc4:0_stop_0" internal_operation_key="rsc4:1_stop_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
      <trigger>
        <pseudo_event id="20" operation="stop" operation_key="clone4_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <pseudo_event id="20" operation="stop" operation_key="clone4_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="9">
    <action_set>
      <rsc_op id="23" operation="demote" operation_key="rsc5:1_demote_0" internal_operation_key="rsc5:0_demote_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc5" long-id="rsc5:1" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_on_node="node1" CRM_meta_on_node_uuid="node1" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="33" operation="demote" operation_key="ms5_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="10" priority="1000000">
    <action_set>
      <pseudo_event id="34" operation="demoted" operation_key="ms5_demoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="23" operation="demote" operation_key="rsc5:1_demote_0" internal_operation_key="rsc5:0_demote_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <pseudo_event id="33" operation="demote" operation_key="ms5_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="11">
    <action_set>
      <pseudo_event id="33" operation="demote" operation_key="ms5_demote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="12">
    <action_set>
      <pseudo_event id="6" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="9" operation="stop" operation_key="rsc1_stop_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
      <trigger>
        <rsc_op id="10" operation="stop" operation_key="rsc2_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <rsc_op id="11" operation="stop" operation_key="rsc3_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <rsc_op id="16" operation="stop" operation_key="rsc4:1_stop_0" internal_operation_key="rsc4:0_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
      <trigger>
        <rsc_op id="17" operation="stop" operation_key="rsc4:0_stop_0" internal_operation_key="rsc4:1_stop_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

