<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0">
    <action_set>
      <pseudo_event id="9" operation="stop" operation_key="group1_stop_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="1" priority="1000000">
    <action_set>
      <rsc_op id="4" operation="probe_complete" operation_key="probe_complete-yingying.site" on_node="yingying.site" on_node_uuid="yingying.site">
        <attributes CRM_meta_op_no_wait="true" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
</transition_graph>

