<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0" priority="1">
    <action_set>
      <rsc_op id="7" operation="start" operation_key="rsc2_start_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc2" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="3" operation="load_stopped_node1" operation_key="load_stopped_node1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1" priority="1000000">
    <action_set>
      <rsc_op id="12" operation="migrate_from" operation_key="rsc1_migrate_from_0" on_node="node2" on_node_uuid="node2">
        <primitive id="rsc1" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_migrate_source="node1" CRM_meta_migrate_target="node2" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="11" operation="migrate_to" operation_key="rsc1_migrate_to_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="11" operation="migrate_to" operation_key="rsc1_migrate_to_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc1" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_migrate_source="node1" CRM_meta_migrate_target="node2" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="3">
    <action_set>
      <pseudo_event id="9" operation="start" operation_key="rsc1_start_0">
        <attributes CRM_meta_timeout="20000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="2" operation="load_stopped_node2" operation_key="load_stopped_node2"/>
      </trigger>
      <trigger>
        <rsc_op id="8" operation="stop" operation_key="rsc1_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <rsc_op id="8" operation="stop" operation_key="rsc1_stop_0" on_node="node1" on_node_uuid="node1">
        <primitive id="rsc1" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="12" operation="migrate_from" operation_key="rsc1_migrate_from_0" on_node="node2" on_node_uuid="node2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5" priority="1000000">
    <action_set>
      <rsc_op id="6" operation="probe_complete" operation_key="probe_complete" on_node="node2" on_node_uuid="node2">
        <attributes CRM_meta_op_no_wait="true" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="6" priority="1000000">
    <action_set>
      <rsc_op id="5" operation="probe_complete" operation_key="probe_complete" on_node="node1" on_node_uuid="node1">
        <attributes CRM_meta_op_no_wait="true" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="7">
    <action_set>
      <pseudo_event id="3" operation="load_stopped_node1" operation_key="load_stopped_node1">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="8" operation="stop" operation_key="rsc1_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <pseudo_event id="2" operation="load_stopped_node2" operation_key="load_stopped_node2">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="9">
    <action_set>
      <pseudo_event id="1" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="8" operation="stop" operation_key="rsc1_stop_0" on_node="node1" on_node_uuid="node1"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

