<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="1"  transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="40" operation="start" operation_key="FencingPass_start_0" on_node="rhel7-2" on_node_uuid="2">
        <primitive id="FencingPass" class="stonith" type="fence_dummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="FencingPass-instance_attributes-gt" score="3">
            <rule id="FencingPass-gt-rule" score="INFINITY">
              <expression id="FencingPass-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="3.5"/>
            </rule>
            <nvpair id="FencingPass-gt-random_sleep_range" name="random_sleep_range" value="4"/>
          </instance_attributes>
          <instance_attributes id="FencingPass-params">
            <nvpair id="FencingPass-random_sleep_range" name="random_sleep_range" value="3"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-2" CRM_meta_on_node_uuid="2" CRM_meta_timeout="90000"  mode="pass" pcmk_host_list="rhel7-3" random_sleep_range="3"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="3" operation="monitor" operation_key="FencingPass_monitor_0" on_node="rhel7-1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="10" operation="monitor" operation_key="FencingPass_monitor_0" on_node="rhel7-2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="17" operation="monitor" operation_key="FencingPass_monitor_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="24" operation="monitor" operation_key="FencingPass_monitor_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="31" operation="monitor" operation_key="FencingPass_monitor_0" on_node="rhel7-5" on_node_uuid="5"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="31" operation="monitor" operation_key="FencingPass_monitor_0" on_node="rhel7-5" on_node_uuid="5">
        <primitive id="FencingPass" class="stonith" type="fence_dummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="FencingPass-instance_attributes-gt" score="3">
            <rule id="FencingPass-gt-rule" score="INFINITY">
              <expression id="FencingPass-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="3.5"/>
            </rule>
            <nvpair id="FencingPass-gt-random_sleep_range" name="random_sleep_range" value="4"/>
          </instance_attributes>
          <instance_attributes id="FencingPass-params">
            <nvpair id="FencingPass-random_sleep_range" name="random_sleep_range" value="3"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="90000"  mode="pass" pcmk_host_list="rhel7-3" random_sleep_range="3"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="24" operation="monitor" operation_key="FencingPass_monitor_0" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="FencingPass" class="stonith" type="fence_dummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="FencingPass-instance_attributes-gt" score="3">
            <rule id="FencingPass-gt-rule" score="INFINITY">
              <expression id="FencingPass-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="3.5"/>
            </rule>
            <nvpair id="FencingPass-gt-random_sleep_range" name="random_sleep_range" value="4"/>
          </instance_attributes>
          <instance_attributes id="FencingPass-params">
            <nvpair id="FencingPass-random_sleep_range" name="random_sleep_range" value="3"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="90000"  mode="pass" pcmk_host_list="rhel7-3" random_sleep_range="3"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="3">
    <action_set>
      <rsc_op id="17" operation="monitor" operation_key="FencingPass_monitor_0" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="FencingPass" class="stonith" type="fence_dummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="FencingPass-instance_attributes-gt" score="3">
            <rule id="FencingPass-gt-rule" score="INFINITY">
              <expression id="FencingPass-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="3.5"/>
            </rule>
            <nvpair id="FencingPass-gt-random_sleep_range" name="random_sleep_range" value="4"/>
          </instance_attributes>
          <instance_attributes id="FencingPass-params">
            <nvpair id="FencingPass-random_sleep_range" name="random_sleep_range" value="3"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="90000"  mode="pass" pcmk_host_list="rhel7-3" random_sleep_range="3"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="4">
    <action_set>
      <rsc_op id="10" operation="monitor" operation_key="FencingPass_monitor_0" on_node="rhel7-2" on_node_uuid="2">
        <primitive id="FencingPass" class="stonith" type="fence_dummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="FencingPass-instance_attributes-gt" score="3">
            <rule id="FencingPass-gt-rule" score="INFINITY">
              <expression id="FencingPass-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="3.5"/>
            </rule>
            <nvpair id="FencingPass-gt-random_sleep_range" name="random_sleep_range" value="4"/>
          </instance_attributes>
          <instance_attributes id="FencingPass-params">
            <nvpair id="FencingPass-random_sleep_range" name="random_sleep_range" value="3"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="90000"  mode="pass" pcmk_host_list="rhel7-3" random_sleep_range="3"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="5">
    <action_set>
      <rsc_op id="3" operation="monitor" operation_key="FencingPass_monitor_0" on_node="rhel7-1" on_node_uuid="1">
        <primitive id="FencingPass" class="stonith" type="fence_dummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="FencingPass-instance_attributes-gt" score="3">
            <rule id="FencingPass-gt-rule" score="INFINITY">
              <expression id="FencingPass-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="3.5"/>
            </rule>
            <nvpair id="FencingPass-gt-random_sleep_range" name="random_sleep_range" value="4"/>
          </instance_attributes>
          <instance_attributes id="FencingPass-params">
            <nvpair id="FencingPass-random_sleep_range" name="random_sleep_range" value="3"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="90000"  mode="pass" pcmk_host_list="rhel7-3" random_sleep_range="3"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="6">
    <action_set>
      <rsc_op id="42" operation="monitor" operation_key="vtest4_monitor_10000" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="vtest4" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest4-instance_attributes-lte-ne" score="3">
            <rule id="vtest4-lte-ne-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest4-lte-ne-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="vtest4-instance_attributes-lte-ne-fake" name="fake" value="old+false"/>
          </instance_attributes>
          <instance_attributes id="vtest4-instance_attributes-gt-ne" score="3">
            <rule id="vtest4-gt-ne-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest4-gt-ne-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="vtest4-instance_attributes-gt-ne-fake" name="new_fake" value="new+false"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest4.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="41" operation="start" operation_key="vtest4_start_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <rsc_op id="41" operation="start" operation_key="vtest4_start_0" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="vtest4" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest4-instance_attributes-lte-ne" score="3">
            <rule id="vtest4-lte-ne-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest4-lte-ne-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="vtest4-instance_attributes-lte-ne-fake" name="fake" value="old+false"/>
          </instance_attributes>
          <instance_attributes id="vtest4-instance_attributes-gt-ne" score="3">
            <rule id="vtest4-gt-ne-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest4-gt-ne-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="vtest4-instance_attributes-gt-ne-fake" name="new_fake" value="new+false"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_name="start" CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest4.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="4" operation="monitor" operation_key="vtest4_monitor_0" on_node="rhel7-1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="11" operation="monitor" operation_key="vtest4_monitor_0" on_node="rhel7-2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="18" operation="monitor" operation_key="vtest4_monitor_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="25" operation="monitor" operation_key="vtest4_monitor_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="32" operation="monitor" operation_key="vtest4_monitor_0" on_node="rhel7-5" on_node_uuid="5"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <rsc_op id="32" operation="monitor" operation_key="vtest4_monitor_0" on_node="rhel7-5" on_node_uuid="5">
        <primitive id="vtest4" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest4-instance_attributes-lte-ne" score="3">
            <rule id="vtest4-lte-ne-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest4-lte-ne-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="vtest4-instance_attributes-lte-ne-fake" name="fake" value="old+false"/>
          </instance_attributes>
          <instance_attributes id="vtest4-instance_attributes-gt-ne" score="3">
            <rule id="vtest4-gt-ne-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest4-gt-ne-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="vtest4-instance_attributes-gt-ne-fake" name="new_fake" value="new+false"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest4.env"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="9">
    <action_set>
      <rsc_op id="25" operation="monitor" operation_key="vtest4_monitor_0" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="vtest4" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest4-instance_attributes-lte-ne" score="3">
            <rule id="vtest4-lte-ne-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest4-lte-ne-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="vtest4-instance_attributes-lte-ne-fake" name="fake" value="old+false"/>
          </instance_attributes>
          <instance_attributes id="vtest4-instance_attributes-gt-ne" score="3">
            <rule id="vtest4-gt-ne-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest4-gt-ne-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="vtest4-instance_attributes-gt-ne-fake" name="new_fake" value="new+false"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest4.env"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="10">
    <action_set>
      <rsc_op id="18" operation="monitor" operation_key="vtest4_monitor_0" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="vtest4" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest4-instance_attributes-lte-ne" score="3">
            <rule id="vtest4-lte-ne-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest4-lte-ne-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="vtest4-instance_attributes-lte-ne-fake" name="fake" value="old+false"/>
          </instance_attributes>
          <instance_attributes id="vtest4-instance_attributes-gt-ne" score="3">
            <rule id="vtest4-gt-ne-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest4-gt-ne-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="vtest4-instance_attributes-gt-ne-fake" name="new_fake" value="new+false"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest4.env"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="11">
    <action_set>
      <rsc_op id="11" operation="monitor" operation_key="vtest4_monitor_0" on_node="rhel7-2" on_node_uuid="2">
        <primitive id="vtest4" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest4-instance_attributes-lte-ne" score="3">
            <rule id="vtest4-lte-ne-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest4-lte-ne-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="vtest4-instance_attributes-lte-ne-fake" name="fake" value="old+false"/>
          </instance_attributes>
          <instance_attributes id="vtest4-instance_attributes-gt-ne" score="3">
            <rule id="vtest4-gt-ne-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest4-gt-ne-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="vtest4-instance_attributes-gt-ne-fake" name="new_fake" value="new+false"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest4.env"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="12">
    <action_set>
      <rsc_op id="4" operation="monitor" operation_key="vtest4_monitor_0" on_node="rhel7-1" on_node_uuid="1">
        <primitive id="vtest4" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest4-instance_attributes-lte-ne" score="3">
            <rule id="vtest4-lte-ne-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest4-lte-ne-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="vtest4-instance_attributes-lte-ne-fake" name="fake" value="old+false"/>
          </instance_attributes>
          <instance_attributes id="vtest4-instance_attributes-gt-ne" score="3">
            <rule id="vtest4-gt-ne-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest4-gt-ne-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="vtest4-instance_attributes-gt-ne-fake" name="new_fake" value="new+false"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest4.env"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="13">
    <action_set>
      <rsc_op id="44" operation="monitor" operation_key="vtest5:0_monitor_10000" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="vtest5" long-id="vtest5:0" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest5-instance_attributes-gt" score="2">
            <rule id="vtest5-gt-rule" score="INFINITY">
              <expression id="vtest5-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
              <expression id="vtest5-gt-rule-e02" type="version" attribute="#ra-version" operation="lte" value="3.0"/>
            </rule>
            <nvpair id="vtest5-instance_attributes-gt-op_sleep" name="new_op_sleep" value="1"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest5.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="43" operation="start" operation_key="vtest5:0_start_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="14">
    <action_set>
      <rsc_op id="43" operation="start" operation_key="vtest5:0_start_0" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="vtest5" long-id="vtest5:0" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest5-instance_attributes-gt" score="2">
            <rule id="vtest5-gt-rule" score="INFINITY">
              <expression id="vtest5-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
              <expression id="vtest5-gt-rule-e02" type="version" attribute="#ra-version" operation="lte" value="3.0"/>
            </rule>
            <nvpair id="vtest5-instance_attributes-gt-op_sleep" name="new_op_sleep" value="1"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="90000"  envfile="/run/resource-agents/vtest5.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="53" operation="start" operation_key="vtest5-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="15">
    <action_set>
      <rsc_op id="26" operation="monitor" operation_key="vtest5:0_monitor_0" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="vtest5" long-id="vtest5:0" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest5-instance_attributes-gt" score="2">
            <rule id="vtest5-gt-rule" score="INFINITY">
              <expression id="vtest5-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
              <expression id="vtest5-gt-rule-e02" type="version" attribute="#ra-version" operation="lte" value="3.0"/>
            </rule>
            <nvpair id="vtest5-instance_attributes-gt-op_sleep" name="new_op_sleep" value="1"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest5.env"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="16">
    <action_set>
      <rsc_op id="46" operation="monitor" operation_key="vtest5:1_monitor_10000" on_node="rhel7-5" on_node_uuid="5">
        <primitive id="vtest5" long-id="vtest5:1" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest5-instance_attributes-gt" score="2">
            <rule id="vtest5-gt-rule" score="INFINITY">
              <expression id="vtest5-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
              <expression id="vtest5-gt-rule-e02" type="version" attribute="#ra-version" operation="lte" value="3.0"/>
            </rule>
            <nvpair id="vtest5-instance_attributes-gt-op_sleep" name="new_op_sleep" value="1"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_on_node="rhel7-5" CRM_meta_on_node_uuid="5" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest5.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="45" operation="start" operation_key="vtest5:1_start_0" on_node="rhel7-5" on_node_uuid="5"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="17">
    <action_set>
      <rsc_op id="45" operation="start" operation_key="vtest5:1_start_0" on_node="rhel7-5" on_node_uuid="5">
        <primitive id="vtest5" long-id="vtest5:1" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest5-instance_attributes-gt" score="2">
            <rule id="vtest5-gt-rule" score="INFINITY">
              <expression id="vtest5-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
              <expression id="vtest5-gt-rule-e02" type="version" attribute="#ra-version" operation="lte" value="3.0"/>
            </rule>
            <nvpair id="vtest5-instance_attributes-gt-op_sleep" name="new_op_sleep" value="1"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_on_node="rhel7-5" CRM_meta_on_node_uuid="5" CRM_meta_timeout="90000"  envfile="/run/resource-agents/vtest5.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="53" operation="start" operation_key="vtest5-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="18">
    <action_set>
      <rsc_op id="33" operation="monitor" operation_key="vtest5:1_monitor_0" on_node="rhel7-5" on_node_uuid="5">
        <primitive id="vtest5" long-id="vtest5:1" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest5-instance_attributes-gt" score="2">
            <rule id="vtest5-gt-rule" score="INFINITY">
              <expression id="vtest5-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
              <expression id="vtest5-gt-rule-e02" type="version" attribute="#ra-version" operation="lte" value="3.0"/>
            </rule>
            <nvpair id="vtest5-instance_attributes-gt-op_sleep" name="new_op_sleep" value="1"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_on_node="rhel7-5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest5.env"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="19">
    <action_set>
      <rsc_op id="48" operation="monitor" operation_key="vtest5:2_monitor_10000" on_node="rhel7-1" on_node_uuid="1">
        <primitive id="vtest5" long-id="vtest5:2" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest5-instance_attributes-gt" score="2">
            <rule id="vtest5-gt-rule" score="INFINITY">
              <expression id="vtest5-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
              <expression id="vtest5-gt-rule-e02" type="version" attribute="#ra-version" operation="lte" value="3.0"/>
            </rule>
            <nvpair id="vtest5-instance_attributes-gt-op_sleep" name="new_op_sleep" value="1"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_on_node="rhel7-1" CRM_meta_on_node_uuid="1" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest5.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="47" operation="start" operation_key="vtest5:2_start_0" on_node="rhel7-1" on_node_uuid="1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="20">
    <action_set>
      <rsc_op id="47" operation="start" operation_key="vtest5:2_start_0" on_node="rhel7-1" on_node_uuid="1">
        <primitive id="vtest5" long-id="vtest5:2" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest5-instance_attributes-gt" score="2">
            <rule id="vtest5-gt-rule" score="INFINITY">
              <expression id="vtest5-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
              <expression id="vtest5-gt-rule-e02" type="version" attribute="#ra-version" operation="lte" value="3.0"/>
            </rule>
            <nvpair id="vtest5-instance_attributes-gt-op_sleep" name="new_op_sleep" value="1"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_on_node="rhel7-1" CRM_meta_on_node_uuid="1" CRM_meta_timeout="90000"  envfile="/run/resource-agents/vtest5.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="53" operation="start" operation_key="vtest5-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="21">
    <action_set>
      <rsc_op id="5" operation="monitor" operation_key="vtest5:2_monitor_0" on_node="rhel7-1" on_node_uuid="1">
        <primitive id="vtest5" long-id="vtest5:2" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest5-instance_attributes-gt" score="2">
            <rule id="vtest5-gt-rule" score="INFINITY">
              <expression id="vtest5-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
              <expression id="vtest5-gt-rule-e02" type="version" attribute="#ra-version" operation="lte" value="3.0"/>
            </rule>
            <nvpair id="vtest5-instance_attributes-gt-op_sleep" name="new_op_sleep" value="1"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_on_node="rhel7-1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest5.env"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="22">
    <action_set>
      <rsc_op id="50" operation="monitor" operation_key="vtest5:3_monitor_10000" on_node="rhel7-2" on_node_uuid="2">
        <primitive id="vtest5" long-id="vtest5:3" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest5-instance_attributes-gt" score="2">
            <rule id="vtest5-gt-rule" score="INFINITY">
              <expression id="vtest5-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
              <expression id="vtest5-gt-rule-e02" type="version" attribute="#ra-version" operation="lte" value="3.0"/>
            </rule>
            <nvpair id="vtest5-instance_attributes-gt-op_sleep" name="new_op_sleep" value="1"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_on_node="rhel7-2" CRM_meta_on_node_uuid="2" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest5.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="49" operation="start" operation_key="vtest5:3_start_0" on_node="rhel7-2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="23">
    <action_set>
      <rsc_op id="49" operation="start" operation_key="vtest5:3_start_0" on_node="rhel7-2" on_node_uuid="2">
        <primitive id="vtest5" long-id="vtest5:3" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest5-instance_attributes-gt" score="2">
            <rule id="vtest5-gt-rule" score="INFINITY">
              <expression id="vtest5-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
              <expression id="vtest5-gt-rule-e02" type="version" attribute="#ra-version" operation="lte" value="3.0"/>
            </rule>
            <nvpair id="vtest5-instance_attributes-gt-op_sleep" name="new_op_sleep" value="1"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_on_node="rhel7-2" CRM_meta_on_node_uuid="2" CRM_meta_timeout="90000"  envfile="/run/resource-agents/vtest5.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="53" operation="start" operation_key="vtest5-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="24">
    <action_set>
      <rsc_op id="12" operation="monitor" operation_key="vtest5:3_monitor_0" on_node="rhel7-2" on_node_uuid="2">
        <primitive id="vtest5" long-id="vtest5:3" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest5-instance_attributes-gt" score="2">
            <rule id="vtest5-gt-rule" score="INFINITY">
              <expression id="vtest5-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
              <expression id="vtest5-gt-rule-e02" type="version" attribute="#ra-version" operation="lte" value="3.0"/>
            </rule>
            <nvpair id="vtest5-instance_attributes-gt-op_sleep" name="new_op_sleep" value="1"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_on_node="rhel7-2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest5.env"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="25">
    <action_set>
      <rsc_op id="52" operation="monitor" operation_key="vtest5:4_monitor_10000" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="vtest5" long-id="vtest5:4" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest5-instance_attributes-gt" score="2">
            <rule id="vtest5-gt-rule" score="INFINITY">
              <expression id="vtest5-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
              <expression id="vtest5-gt-rule-e02" type="version" attribute="#ra-version" operation="lte" value="3.0"/>
            </rule>
            <nvpair id="vtest5-instance_attributes-gt-op_sleep" name="new_op_sleep" value="1"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="4" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest5.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="51" operation="start" operation_key="vtest5:4_start_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="26">
    <action_set>
      <rsc_op id="51" operation="start" operation_key="vtest5:4_start_0" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="vtest5" long-id="vtest5:4" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest5-instance_attributes-gt" score="2">
            <rule id="vtest5-gt-rule" score="INFINITY">
              <expression id="vtest5-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
              <expression id="vtest5-gt-rule-e02" type="version" attribute="#ra-version" operation="lte" value="3.0"/>
            </rule>
            <nvpair id="vtest5-instance_attributes-gt-op_sleep" name="new_op_sleep" value="1"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="4" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="90000"  envfile="/run/resource-agents/vtest5.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="53" operation="start" operation_key="vtest5-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="27">
    <action_set>
      <rsc_op id="19" operation="monitor" operation_key="vtest5:4_monitor_0" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="vtest5" long-id="vtest5:4" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest5-instance_attributes-gt" score="2">
            <rule id="vtest5-gt-rule" score="INFINITY">
              <expression id="vtest5-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
              <expression id="vtest5-gt-rule-e02" type="version" attribute="#ra-version" operation="lte" value="3.0"/>
            </rule>
            <nvpair id="vtest5-instance_attributes-gt-op_sleep" name="new_op_sleep" value="1"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="4" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest5.env"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="28" priority="1000000">
    <action_set>
      <pseudo_event id="54" operation="running" operation_key="vtest5-clone_running_0">
        <attributes CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="43" operation="start" operation_key="vtest5:0_start_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="45" operation="start" operation_key="vtest5:1_start_0" on_node="rhel7-5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <rsc_op id="47" operation="start" operation_key="vtest5:2_start_0" on_node="rhel7-1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="49" operation="start" operation_key="vtest5:3_start_0" on_node="rhel7-2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="51" operation="start" operation_key="vtest5:4_start_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <pseudo_event id="53" operation="start" operation_key="vtest5-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="29">
    <action_set>
      <pseudo_event id="53" operation="start" operation_key="vtest5-clone_start_0">
        <attributes CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="monitor" operation_key="vtest5:2_monitor_0" on_node="rhel7-1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="12" operation="monitor" operation_key="vtest5:3_monitor_0" on_node="rhel7-2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="19" operation="monitor" operation_key="vtest5:4_monitor_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="26" operation="monitor" operation_key="vtest5:0_monitor_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="33" operation="monitor" operation_key="vtest5:1_monitor_0" on_node="rhel7-5" on_node_uuid="5"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="30">
    <action_set>
      <rsc_op id="58" operation="monitor" operation_key="vtest7:0_monitor_11000" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="vtest7" long-id="vtest7:0" class="ocf" provider="kgaillot" type="vstateful"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest7-instance_attributes-gt" score="2">
            <rule id="vtest7-gt-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest7-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.2.0"/>
            </rule>
            <nvpair id="vtest7-instance_attributes-gt-fake" name="fake" value="new-ordinary"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="11000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_role="Slave" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest7.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="57" operation="start" operation_key="vtest7:0_start_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="31">
    <action_set>
      <rsc_op id="57" operation="start" operation_key="vtest7:0_start_0" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="vtest7" long-id="vtest7:0" class="ocf" provider="kgaillot" type="vstateful"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest7-instance_attributes-gt" score="2">
            <rule id="vtest7-gt-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest7-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.2.0"/>
            </rule>
            <nvpair id="vtest7-instance_attributes-gt-fake" name="fake" value="new-ordinary"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest7.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="67" operation="start" operation_key="vtest7-master_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="32">
    <action_set>
      <rsc_op id="27" operation="monitor" operation_key="vtest7:0_monitor_0" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="vtest7" long-id="vtest7:0" class="ocf" provider="kgaillot" type="vstateful"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest7-instance_attributes-gt" score="2">
            <rule id="vtest7-gt-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest7-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.2.0"/>
            </rule>
            <nvpair id="vtest7-instance_attributes-gt-fake" name="fake" value="new-ordinary"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest7.env"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="33">
    <action_set>
      <rsc_op id="60" operation="monitor" operation_key="vtest7:1_monitor_11000" on_node="rhel7-5" on_node_uuid="5">
        <primitive id="vtest7" long-id="vtest7:1" class="ocf" provider="kgaillot" type="vstateful"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest7-instance_attributes-gt-eq" score="3">
            <rule id="vtest7-gt-eq-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest7-gt-eq-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.2.0"/>
            </rule>
            <nvpair id="vtest7-instance_attributes-gt-eq-fake" name="fake" value="new-special"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="11000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_on_node="rhel7-5" CRM_meta_on_node_uuid="5" CRM_meta_role="Slave" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest7.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="59" operation="start" operation_key="vtest7:1_start_0" on_node="rhel7-5" on_node_uuid="5"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="34">
    <action_set>
      <rsc_op id="59" operation="start" operation_key="vtest7:1_start_0" on_node="rhel7-5" on_node_uuid="5">
        <primitive id="vtest7" long-id="vtest7:1" class="ocf" provider="kgaillot" type="vstateful"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest7-instance_attributes-gt-eq" score="3">
            <rule id="vtest7-gt-eq-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest7-gt-eq-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.2.0"/>
            </rule>
            <nvpair id="vtest7-instance_attributes-gt-eq-fake" name="fake" value="new-special"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_on_node="rhel7-5" CRM_meta_on_node_uuid="5" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest7.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="67" operation="start" operation_key="vtest7-master_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="35">
    <action_set>
      <rsc_op id="34" operation="monitor" operation_key="vtest7:1_monitor_0" on_node="rhel7-5" on_node_uuid="5">
        <primitive id="vtest7" long-id="vtest7:1" class="ocf" provider="kgaillot" type="vstateful"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest7-instance_attributes-gt-eq" score="3">
            <rule id="vtest7-gt-eq-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest7-gt-eq-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.2.0"/>
            </rule>
            <nvpair id="vtest7-instance_attributes-gt-eq-fake" name="fake" value="new-special"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_on_node="rhel7-5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest7.env"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="36">
    <action_set>
      <rsc_op id="62" operation="monitor" operation_key="vtest7:2_monitor_11000" on_node="rhel7-1" on_node_uuid="1">
        <primitive id="vtest7" long-id="vtest7:2" class="ocf" provider="kgaillot" type="vstateful"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest7-instance_attributes-gt" score="2">
            <rule id="vtest7-gt-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest7-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.2.0"/>
            </rule>
            <nvpair id="vtest7-instance_attributes-gt-fake" name="fake" value="new-ordinary"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="11000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_on_node="rhel7-1" CRM_meta_on_node_uuid="1" CRM_meta_role="Slave" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest7.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="61" operation="start" operation_key="vtest7:2_start_0" on_node="rhel7-1" on_node_uuid="1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="37">
    <action_set>
      <rsc_op id="61" operation="start" operation_key="vtest7:2_start_0" on_node="rhel7-1" on_node_uuid="1">
        <primitive id="vtest7" long-id="vtest7:2" class="ocf" provider="kgaillot" type="vstateful"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest7-instance_attributes-gt" score="2">
            <rule id="vtest7-gt-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest7-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.2.0"/>
            </rule>
            <nvpair id="vtest7-instance_attributes-gt-fake" name="fake" value="new-ordinary"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_on_node="rhel7-1" CRM_meta_on_node_uuid="1" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest7.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="67" operation="start" operation_key="vtest7-master_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="38">
    <action_set>
      <rsc_op id="6" operation="monitor" operation_key="vtest7:2_monitor_0" on_node="rhel7-1" on_node_uuid="1">
        <primitive id="vtest7" long-id="vtest7:2" class="ocf" provider="kgaillot" type="vstateful"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest7-instance_attributes-gt" score="2">
            <rule id="vtest7-gt-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest7-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.2.0"/>
            </rule>
            <nvpair id="vtest7-instance_attributes-gt-fake" name="fake" value="new-ordinary"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="2" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_on_node="rhel7-1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest7.env"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="39">
    <action_set>
      <rsc_op id="64" operation="monitor" operation_key="vtest7:3_monitor_11000" on_node="rhel7-2" on_node_uuid="2">
        <primitive id="vtest7" long-id="vtest7:3" class="ocf" provider="kgaillot" type="vstateful"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest7-instance_attributes-gt" score="2">
            <rule id="vtest7-gt-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest7-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.2.0"/>
            </rule>
            <nvpair id="vtest7-instance_attributes-gt-fake" name="fake" value="new-ordinary"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="11000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_on_node="rhel7-2" CRM_meta_on_node_uuid="2" CRM_meta_role="Slave" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest7.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="63" operation="start" operation_key="vtest7:3_start_0" on_node="rhel7-2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="40">
    <action_set>
      <rsc_op id="63" operation="start" operation_key="vtest7:3_start_0" on_node="rhel7-2" on_node_uuid="2">
        <primitive id="vtest7" long-id="vtest7:3" class="ocf" provider="kgaillot" type="vstateful"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest7-instance_attributes-gt" score="2">
            <rule id="vtest7-gt-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest7-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.2.0"/>
            </rule>
            <nvpair id="vtest7-instance_attributes-gt-fake" name="fake" value="new-ordinary"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_on_node="rhel7-2" CRM_meta_on_node_uuid="2" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest7.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="67" operation="start" operation_key="vtest7-master_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="41">
    <action_set>
      <rsc_op id="13" operation="monitor" operation_key="vtest7:3_monitor_0" on_node="rhel7-2" on_node_uuid="2">
        <primitive id="vtest7" long-id="vtest7:3" class="ocf" provider="kgaillot" type="vstateful"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest7-instance_attributes-gt" score="2">
            <rule id="vtest7-gt-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest7-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.2.0"/>
            </rule>
            <nvpair id="vtest7-instance_attributes-gt-fake" name="fake" value="new-ordinary"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="3" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_on_node="rhel7-2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest7.env"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="42">
    <action_set>
      <rsc_op id="66" operation="monitor" operation_key="vtest7:4_monitor_11000" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="vtest7" long-id="vtest7:4" class="ocf" provider="kgaillot" type="vstateful"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest7-instance_attributes-gt" score="2">
            <rule id="vtest7-gt-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest7-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.2.0"/>
            </rule>
            <nvpair id="vtest7-instance_attributes-gt-fake" name="fake" value="new-ordinary"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="4" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="11000" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_role="Slave" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest7.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="65" operation="start" operation_key="vtest7:4_start_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="43">
    <action_set>
      <rsc_op id="65" operation="start" operation_key="vtest7:4_start_0" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="vtest7" long-id="vtest7:4" class="ocf" provider="kgaillot" type="vstateful"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest7-instance_attributes-gt" score="2">
            <rule id="vtest7-gt-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest7-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.2.0"/>
            </rule>
            <nvpair id="vtest7-instance_attributes-gt-fake" name="fake" value="new-ordinary"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="4" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_name="start" CRM_meta_notify="false" CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest7.env"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="67" operation="start" operation_key="vtest7-master_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="44">
    <action_set>
      <rsc_op id="20" operation="monitor" operation_key="vtest7:4_monitor_0" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="vtest7" long-id="vtest7:4" class="ocf" provider="kgaillot" type="vstateful"/>
        <rsc_versioned_attrs>
          <instance_attributes id="vtest7-instance_attributes-gt" score="2">
            <rule id="vtest7-gt-rule" score="INFINITY" boolean-op="and">
              <expression id="vtest7-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.2.0"/>
            </rule>
            <nvpair id="vtest7-instance_attributes-gt-fake" name="fake" value="new-ordinary"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_clone="4" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/vtest7.env"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="45" priority="1000000">
    <action_set>
      <pseudo_event id="68" operation="running" operation_key="vtest7-master_running_0">
        <attributes CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="57" operation="start" operation_key="vtest7:0_start_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="59" operation="start" operation_key="vtest7:1_start_0" on_node="rhel7-5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <rsc_op id="61" operation="start" operation_key="vtest7:2_start_0" on_node="rhel7-1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="63" operation="start" operation_key="vtest7:3_start_0" on_node="rhel7-2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="65" operation="start" operation_key="vtest7:4_start_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <pseudo_event id="67" operation="start" operation_key="vtest7-master_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="46">
    <action_set>
      <pseudo_event id="67" operation="start" operation_key="vtest7-master_start_0">
        <attributes CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="6" operation="monitor" operation_key="vtest7:2_monitor_0" on_node="rhel7-1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="13" operation="monitor" operation_key="vtest7:3_monitor_0" on_node="rhel7-2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="20" operation="monitor" operation_key="vtest7:4_monitor_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="27" operation="monitor" operation_key="vtest7:0_monitor_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="34" operation="monitor" operation_key="vtest7:1_monitor_0" on_node="rhel7-5" on_node_uuid="5"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="47">
    <action_set>
      <pseudo_event id="82" operation="running" operation_key="grouptest2_running_0">
        <attributes CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="75" operation="start" operation_key="gvtest1_start_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="77" operation="start" operation_key="gvtest2_start_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="79" operation="start" operation_key="gvtest3_start_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <pseudo_event id="81" operation="start" operation_key="grouptest2_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="48">
    <action_set>
      <pseudo_event id="81" operation="start" operation_key="grouptest2_start_0">
        <attributes CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="49">
    <action_set>
      <rsc_op id="76" operation="monitor" operation_key="gvtest1_monitor_10000" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="gvtest1" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest1.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="75" operation="start" operation_key="gvtest1_start_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="50">
    <action_set>
      <rsc_op id="75" operation="start" operation_key="gvtest1_start_0" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="gvtest1" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_name="start" CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest1.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="7" operation="monitor" operation_key="gvtest1_monitor_0" on_node="rhel7-1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="14" operation="monitor" operation_key="gvtest1_monitor_0" on_node="rhel7-2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="21" operation="monitor" operation_key="gvtest1_monitor_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="28" operation="monitor" operation_key="gvtest1_monitor_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="35" operation="monitor" operation_key="gvtest1_monitor_0" on_node="rhel7-5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <pseudo_event id="81" operation="start" operation_key="grouptest2_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="51">
    <action_set>
      <rsc_op id="35" operation="monitor" operation_key="gvtest1_monitor_0" on_node="rhel7-5" on_node_uuid="5">
        <primitive id="gvtest1" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest1.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="52">
    <action_set>
      <rsc_op id="28" operation="monitor" operation_key="gvtest1_monitor_0" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="gvtest1" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest1.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="53">
    <action_set>
      <rsc_op id="21" operation="monitor" operation_key="gvtest1_monitor_0" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="gvtest1" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest1.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="54">
    <action_set>
      <rsc_op id="14" operation="monitor" operation_key="gvtest1_monitor_0" on_node="rhel7-2" on_node_uuid="2">
        <primitive id="gvtest1" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest1.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="55">
    <action_set>
      <rsc_op id="7" operation="monitor" operation_key="gvtest1_monitor_0" on_node="rhel7-1" on_node_uuid="1">
        <primitive id="gvtest1" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest1.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="56">
    <action_set>
      <rsc_op id="78" operation="monitor" operation_key="gvtest2_monitor_10000" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="gvtest2" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest2.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="77" operation="start" operation_key="gvtest2_start_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="57">
    <action_set>
      <rsc_op id="77" operation="start" operation_key="gvtest2_start_0" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="gvtest2" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_name="start" CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest2.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="8" operation="monitor" operation_key="gvtest2_monitor_0" on_node="rhel7-1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="15" operation="monitor" operation_key="gvtest2_monitor_0" on_node="rhel7-2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="22" operation="monitor" operation_key="gvtest2_monitor_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="29" operation="monitor" operation_key="gvtest2_monitor_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="36" operation="monitor" operation_key="gvtest2_monitor_0" on_node="rhel7-5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <rsc_op id="75" operation="start" operation_key="gvtest1_start_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <pseudo_event id="81" operation="start" operation_key="grouptest2_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="58">
    <action_set>
      <rsc_op id="36" operation="monitor" operation_key="gvtest2_monitor_0" on_node="rhel7-5" on_node_uuid="5">
        <primitive id="gvtest2" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest2.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="59">
    <action_set>
      <rsc_op id="29" operation="monitor" operation_key="gvtest2_monitor_0" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="gvtest2" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest2.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="60">
    <action_set>
      <rsc_op id="22" operation="monitor" operation_key="gvtest2_monitor_0" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="gvtest2" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest2.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="61">
    <action_set>
      <rsc_op id="15" operation="monitor" operation_key="gvtest2_monitor_0" on_node="rhel7-2" on_node_uuid="2">
        <primitive id="gvtest2" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest2.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="62">
    <action_set>
      <rsc_op id="8" operation="monitor" operation_key="gvtest2_monitor_0" on_node="rhel7-1" on_node_uuid="1">
        <primitive id="gvtest2" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest2.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="63">
    <action_set>
      <rsc_op id="80" operation="monitor" operation_key="gvtest3_monitor_10000" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="gvtest3" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest3.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="79" operation="start" operation_key="gvtest3_start_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="64">
    <action_set>
      <rsc_op id="79" operation="start" operation_key="gvtest3_start_0" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="gvtest3" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_name="start" CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest3.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="9" operation="monitor" operation_key="gvtest3_monitor_0" on_node="rhel7-1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="16" operation="monitor" operation_key="gvtest3_monitor_0" on_node="rhel7-2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="23" operation="monitor" operation_key="gvtest3_monitor_0" on_node="rhel7-3" on_node_uuid="3"/>
      </trigger>
      <trigger>
        <rsc_op id="30" operation="monitor" operation_key="gvtest3_monitor_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <rsc_op id="37" operation="monitor" operation_key="gvtest3_monitor_0" on_node="rhel7-5" on_node_uuid="5"/>
      </trigger>
      <trigger>
        <rsc_op id="77" operation="start" operation_key="gvtest2_start_0" on_node="rhel7-4" on_node_uuid="4"/>
      </trigger>
      <trigger>
        <pseudo_event id="81" operation="start" operation_key="grouptest2_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="65">
    <action_set>
      <rsc_op id="37" operation="monitor" operation_key="gvtest3_monitor_0" on_node="rhel7-5" on_node_uuid="5">
        <primitive id="gvtest3" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-5" CRM_meta_on_node_uuid="5" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest3.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="66">
    <action_set>
      <rsc_op id="30" operation="monitor" operation_key="gvtest3_monitor_0" on_node="rhel7-4" on_node_uuid="4">
        <primitive id="gvtest3" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-4" CRM_meta_on_node_uuid="4" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest3.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="67">
    <action_set>
      <rsc_op id="23" operation="monitor" operation_key="gvtest3_monitor_0" on_node="rhel7-3" on_node_uuid="3">
        <primitive id="gvtest3" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-3" CRM_meta_on_node_uuid="3" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest3.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="68">
    <action_set>
      <rsc_op id="16" operation="monitor" operation_key="gvtest3_monitor_0" on_node="rhel7-2" on_node_uuid="2">
        <primitive id="gvtest3" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-2" CRM_meta_on_node_uuid="2" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest3.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="69">
    <action_set>
      <rsc_op id="9" operation="monitor" operation_key="gvtest3_monitor_0" on_node="rhel7-1" on_node_uuid="1">
        <primitive id="gvtest3" class="ocf" provider="kgaillot" type="vdummy"/>
        <rsc_versioned_attrs>
          <instance_attributes id="grouptest2-instance_attributes-gt" score="3">
            <rule id="grouptest2-gt-rule" score="INFINITY">
              <expression id="grouptest2-gt-rule-e01" type="version" attribute="#ra-version" operation="gt" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-gt-fake" name="fake" value="2-new"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes-lte" score="2">
            <rule id="grouptest2-lte-rule" score="INFINITY">
              <expression id="grouptest2-lte-rule-e01" type="version" attribute="#ra-version" operation="lte" value="1.0"/>
            </rule>
            <nvpair id="grouptest2-instance_attributes-lte-fake" name="fake" value="2-old"/>
          </instance_attributes>
          <instance_attributes id="grouptest2-instance_attributes" score="1">
            <nvpair id="grouptest2-instance_attributes-fake" name="fake" value="2-bad"/>
          </instance_attributes>
        </rsc_versioned_attrs>
        <attributes CRM_meta_on_node="rhel7-1" CRM_meta_on_node_uuid="1" CRM_meta_op_target_rc="7" CRM_meta_timeout="20000"  envfile="/run/resource-agents/gvtest3.env" fake="2-bad"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
</transition_graph>
