<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="1"  transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="91" operation="start" operation_key="container1_start_0" on_node="rhel7-2" on_node_uuid="2">
        <primitive id="container1" class="ocf" provider="heartbeat" type="VirtualDomain"/>
        <attributes CRM_meta_remote_node="lxc1" CRM_meta_timeout="90000" config="/var/lib/pacemaker/cts/lxc/lxc1.xml"  force_stop="true" hypervisor="lxc:///"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="90" operation="stop" operation_key="container1_stop_0" on_node="rhel7-1" on_node_uuid="1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="90" operation="stop" operation_key="container1_stop_0" on_node="rhel7-1" on_node_uuid="1">
        <primitive id="container1" class="ocf" provider="heartbeat" type="VirtualDomain"/>
        <attributes CRM_meta_remote_node="lxc1" CRM_meta_timeout="90000" config="/var/lib/pacemaker/cts/lxc/lxc1.xml"  force_stop="true" hypervisor="lxc:///"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="108" operation="stop" operation_key="lxc1_stop_0" on_node="rhel7-1" on_node_uuid="1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="97" operation="promote" operation_key="lxc-ms_promote_0" internal_operation_key="lxc-ms:0_promote_0" on_node="lxc1" on_node_uuid="lxc1" router_node="rhel7-2">
        <primitive id="lxc-ms" long-id="lxc-ms:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="90000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="94" operation="start" operation_key="lxc-ms_start_0" internal_operation_key="lxc-ms:0_start_0" on_node="lxc1" on_node_uuid="lxc1" router_node="rhel7-2"/>
      </trigger>
      <trigger>
        <rsc_op id="95" operation="demote" operation_key="lxc-ms_demote_0" internal_operation_key="lxc-ms:0_demote_0" on_node="lxc1" on_node_uuid="lxc1" router_node="rhel7-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="104" operation="promote" operation_key="lxc-ms-master_promote_0"/>
      </trigger>
      <trigger>
        <rsc_op id="109" operation="start" operation_key="lxc1_start_0" on_node="rhel7-2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <rsc_op id="96" operation="stop" operation_key="lxc-ms_stop_0" internal_operation_key="lxc-ms:0_stop_0" on_node="lxc1" on_node_uuid="lxc1" router_node="rhel7-1">
        <primitive id="lxc-ms" long-id="lxc-ms:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="90000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="95" operation="demote" operation_key="lxc-ms_demote_0" internal_operation_key="lxc-ms:0_demote_0" on_node="lxc1" on_node_uuid="lxc1" router_node="rhel7-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="102" operation="stop" operation_key="lxc-ms-master_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <rsc_op id="95" operation="demote" operation_key="lxc-ms_demote_0" internal_operation_key="lxc-ms:0_demote_0" on_node="lxc1" on_node_uuid="lxc1" router_node="rhel7-1">
        <primitive id="lxc-ms" long-id="lxc-ms:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="90000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="106" operation="demote" operation_key="lxc-ms-master_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <rsc_op id="94" operation="start" operation_key="lxc-ms_start_0" internal_operation_key="lxc-ms:0_start_0" on_node="lxc1" on_node_uuid="lxc1" router_node="rhel7-2">
        <primitive id="lxc-ms" long-id="lxc-ms:0" class="ocf" provider="pacemaker" type="Stateful"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="90000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="96" operation="stop" operation_key="lxc-ms_stop_0" internal_operation_key="lxc-ms:0_stop_0" on_node="lxc1" on_node_uuid="lxc1" router_node="rhel7-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="100" operation="start" operation_key="lxc-ms-master_start_0"/>
      </trigger>
      <trigger>
        <rsc_op id="109" operation="start" operation_key="lxc1_start_0" on_node="rhel7-2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6" priority="1000000">
    <action_set>
      <pseudo_event id="107" operation="demoted" operation_key="lxc-ms-master_demoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="95" operation="demote" operation_key="lxc-ms_demote_0" internal_operation_key="lxc-ms:0_demote_0" on_node="lxc1" on_node_uuid="lxc1" router_node="rhel7-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="106" operation="demote" operation_key="lxc-ms-master_demote_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <pseudo_event id="106" operation="demote" operation_key="lxc-ms-master_demote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="8" priority="1000000">
    <action_set>
      <pseudo_event id="105" operation="promoted" operation_key="lxc-ms-master_promoted_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="97" operation="promote" operation_key="lxc-ms_promote_0" internal_operation_key="lxc-ms:0_promote_0" on_node="lxc1" on_node_uuid="lxc1" router_node="rhel7-2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9">
    <action_set>
      <pseudo_event id="104" operation="promote" operation_key="lxc-ms-master_promote_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="101" operation="running" operation_key="lxc-ms-master_running_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="103" operation="stopped" operation_key="lxc-ms-master_stopped_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="107" operation="demoted" operation_key="lxc-ms-master_demoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="10" priority="1000000">
    <action_set>
      <pseudo_event id="103" operation="stopped" operation_key="lxc-ms-master_stopped_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="96" operation="stop" operation_key="lxc-ms_stop_0" internal_operation_key="lxc-ms:0_stop_0" on_node="lxc1" on_node_uuid="lxc1" router_node="rhel7-1"/>
      </trigger>
      <trigger>
        <pseudo_event id="102" operation="stop" operation_key="lxc-ms-master_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="11">
    <action_set>
      <pseudo_event id="102" operation="stop" operation_key="lxc-ms-master_stop_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="107" operation="demoted" operation_key="lxc-ms-master_demoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="12" priority="1000000">
    <action_set>
      <pseudo_event id="101" operation="running" operation_key="lxc-ms-master_running_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="94" operation="start" operation_key="lxc-ms_start_0" internal_operation_key="lxc-ms:0_start_0" on_node="lxc1" on_node_uuid="lxc1" router_node="rhel7-2"/>
      </trigger>
      <trigger>
        <pseudo_event id="100" operation="start" operation_key="lxc-ms-master_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="13">
    <action_set>
      <pseudo_event id="100" operation="start" operation_key="lxc-ms-master_start_0">
        <attributes CRM_meta_clone_max="2" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_master_max="1" CRM_meta_master_node_max="1" CRM_meta_notify="false" CRM_meta_timeout="90000" />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="103" operation="stopped" operation_key="lxc-ms-master_stopped_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="107" operation="demoted" operation_key="lxc-ms-master_demoted_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="14">
    <action_set>
      <rsc_op id="110" operation="monitor" operation_key="lxc1_monitor_30000" on_node="rhel7-2" on_node_uuid="2">
        <primitive id="lxc1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="container1" CRM_meta_interval="30000" CRM_meta_name="monitor" CRM_meta_timeout="30000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="109" operation="start" operation_key="lxc1_start_0" on_node="rhel7-2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="15">
    <action_set>
      <rsc_op id="109" operation="start" operation_key="lxc1_start_0" on_node="rhel7-2" on_node_uuid="2">
        <primitive id="lxc1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="container1" CRM_meta_name="start" CRM_meta_timeout="60000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="91" operation="start" operation_key="container1_start_0" on_node="rhel7-2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="108" operation="stop" operation_key="lxc1_stop_0" on_node="rhel7-1" on_node_uuid="1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="16">
    <action_set>
      <rsc_op id="108" operation="stop" operation_key="lxc1_stop_0" on_node="rhel7-1" on_node_uuid="1">
        <primitive id="lxc1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="container1" CRM_meta_timeout="90000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="96" operation="stop" operation_key="lxc-ms_stop_0" internal_operation_key="lxc-ms:0_stop_0" on_node="lxc1" on_node_uuid="lxc1" router_node="rhel7-1"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="17">
    <action_set>
      <pseudo_event id="25" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="90" operation="stop" operation_key="container1_stop_0" on_node="rhel7-1" on_node_uuid="1"/>
      </trigger>
      <trigger>
        <rsc_op id="96" operation="stop" operation_key="lxc-ms_stop_0" internal_operation_key="lxc-ms:0_stop_0" on_node="lxc1" on_node_uuid="lxc1" router_node="rhel7-1"/>
      </trigger>
      <trigger>
        <rsc_op id="108" operation="stop" operation_key="lxc1_stop_0" on_node="rhel7-1" on_node_uuid="1"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>
