<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY"  transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="7" operation="monitor" operation_key="FAKE_monitor_60000" on_node="18builder" on_node_uuid="5">
        <primitive id="FAKE" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_interval="60000" CRM_meta_name="monitor" CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="6" operation="start" operation_key="FAKE_start_0" on_node="18builder" on_node_uuid="5"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="6" operation="start" operation_key="FAKE_start_0" on_node="18builder" on_node_uuid="5">
        <primitive id="FAKE" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="stop" operation_key="FAKE_stop_0" on_node="18builder" on_node_uuid="5"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="5" operation="stop" operation_key="FAKE_stop_0" on_node="18builder" on_node_uuid="5">
        <primitive id="FAKE" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" />
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="3">
    <action_set>
      <rsc_op id="9" operation="monitor" operation_key="remote1_monitor_30000" on_node="18builder" on_node_uuid="5">
        <primitive id="remote1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="FAKE" CRM_meta_interval="30000" CRM_meta_name="monitor" CRM_meta_timeout="30000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="8" operation="start" operation_key="remote1_start_0" on_node="18builder" on_node_uuid="5"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <rsc_op id="8" operation="start" operation_key="remote1_start_0" on_node="18builder" on_node_uuid="5">
        <primitive id="remote1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="FAKE" CRM_meta_name="start" CRM_meta_timeout="60000" />
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="6" operation="start" operation_key="FAKE_start_0" on_node="18builder" on_node_uuid="5"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <pseudo_event id="1" operation="all_stopped" operation_key="all_stopped">
        <attributes />
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="stop" operation_key="FAKE_stop_0" on_node="18builder" on_node_uuid="5"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>
