<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="25" operation="start" operation_key="container1_start_0" on_node="18node2" on_node_uuid="2">
        <primitive id="container1" class="ocf" provider="heartbeat" type="VirtualDomain"/>
        <attributes CRM_meta_timeout="20000" config="/home/dvossel/virtual_machines/lxc/lxc1.xml" crm_feature_set="3.0.7" force_stop="true" hypervisor="lxc:///"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="stop" operation_key="container1_stop_0" on_node="18node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="5" operation="stop" operation_key="container1_stop_0" on_node="18node2" on_node_uuid="2">
        <primitive id="container1" class="ocf" provider="heartbeat" type="VirtualDomain"/>
        <attributes CRM_meta_timeout="20000" config="/home/dvossel/virtual_machines/lxc/lxc1.xml" crm_feature_set="3.0.7" force_stop="true" hypervisor="lxc:///"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="54" operation="stop" operation_key="lxc1_stop_0" on_node="18node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="40" operation="monitor" operation_key="M_monitor_10000" internal_operation_key="M:4_monitor_10000" on_node="lxc1" on_node_uuid="lxc1" router_node="18node2">
        <primitive id="M" long-id="M:4" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_clone="4" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="39" operation="start" operation_key="M_start_0" internal_operation_key="M:4_start_0" on_node="lxc1" on_node_uuid="lxc1" router_node="18node2"/>
      </trigger>
      <trigger>
        <rsc_op id="55" operation="start" operation_key="lxc1_start_0" on_node="18node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <rsc_op id="39" operation="start" operation_key="M_start_0" internal_operation_key="M:4_start_0" on_node="lxc1" on_node_uuid="lxc1" router_node="18node2">
        <primitive id="M" long-id="M:4" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_clone="4" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="38" operation="stop" operation_key="M_stop_0" internal_operation_key="M:4_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="start" operation_key="M-clone_start_0"/>
      </trigger>
      <trigger>
        <rsc_op id="55" operation="start" operation_key="lxc1_start_0" on_node="18node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <pseudo_event id="38" operation="stop" operation_key="M_stop_0" internal_operation_key="M:4_stop_0">
        <attributes CRM_meta_clone="4" CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="stop" operation_key="container1_stop_0" on_node="18node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <pseudo_event id="12" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="43" operation="stop" operation_key="M-clone_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5" priority="1000000">
    <action_set>
      <pseudo_event id="44" operation="stopped" operation_key="M-clone_stopped_0">
        <attributes CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="38" operation="stop" operation_key="M_stop_0" internal_operation_key="M:4_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="43" operation="stop" operation_key="M-clone_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <pseudo_event id="43" operation="stop" operation_key="M-clone_stop_0">
        <attributes CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="7" priority="1000000">
    <action_set>
      <pseudo_event id="42" operation="running" operation_key="M-clone_running_0">
        <attributes CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="39" operation="start" operation_key="M_start_0" internal_operation_key="M:4_start_0" on_node="lxc1" on_node_uuid="lxc1" router_node="18node2"/>
      </trigger>
      <trigger>
        <pseudo_event id="41" operation="start" operation_key="M-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <pseudo_event id="41" operation="start" operation_key="M-clone_start_0">
        <attributes CRM_meta_clone_max="5" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="44" operation="stopped" operation_key="M-clone_stopped_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9">
    <action_set>
      <rsc_op id="22" operation="monitor" operation_key="A_monitor_0" on_node="lxc2" on_node_uuid="lxc2" router_node="18node2">
        <primitive id="A" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="10">
    <action_set>
      <rsc_op id="18" operation="monitor" operation_key="A_monitor_0" on_node="lxc1" on_node_uuid="lxc1" router_node="18node2">
        <primitive id="A" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="55" operation="start" operation_key="lxc1_start_0" on_node="18node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="11">
    <action_set>
      <rsc_op id="49" operation="monitor" operation_key="B_monitor_10000" on_node="lxc1" on_node_uuid="lxc1" router_node="18node2">
        <primitive id="B" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="48" operation="start" operation_key="B_start_0" on_node="lxc1" on_node_uuid="lxc1" router_node="18node2"/>
      </trigger>
      <trigger>
        <rsc_op id="55" operation="start" operation_key="lxc1_start_0" on_node="18node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="12">
    <action_set>
      <rsc_op id="48" operation="start" operation_key="B_start_0" on_node="lxc1" on_node_uuid="lxc1" router_node="18node2">
        <primitive id="B" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="12" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="47" operation="stop" operation_key="B_stop_0"/>
      </trigger>
      <trigger>
        <rsc_op id="55" operation="start" operation_key="lxc1_start_0" on_node="18node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="13">
    <action_set>
      <pseudo_event id="47" operation="stop" operation_key="B_stop_0">
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="stop" operation_key="container1_stop_0" on_node="18node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <pseudo_event id="12" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="14">
    <action_set>
      <rsc_op id="23" operation="monitor" operation_key="B_monitor_0" on_node="lxc2" on_node_uuid="lxc2" router_node="18node2">
        <primitive id="B" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="15">
    <action_set>
      <rsc_op id="19" operation="monitor" operation_key="C_monitor_0" on_node="lxc1" on_node_uuid="lxc1" router_node="18node2">
        <primitive id="C" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="55" operation="start" operation_key="lxc1_start_0" on_node="18node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="16">
    <action_set>
      <rsc_op id="24" operation="monitor" operation_key="D_monitor_0" on_node="lxc2" on_node_uuid="lxc2" router_node="18node2">
        <primitive id="D" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="17">
    <action_set>
      <rsc_op id="20" operation="monitor" operation_key="D_monitor_0" on_node="lxc1" on_node_uuid="lxc1" router_node="18node2">
        <primitive id="D" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_op_target_rc="7" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="55" operation="start" operation_key="lxc1_start_0" on_node="18node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="18">
    <action_set>
      <rsc_op id="55" operation="start" operation_key="lxc1_start_0" on_node="18node2" on_node_uuid="2">
        <primitive id="lxc1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="container1" CRM_meta_name="start" CRM_meta_timeout="60000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="25" operation="start" operation_key="container1_start_0" on_node="18node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <rsc_op id="54" operation="stop" operation_key="lxc1_stop_0" on_node="18node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="19">
    <action_set>
      <rsc_op id="54" operation="stop" operation_key="lxc1_stop_0" on_node="18node2" on_node_uuid="2">
        <primitive id="lxc1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="container1" CRM_meta_timeout="20000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="20">
    <action_set>
      <rsc_op id="6" operation="monitor" operation_key="lxc1_monitor_30000" on_node="18node2" on_node_uuid="2">
        <primitive id="lxc1" class="ocf" provider="pacemaker" type="remote"/>
        <attributes CRM_meta_container="container1" CRM_meta_interval="30000" CRM_meta_name="monitor" CRM_meta_timeout="30000" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="55" operation="start" operation_key="lxc1_start_0" on_node="18node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="21" priority="1000000">
    <action_set>
      <rsc_op id="21" operation="probe_complete" operation_key="probe_complete" on_node="lxc2" on_node_uuid="lxc2" router_node="18node2">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="22" operation="monitor" operation_key="A_monitor_0" on_node="lxc2" on_node_uuid="lxc2" router_node="18node2"/>
      </trigger>
      <trigger>
        <rsc_op id="23" operation="monitor" operation_key="B_monitor_0" on_node="lxc2" on_node_uuid="lxc2" router_node="18node2"/>
      </trigger>
      <trigger>
        <rsc_op id="24" operation="monitor" operation_key="D_monitor_0" on_node="lxc2" on_node_uuid="lxc2" router_node="18node2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="22" priority="1000000">
    <action_set>
      <rsc_op id="17" operation="probe_complete" operation_key="probe_complete" on_node="lxc1" on_node_uuid="lxc1" router_node="18node2">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.7"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="18" operation="monitor" operation_key="A_monitor_0" on_node="lxc1" on_node_uuid="lxc1" router_node="18node2"/>
      </trigger>
      <trigger>
        <rsc_op id="19" operation="monitor" operation_key="C_monitor_0" on_node="lxc1" on_node_uuid="lxc1" router_node="18node2"/>
      </trigger>
      <trigger>
        <rsc_op id="20" operation="monitor" operation_key="D_monitor_0" on_node="lxc1" on_node_uuid="lxc1" router_node="18node2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="23">
    <action_set>
      <pseudo_event id="12" operation="probe_complete" operation_key="probe_complete">
        <attributes crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="17" operation="probe_complete" operation_key="probe_complete" on_node="lxc1" on_node_uuid="lxc1" router_node="18node2"/>
      </trigger>
      <trigger>
        <rsc_op id="21" operation="probe_complete" operation_key="probe_complete" on_node="lxc2" on_node_uuid="lxc2" router_node="18node2"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="24">
    <action_set>
      <pseudo_event id="11" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.7"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="stop" operation_key="container1_stop_0" on_node="18node2" on_node_uuid="2"/>
      </trigger>
      <trigger>
        <pseudo_event id="38" operation="stop" operation_key="M_stop_0" internal_operation_key="M:4_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="47" operation="stop" operation_key="B_stop_0"/>
      </trigger>
      <trigger>
        <rsc_op id="54" operation="stop" operation_key="lxc1_stop_0" on_node="18node2" on_node_uuid="2"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

